<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa users >}} Users & Access, select **Invite New Users**.

1. Under Invite By Email:

    - Enter the user's **Email** address.
    - Assign the user to a group from the **Group** dropdown menu.
    - Click **{{< fa plus >}}** under **Role** to assign roles to that user:

        1. Click **{{< fa plus >}}** next to the role for each role to be assigned.
        2. Click **Assign Additional Roles (Optional)**.^[Users invited without additional roles applied will be automatically assigned to a [{{< fa wrench >}} Basic User]{.bubble} role with minimal permissions.]

1. Click **{{< fa envelope >}} Send Invite**.

    Users will receive an email invitation that they must accept to join your organization.

::: {.callout}
## Try inviting yourself!

a. Add **+1** to your email handle (**handle+1@your-company.com**) and accept the invitation.
b. Then, confirm that the invitation has disappeared from Pending Invites and that your new user has a join date under Invite History.

:::

::::


:::: {.content-hidden unless-format="revealjs"}
**Invite a new user**

1. Enter the details under Invite by Email:
  - **Group** — The group you created earlier.
  - **Role** — The role you created earlier.
2. Click **{{< fa envelope >}} Send Invite**.

::: {.embed}
**Tip:** Try inviting yourself! Add **+1** to your email handle (**handle+1@your-company.com**) and accept the invitation.

Then, confirm that the invitation has disappeared from Pending Invites and that your new user has a join date under Invite History.

:::


::::