---
title: "Customizing Your <br>Model Inventory"
subtitle: "Administrator Fundamentals — Module 2 of 4<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
lightbox: true
format:
  revealjs:
    controls: true
    controls-tutorial: true
    help: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /validmind.png
    footer: "{{< var validmind.training >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/training/training.qmd)"
    revealjs-plugins:
      - slideover
  html:
  # Change this to the file name prepended by a _ to get around the global HTML output settings required by _metadata.yml
    output-file: _customizing-your-model-inventory.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

# Learning objectives {.center}

_"As an **administrator** who has set up our organization's foundational units and granted users granulated access to the {{< var validmind.platform >}}, I want to configure our model inventory and customize our reusable resources."_

::: {.tc}
<br>
This second module is part of a four-part series:
<br><br>
[Administrator Fundamentals](/training/administrator-fundamentals/administrator-fundamentals-register.qmd){.button target="_blank"}
:::

## Module 2 — Contents {.center}

::: {.f2}
1. [The {{< var validmind.platform >}} model inventory](#the-validmind-inventory)
2. [Configure model inventory fields](#configure-inventory-fields)
3. [Customize documentation templates](#customize-documentation-templates)
4. [Configure reusable blocks](#configure-reusable-blocks)

:::

First, let's make sure you can log in to {{< var vm.product >}}.

{{< include /training/assets/_revealjs-navigation.qmd >}}

## Before you begin {.center}

::: {.panel-tabset}

### Prerequisite course

To continue, you need to have been [onboarded](administrator-fundamentals-register.qmd#register){target="_blank"} onto {{< var validmind.training >}} with the [**{{< fa hand >}} Customer Admin**]{.bubble} role and completed the first module of this course:

::: {.tc}
<!-- IMPORTANT: USE THE .HTML PATH AND NOT THE .QMD PATH FOR THE REVEALJS OUTPUT -->
[Onboarding Your Organization](onboarding-your-organization.html){.button target="_blank"}
:::

:::: {.tc .mt5 .f2 .embed}
Already logged in and refreshed this module? Click [{{< fa chevron-right >}}]() to continue.

:::


### Log in

1. Log in to check your access:

::: {.tc}
[Log in to {{< var vm.product >}}](https://app.prod.validmind.ai){.button target="_blank"}
:::

::: {.tc .f3}
Be sure to return to this page afterwards.
:::

2. After you successfully log in, refresh the page to connect this training module up to the {{< var validmind.platform >}}:

::: {.tc}
<button class="button" onClick="window.location.reload();">Refresh Page</button>

:::

:::

<br>

<!-- USING THE VARIABLE IN THE HEADING MESSES UP THE PAGE ANCHOR -->

# The ValidMind inventory {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.slideover--r}
**Welcome to the {{< fa cubes >}} Inventory**

Use the model inventory to track comprehensive details for all your models throughout the model lifecycle. The model inventory is customizable and extensible, with a layout that can be configured to suit your needs.

::: {.embed}
In a usual model lifecycle, models are independently registered in your model inventory by your development team.

For this training course, we'll have you register a dummy model via the **{{< fa plus >}} Register Model** modal to familiarize you with the {{< var validmind.platform >}} interface and the model details page.
:::

**Let's register a model together** on the next page. {{< fa hand-point-right >}}

::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory/?register=open" background-interactive="true" data-preload="yes"}

:::: {.slideover--r .three-quarters .auto-collapse-10}
**Register a new model**

1. Select the option for a **new model**.
2. You can fill in other options according to your preference.
3. Click **{{< fa plus >}} Register Model** to add the model to your inventory.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.slideover--l .three-quarters .auto-collapse-10}
**View model details**

Once you've registered your model:

1. **Select the name of your model you registered** to open up the model details page.
2. Scroll through the page to explore the default layout, and the fields available out-of-the-box.

When you're done, click [{{< fa chevron-right >}}]() to learn how to customize your model inventory.

::::

# Configure inventory fields {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage model inventory fields

::: {.tc}
[Learn more ...](/guide/model-inventory/manage-model-inventory-fields.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next pages. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/model-inventory/_model-inventory-fields.qmd >}}

::: {.panel-tabset}

### Add or edit inventory fields

{{< include /guide/model-inventory/_add-edit-inventory-fields.qmd >}}

### Inventory field types

{{< include /guide/model-inventory/_inventory-field-types.qmd >}}

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Add an inventory field**
:::

1. Under Workspace Settings, select **{{< fa sliders >}} Inventory Fields**.
2. Click **{{< fa plus >}} Add New Field**.
3. Select the field [type]{.smallcaps}, enter a [name]{.smallcaps}, and a [description]{.smallcaps}.
4. Click **Save** to add your field.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Mange model stakeholder types!

::: {.tc}
[Learn more ...](/guide/configuration/manage-model-stakeholder-types.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::: {.f5 .pr3 .pl3 .mt4 .embed}
Please note that the stock **Model Developer**, **Model Owner**, and **Model Validator** stakeholder types are required by default for all models, and as such cannot be cannot be modified.
:::

:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/configuration/_model-stakeholder-types.qmd >}}

::: {.f4}

::: {.panel-tabset}

### 1. Add model stakeholder types

{{< include /guide/configuration/_add-model-stakeholder-types.qmd >}}

### 2. Manage stakeholder type permissions

{{< include /guide/configuration/_manage-stakeholder-type-permissions.qmd >}}

:::

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Add a model stakeholder type**
:::

Under User Permissions, select **{{< fa users >}} Model Stakeholder Types**:

1. Click **{{< fa plus >}} Add New Stakeholder Type**.
2. Enter the unique **[name]{.smallcaps}** and **[description]{.smallcaps}** for the stakeholder type.
3. Click on the stakeholder type whose permissions you added above.
4. On the **Permissions** tab, select **Edit Permissions** to modify inventory field permissions to or from that type.
5. Toggle specific permissions for that stakeholder type by checking or unchecking the boxes next to the permission. 
6. Click **Save Permissions** to apply your changes.

::::

# Customize documentation templates {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage user groups

::: {.tc}
[Learn more ...](/guide/configuration/manage-groups.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/configuration/_user-groups.qmd >}}

{{< include /guide/configuration/_add-groups.qmd >}}

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Add a user group**
:::

Under User Permissions in the sidebar, select **{{< fa users >}} Groups**.

1. Next to All Groups, click **{{< fa plus >}} Create New Group** to open the Create New Group menu.
2. Enter a **[group name]{.smallcaps}** and **[group description]{.smallcaps}** for the new group and click **Continue**.
3. Select users from the list to add them to the group.
4. Click **{{< fa check >}} Create Group** to save.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage user roles

::: {.tc}
[Learn more ...](/guide/configuration/manage-roles.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/configuration/_user-roles.qmd >}}

::: {.panel-tabset}

### 1. Add user roles

{{< include /guide/configuration/_add-roles.qmd >}}

### 2. Manage role permissions

{{< include /guide/configuration/_manage-role-permissions.qmd >}}

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Create role & assign permissions**
:::

Under User Permissions, select **{{< fa user-group >}} Roles**.

1. Click **{{< fa plus >}} Add New Role**.
2. Enter the unique **[name]{.smallcaps}** and **[description]{.smallcaps}** for the role.
3. Click **{{< fa plus >}} Add Role**.
4. Select the role you created above.
5. On the **Permissions** tab, select **Edit Permissions**.
6. Toggle specific user permissions for that role by checking or unchecking the boxes next to the permission.
7. Click **Save Permissions** to apply your changes.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage global permissions

::: {.tc}
[Learn more ...](/guide/configuration/manage-permissions.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

In addition to assigning permissions via individual user roles, you can add roles to your global permissions:

{{< include /guide/configuration/_manage-permissions.qmd >}}

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Modify global permissions**
:::

1. Under User Permissions, select **{{< fa screwdriver-wrench >}} Permissions**.
2. **Add the role you created earlier** to a specific permission by clicking **{{< fa plus >}}**, then selecting the permission from the drop-down menu.
2. **Remove the role you created earlier** from a specific permission by clicking **{{< fa x >}}** next to the role.

::::

# Configure reusable blocks {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Invite users via email

::: {.tc}
[Learn more ...](/guide/configuration/manage-users.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

::: {.panel-tabset}
Grant users access to the {{< var validmind.platform >}} by sending them email invitations to join your organization:

### Invite new users

{{< include /guide/configuration/_invite-users.qmd >}}

### Monitor invitations

{{< include /guide/configuration/_monitor-invitations.qmd >}}
:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--r .three-quarters .auto-collapse-10}
**Invite a new user**

Invite a user to join your organization:

- **Group** — The group you created earlier.
- **Role** — The role you created earlier.

::: {.embed}
**Hint:** Try inviting yourself! Add **+1** to your email handle (**handle+1@your-company.com**) and accept the invitation.

Then, confirm that the invitation has disappeared from Pending Invites and that your new user has a join date under Invite History.

:::

When you are done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage role users

::: {.tc}
[Learn more ...](/guide/configuration/manage-roles.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

After granting access to your users, you can adjust their roles as needed:

{{< include /guide/configuration/_manage-role-users.qmd >}}

::: {.panel-tabset}

### Add role to user

{{< include /guide/configuration/_add-role-to-user.qmd >}}

### Delete role from user

{{< include /guide/configuration/_delete-role-from-user.qmd >}}

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Modify a role's users**
:::

1. Under User Permissions, select **{{< fa user-group >}} Roles**.
2. **Click on the role you created earlier** and select the **Users** tab.
2. **For the user you invited earlier,** click **{{< fa plus >}}** to open the Assign Roles menu.
3. Click **{{< fa plus >}}** next to the role for each role to be assigned.
4. Click **{{< fa puzzle-piece >}} Assign Roles to User** to save changes.
5. Click **{{< fa x >}}** to delete a role from a user.

::::

# In summary {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Onboarding your organization

:::

::: {.column width="70%" .bl .pl4 .f3}
In this first module, you learned how to:

- [x] Set up your organization's foundational units
- [x] Manage user groups, user roles, & role permissions
- [x] Invite users to the {{< var validmind.platform >}}
- [x] Control the access users have to the {{< var validmind.platform >}}

:::
::::

::: {.tc}
<br>
Continue your {{< var vm.platform >}} administration journey with:
<br><br>
<!-- IMPORTANT: USE THE .HTML PATH AND NOT THE .QMD PATH FOR THE REVEALJS OUTPUT -->
[Customizing Your Model Inventory](customizing-your-model-inventory.html){.button target="_blank"}
:::
