---
title: "Onboarding <br>Your Organization"
subtitle: "Administrator Fundamentals — Module 1 of 4<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
lightbox: true
format:
  revealjs:
    controls: true
    controls-tutorial: true
    help: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /validmind.png
    footer: "{{< var validmind.training >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/training/training.qmd)"
    revealjs-plugins:
      - slideover
  html:
  # Change this to the file name prepended by a _ to get around the global HTML output settings required by _metadata.yml
    output-file: _onboarding-your-organization.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

# Learning objectives {.center}

_"As an **administrator** who is new to {{< var vm.product >}}, I want to learn how to set up the {{< var validmind.platform >}} for our requirements, define granular access to {{< var vm.platform >}} features, and invite users to join our configured organization."_

::: {.tc}
<br>
This first module is part of a four-part series:
<br><br>
[Administrator Fundamentals](/training/administrator-fundamentals/administrator-fundamentals-register.qmd){.button target="_blank"}
:::


## Module 1 — Contents {.center}

::: {.f2}
1. [The {{< var validmind.platform >}}](#the-validmind-platform)
2. [Set up your organization](#set-up-your-organization)
3. [Set up groups, roles, & permissions](#groups-roles-permissions)
4. [Grant users access to your organization](#grant-users-access)

:::

First, let's make sure you can log in to {{< var vm.product >}}.

{{< include /training/assets/_revealjs-navigation.qmd >}}

## Before you begin {.center}

::: {.panel-tabset}

### Registration

To continue, you need to have been [onboarded](administrator-fundamentals-register.qmd#register){target="_blank"} onto {{< var validmind.training >}} with the [**{{< fa hand >}} Customer Admin**]{.bubble} role.

<br>

:::: {.tc .mt5 .f2 .embed}
Already logged in and refreshed this module? Click [{{< fa chevron-right >}}]() to continue.

:::

{{< include /training/common-slides/_log-in.qmd >}}

:::

<!-- USING THE VARIABLE IN THE HEADING MESSES UP THE PAGE ANCHOR -->

# The ValidMind Platform {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {background-iframe="https://app.prod.validmind.ai" background-interactive="true" data-preload="yes"}

:::: {.slideover--r}
**Welcome to the {{< var validmind.platform >}}**

From here, you can:

- Keep track of all your organization's models and their progress throughout the model lifecycle in the customizable inventory ...
- Manage your organization's custom setup, including inventory fields and reusable templates and blocks ...
- Manage users and user access to features ...
- Set up workflows and attestations to streamline the governance of your models ...
- View analytics on your models and findings, and create custom reports ...
- ... and much more!

::: {.embed}
**Can't load the {{< var validmind.platform >}}?**

Make sure you're logged in and have refreshed the page in a Chromium-based browser.
:::

When you're done exploring, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.slideover--l}
**Welcome to {{< fa gear >}} Settings**

Your hub for configuring and managing your organization, from user invitations to reusable templates, and more.

::: {.embed}
Default settings are provided for you as examples, but ideally your settings should reflect your organization's custom needs and governance goals.
:::

**Learn how to set up the basic foundations for your organization** in the next section. {{< fa hand-point-right >}}

::::

# Set up your organization {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Business units & use cases

::: {.tc}
[Learn more ...](/guide/configuration/set-up-your-organization.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next pages. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

Get your organization ready for use by first defining business units and use cases:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Organization**.

::: {.panel-tabset}

#### Add business units

{{< include /guide/configuration/_add-business-units.qmd >}}

#### Add use cases

{{< include /guide/configuration/_add-use-cases.qmd >}}

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/organization" background-interactive="true" data-preload="yes"}

:::: {.slideover--r .three-quarters .auto-collapse-10}
::: {.tc}
**Add a business unit**
:::

1. Click **{{< fa plus >}} Add New Business Unit** under Business Units.
2. Enter in your **[business unit name]{.smallcaps}**.
3. Click **{{< fa plus >}} Add Business Unit** to save your changes.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/settings/organization" background-interactive="true" data-preload="yes"}

:::: {.slideover--l .auto-collapse-10}
::: {.tc}
**Add a use case**
:::

1. Click **{{< fa plus >}} Add New Use Case** under Use Cases.
2. Enter in the **[title]{.smallcaps}** and select a **[category]{.smallcaps}** for your use case.
3. Click **{{< fa plus >}} Add Use Case** to save your changes.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Risk areas & validation guidelines

::: {.tc}
[Learn more ...](/guide/model-validation/manage-validation-guidelines.html#set-up-validation-guidelines){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

Next, define your risk areas and validation guidelines:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Risk Areas & Validation Guidelines**.

::: {.panel-tabset}

### a. Add risk areas

{{< include /guide/model-validation/_add-risk-areas.qmd >}}

### b. Add validation guidelines

{{< include /guide/model-validation/_add-validation-guidelines.qmd >}}

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/risk-areas" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .half .auto-collapse-10}
::: {.tc}
**Add a risk area**
:::

1. Click **{{< fa plus >}} Add Risk Area**.
2. Provide a **[name]{.smallcaps}** and **[description]{.smallcaps}** for your risk area.
3. Click **Add Risk Area** to create your risk area.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/settings/risk-areas" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add a validation guideline**
:::

1. Hover over the risk area you added previously until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.
2. Select **{{< fa plus >}} Add Guideline**.
3. Provide a **[title]{.smallcaps}** and **[description]{.smallcaps}** for your guideline.
4. Click **Add Guideline** to insert your guideline to your risk area.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

# Groups, roles, & permissions {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage user groups

::: {.tc}
[Learn more ...](/guide/configuration/manage-groups.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/configuration/_user-groups.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under User Permissions, select **Groups**.

::: {.panel-tabset}

#### a. Add groups

{{< include /guide/configuration/_add-groups.qmd >}}

#### b. Add users to groups

{{< include /guide/configuration/_add-remove-group-members.qmd >}}

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/groups" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add a user group**
:::

1. Next to All Groups, click **{{< fa plus >}} Create New Group** to open the Create New Group menu.
2. Enter a **[group name]{.smallcaps}** and **[group description]{.smallcaps}** for the new group and click **Continue**.
3. Select users from the list to add them to the group.
4. Click **{{< fa check >}} Create Group** to save.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage user roles

::: {.tc}
[Learn more ...](/guide/configuration/manage-roles.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/configuration/_user-roles.qmd >}}

::: {.panel-tabset}

### 1. Add user roles

{{< include /guide/configuration/_add-roles.qmd >}}

### 2. Manage role permissions

{{< include /guide/configuration/_manage-role-permissions.qmd >}}

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/roles" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .half .auto-collapse-10}
::: {.tc}
**Create new role**
:::

1. Click **{{< fa plus >}} Add New Role**.
2. Enter the unique **[name]{.smallcaps}** and **[description]{.smallcaps}** for the role.
3. Click **{{< fa plus >}} Add Role**.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/settings/roles" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Assign role permissions**
:::

1. Select the role you created previously.
2. On the **Permissions** tab, select **Edit Permissions**.
3. Toggle specific user permissions for that role by checking or unchecking the boxes next to the permission.
4. Click **Save Permissions** to apply your changes.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage global permissions

::: {.tc}
[Learn more ...](/guide/configuration/manage-permissions.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

In addition to assigning permissions via individual user roles, you can add roles to your global permissions:

{{< include /guide/configuration/_manage-permissions.qmd >}}

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/permissions" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Modify global permissions**
:::

1. **Add the role you created earlier** to two permissions by clicking **{{< fa plus >}}**, then selecting the role from the drop-down menu.
2. **Remove the role you created earlier** from one of the permissions you added above by clicking **{{< fa x >}}** next to the role.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

# Grant users access {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Invite users via email

::: {.tc}
[Learn more ...](/guide/configuration/manage-users.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

Once you've set up the basics, grant users access to the {{< var validmind.platform >}} by sending them email invitations to join your organization:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under User Permissions, select **Invite New Users**.

::: {.panel-tabset}

### Invite new users

{{< include /guide/configuration/_invite-users.qmd >}}

### Monitor invitations

{{< include /guide/configuration/_monitor-invitations.qmd >}}
:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/invitation" background-interactive="true" data-preload="yes"}

:::: {.slideover--l .three-quarters .auto-collapse-10}
{{< include _invite-new-user.qmd >}}

When you are done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage roles on users

::: {.tc}
[Learn more ...](/guide/configuration/manage-users.qmd#manage-user-roles){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}

After granting access to your users, you can adjust their roles as needed:

{{< include /guide/configuration/_manage-user-roles.qmd >}}

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/user-directory" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add role to user**
:::

1. **For the user you invited earlier,** click the {{< fa circle-plus >}} icon to open the Assign Roles menu for that user.
2. Click **{{< fa plus >}}** next to a role to assign that role to the user.
3. Click **{{< fa puzzle-piece >}} Assign Roles to User** to save changes.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

# In summary {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Onboarding your organization

:::

::: {.column width="70%" .bl .pl4 .f3}
In this first module, you learned how to:

- [x] Set up your organization's foundational units
- [x] Manage user groups, user roles, & role permissions
- [x] Invite users to the {{< var validmind.platform >}}
- [x] Control the access users have to the {{< var validmind.platform >}}

:::
::::

::: {.tc}
<br>
Continue your {{< var vm.platform >}} administration journey with:
<br><br>
<!-- IMPORTANT: USE THE .HTML PATH AND NOT THE .QMD PATH FOR THE REVEALJS OUTPUT -->
[Customizing Your Model Inventory](customizing-your-model-inventory.html){.button target="_blank"}
:::