---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Organizational Oversight <br>& Reporting"
subtitle: "Administrator Fundamentals — Module 4 of 4<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
lightbox: true
format:
  revealjs:
    include-in-header:
      - text: |
          <script src="/training/assets/vmurl-settings.js"></script>
    controls: true
    controls-tutorial: true
    help: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /favicon.svg
    footer: "{{< var validmind.training >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/training/training.qmd)"
    revealjs-plugins:
      - slideover
  html:
  # Change this to the file name prepended by a _ to get around the global HTML output settings required by _metadata.yml
    output-file: _organizational-oversight-reporting.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

# Learning objectives {.center}

_"As an **administrator** who has configured the {{< var validmind.platform >}} to suit our organizational requirements, I want to use {{< var vm.product >}} to oversee how our teams interact with our records (models) and customize reporting to provide insights tailored to our use cases."_

::: {.tc}
<br>
This final module is part of a four-part series:
<br><br>
[Administrator Fundamentals](/training/administrator-fundamentals/administrator-fundamentals-register.qmd){.button target="_blank"}
:::


## Module 4 — Contents {.center}

::: {.f2}
1. [Audit organization activity](#audit-organization-activity)
2. [Audit workflows](#audit-workflows)
3. [Work with analytics](#work-with-analytics)

:::

First, let's make sure you can log in to {{< var vm.product >}}.

{{< include /training/assets/_revealjs-navigation.qmd >}}

## Before you begin {.center}

::: {.panel-tabset}

### Prerequisite courses

To continue, you need to have been [onboarded](administrator-fundamentals-register.qmd#register){target="_blank"} onto {{< var validmind.training >}} with the [**{{< fa hand >}} Customer Admin**]{.bubble} role and completed the first three modules of this course:

<!-- IMPORTANT: USE THE .HTML PATH AND NOT THE .QMD PATH FOR THE REVEALJS OUTPUT -->

:::: {.columns}
::: {.column width="30%"}
::: {.tc}
[Module 1](onboarding-your-organization.html){.button target="_blank"}
:::

:::
::: {.column width="30%"}
::: {.tc}
[Module 2](customizing-your-inventory.html){.button target="_blank"}
:::

:::

::: {.column width="30%"}
::: {.tc}
[Module 3](using-validmind-for-risk-management.html){.button target="_blank"}
:::

:::
::::

:::: {.tc .mt5 .f2 .embed}
Already logged in and refreshed this module? Click [{{< fa chevron-right >}}]() to continue.

:::

{{< include /training/common-slides/_log-in.qmd >}}

:::

# Audit organization activity {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
View settings activity

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/reporting/view-settings-activity.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f4}
{{< include /guide/reporting/_view-settings-activity-overview.qmd >}}

{{< include /guide/reporting/_view-settings-activity-steps.qmd >}}

:::

::::

## {background-iframe="https://app.prod.validmind.ai/activity" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Review settings activity**
:::

1. In the left sidebar, click **{{< fa wifi >}} Activity**.
2. Select the **Settings Activity** tab:
  -  Click **{{< fa filter >}} Filter** to open the filter popover and select the **Event Type**s you want to filter by from the drop-down menu.
  -  Click **{{< fa chevron-down >}} View Details** to reveal more details about the activity when the option is available on an entry.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

{{< include /training/common-slides/_view-record-activity.qmd >}}

{{< include /training/common-slides/_review-model-activity.qmd >}}

# Audit workflows {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
View workflow executions

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/workflows/working-with-workflows.qmd#view-all-workflow-executions){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f4}

{{< include /guide/workflows/_view-workflow-executions.qmd >}}

:::
::::

## {background-iframe="https://app.prod.validmind.ai/workflows" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**View all workflow executions**
:::

- Use the buttons or keyboard shortcuts to control the timeline
- Use **{{< fa magnifying-glass >}} Search** to search the timeline.
- Use **{{< fa filter >}} Filter** to filter the timeline.
- Click on any listed workflow to review the details of that specific workflow.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
View record & artifact workflows

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/workflows/manage-workflows.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f4}

Review workflows associated with your records or artifacts:

::: {.panel-tabset}
### Review active workflows

{{< include /guide/workflows/_review-active-workflows.qmd >}}

### Review workflow history

{{< include /guide/workflows/_review-workflow-history.qmd >}}

:::

:::
::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**View active workflows**
:::

1. Select the name of your model you registered for this course to open up the record details page.
2. On the landing page of your model, locate the **Active Workflows** section.
3. Click on the name of any active workflow to review that specific workflow's details.
4. Close the detail view for your workflow.
5. Click **{{< fa arrow-right-arrow-left >}} See All Workflows** to see records of workflows by status.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

# Work with analytics {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {background-iframe="https://app.prod.validmind.ai/analytics" background-interactive="true" data-preload="yes"}

:::: {.slideover--r .three-quarters .auto-collapse-10}
**Welcome to {{< fa square-poll-vertical >}} Analytics**

Here, you can find executive summaries, track information on records (models), artifacts (findings), and more.

::: {.embed}
Default report widgets are provided in the **Models** (model-type records only) and **Validation Issues** (Validation Issue artifacts only) dashboards.

You can supplement these with your own custom reports in additional dashboards to suit your organizational needs.

:::

When you're done exploring, click [{{< fa chevron-right >}}]() to learn more about analytics.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
View report data

::: {.tc}
[Learn more ...](/guide/reporting/view-report-data.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::: {.f4 .pr3 .pl3 .mt4 .embed}
Reports will not include data or artifacts from [archived records](/guide/inventory/archive-delete-records.qmd){target="_blank"}.
:::
:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/reporting/_view-report-data.qmd >}}

:::

::::

## {background-iframe="https://app.prod.validmind.ai/analytics" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**View detailed analytics**
:::

1. Click on the tab for the type of reports you want to review.
2. For each of the bar or pie charts, hover for numerical breakdowns or click on individual sections to get a more detailed view.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage custom reports

::: {.tc}
[Learn more ...](/guide/reporting/manage-custom-reports.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/reporting/_add-custom-analytics.qmd >}}

::: {.panel-tabset}

### 1. Create an analytics page

{{< include /guide/reporting/_create-an-analytics-page.qmd >}}

### 2. Create a visualization

::: {.f4}

{{< include /guide/reporting/_create-a-visualization.qmd >}}

:::

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/analytics" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Create an analytics page**
:::

1. Click **{{< fa plus >}} Add Page**.
2. On the Add New Page module, enter the **Page Name** and the **Description**.
3. Click **Add New Page** to create your custom analytics page.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/analytics" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Create a custom visualization**
:::

1. Click on the tab for the custom page you added previously.
1. Click **{{< fa pencil >}} Edit Dashboard** and select **{{< fa pencil >}} Add Widget** then **{{< fa pencil >}} Add Visualization**.
3. On the Add Visualization panel, enter your **Title**.
4. Select a **Visualization Type**.
5. Select a **Dataset**.
6. Select the visualization configuration options to apply to the dataset.
7. Click **Add Visualization** to insert your custom widget onto the analytics page.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::


# In summary {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Organizational oversight & reporting

::: {.f3}
<br>Want to learn more? Find your next learning resource on [{{< fa graduation-cap >}} {{< var validmind.training >}}](/training/training.qmd){target="_blank"}.

:::

:::

::: {.column width="70%" .bl .pl4 .f3}
In this final module, you learned how to:

- [x] Track updates on records
- [x] Review workflows and workflow history
- [x] Navigate the analytics dashboard
- [x] Create custom report dashboards and visualizations

:::
::::

::: {.f2}
<br>
There is more that {{< var vm.product >}} can do to help you oversee records and unite your risk management teams within one comprehensive tool:
:::

::: {.tc}
[All {{< var validmind.platform >}} guides](/guide/guides.qmd){.button target="_blank"}

:::