---
title: "Using {{< var vm.product >}} for <br>Model Risk Management"
subtitle: "Administrator Fundamentals — Module 3 of 4<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
lightbox: true
format:
  revealjs:
    controls: true
    controls-tutorial: true
    help: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /favicon.svg
    footer: "{{< var validmind.training >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/training/training.qmd)"
    revealjs-plugins:
      - slideover
  html:
  # Change this to the file name prepended by a _ to get around the global HTML output settings required by _metadata.yml
    output-file: _using-validmind-for-model-risk-management.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

# Learning objectives {.center}

::: {.f2}
_"As an **administrator** who has set up user access to the {{< var validmind.platform >}} and prepared our model inventory for tracking models, I want to maximize the potential of {{< var vm.product >}} as a centralized hub for risk management oversight by configuring workflows, regulations and policies, and attestations in accordance with our organization's requirements."_

:::

::: {.tc}
<br>
This third module is part of a four-part series:
<br><br>
[Administrator Fundamentals](/training/administrator-fundamentals/administrator-fundamentals-register.qmd){.button target="_blank"}
:::


## Module 3 — Contents {.center}

::: {.f2}
1. [{{< var vm.product >}} for model risk management](#validmind-for-model-risk-management)
2. [Set up & manage custom workflows](#set-up-manage-workflows)
3. [Manage regulations & policies](#manage-regulations-policies)
4. [Configure attestations](#configure-attestations)

:::

First, let's make sure you can log in to {{< var vm.product >}}.

{{< include /training/assets/_revealjs-navigation.qmd >}}

## Before you begin {.center}

::: {.panel-tabset}

### Prerequisite courses

To continue, you need to have been [onboarded](administrator-fundamentals-register.qmd#register){target="_blank"} onto {{< var validmind.training >}} with the [**{{< fa hand >}} Customer Admin**]{.bubble} role and completed the first two modules of this course:


<!-- IMPORTANT: USE THE .HTML PATH AND NOT THE .QMD PATH FOR THE REVEALJS OUTPUT -->

:::: {.columns}
::: {.column width="50%"}
::: {.tc}
[Onboarding Your Organization](onboarding-your-organization.html){.button target="_blank"}
:::

:::
::: {.column width="50%"}
::: {.tc}
[Customizing Your Model Inventory](customizing-your-model-inventory.html){.button target="_blank"}
:::

:::
::::

:::: {.tc .mt5 .f2 .embed}
Already logged in and refreshed this module? Click [{{< fa chevron-right >}}]() to continue.

:::

{{< include /training/common-slides/_log-in.qmd >}}

:::

<!-- USING THE VARIABLE IN THE HEADING MESSES UP THE PAGE ANCHOR -->

# ValidMind for model risk management {background-color="#083E44" background-image="/training/assets/home-hero.svg"}


## {background-iframe="https://app.prod.validmind.ai" background-interactive="true" data-preload="yes"}

:::: {.slideover--r}
**Welcome back to the {{< var validmind.platform >}}**

The {{< var validmind.platform >}} is more than just a model inventory where your model development and model validation teams collaborate seamlessly and more efficiently — it's also an indispensable tool for model risk management oversight:

- Configure workflows to match your organizational needs for every part of your model lifecycles.
- Set up attestations to support compliance and governance processes.
- Customize reporting to provide insights tailored to your use cases.

::: {.embed}
**Can't load the {{< var validmind.platform >}}?**

Make sure you're logged in and have refreshed the page in a Chromium-based browser.
:::

Let's continue our journey by learning how to **set up workflows** for your use case on the next pages. {{< fa hand-point-right >}}

::::

# Set up & manage workflows {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Model workflow elements

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/workflows/setting-up-workflows.qmd){.button target="_blank"}
:::

<br>Learn how to **manage model stages** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f4}

{{< include /guide/workflows/_set-up-model-workflows.qmd >}}

A workflow is comprised of an interplay of these elements:

::: {.panel-tabset}
### Workflow step types

{{< include /guide/workflows/_workflow-step-types.qmd >}}

### Conditional requirements

{{< include /guide/workflows/_conditional-requirements.qmd >}}

### Workflow states

{{< include /guide/workflows/_workflow-states.qmd >}}

:::

:::
::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Manage model stages

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/workflows/manage-model-stages.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/workflows/_configure-model-stages.qmd >}}

#### Add model stages

{{< include /guide/workflows/_add-model-stages.qmd >}}


:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/statuses" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .half .auto-collapse-10}
::: {.tc}
**Add a model stage**
:::

1. Click **{{< fa plus >}} Add Model Stage**.
2. On the Add New Model Stage modal that appears:
    a. Provide a stage **[name]{.smallcaps}**
    b. Provide a stage **[description]{.smallcaps}**
    c. Assign a **[color]{.smallcaps}** to the stage
3. When you are done, click **Save** to apply your changes.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Configure model workflows

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/workflows/configure-model-workflows.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next pages. {{< fa hand-point-right >}}

::: {.f5 .pl3 .mt4 .pr3 .embed}
For more assistance configuring workflows, refer to our [Workflow configuration examples](/guide/workflows/workflow-configuration-examples.qmd){target="_blank"}.

:::

:::

::: {.column width="70%" .bl .pl4 .f4}

{{< include /guide/workflows/_configure-model-workflows.qmd >}}

To set up a new custom workflow, you'll need to complete these three steps in sequence:

::: {.panel-tabset}

### 1. Add workflow

{{< include /guide/workflows/_add-new-workflows.qmd >}}

### 2. Configure workflow steps

{{< include /guide/workflows/_configure-workflow-steps.qmd >}}

### 3. Link workflow together

{{< include /guide/workflows/_link-workflow-together.qmd >}}

:::

:::
::::

## {background-iframe="https://app.prod.validmind.ai/settings/workflows" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add a model workflow**
:::

1. Click **{{< fa plus >}} Add Workflow**.
2. On the Add New Workflow modal, enter in a **[title]{.smallcaps}** and a **[description]{.smallcaps}** the workflow.
3. Under **[workflow start]{.smallcaps}**, select **Manually**.
4. Under **[workflow expected duration]{.smallcaps}**, define the SLA for the workflow.
5. Click **Add Workflow** to save your blank workflow.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/settings/workflows" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Configure & link workflow steps**
:::

1. Click on the workflow you'd added earlier, then:
    - To add a step, drag and drop a new step onto the canvas. For example: {{< fa arrow-pointer >}} User Action v2
    - Double-click the new step to open up the configuration modal.
2. After you're finished with step configuration, click **Update Step** to apply your changes.
3. After you've configured a step, link your example workflow together:
    - Locate the [**Start**]{.bubble .green .green-bg} of your workflow.
    - Drag from the **{{< fa circle >}}** at the bottom of [**Start**]{.bubble .green .green-bg} to the top **{{< fa circle >}}** on the step you added previously.
4. Designate the end of your workflow by dragging an **{{< fa circle-stop >}} End** step onto the canvas.
5. Link your previous step to the **{{< fa circle-stop >}} End** step by clicking on the bottom **{{< fa circle >}}** of that step, and dragging to the top **{{< fa circle >}}** of the **{{< fa circle-stop >}} End** step.
6. Click **Save Workflow** to apply your changes.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Run model workflows

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/workflows/manage-model-workflows.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

Now, let's initiate our sample workflow manually:

{{< include /guide/workflows/_initiate-model-workflows.qmd >}}

:::
::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Initiate a model workflow**
:::

1. Select the name of your model you registered for this course to open up the model details page.
2. On the landing page of your model, locate the [active workflows]{.smallcaps} section.
3. Click **{{< fa arrow-right-arrow-left >}} See All Workflows**.
4. Select **{{< fa arrow-right >}} Run Workflow** for the workflow you configured earlier, then select **Run Now** under **[workflow start]{.smallcaps}**.
5. Click **{{< fa arrow-right >}} Run Workflow Now** to confirm.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Reset & abort model workflows

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/workflows/transition-model-workflows.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

As an administrator, you may need to reset or abort model workflows as required:

::: {.panel-tabset}

#### Reset workflows

{{< include /guide/workflows/_reset-model-workflows.qmd >}}

#### Abort workflows

{{< include /guide/workflows/_abort-workflows.qmd >}}

:::

:::
::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .auto-collapse-10}
::: {.tc}
**Reset a model workflow**
:::

1. Select the name of your model you registered for this course to open up the model details page.
2. On the landing page of your model, locate the [active workflows]{.smallcaps} section.
3. Click on the name of the workflow you manually initiated earlier to open that workflow's details.
4. Click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa ban >}} Abort Workflow**.
5. Toggle **[restart workflow after aborting]{.smallcaps}** on, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to restart your workflow.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

# Manage regulations & policies {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

{{< include /training/common-slides/_document-checker.qmd >}}

<br>
Learn how to **customize the regulations and policies available to the {{< var vm.checker >}}** on the next pages. {{< fa hand-point-right >}}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Add regulations & policies

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/templates/customize-virtual-document-validator.qmd#manage-regulations-and-policies){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/templates/_regulations-policies.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Regulations & Policies**.

{{< include /guide/templates/_add-regulations-policies.qmd >}}

:::
::::

## {background-iframe="https://app.prod.validmind.ai/settings/regulations" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add a regulation or policy**
:::

1. Click **{{< fa plus >}} Add** to create a new regulation or policy.
2.  Provide a **[regulation or policy name]{.smallcaps}** and an optional **[description]{.smallcaps}**.
3. Click **Add** to create your regulation or policy.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Add assessments

::: {.tc}
[Learn more ...](/guide/templates/customize-virtual-document-validator.qmd#add-or-clone-assessments){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/templates/_assessments.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Regulations & Policies**.

3. Select the regulation or policy you want to add an assessment for by clicking on it.

{{< include /guide/templates/_add-assessments.qmd >}}

:::
::::

## {background-iframe="https://app.prod.validmind.ai/settings/regulations" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add an assessment**
:::

1. Select the regulation or policy you added in the previous step by clicking on it.
2. Click **{{< fa plus >}} Add** to create a new assessment.
3.  Provide an **[assessment name]{.smallcaps}** and an optional **[description]{.smallcaps}**.
6. Click **Add** to create your assessment.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Add assessment questions

::: {.tc}
[Learn more ...](/guide/templates/customize-virtual-document-validator.qmd#add-or-edit-assessment-questions){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/templates/_add-assessment-questions.qmd >}}
:::
::::

## {background-iframe="https://app.prod.validmind.ai/settings/regulations" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add an assessment question**
:::

1. Select the assessment you want to add questions to by clicking on it.
2. Click **{{< fa plus >}} Add Question(s)** to create a new question.
3. Enter in the **[questions]{.smallcaps}**.
4. Click **Add # Question(s)** to insert questions into the assessment.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::


# Configure attestations {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Work with attestations

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/attestation/working-with-attestations.qmd){.button target="_blank"}
:::


:::

::: {.column width="70%" .bl .pl4 .f3}

{{< include /guide/attestation/_attestations.qmd >}}

::: {.panel-tabset}

#### Attestation periods

Attestation periods are typically scheduled quarterly or annually and should be configured to align with regulatory or internal review cycles.

#### Attestation fields

By default, attestations include the model name. Add additional model inventory fields as needed.

#### Questionnaires

Attestation questionnaires should confirm that key controls, governance processes, and documentation requirements have been followed.

:::

:::

<br>Learn how to **set up attestations** on the next page. {{< fa hand-point-right >}}


::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Set up attestations

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/attestation/set-up-attestations.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}

:::

::: {.column width="70%" .bl .pl4 .f3}

::: {.panel-tabset}

#### 1. Add attestations

{{< include /guide/attestation/_add-attestations.qmd >}}

#### 2. Configure attestations

::: {.f4}

{{< include /guide/attestation/_configure-attestations.qmd >}}

:::

:::

:::

::::

## {background-iframe="https://app.prod.validmind.ai/settings/attestations" background-interactive="true" data-preload="yes"}

:::: {.slideover--b .three-quarters .auto-collapse-10}
::: {.tc}
**Add an attestation**
:::

1. Click **{{< fa plus >}} Add Attestation**.
2. Enter a **[name]{.smallcaps}** and **[description]{.smallcaps}** for the attestation.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/settings/attestations" background-interactive="true" data-preload="yes"}

:::: {.slideover--l .three-quarters .auto-collapse-10}
**Configure an attestation**

Click on the name of the attestation you added previously to configure it:

1. Click **{{< fa plus >}} Add Attestation Period** and add a period.
    - Enter in the **[name]{.smallcaps}**, **[start date]{.smallcaps}**, and **[end date]{.smallcaps}**.
    - Click **Add Period**.
2. Under Relevant Attestation Fields, drag fields into the **Relevant Attestation Fields** column to display in model snapshots.
3. Under Questionnaire Template, click the template area to edit, then click **Save** to apply your changes.

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

# In summary {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
{{< var vm.product >}} for model risk management

:::

::: {.column width="70%" .bl .pl4 .f3}
In this third module, you learned how to:

- [x] Use {{< var vm.product >}} to oversee your entire MRM lifecycle
- [x] Set up model stages and custom workflows
- [x] Manage and review workflows on models
- [x] Set up and schedule attestations

:::
::::

::: {.tc}
<br>
Continue your {{< var vm.platform >}} administration journey with:
<br><br>
<!-- IMPORTANT: USE THE .HTML PATH AND NOT THE .QMD PATH FOR THE REVEALJS OUTPUT -->
[Organizational Oversight & Reporting](organizational-oversight-reporting.html){.button target="_blank"}
:::
