---
title: "ValidMind <br>Documentation 2.0"
subtitle: "Part 1 — Get Started"
lightbox: true
# REMOVE THE SEARCH FALSE TOGGLE WHEN THE COURSE IS READY TO BE PUBLISHED
search: false
format:
  revealjs:
    controls: true
    controls-tutorial: true
    help: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /validmind.png
    footer: "{{< var vm.product >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/index.qmd)"
  html:
  # Change this to the file name prepended by a _ to get around the global HTML output settings required by _metadata.yml
    output-file: _course-slides.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

# A story

_Imagine a new user landing on our site. They're excited to try our product — but what does the ideal user journeys look like?_

## In this demo

1. [An immediate problem](#an-immediate-problem)
2. [Towards a fix](#towards-a-fix)
3. [Live preview](#live-demo)

# An immediate problem {background-color="#083E44" background-image="../assets/home-hero.svg"}

## {background-iframe="https://docs.validmind.ai/" background-interactive="yes" data-preload="yes"} 

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f4 .tc .pl4 .pr4 .overlay}
Our current documentation experience presents **too many choices** without a clear call to action for non-developers.

::::

## {background-iframe="https://docs.validmind.ai/" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f3 .pl4 .pr4 .overlay}
::: {.tc}
**The homepage experience**
:::

::: {.f4}
The "Get Started" section is buried under a layer of navigation, making harder for new users to find what they need.

- The three main card tiles lack clear, compelling next actions.
- Prime real estate is used for secondary content, like blog and event links, instead of actionable next steps for users.
:::
::::

## {background-iframe="https://docs.validmind.ai/about/overview.html" background-interactive="yes" data-preload="yes"}

:::: {.fr .f3 .mv5 .nr4 .pa5 .overlay}
::: {.f2}
**Content & navigation**
:::

- The “About” section is overloaded with<br> different content types that could be separated.
- Meanwhile, sections like “Support” and “FAQ”<br> could be combined to simplify navigation.

::::

# Towards a fix {background-color="#083E44" background-image="../assets/home-hero.svg"}

<!-- USE `.scrollable` IN AN H2  -->
## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
How can we fix this?

::: {.f3}
<br>Experience a mockup **live** on the next page. {{< fa hand-point-right >}}
:::
:::

::: {.column width="70%" .bl .pl4 .f3}
- **Prioritize a** **clear CTA** for onboarding—make "Getting Started" prominent and accessible to all users.
- **Improve content segmentation** so that users can easily navigate based on their role and experience level.
- **Streamline the** **navigation structure**, reducing unnecessary layers and surfacing key information faster.
- **Optimize homepage real estate** to focus on user action rather than secondary content.

::: {.panel-tabset}

### Guiding principles

::: {.f4}
To address the issues with onboarding and documentation clarity, the following principles guide the redesign:

1. **Flatten the navigation**: Refuce redundancy & streamline entry points, prioritizing access to key resources.
2. **Simplify user tasks**: Highlight the most common actions users need to take, and ensure these tasks are surfaced intuitively.
3. **Reduce verbiage**: Keep instructions and descriptions concise and actionable to help users find what they need quicker.
4. **Segment and sequence content types**: Reevaluate core guides and ensure that all "potals" follow a similiar visual and structural identity.
:::

### Content segmentation

::: {.f4}
To improve content segmentation, the site has already been evolving towards three distinct portals. Each portal has its own identity, reducing content overlap and making it easier for users to find relevant information:

1. **User guides** — Structured for general users, focusing on step-by-step instructions, best practices, and troubleshooting. (More a landing page than a portal today.)
2. **Developer portal** — A dedicated space for notebooks, Python API reference, and code samples.
3. **Training portal** — Learning resources, tutorials, and future certification program, following the current training portal standard.

:::

:::

:::
::::

## {background-iframe="https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7863/solidify-ideal-new-site-structure/index.html" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f3 .pl4 .pr4 .overlay}
::: {.tc}
**A simpler home page**
:::

::: {.f4}
- Our future homepage reimagines user onboarding by making "Getting Started" an immediate, accessible experience for all user roles, worded in a way that is also welcoming to aspiring MRM professionals.
- Instead of forcing users to dig through layers of navigation, the homepage itself now serves as the entry point for their journey.
:::
::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
A focused, role-based onboarding experience

::: {.f3}
<br>Experience a before and after mockup **live** on the next page. {{< fa hand-point-right >}}
:::
:::

::: {.column width="70%" .bl .pl4 .f3}
- **A clear value proposition**—what ValidMind helps them achieve.
- **A simple "getting started" path**—highlighting key actions upfront.
- **A single, focused call to action**—eliminating confusion on what to do next.

::: {.callout}
This approach means that developers can **dive straight into the library** with a code snippet and sample workflows. Validators see **compliance-focused tools that link to regulatory needs**. And admins find **clear onboarding steps** to manage users and workflows.
:::

:::

The new onboarding section delivers clarity and direction for every user role. Instead of a generic starting point, each persona — developers, validators, and admins — gets a tailored experience that aligns with their specific needs.

::::

## {background-iframe="https://docs.validmind.ai/get-started/get-started.html" data-preload="yes"}

:::: {.fr .f3 .mv5 .nr4 .pa5 .overlay}
::: {.f2}
**Current getting started ...**
:::

- We have a QuickStart, **but it works only for developers.**
- Everyone else gets deep links into the documentation
<br> without a structured learning journey.

::: {.f4 .pl3 .pr3 .embed}
But even for developers, **the segmentation of content is not entirely clear.**
:::

::::

## {background-iframe="https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7863/solidify-ideal-new-site-structure/get-started/get-started.html" data-preload="yes"}

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f3 .pl4 .pr4 .overlay}
::: {.tc}
**One role, one path**
:::

::: {.f4}
By structuring onboarding around distinct personas, we eliminate guesswork and ensure that each user can engage with ValidMind, makes the platform more approachable for everyone.
:::
::::

## {background-iframe="https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7863/solidify-ideal-new-site-structure/index.html#overview" background-interactive="yes" data-preload="yes"}

:::: {.fr .f3 .mv5 .nr4 .pa5 .overlay}
::: {.f2}
**Beyond role-based onboarding**
:::

Beyond just guiding users into the platform, 
<br>the new home page will also explain our 
<br>value proposition to a broader audience.

::::

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Enable more than one persona

::: {.f4}
Whether they are an admin setting up the system or a validator reviewing models, they are met with a targeted QuickStart experience that helps them achieve their goals efficiently and confidently.
:::
:::

::: {.column width="70%" .bl .pl4 .f3}
The homepage will highlight key capabilities: proactive risk management for more reliable models, compliance support for evolving regulations, cross-functional collaboration for transparency, and continuous monitoring to catch issues early. 

As part of this effort, we plan to rework our "About" section to cover:

- **Value proposition** for ValidMind as a platform
- **Product tour** for a quick, general overview
- **A general CTA** for when we have piqued curiosity

:::

The idea here is that ValidMind goes beyond compliance — the platform builds confidence in every model decision.

::::

## {background-iframe="https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7863/solidify-ideal-new-site-structure/support/support.html" background-interactive="yes" data-preload="yes"}

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f3 .pl4 .pr4 .overlay}
::: {.tc}
**An improved support experience**
:::

::: {.f4}
As part of flattening our navigation, we can also improve the support experience by combining our main “Support” landing page with our “FAQ” section.
:::
::::

## {background-iframe="https://docs.validmind.ai/developer/get-started-validmind-library.html" background-interactive="yes" data-preload="yes"}

:::: {.absolute bottom=15 left=0 right=50 .w-100 .tc .f3 .pl4 .pr4 .overlay}
**Current developer portal ...**

::: {.f4}
Mish-mash of random user guides and conceptual overload.
:::
::::


## {background-iframe="https://docs-demo.vm.validmind.ai/pr_previews/beck/sc-7863/solidify-ideal-new-site-structure/developer/get-started-validmind-library.html" background-interactive="yes" data-preload="yes"}

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f3 .pl4 .pr4 .overlay}
::: {.tc}
**A refined, structured experience for developers**
:::

::: {.f4}
The redesigned ValidMind developer portal transforms onboarding into a clear, guided journey that helps developers get started quickly and efficiently.
:::
::::

# Live preview {background-color="#083E44" background-image="../assets/home-hero.svg"}

## Have feedback?

Great! Head to PR#638 in the `documentation` repo and leave some comments:

::: {.tc}
<!-- CHANGE THIS TO THE RELEVANT USER GUIDE SECTION -->

[PR#638](https://github.com/validmind/documentation/pull/638){.button target="_blank"}
:::
<br>

Click **LIVE PREVIEW** to bring up the smoke & mirrors mockup used by this demo. The ideas in this mockup are just that — ideas. Design and refinement to come (with your help!).