---
title: "Try it in your own developer environment"
date: last-modified
aliases:
  - /guide/quickstart-try-developer-framework-in-your-own-developer-environment.html
---

Learn how to document a model with {{< var vm.product >}} locally in your own developer environment. You can either clone our open-source repository or download the code samples to run the notebook.

::: {.attn}

## {{< fa star-of-life >}} Before you begin

To try out {{< var vm.product >}}, you need to be a registered user on the {{< var validmind.platform >}}.

::: {.callout}
## Need an account for {{< var vm.product >}}?
Signing up is FREE — {{< var link.register >}} 
:::

You should be familiar with using standard software development tools, including the command line, and have a developer environment set up locally, such as Visual Studio Code. 

- To run our sample Jupyter Notebooks locally, your developer environment must support Python {{< var version.python >}}.
- To clone our open-source repository, you must have access to [GitHub](https://github.com/). Alternatively, you must be able to download a `.zip` file containing our code samples that include the introductory Jupyter Notebook.

:::

## Steps

Start by retrieving our notebook samples from GitHub, or download them from our website.

#### Option 1: Clone the open-source repository

1. Open a terminal or command prompt.

2. Navigate to the directory where you want to clone the repository.

3. Run the following command: 

   ```bash
   git clone https://github.com/validmind/validmind-library.git
   ```

4. After the cloning process is complete, open `notebooks/quickstart/quickstart_model_documentation.ipynb` in your developer environment and [run the notebook](#run-the-notebook).

   The notebook will guide you through installing the {{< var validmind.developer >}}, initializing the Python environment, and finally connecting the {{< var vm.developer >}} to the {{< var validmind.platform >}}.

#### Option 2: Download the code samples 

1. Download our selection of code samples: [`notebooks.zip`](/notebooks.zip)

2. Navigate to the location where you saved `notebooks.zip` and extract the contents.

   Depending on your operating system, you can right-click on `notebooks.zip` and select **Extract All ...** or **Extract Here**, for example.

3. Navigate to the folder where you extracted the files.

4. Open `notebooks/quickstart/quickstart_model_documentation.ipynb` in your developer environment and [run the notebook](#run-the-notebook).

   The notebook will guide you through installing the {{< var validmind.developer >}}, initializing the Python environment, and finally connecting the {{< var vm.developer >}} to the {{< var validmind.platform >}}.

### Run the notebook

1. Follow the instructions to run the first two code cells in the notebook, which will set the stage by installing and initializing {{< var vm.product >}}:[^1]

   - Hover over each cell and click the {{< fa circle-play >}} **icon**; OR
   - Press `Shift + Enter` on Windows or `Cmd + Enter` if you are on a Mac

   
2. Under the cell at bottom of the **Initialize the ValidMind Library** section, confirm that you see a success message that looks something like this:
   
    ```bash
    2024-10-08 22:06:42,610 - INFO(validmind.api_client): 🎉 Connected to {{< var vm.product >}}!
    📊 Model: [Demo] Customer Churn Model (ID: clwqy70qd01my22ikc49paar9)
    📁 Document Type: model_documentation
    ```
   
    This message verifies that the {{< var vm.developer >}} works as expected as is connected to the correct model within the {{< var vm.platform >}}. 

You can now continue running the rest of the cells if you want to see how the demo notebook works or, to save some time, you can move on to the [Explore sample model documentation](/get-started/platform/explore-sample-model-documentation.qmd) to explore the {{< var vm.platform >}}. 

## What's next

Continue with [Explore sample model documentation](/get-started/platform/explore-sample-model-documentation.qmd) to learn more about using the {{< var validmind.platform >}} hands-on.


<!-- FOOTNOTES -->

[^1]: [Install and initialize the {{< var validmind.developer >}}](/developer/model-documentation/install-and-initialize-validmind-library.qmd)
