---
title: "September 26, 2023"
keywords: "release notes, ai risk, model risk management, ValidMind"
date: last-modified
---

## Release highlights

In this release, we've added support for large language models (LLMs) to enhance the capabilities of our Developer Framework, along with a number of new demo notebooks that you can try out. Other enhancements improve the experience for developers and with our documentation.

### ValidMind Developer Framework (v1.19.0)

<!---John6797/sc 2062/sentiment analysis demo notebook should support by @johnwalz97 in [#224](https://github.com/validmind/validmind-python/pull/224)--->
- **Sentiment analysis notebook demo for large language model (LLM) support**. We added initial support for large language models (LLMs) in ValidMind via the new `FoundationModel` class. Users can create an instance of a `FoundationModel` and specify `predict_fn` and a `prompt` and pass that into any test plan or test suite, for example. The `predict_fn` must be defined by the user and implements the logic for calling the Foundation LLM (usually via API).

<!---John6797/sc 2088/implement prompt validation metrics poc by @johnwalz97 in [#232](https://github.com/validmind/validmind-python/pull/232)--->
- **Implement prompt validation metrics**. As a proof of concept, we added initial native prompt validation tests to the Developer Framework. It also adds a demo notebook and simple template to test out these metrics on the Sentiment Analysis LLM model we have built.

::: {.callout-tip}
## Interested in our LLM functionality?
Large language model (LLM) functionality will be part of our closed beta: 

- [Read the announcement](https://validmind.com/announcing-validminds-closed-beta-coming-soon/)
- [Join the waitlist](../../guide/join-closed-beta.qmd)
:::

<!---SC-2061: Support hugging face models by @AnilSorathiya in [#222](https://github.com/validmind/validmind-python/pull/222)--->
- **Support for Hugging Face models**. ValidMind can now validate pre-trained models from the HuggingFace Hub, including any language model compatible with the HF transformers API. 
   
   Includes a **financial news sentiment analysis demo** that runs documentation tests for a Hugging Face model with text classification using the [financial_phrasebank](https://huggingface.co/datasets/financial_phrasebank). [Try it ...](../../notebooks/llm/hugging_face_integration_demo.ipynb)

<!---[SC-1956] Credit risk scorecard demo notebooks by @juanmleng in [#223](https://github.com/validmind/validmind-python/pull/223)--->
- **New credit risk scorecard demo notebooks**. We added demo notebooks and supporting files for:
  - Developing credit risk scorecards. [Try it ...](../../notebooks/credit_risk_scorecard_development_demo.ipnyb)
  - Validating credit risk scorecards. [Try it ...](../../notebooks/credit_risk_scorecard_validation_demo.ipnyb)

<!---
### ValidMind Platform UI (v1.6.0)
--->

## How to upgrade

To access the latest version of the [ValidMind Platform UI](http://app.prod.validmind.ai/), reload your browser tab.

To upgrade the ValidMind Developer Framework:

- [Using Jupyter Hub](../../guide/try-developer-framework-with-jupyterhub.qmd): reload your browser tab and re-run the `!pip install --upgrade validmind` cell.

- [Using Docker](../../guide/try-developer-framework-with-docker.qmd): pull the latest Docker image:
    
    ```jsx
    docker pull validmind/validmind-jupyter-demo:latest
    
    ```
    
- [In your own developer environment](../../guide/install-and-initialize-developer-framework.qmd): restart your notebook and re-run:
    
    ```python
    !pip install validmind
    ```