---
title: "Document models"
date: last-modified
---

Generate model documentation starting with your model or model predictions, load your model or predictions into the {{< var vm.developer >}}, then finally view the results and refine your documentation in the {{< var vm.platform >}} to make it ready for approval.

::: {.prereq}

## Prerequisites 

- [x] {{< var link.login >}}
- [x] You are the model owner.
- [x] You are a `Developer` or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## End-to-end workflow  

### In your modeling environment

1. Build your model or your model predictions.[^2]

2. Export the datasets and model or predictions.

### With the {{< var validmind.developer >}}

1. **From your modeling environment**, load the trained datasets and models or predictions.

2. [Install and initialize the client library.](install-and-initialize-client-library.qmd)

3. Select the relevant tests.

4. Review if all tests are covered by ValidMind or your external test provider:
    
   - **If all tests are NOT covered** — Create and register additional tests.
   - **If all tests are covered** — 
      a. Run the selected tests.
      b. Review your test results. 

### In the {{< var validmind.platform >}}

1. **After installing and initalizing the {{< var validmind.developer >}}**,[^4] add content blocks[^3] to your model documentation: 
   
   Select the block type:
   
      - **For test-driven blocks** — Select from available test provider results[^5]
      - **For text blocks** — 
         
         a. For new block:
            1. Add new editable text content block
            2. Review and collaborate on the content block
         b. For existing blocks: Select from available texts from content provider

2. [Submit your model documentation for review](/guide/model-documentation/submit-for-approval.qmd).

## What's next 

- [Store project credentials in `.env` files](store-credentials-in-env-file.qmd)
- [Work with test results](work-with-test-results.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: 

   **No available model?**<br>
   You can still run tests and log documentation with ValidMind as long as you're able to [load the model predictions](/faq/faq-documentation.qmd#can-i-run-tests-and-log-documentation-without-having-a-model-available). 

[^3]: [Work with content blocks](/guide/model-documentation/work-with-content-blocks.qmd)

[^4]: [Install and initialize the client library](install-and-initialize-client-library.qmd)

[^5]: [Work with test results](work-with-test-results.qmd)
