---
title: "Generate model documentation"
date: last-modified
---

Generate model documentation starting with your model or model predictions, load your model or predictions into the {{< var validmind.developer >}}, then finally view the results and refine your documentation in the {{< var validmind.platform >}}.

::: {.prereq}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are the model owner.
- [x] You are a `Developer`, or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## End-to-end workflow

### In your modeling environment

1. Build your model or your model predictions.

2. Export the datasets and model or predictions.

Next, go to **With the {{< var validmind.developer >}}, Step 2**.  {{< fa arrow-right >}}

### With the {{< var validmind.developer >}}

1. Create a notebook to select and build the relevant tests.

2. {{< fa arrow-right >}} **From your modeling environment**, load the trained datasets and models or predictions.

3. {{< fa arrow-right >}} Use the instructions from **In the {{< var vm.platform >}}, Step 3**, [initialize the {{< var validmind.developer >}}](install-and-initialize-developer-framework.qmd).

4. Select the relevant tests.

5. Review if all tests are covered by ValidMind or your external test provider:
    
   - If all tests are NOT covered — Create and register additional tests.
   - If all tests are covered — 
      a. Run the selected tests.
      b. Review your test results. 

Next, go to **In the {{< var validmind.platform >}}, Step 5**.  {{< fa arrow-right >}} 

### In the {{< var validmind.platform >}}

1. [Register a new model](/guide/model-inventory/register-models-in-inventory.qmd).

2. Review the template structure.

3. [Locate the {{< var vm.developer >}} integration instructions](install-and-initialize-developer-framework.qmd#locate-the-framework-integration-instructions). 
   
4.  Go to **With the {{< var validmind.developer >}}, Step 3**. {{< fa arrow-right >}}

5. {{< fa arrow-right >}} After **With the {{< var validmind.developer >}}, Step 6**, [add content blocks](/guide/model-documentation/work-with-content-blocks.qmd) to your model documentation: 
   
   Select the block type:
   
      - **For test-driven blocks** — Select from available test provider results[^2]
      - **For text blocks** — 
         
         - For new block:
            - Add new editable text content block
            - Review and collaborate on the content block
         - For existing blocks: Select from available texts from content provider

6. [Submit your model documentation for review](/guide/model-documentation/submit-for-approval.qmd).

## What's next

- [Store project credentials in `.env` files](store-credentials-in-env-file.qmd)
- [Work with test results](work-with-test-results.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Work with test results](work-with-test-results.qmd)
