---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
# USING THE VARIABLE IN THE TITLE MESSES UP THE BREADCRUMB
title: "Install and initialize the ValidMind Library"
date: last-modified
aliases:
  - install-and-initialize-validmind.html
  - /guide/install-and-initialize-validmind-library.html
  - /guide/install-and-initialize-developer-framework.html
  - install-and-initialize-client-library.html
---

Initialize the {{< var validmind.developer >}} with the _code snippet_ unique to each model per document to connect your environment to the {{< var validmind.platform >}}, ensuring test results are uploaded to the correct model and automatically populated in the right document.


::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model you want to connect to is registered in the model inventory.[^1]
- [x] The model document has a template applied.[^2]
- [x] You are the model owner, model validator, or another model stakeholder with write access to the model's documents.[^3]

::: {.callout}
The {{< var validmind.developer >}} requires access to the data sources where relevant datasets and model files are stored in order to help you run tests.

:::


:::

## Installing the {{< var validmind.developer >}}

In order to upload test results from the {{< var validmind.developer >}} to the {{< var validmind.platform >}}, provide the following information through a code snippet copied from the {{< var vm.platform >}}:

| Argument      | Description                        |
|---------------|------------------------------------|
| `api_host`    | The location of the {{< var vm.product >}} API  |
| `api_key`     | The account API key                |
| `api_secret`  | The account secret key             |
| `document`  | The model document identifier key             |
| `model`     | The model identifier             |

### Get your code snippet

Retrieve your code snippet for your model's selected document from the {{< var validmind.platform >}}:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model by clicking on it or find your model by applying a filter or searching for it.[^4]

3. In the left sidebar that appears for your model, click **{{< fa rocket >}} Getting Started**.

4. Select the **[document]{.smallcaps}** you want to automatically upload test results to.[^5]

5. Locate the code snippet and click **{{< fa regular copy >}} Copy snippet to clipboard**.

### Install the {{< var vm.developer >}}

To install the {{< var vm.developer >}}:

```python
%pip install validmind
```

### Initialize the {{< var vm.developer >}}

To initialize the {{< var vm.developer >}}, paste the code snippet with the client integration details directly into your development source code, replacing this example with your own:

```python
import validmind as vm

vm.init(
  api_host = "{{< var api.host >}}/tracking",
  api_key = "API_KEY",
  api_secret = "API_SECRET",
  document="document-key", # requires library >=2.12.0
  model = "MODEL_IDENTIFIER"
)
```

:::{.callout}
To also enable monitoring, add `monitoring=True` to the `vm.init` method in your code snippet. [^6]
:::

After you run the code snippet in your environment, the {{< var validmind.developer >}} will connect to your model and selected document in the {{< var validmind.platform >}}. Automate your workflow by using the {{< var vm.developer >}} to run tests, then seamlessly upload your test results to the {{< var vm.platform >}}.

## Upgrade the {{< var validmind.developer >}}

After installing {{< var vm.product >}},[^7] you'll want to periodically make sure you are on the latest version to access any new features and other enhancements: 

1. In your Jupyter Notebook or developer environment, retrieve the information for the currently installed version of {{< var vm.product >}}:

    ```python
    %pip show validmind
    ```

::: {.column-margin}
**Example output:**
```bash
Name: validmind
Version: 2.5.15
...
```
:::

2. If the version returned is lower than the version indicated in our production open-source code,[^8] run the following command:

    ```python
    %pip install --upgrade validmind
    ```

<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with templates](/guide/templates/working-with-document-templates.qmd)

[^3]: [Manage model stakeholders](/guide/model-inventory/edit-model-inventory-fields.qmd#manage-model-stakeholders)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^6]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^7]: [Install {{< var vm.product >}}](#install-validmind)

[^8]: **ValidMind GitHub:** [validmind-library/validmind/&lowbar;&lowbar;version&lowbar;&lowbar;.py](https://github.com/validmind/validmind-library/blob/prod/validmind/__version__.py)