---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Store model credentials in `.env` files"
date: last-modified
aliases:
  - /guide/store-credentials-in-env-file.html
listing:
  - id: whats-next
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    grid-columns: 2
    contents:
    - ../how-to/testing-overview.qmd
    - ../how-to/feature-overview.qmd
---

Learn how to store model identifier credentials in a `.env` file instead of using inline credentials, allowing you to follow best practices for security when running Jupyter Notebooks.

<br>

::: {.callout-button .pl4 .nt4}
::: {.callout collapse="true" appearance="minimal"}
### Why is it recommended to store credentials in a `.env` file?

Storing credentials in a `.env` file is considered a best practice for security. Embedding credentials directly within the code makes them more susceptible to accidental exposure when sharing code or collaborating on models.

Keeping model credentials in a separate file also allows for precise access control and ensures that sensitive credentials are not publicly accessible.

:::
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model is registered in the model inventory.[^1]
- [x] You are the model owner, model validator, or another model stakeholder with sufficient permissions to perform the tasks in this guide.[^2]

::: {.callout}
Before you follow the steps on this page, we recommend that you first complete our introductory guide on how to [Install and initialize the {{< var validmind.developer >}}](/developer/model-documentation/install-and-initialize-validmind-library.qmd).

:::

:::

## 1. Store credentials in an `.env` file

::: {.panel-tabset}

### a. Get your code snippet

In the {{< var validmind.platform >}}, retrieve the code snippet for your model:

i. In the left sidebar, click **{{< fa cubes >}} Inventory**.

ii. Select a model by clicking on it or find your model by applying a filter or searching for it.[^3]

iii. In the left sidebar that appears for your model, click **{{< fa rocket >}} Getting Started**.

iv. (Optional) Select the **[document]{.smallcaps}** you want to automatically upload test results to.[^4]

v. Locate the code snippet and click **{{< fa regular copy >}} Copy snippet to clipboard**.

### b. Create an `.env` file

i. Create a new file in the same folder as your notebook and name it `.env`.

   This is a hidden file, so you may need to change your settings to view it.

ii. Use the code snippet from your clipboard to build the credentials in your `.env` file in the following format:[^5]

      ```yaml
      VM_API_HOST=<api_host>
      VM_API_KEY=<api_key>
      VM_API_SECRET=<api_secret>
      VM_API_MODEL=<model>
      ```

To define the document to connect the {{< var validmind.developer >}} to, or to enable monitoring, include these in your `vm.init()` snippet within your Jupyter Notebook.[^6]

:::

## 2. Use credentials in your Jupyter Notebook

a. After installing the {{< var validmind.developer >}} within your Jupyter Notebook,[^7] insert this code snippet in a code cell above your model identifier credentials:

   ```python
   %load_ext dotenv
   %dotenv dev.env
   ```

b. Remove the inline credentials from `vm.init()` after importing the {{< var vm.developer >}}:

   ::: {.panel-tabset}

   ### Without ongoing monitoring

   Example updated code cell:

   ```python
   %load_ext dotenv
   %dotenv .env

   import validmind as vm

   vm.init(
      document="document-key",
   )
   ```

   ### With ongoing monitoring

   Example updated code cell including ongoing monitoring:[^8]

   ```python
   %load_ext dotenv
   %dotenv .env

   import validmind as vm

   vm.init(
      document="monitoring",
      monitoring=True
   )
   ```

   :::

   ::: {.callout}
   ## A template must already be applied to your selected document to populate test results in the {{< var validmind.platform >}}.

   Selecting a document to connect to requires {{< var validmind.developer >}} version >=2.12.0.[^9] Attempting to initialize the {{< var vm.developer >}} with a document that does not have a template applied will result in an error.

   :::

c. Run the cell.

   Instead of using inline credentials, this code cell will now load your model credentials from a `.env` file.

## What's next

:::{#whats-next}
:::


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Manage model stakeholders](/guide/model-inventory/edit-model-inventory-fields.qmd#manage-model-stakeholders)

[^3]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^4]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^5]:

    For example, if your credentials look like this:

    ```python
    import validmind as vm

    vm.init(
    api_host = "https://api.prod.validmind.ai/api/v1/tracking",
    api_key = "key123",
    api_secret = "secret456",
    document = "document-key",
    model = "model789"
    )
    ```

    Then your `.env` file should look like this:

    ```bash
    VM_API_HOST=https://api.prod.validmind.ai/api/v1/tracking
    VM_API_KEY=key123
    VM_API_SECRET=secret456
    VM_API_MODEL=model789
    ```

[^6]: [Use credentials in your Jupyter Notebook](#use-credentials-in-your-jupyter-notebook)

[^7]: [Install and initialize the {{< var validmind.developer >}}](/developer/model-documentation/install-and-initialize-validmind-library.qmd#install-the)

[^8]: [Enable monitoring](/guide/monitoring/enable-monitoring.qmd)

[^9]: [Install and initialize the {{< var validmind.developer >}}](/developer/model-documentation/install-and-initialize-validmind-library.qmd#install-the)
