---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Video Intros & Outros"
subtitle: "_Need an intro slide for a video? Simply add another page to this presentation and start your video recording with that. (Same for outros.)_"
search: false
format:
  revealjs:
    controls: false
    progress: false
    controls-tutorial: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, custom.scss]
    slide-number: false
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: favicon.svg
    footer: ""
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "home-hero.svg"
---

# Intros for training modules

# Developer Fundamentals {background-color="#083E44" background-image="home-hero.svg"}

_docs.validmind.ai/training_

# Train a model {background-color="#083E44" background-image="home-hero.svg"}

# Validating Models 101 {backgrouqnd-color="#083E44" background-image="home-hero.svg"}

_docs.validmind.ai/training_

# Intros for task videos

# Register as a new user {background-color="#083E44" background-image="home-hero.svg"}

# Intros for FAQ-style videos

# How do I ... add tests? {background-color="#083E44" background-image="home-hero.svg"}

# Intros for product stuff

# Product Tour {background-color="#083E44" background-image="home-hero.svg"}

# Model Inventory {background-color="#083E44" background-image="home-hero.svg"}

# Documentation, Templates, and Validation {background-color="#083E44" background-image="home-hero.svg"}

# Outros

<!-- Just a blank slide for now -->

# {background-color="#083E44" background-image="home-hero.svg"}
