---
title: "December 13, 2023"
---

## Release highlights

This release includes bug fixes for the {{< var validmind.platform >}} and reduces the external dependencies for our user-facing documentation site. 

## Bug fixes 

<!---Makes author's name contextual to currently logged user by @gtagle in [#492](https://github.com/validmind/frontend/pull/492)--->
- **Contextualize references to the current user**. We fixed an issue where activity logs indicated user references out of context, displaying the current user's full name instead of referring to them as "you".

<!---Respect width/height when available by @cachafla in [#498](https://github.com/validmind/frontend/pull/498)--->
- **Respect width and height for plots when available**. We fixed an issue where some plots were being cut off due to having more height than available in the current viewport. This issue was fixed by respecting the plot's original defined height instead of setting a maximum pre-configured height on the frontend.

## Documentation updates

<!---Remove safe external dependencies by @nrichers in [#147](https://github.com/validmind/documentation/pull/147)--->
**Remove safe external dependencies**. To improve loading times and reduce the reliance on being connected to the internet, we removed some external dependencies for our docs site:

- Fonts are now stored and imported locally
- Some unneeded font references in our template schema docs have been removed

## How to upgrade

To access the latest version of the [{{< var validmind.platform >}}](http://app.prod.validmind.ai/), reload your browser tab.

To upgrade the {{< var validmind.developer >}}:

- [Using JupyterHub](/get-started/developer/try-with-jupyterhub.qmd): Reload your browser tab and re-run the `%pip install --upgrade validmind` cell.

- [In your own developer environment](/developer/model-documentation/install-and-initialize-client-library.qmd): Restart your notebook and re-run:
    
    ```python
    %pip install validmind
    ```