---
title: "Code samples"
date: last-modified
listing:
  type: grid
  image-placeholder: "jupyter-logo-rectangle.svg"
  max-description-length: 250
  image-height: "100%"
  fields: [title, description, reading-time]
  contents: 
    - "../notebooks/code_samples/*/*.ipynb"
    - "../notebooks/code_samples/custom_tests/integrate_external_test_providers.ipynb"
fig-cap-location: top
aliases:
  - /guide/samples-jupyter-notebooks.html
---

Our Jupyter Notebook code samples showcase the capabilities and features of the {{< var validmind.developer >}}, while also providing you with useful examples that you can build on and adapt for your own use cases. 

:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns .mt2 .pb3}

[{{< fa code >}} Try Notebooks on JupyterHub]({{< var url.jupyterhub >}}/){.button .button-green target="_blank"}

:::

::: {.w-30-ns .mt2 .pb3}

[{{< fa download >}} Download Notebooks & Datasets](/notebooks.zip){.button .button-green target="_blank"}

:::

::: {.w-30-ns .mt2 .pb3}

[{{< fa brands github >}} Access Notebooks on GitHub](https://github.com/validmind/validmind-library/tree/main/notebooks){.button .button-green target="_blank"}

:::


::::

## QuickStart for Customer Churn Model Documentation — Full Suite

Learn how to use dataset and model documentation function on a simple customer churn model. The easiest way to try the QuickStart is on JupyterHub or Google Colaboratory:

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}

JupyterHub
: A a web-based platform when you can interact with Jupyter Notebook instances on a shared server. It is commonly used as a collaborative and interactive computing environment for data analysis, scientific research, and programming.

::: {.tc}
[{{< fa code >}} Quickstart on JupyterHub]({{< var url.jupyterhub >}}/hub/user-redirect/lab/tree/quickstart_customer_churn_full_suite.ipynb){.button target="_blank"}

:::

:::

::: {.w-40-ns}

Google Colaboratory (Colab)
: A free Jupyter Notebook environment that runs in the cloud. There, you can work with our Jupyter Notebooks by saving your own copy, write and execute code, share your work to collaborate with others in real-time.

::: {.tc}
[{{< fa brands google >}} Quickstart on Colab](https://colab.research.google.com/drive/1NLtjCFUZV2I_ttGUkiAL9uwGZK_SGUlw?usp=share_link){.button target="_blank"}

:::

:::

::::


## Code samples for your use case
