---
# Sample Kubernetes manifest for configuring the Docker docs site
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validmind-docs
  labels:
    app: validmind-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validmind-docs
  template:
    metadata:
      labels:
        app: validmind-docs
    spec:
      containers:
      - name: validmind-docs
        image: validmind/docs:latest
        ports:
        - containerPort: 80
        env:
        - name: VALIDMIND_URL
          value: "https://your-custom-app.validmind.ai"
        - name: JUPYTERHUB_URL
          value: "https://your-custom-jupyter.validmind.ai"
---
# Option 2: ConfigMap approach (more maintainable)
apiVersion: v1
kind: ConfigMap
metadata:
  name: validmind-docs-config
data:
  VALIDMIND_URL: "https://your-custom-app.validmind.ai"
  JUPYTERHUB_URL: "https://your-custom-jupyter.validmind.ai"
---
# Deployment using ConfigMap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validmind-docs-configmap
  labels:
    app: validmind-docs-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validmind-docs-configmap
  template:
    metadata:
      labels:
        app: validmind-docs-configmap
    spec:
      containers:
      - name: validmind-docs
        image: validmind/docs:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: validmind-docs-config
---
# Service for accessing the documentation
apiVersion: v1
kind: Service
metadata:
  name: validmind-docs
spec:
  selector:
    app: validmind-docs  # Change to validmind-docs-configmap if using the ConfigMap deployment
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 