---
title: "Archive and delete models"
date: last-modified
---

Archive models within the model inventory when they are decommissioned or delete models that you no longer require records of, keeping your inventory accurate and up to date with your organization's current resources.

::: {.callout}
## By default, only the Customer Admin role[^1] can access archived models.

- Archived models are read-only, and do not contribute to sub-data, statistics or reports. 
- Findings from archived models will not be displayed, and reports will not include data from archived models.
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^2]
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

:::

## Change model stages

::: {.callout}
##  Instead of manually modifying your models' stages,[^4] we recommend manipulating stages via customized workflows.[^5]

Workflows increase oversight over the stage transitions of models by providing a more extensive audit history,[^6] and also allow you to wrap other organization policies into your transitions — such as inclusion of specific stakeholder approval.
:::

The model inventory within the {{< var validmind.platform >}} should reflect the state of models within your organization: 

- If you decomission a model, you can archive it within the model inventory. 
- Conversely, if there is a renewed business need for a model that has been archived, you can activate it again.

To change a model's stage:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**. 

2. Select a model or find your model by applying a filter or searching for it.[^7]

3. Click on the [model stage]{.smallcaps} section.

4. You can then select the appropriate stage for the model.

5. Click **Save** to transition the model into your selected stage.

::: {.panel-tabset}

#### Archive models

a. Select **Archived** from the [model stage]{.smallcaps} drop-down menu.

b. Click **Save** to proceed with archival.

c. After you confirm, the model is flagged as archived in the model inventory.

Archived models can be reactivated to make them available for use again in the inventory.

#### Activate models

a. Select **Active** from the [model stage]{.smallcaps} drop-down menu.

b. Click **Save** to proceed with activation.

d. After you confirm, the model is set to active in the model inventory.

:::

## Delete models

If a model was created in error, or you otherwise no longer require a model to be tracked in the model inventory, you can delete it.

::: {.callout-important}
## Model deletion is also permanent and cannot be undone.
:::

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^8]

3. Under the [model stage]{.smallcaps} section, select **Deleted**.

4. After you confirm deletion, the model is removed from the model inventory.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Register models in the inventory](register-models-in-inventory.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Manage model stages](/guide/model-workflows/manage-model-stages.qmd)

[^5]: [Setting up workflows](/guide/model-workflows/setting-up-workflows.qmd)

[^6]: [Working with model workflows](/guide/model-workflows/working-with-model-workflows.qmd)

[^7]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^8]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)
