---
title: "Edit model inventory fields"
date: last-modified
aliases:
  - /guide/edit-model-inventory-fields.html
---

Edit individual detail fields on a model to ensure that model details are accurate and up-to-date.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model is registered in the model inventory.[^1]
- [x] You are the model owner[^2] for the model you would like edit the details of, a [{{< fa hand >}} Customer Admin]{.bubble}, or assigned another role or stakeholder type with sufficient permissions to perform the tasks in this guide.[^3]

:::

## Steps

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^4]

3. Hover over a field until the **{{< fa pencil >}}** appears, then click to make your changes.

4. Click **Save** to apply your changes.

### Manage model stakeholders

1. On the model's detail page, click on the model stakeholder type[^5] you'd like to add users to.

2. Select your desired users from the drop-down menu.

    To remove a user from a stakeholder type, click on the **{{< fa x >}}**  to the right of their name.

3. Click **Save** to apply your changes.

### Manage supporting documentation

::: {.callout title="Uploaded files must be less than 50 MB each in size."}
- To work with attachments on models, first add an attachment inventory field.[^6]
- Select attachments on models as context documents when generating text blocks with AI within your documents.[^7]
:::

::: {.panel-tabset}

#### Add attachments to a model

1. On the model's detail page, click on the header of your attachment field.

{{< include _add-attachments.qmd >}}

#### Remove attachments from a model

1. On the model's detail page, click on the header of your attachment field.

{{< include _remove-attachments.qmd >}}

:::


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](register-models-in-inventory.qmd)

[^2]: [Manage model stakeholders](/guide/model-inventory/edit-model-inventory-fields.qmd#manage-model-stakeholders)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)

[^6]: [Manage model inventory fields](manage-model-inventory-fields.qmd#inventory-field-types)

[^7]: [Work with content blocks](/guide/model-documentation/work-with-content-blocks.qmd#generate-text-with-ai-beta)
