---
title: "Manage model inventory custom fields"
date: last-modified
---

Create and edit custom fields that appear on all models in your model inventory. 

## Prerequisites

- {{< var link.login >}}

- To configure templates, you must hold the `Customer Admin` role.[^1]

## Add or edit custom fields

1. Click **{{< fa gear >}} Settings**.

2. Under Workspace Settings, click **Custom Fields**. Here you can edit existing custom fields, or add a new one:

    - To add a new field, click **+ Add new field**. 
    - To edit an existing field, select **{{< fa pencil >}} Edit** under the Actions column for the desired field.

    At a minimum, you must provide the required information indicated by `*`. You can also choose to indicate that a field is **required on registration**.

3. When you are satisfied with the setup of your field, click **Save**.

#### Custom field types

| Field type | Details | 
|---:|---|
| Single Line Text | Simple text value. |
| Long Text | Toggle **Enable rich text formatting** to create a template using the rich text editor. |
| Single Select | Click **+ Add Option** to define a list of options. |
| Multiple Select | Click **+ Add Option** to define a list of options. |
| Checkbox | A `true`/`false` value set by a toggle. |
| Number | Text value in valid number format. |
| URL | Text value in valid URL format. |
| Date | Date value in `yyyy-mm-dd` format. |
| Date Time | Date value in `yyyy-mm-dd, 24hr` format. |
| Email |Text value in valid email (`user@domain.com`) format. |
| User | Select list pre-populated with users from your User Directory.[^2] |
: {.hover tbl-colwidths="[25,75]"}

## Delete custom fields

1. Click **{{< fa gear >}} Settings**.

2. Under Workspace Settings, click **Custom Fields**. 

3. Select **{{< fa pencil >}} Edit** under the Actions column for the field you'd like to delete.

4. Click **Delete**.

    After you confirm, the field will be removed.

## What's next

- [Register models in the inventory](register-models-in-inventory.qmd)
- [Edit model inventory fields](edit-model-inventory-fields.qmd)
- [Work with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)


<!-- FOOTNOTES -->

[^1]: [Managing users (Supported roles)](/guide/configuration/managing-users.qmd#supported-roles)

[^2]: [Managing users](/guide/configuration/managing-users.qmd)