---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage model inventory fields"
date: last-modified
aliases:
  - manage-inventory-custom-fields.html
  - /guide/manage-inventory-custom-fields.html
includes:
    inventory: true
---

{{< include /guide/model-inventory/_model-inventory-fields.qmd >}}

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## View, search, and filter inventory fields

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Models, select **Model Inventory Fields**.

    Displayed in groups[^2] as lists are the inventory fields available to models in your organization with a quick view of:[^3]

    - Number of workflows that field is used in[^4]
    - The field key
    - The field type[^5]
    - Field description
    - Whether or not the field is required when creating models
    - Quick actions you can take on the inventory field

3. Narrow down existing inventory fields available to your models by searching or filtering for results:

::: {.panel-tabset}

#### Search fields

a. Click **{{< fa magnifying-glass >}} Search** to search by keywords within an inventory field.

b. Select whether to search in the **Title** or **Description**.

c. Click **Search** to narrow down your results by your entered keywords.

    Expand any inventory field group to see more fields.

#### Filter fields

a. Click **{{< fa filter >}} Filter** to filter fields by any of the following criteria:

    - **[required on creation]{.smallcaps}** — Whether or not the field was set up as required on model registration.
    - **[types]{.smallcaps}** — What type of field it is.
    - **[workflow triggered by field]{.smallcaps}** — What workflows are initiated when this field is edited.[^6]
    - **[write permissions]{.smallcaps}** — Which model stakeholder types have permissions to edit this field.[^7]

b. Click **Apply Filters** to narrow down your results by your configured criteria.

    Expand any inventory field group to see more fields.

:::

::: {.callout title="Note that searching and filtering of fields stack."}
For example, if you first search by keyword for `date` under **Title** without clearing that search, any additional filters applied will only apply to the results returned by that initial search.
:::

## Add or edit inventory fields
<span id="add-edit"></span>

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Models, select **Model Inventory Fields**.

    Here you can edit existing inventory fields, or add a new one:

{{< include /guide/model-inventory/_add-edit-inventory-fields.qmd >}}

### Rename custom field keys

To rename the field keys for custom inventory fields:

{{< include /guide/model-inventory/_rename-field-keys.qmd >}}

#### Inventory field types

{{< include /guide/model-inventory/_field-types.qmd >}}

## Add inventory field groups

To group model inventory fields, first create an inventory field group:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Models, select **Model Inventory Fields**.

3. Click **{{< fa plus >}} Add Group** and enter in a **[name]{.smallcaps}** and a **[description]{.smallcaps}** for the group.

4. Click **Create Group** to add the new group.

5. Assign the desired fields to the group.[^8]

## Delete inventory fields

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Models, select **Model Inventory Fields**.

3. Hover over the field you would like to delete.

4. When the **{{< fa ellipsis-vertical >}}** appears under the Actions column, click on it and select [**{{< fa trash-can >}} Delete Field**]{.red}.

5. After you confirm, the field will be removed.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Add inventory field groups](#add-inventory-field-groups)

[^3]:

    ::: {.callout title="Missing column headers?"}
    Click, hold, and drag to the right to reveal additional columns.
    :::

[^4]:

    This count only applies to custom fields.<br>

    [Working with workflows](/guide/workflows/working-with-workflows.qmd)

[^5]: [Inventory field types](#inventory-field-types)

[^6]: [Configure workflows](/guide/workflows/configure-workflows.qmd)

[^7]: [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)

[^8]: [Add or edit inventory fields](#add-or-edit-inventory-fields)