---
title: "Register models in the inventory"
date: last-modified
aliases:
  - /guide/register-models-in-model-inventory.html
---

Register models with {{< var vm.product >}} as the first step towards streamlining your model documentation and validation workflow. 

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are the model owner.[^1]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^2]

:::

## Steps

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Click **{{< fa plus >}} Register Model**.

3. Depending on whether or not your organization has additional fields[^3] required on model registration, input the information on the Register New Model panel.

::: {.panel-tabset}

#### 1. Basic Model Information

If no additional fields are required on creation for your models:

a.  Provide the information outlined in the basic model information fields table below.

b. Click **Register Model** to create a new entry in the model inventory.

c. Click **Next {{< fa angle-right >}}** to continue to assignment of model stakeholders.[^4]

| Field | Description |
|---:|---|
| [model name]{.smallcaps} | The name of your model. |
| [group]{.smallcaps}  | (conditional) If you belong to multiple user groups,[^5] select the group that can see the model. |
| [business unit]{.smallcaps}  | Business unit[^6] associated with the model. |
| [use case]{.smallcaps}  | The model's use case.[^7] |
| [is it a vendor model]{.smallcaps}[?]{.smallercaps}  (optional) | If the model is a vendor model, toggle **Is Vendor Model**.[^8] |
| [vendor name]{.smallcaps}  (conditional) | If the model is a vendor model, provide the vendor's name. |
| [purpose]{.smallcaps}  | Explain what the model will be used for. |
| [preliminary risk tier]{.smallcaps}  | Assign a preliminary risk tier. |
: **Basic model information** fields {.hover tbl-colwidths="[30,70]"}

#### 2. Model Stakeholders

a. Select the model stakeholders to add to the model upon registration.

  - By default, only **[model owner]{.smallcaps}**s are required.
  - Additional optional or required model stakeholders can be configured by your customer admin.

b. Click **Next {{< fa angle-right >}}** to continue to additional model information (if required), or **Register Model** to create a new entry in the model inventory.

#### 3. Additional Model Information

If additional fields are required on model registration for your organization:

a. First enter the basic model information and assign model stakeholders, then click **Next {{< fa chevron-right >}}**.

b. Fill in your organization's required additional fields.

c. Click **Register Model** to create a new entry in the model inventory.

:::


<!-- FOOTNOTES -->

[^1]: [Manage model stakeholders](/guide/model-inventory/edit-model-inventory-fields.qmd#manage-model-stakeholders)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Manage model inventory fields](manage-model-inventory-fields.qmd)

[^4]: [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)

[^5]: [Manage groups](/guide/configuration/manage-groups.qmd)

[^6]: [Manage business units](/guide/configuration/set-up-your-organization.qmd#manage-business-units)

[^7]: [Manage use cases](/guide/configuration/set-up-your-organization.qmd#manage-use-cases)

[^8]: [Vendor model](/about/glossary/glossary.qmd#vendor-model)
