---
title: "Working with the model inventory"
date: last-modified
listing:
  - id: model-inventory
    type: grid
    max-description-length: 250
    grid-columns: 2
    sort: false
    fields: [title, description]
    contents:
      - register-models-in-inventory.qmd
      - customize-model-inventory-layout.qmd
      - edit-model-inventory-fields.qmd
      - customize-model-overview-page.qmd
aliases:
  - /guide/working-with-model-inventory.html
---

Get started with the {{< var vm.product >}} inventory, which tracks comprehensive details for all your models throughout the model lifecycle. The model inventory is customizable and extensible, with a layout that can be configured to suit each user's needs.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]

:::

## Search, filter, and sort models

:::{.callout}
Changes are automatically saved and will affect only your account.
:::

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Use the top buttons to narrow down models and organize the model inventory to your preference:
   - **{{< fa magnifying-glass >}} Search** — Search for models using keywords in the model name.
   - **{{< fa filter >}} Filter** — Filter models using different criteria.[^2]
   - **{{< fa arrow-up-wide-short >}} Sort** — Reorder the list using different criteria in ascending or descending order.[^3]

::: {.callout title="Note that searching, filtering, and sorting of fields stack."}
For example, if you first search by keyword for `ValidMind` without clearing that search, any additional filtering and sorting applied will only apply to the results returned by the previous criteria.

:::

## {{< var vm.product >}} model inventory

:::{#model-inventory}
:::

## What's next

- [Managing the model inventory](managing-model-inventory.qmd)
- [View model activity](view-model-activity.qmd)


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](register-models-in-inventory.qmd)

[^2]:

- [**[business units]{.smallcaps}**](/guide/configuration/set-up-your-organization.qmd#manage-business-units)
- [**[developers]{.smallcaps}**](/guide/configuration/manage-model-stakeholder-types.qmd#manage-stakeholder-types-on-models)
- **[model tiering]{.smallcaps}**
- [**[model stage]{.smallcaps}**](/guide/workflows/manage-model-stages.qmd)
- [**[owners]{.smallcaps}**](/guide/configuration/manage-model-stakeholder-types.qmd#manage-stakeholder-types-on-models)
- [**[use]{.smallcaps}**](/guide/configuration/set-up-your-organization.qmd#manage-use-cases)
- [**[validators]{.smallcaps}**](/guide/configuration/manage-model-stakeholder-types.qmd#manage-stakeholder-types-on-models)
- [**[vendor model]{.smallcaps}**](/about/glossary/glossary.qmd#vendor-model)

[^3]:

- **[name]{.smallcaps}**
- [**[business unit]{.smallcaps}**](/guide/configuration/set-up-your-organization.qmd#manage-business-units)
- [**[use]{.smallcaps}**](/guide/configuration/set-up-your-organization.qmd#manage-use-cases)
- **[tier]{.smallcaps}**
- [**[stage]{.smallcaps}**](/guide/workflows/manage-model-stages.qmd)
- **[creation date]{.smallcaps}**
- [**[vendor name]{.smallcaps}**](/about/glossary/glossary.qmd#vendor-model)
- **[updated date]{.smallcaps}**
- [**[documentation updated date]{.smallcaps}**](/guide/model-documentation/working-with-model-documentation.qmd)