name: Create .env file
description: Creates the `.env` file on the fly from GitHub secrets

inputs: {}

runs: 
  using: "composite"
  steps: 
    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo VM_API_HOST=${{ secrets.PLATFORM_API_HOST }} >> .env 
        echo VM_API_KEY=${{ secrets.PLATFORM_API_KEY }} >> .env 
        echo VM_API_SECRET=${{ secrets.PLATFORM_API_SECRET }} >> .env 
        echo VM_API_MODEL=${{ secrets.PLATFORM_DEV_MODEL }} >> .env 
        cat .env