---
title: "October 25, 2023"
keywords: "release notes, ai risk, model risk management, ValidMind"
---

## Release highlights

<!---Platform overview rewrite by @nrichers in [#138](https://github.com/validmind/documentation/pull/138)--->
- **Platform overview rewrite**. We expanded our platform overview to provide more background information about what ValidMind offers and how we enable you to comply with policies and regulations such as SR 11-7 and SS1/23. [Read more ...](../../guide/overview.qmd)



### ValidMind Developer Framework (v1.22.0)


### ValidMind Platform UI (v1.8.0)


## How to upgrade

To access the latest version of the [ValidMind Platform UI](http://app.prod.validmind.ai/), reload your browser tab.

To upgrade the ValidMind Developer Framework:

- [Using Jupyter Hub](../../guide/try-developer-framework-with-jupyterhub.qmd): reload your browser tab and re-run the `!pip install --upgrade validmind` cell.

- [Using Docker](../../guide/try-developer-framework-with-docker.qmd): pull the latest Docker image:
    
    ```jsx
    docker pull validmind/validmind-jupyter-demo:latest
    
    ```
    
- [In your own developer environment](../../guide/install-and-initialize-developer-framework.qmd): restart your notebook and re-run:
    
    ```python
    !pip install validmind
    ```