---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Enable monitoring"
date: last-modified
---

To start uploading ongoing monitoring results for a model to {{< var vm.product >}}, enable monitoring in your code snippet within the {{< var validmind.platform >}} and then select a monitoring template. You can enable monitoring for both new and existing models.

::: {.callout title="To try out monitoring, check out the code sample for ongoing monitoring of models."}
[Quickstart for ongoing monitoring of models with {{< var vm.product >}} {{< fa hand-point-right >}}](/notebooks/use_cases/ongoing_monitoring/quickstart_customer_churn_ongoing_monitoring.ipynb)
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa code >}} Developer]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]
- [x] The model is in the pre-approval stage for performance testing or the model has been approved and is in production.

:::

## Steps

::: {.panel-tabset}

### 1. Get monitoring code snippet

{{< include /developer/model-documentation/_code-snippet.qmd >}}

To enable ongoing monitoring for a model, add `monitoring=True` to your code snippet:

a. In the {{< var validmind.platform >}}, either register a new model[^2] or locate an existing model:

   - In the left sidebar, click **{{< fa cubes >}} Inventory**.
   - Select a model or find your model by applying a filter or searching for it.[^3]

b. Copy the code snippet for the model:

   - In the left sidebar that appears for your model, click **{{< fa rocket >}} Getting Started**.
   - Select `Monitoring` from the **[document]{.smallcaps}** drop-down menu.[^4]
   - Set **[enable monitoring]{.smallcaps}[?]{.smallercaps}** to true.
   - Click **{{< fa regular copy >}} Copy snippet to clipboard**.

### 2. Select monitoring template

Before you can start sending ongoing monitoring data using the {{< var validmind.developer >}} to the {{< var validmind.platform >}}, you must select a monitoring template:

a. In the {{< var validmind.platform >}}, click **{{< fa cubes >}} Inventory** in the left sidebar.

b. Select a model or find your model by applying a filter or searching for it.[^6]

c. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** tab.[^7]

d. Click on a Ongoing Monitoring type file.[^8]

e. From the **[template]{.smallcaps}** drop-down, select one of the available monitoring templates.

f. Click **Use Template** to apply your desired template.

   - After you select a template, the initial document where your ongoing monitoring results will be stored becomes available.
   - Review this documents structure to confirm that it meets your requirements, then start running your code to populate the template with monitoring results.

### 3. Run code snippet

a. Paste the code snippet into your Jupyter Notebook or other development environment.

b. Confirm that `monitoring=True` is present in the `vm.init` method, similar to this example:

   ```python
   import validmind as vm

   vm.init(
       api_host="https://api.prod.validmind.ai/api/v1/tracking",
       api_key="...",
       api_secret="...",
       model="...",
       document="monitoring", # requires library >=2.12.0
       monitoring=True
   )
   ```
   <br>

   ::: {.callout-button .pl4 .nt4}
   ::: {.callout collapse="true" appearance="minimal"}
   ### How do I enable monitoring when I am storing credentials in an `.env` file?

   :::: {.flex .flex-wrap .justify-around}

   ::: {.w-60-ns .pr3}

   Load your model credentials from your `.env` file, then remove the inline credentials from `vm.init()` after importing the {{< var vm.developer >}}.

   You'll still need to include your document key and the monitoring flag.

   [Store model credentials in `.env` files](/developer/model-documentation/store-credentials-in-env-file.qmd){.button .button-green}

   :::

   ::: {.w-40-ns}

   ```python
   %load_ext dotenv
   %dotenv .env

   import validmind as vm

   vm.init(
      document="monitoring",
      monitoring=True
   )
   ```

   :::

   ::::


   :::
   :::

c. Run the code snippet to initialize the {{< var validmind.developer >}} and connect to the selected monitoring document for your model in the {{< var validmind.platform >}}.[^5]

::: {.callout}
## A template must already be applied to your selected document to populate monitoring test results in the {{< var validmind.platform >}}.

Attempting to initialize the {{< var vm.developer >}} with a document that does not have a template applied will result in an error.

:::

:::


## What's next

After you have enabled ongoing monitoring and run your code to generate some output, you can start reviewing the monitoring results.[^9]


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^3]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^4]: Selecting a **[document]{.smallcaps}** to connect to requires {{< var validmind.developer >}} version >=2.12.0.

[^5]: [Install and initialize the {{< var validmind.developer >}}](/developer/model-documentation/install-and-initialize-validmind-library.qmd)

[^6]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^7]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^8]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^9]: [Review monitoring results](review-monitoring-results.qmd)