---
title: "[validmind](/validmind/validmind.qmd).lending_club"
sidebar: validmind-reference
toc-depth: 4
toc-expand: 4
# module.qmd.jinja2
---

<!-- function.qmd.jinja2 -->

## load_data<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">load_data</span>():

:::

<!-- function.qmd.jinja2 -->

## preprocess<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">preprocess</span>(<span class="params"><span class="n">df</span><span class="muted">,</span></span><span class="params"><span class="n">split_option</span><span class="o">=</span><span class="s1">'train_test_val'</span><span class="muted">,</span></span><span class="params"><span class="n">train_size</span><span class="o">=</span><span class="kc">0.6</span><span class="muted">,</span></span><span class="params"><span class="n">test_size</span><span class="o">=</span><span class="kc">0.2</span></span>):

:::

<!-- docstring.jinja2 -->

Split a time series DataFrame into train, validation, and test sets.

**Arguments**

- `df (pandas.DataFrame)`: The time series DataFrame to be split.
- `split_option (str)`: The split option to choose from: 'train_test_val' (default) or 'train_test'.
- `train_size (float)`: The proportion of the dataset to include in the training set. Default is 0.6.
- `test_size (float)`: The proportion of the dataset to include in the test set. Default is 0.2.

**Returns**

- train_df (pandas.DataFrame): The training set. validation_df (pandas.DataFrame): The validation set (only returned if split_option is 'train_test_val'). test_df (pandas.DataFrame): The test set.

<!-- function.qmd.jinja2 -->

## transform<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">transform</span>(<span class="params"><span class="n">df</span><span class="muted">,</span></span><span class="params"><span class="n">transform_func</span><span class="o">=</span><span class="s1">'diff'</span></span>):

:::
