---
title: "Before you begin"
date: last-modified
---

## Prerequisites

::: {.callout-tip}
### Need an account for ValidMind? 
Signing up is FREE — **[Create your account](https://app.prod.validmind.ai)**.
:::


To try out ValidMind, you need to be a registered user on the ValidMind Platform.

To connect the {{< var vm_framework >}} to the ValidMind Platform and to access the web user interface, you must be able to access our domains:

- validmind.ai
- validmind.com

If necessary, ask a network administrator to add these domains to your firewall allowlist (whitelist). 

If your company has strict security requirements and requires you to connect via VPN or AWS PrivateLink, please contact your IT/InfoSec team. For additional help setting up a VPN or PrivateLink with ValidMind's MRM platform please visit [configure AWS PrivateLink](configure-aws-privatelink.qmd) or send an email to <support@validmind.ai>.

### QuickStart requirements

To follow the QuickStart, you need access to ONE of the following:

- [Jupyter Hub](quickstart-try-developer-framework-with-jupyterhub.qmd) (recommended)
- [Google Colaboratory (Colab)](quickstart-try-developer-framework-with-colab.qmd)
- [Docker Desktop](quickstart-try-developer-framework-with-docker.qmd)

To run our sample Jupyter notebooks locally, your developer environment must support **Python {{< var python-version >}}**.

### Access to ValidMind's Web UI

You need to be able to access our ValidMind Web UI from a modern browser such as Microsoft Edge, Google Chrome, Apple Safari, or Mozilla Firefox.

## What's next

Continue with Explore the {{< var vm_dev >}}. We recommend using [Jupyter Hub](quickstart-try-developer-framework-with-jupyterhub.qmd). 

