---
title: "Review and comment on documentation projects"
date: last-modified
---

Learn how to use the ValidMind UI editor to review, and comment on a documentation project. This topic is relevant for:

* Model developers who want to review their model documentation in the ValidMind UI
* Model developers who want to post a comment or to respond to a comment on a documentation project

## Prerequisites

* The model you are documenting is registered in the model inventory
* A documentation project has already been created for this project
* A model developer has started generating documentation, either using the Developer Framework or via the online UI editor
* You are logged into the ValidMind Platform

## View model documentation

1. Navigate to the relevant model documentation project:

   In the **Documentation Projects** page, select the project corresponding to the model for which you want to view documentation.

2. On the **Overview** page, select **Documentation** on the left.

3. You can now jump to any section of the model documentation by expanding the table of contents on the left and selecting the relevant section you would like to view.

## Post comments on the documentation

1. In any section of the documentation, select a portion of text that you would like to comment on, and click the **Add comment** button that appears.

<!--- **Need image** --->

2. Enter your comment and click **Submit**.

3. You can now view the comment by highlighting the corresponding portion of text or by clicking the **Comments** tab in the **ValidMind Insights** right sidebar.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

* [Working with model documentation](working-with-model-documentation.qmd)
* [View documentation guidelines](view-documentation-guidelines.qmd)
* [Submit for approval](submit-for-approval.qmd)
