:::: {.content-visible unless-format="revealjs"}
Configure conditional requirements for the following step types:^[[Workflow step types](/guide/model-workflows/setting-up-model-workflows.qmd#workflow-step-types)]

::: {.panel-tabset}
### Transitions

#### {{< fa cube >}} Model Stage Change

[optional]{.smallcaps .pink}

1. Under **[when these conditions are met]{.smallcaps}**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add Rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add Group** to add a linked group of rules that all must be true to qualify.

### Actions

#### {{< fa arrow-pointer >}} User Action v2

[optional]{.smallcaps .pink}

1. Under **[display action button when]{.smallcaps}**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add Rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add Group** to add a linked group of rules that all must be true to qualify.

#### {{< fa users >}} Approval

- Select from either **User Roles**,^[[Manage roles](/guide/configuration/manage-roles.qmd)] **Model Stakeholder Types**,^[[Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)] or either **User Role** or **User Type** inventory field^[[Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#inventory-field-types)
] for your **[approval group]{.smallcaps}**.

- Under **[threshold]{.smallcaps}**, set the minimum percentage of approvers required for the resource to be approved.

#### {{< fa bullhorn >}} Broadcast

Select from either **Model Stakeholder Types**^[[Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)] or **Organization Roles**^[[Manage roles](/guide/configuration/manage-roles.qmd)].

### Conditional

#### {{< fa maximize >}} Condition Branch

1. Under each branch's **[conditions]{.smallcaps}**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add Rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add Group** to add a linked group of rules that all must be true to qualify.

#### {{< fa clock >}} Wait

Select when you would like to [resume workflow:]{.smallcaps}

- **After Time Interval** — Set the **[wait duration]{.smallcaps}** in minutes, hours, or days.
- **At Specified Date** — Set the **[wait until]{.smallcaps}** a specific timestamp.
- **At Specified Date on Model Field** — Set the **[model field]{.smallcaps}**^[[Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#inventory-field-types)] with a valid `Date` or `Date Time` type model inventory field that defines the specific timestamp on a per model basis.

:::

::::



:::: {.content-hidden unless-format="revealjs"}
Configure conditional requirements for the following step types:

- {{< fa cube >}} Model Stage Change **[optional]{.smallercaps}**

- {{< fa arrow-pointer >}} User Action v2 **[optional]{.smallercaps}**

- {{< fa users >}} Approval

- {{< fa bullhorn >}} Broadcast

- {{< fa maximize >}} Condition Branch

- {{< fa clock >}} Wait

::::