:::: {.content-visible unless-format="revealjs"}
::: {.panel-tabset}

### Transitions

#### {{< fa cube >}} Model Stage Change

- Transitions a model into another stage.
- Requires available model stages associated with the workflow.^[[Manage model stages](/guide/model-workflows/manage-model-stages.qmd)]

| Field | Description |
|---:|---|
| [when these conditions are met]{.smallcaps} (optional) | Add conditional requirements to qualify for this step.^[ [Conditional requirements](/guide/model-workflows/setting-up-model-workflows.qmd#conditional-requirements)]  |
| [set model stage to]{.smallcaps} | Select the model stage to transition to. |
: **{{< fa cube >}} Model Stage Change** step configuration {.hover tbl-colwidths="[40,60]"}

#### {{< fa wifi >}} Workflow State Change
Transitions the workflow into another workflow state.^[[Workflow states](/guide/model-workflows/setting-up-model-workflows.qmd#workflow-states)]

| Field | Description |
|---:|---|
| [set workflow state to]{.smallcaps} | Select or add^[Click **{{< fa plus >}} Add New State** to create a new state unique to this workflow.] the workflow state to transition the workflow to.  |
| [progress]{.smallcaps} | Indicate the progress of the workflow at this transition into the next state. |
: **{{< fa wifi >}} Workflow State Change** step configuration {.hover tbl-colwidths="[30,70]"}

### Actions

#### {{< fa arrow-pointer >}} User Action v2

Creates a button that performs an action on behalf of the user.

| Field | Description |
|---:|---|
| [display action button when]{.smallcaps}  (optional) | Add conditional requirements for displaying this step.^[[Conditional requirements](/guide/model-workflows/setting-up-model-workflows.qmd#conditional-requirements)]  |
| [action button label]{.smallcaps} | Text that displays on your action button. |
| [request fields]{.smallcaps} (optional) | Include required inventory fields alongside your action.[^step-types-1]  |
: **{{< fa arrow-pointer >}} User Action v2** step configuration {.hover tbl-colwidths="[40,60]"}

#### {{< fa users >}} Approval

Display a preconfigured message to users in the selected **[approval group]{.smallcaps}**.

- Select from either **User Roles**, **Model Stakeholder Types**,or either **User Role** or **User Type** inventory field.^[[Conditional requirements](/guide/model-workflows/setting-up-model-workflows.qmd#conditional-requirements)]
- Must be connected to both a rejection and approval {{< fa cube >}} Model Stage Change step.[^step-types-2]

| Field | Description |
|---:|---|
| [approval group]{.smallcaps}  | Select the roles, stakeholders, or user fields responsible for approval. |
| [threshold]{.smallcaps} | Percentage of approvers required for approval. |
| Approval Message | When your workflow reaches this {{< fa users >}} Approval step, the selected [approval group]{.smallcaps}  will shown this message.^[Enter in a **[title]{.smallcaps}** and a **[message]{.smallcaps}** to display.] |
: **{{< fa users >}} Approval** step configuration {.hover tbl-colwidths="[35,65]"}

#### {{< fa bullhorn >}} Broadcast

Send email notifications to users in selected groups. Select from either **User Roles** or **Model Stakeholder Types**.^[[Conditional requirements](/guide/model-workflows/setting-up-model-workflows.qmd#conditional-requirements)]

| Field | Description |
|---:|---|
| Select roles  | Select the **Model Stakeholder Types** or **User Roles** to receive the email. |
| [subject]{.smallcaps} | Subject of the email. |
| [message]{.smallcaps} | Body of the email. Use the rich text editor to compose your message.^[Include details about the model the workflow is running on using the **{ } Insert Variable** drop-down.] |
: **{{< fa bullhorn >}} Broadcast** step configuration {.hover tbl-colwidths="[25,75]"}

### Conditional

#### {{< fa maximize >}} Condition Branch

- Allows diverging paths based on conditional requirements.
- A `default` branch will be automatically included as a catch-all `else` path to ensure that your conditional logic is complete.

::: {.callout-important}
Workflows cannot be saved until condition branches are connected to other steps.
:::

To configure a condition branch:

1. On the Configure Condition Branch modal, click **{{< fa plus >}} Add Branch**.
2. Enter in the **[path name]{.smallcaps}** and designate the **[conditions]{.smallcaps}**^[[Conditional requirements](/guide/model-workflows/setting-up-model-workflows.qmd#conditional-requirements)] that apply to this path.
3. Continue with steps 1 and 2 until your conditional branch logic is complete.

    To remove a path, click **{{< fa ellipsis-vertical >}}** and select **{{< fa trash-can >}} Remove Path**.
4. When you are finished setting up all your branch paths, click **Update Step** to save your step.

    Proceed with linking the Condition Branch with your subsequent steps.^[[Link workflow together](/guide/model-workflows/configure-model-workflows.qmd#link-workflow-together)]

#### {{< fa clock >}} Wait

- Creates a time condition for displaying next available action.^[[Conditional requirements](/guide/model-workflows/setting-up-model-workflows.qmd#conditional-requirements)]
- Used to enforce a time delay or a calendar date milestone.

::: {.callout title="Time stamp configuration is in the current user's timezone."}
Other users viewing those fields or the workflow will see the value automatically in their timezone.

:::

To configure a wait step, select when you would like to [resume workflow:]{.smallcaps}

| Option | Required field | Description |
|---:|---|---|
| After Time Interval  | [wait duration]{.smallcaps} | Wait for a set amount of time. Applies to all models under the workflow. |
| At Specified Date | [wait until]{.smallcaps} | Wait until a specific timestamp. Applies to all models under the workflow. If the milestone date inputted is in the past, the next workflow step will display immediately. |
| At Specified Date on Model Field | [model field]{.smallcaps}^[[Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#inventory-field-types)] | Wait until a specific timestamp as defined by a model inventory field on a per model basis. If the selected field is empty^[Make model inventory fields **[required on registration]{.smallcaps}** to ensure necessary fields have valid values.] or the milestone date inputted is in the past, the next workflow step will display immediately. |
: **{{< fa clock >}} Wait** step configuration {.hover tbl-colwidths="[30,15,45]"}

### Workflow Logic

#### {{< fa arrow-right-arrow-left >}} Run Workflow

Triggers another workflow indicated by **[select workflow to run]{.smallcaps}**, allowing you to chain workflows.

#### {{< fa circle-stop >}} End

- Designates the end of your workflow.
- Use this step when all of your other steps have been configured and linked together.^[[Link workflow together](/guide/model-workflows/configure-model-workflows.qmd#link-workflow-together)]
:::


<!-- ADDITIONAL FOOTNOTES -->

[^step-types-1]:

    - Select the field, then click **{{< fa plus >}} Add Field** to insert.
    - [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd)

[^step-types-2]: **[Configure model workflows](/guide/model-workflows/configure-model-workflows.qmd#create-custom-workflows):**<br><br>

    1. Configure two **{{< fa cube >}} Model Stage Change** steps for your associated rejection and approval stages.
    2. Then, from the bottom of your **{{< fa users >}} Approval** step:
        a. Connect the left [**{{< fa circle >}}**]{.red} (red) to your rejection step.
        b. Connect the right [**{{< fa circle >}}**]{.green} (green) to your approval step.

::::




:::: {.content-hidden unless-format="revealjs"}

#### {{< fa cube >}} Model Stage Change
Transitions a model into another stage.

#### {{< fa wifi >}} Workflow State Change

Transitions the workflow into another workflow state.

#### {{< fa arrow-pointer >}} User Action v2

Creates a button that performs an action on behalf of the user.

#### {{< fa users >}} Approval

Display a preconfigured message users in the selected **[approval group]{.smallcaps}**.

#### {{< fa bullhorn >}} Broadcast

Send email notifications to users in selected groups.

#### {{< fa maximize >}} Condition Branch

Allows diverging paths based on conditional requirements.

#### {{< fa clock >}} Wait

Creates a time condition for displaying next available action.

#### {{< fa arrow-right-arrow-left >}} Run Workflow

Triggers another workflow indicated by **[select workflow to run]{.smallcaps}**, allowing you to chain workflows.

#### {{< fa circle-stop >}} End

Designates the end of your workflow.

::::
