:::: {.content-visible unless-format="revealjs"}
Workflow states are statuses unique to a specific workflow, discrete from model stages.^[[Manage model stages](/guide/model-workflows/manage-model-stages.qmd)]

#### Add workflow states

Add workflow states by either while configuring a **{{< fa wifi >}} Workflow State Change** step,^[[Configure workflow steps](/guide/model-workflows/configure-model-workflows.qmd#configure-workflow-steps)] or via the **{{< fa gear >}} Settings** page:

1. In the left sidebar, click **{{< fa gear >}} Settings**.
2. Under Workspace, select **Workflow States**.
3. Click on the workflow you'd like to modify workflow states for.
4. Click **{{< fa gear >}} Add New Workflow State**.
5. Enter in a **[name]{.smallcaps}** and a **[description]{.smallcaps}**, then select a **[color]{.smallcaps}** for your workflow state.
6. Click **Save** to create the workflow state.

#### Delete workflow states

::: {.callout-important title="Workflow state deletion is permanent."}
If a state is or was previously in use  on a workflow within a {{< fa wifi >}} Workflow State Change step, the state cannot be deleted.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.
2. Under Workspace, select **Workflow States**.
3. Click on the workflow you'd like to delete workflow states for.
4. Hover over the workflow state until the **{{< fa trash-can >}}** appears, then click on it.
5. After you confirm, the workflow state will be removed.

::::


:::: {.content-hidden unless-format="revealjs"}
Workflow states are statuses unique to a specific workflow, discrete from model stages.

#### Add workflow states

Add workflow states by either while configuring a **{{< fa wifi >}} Workflow State Change** step, or via the **{{< fa gear >}} Settings** page:

1. In the left sidebar, click **{{< fa gear >}} Settings**.
2. Under Workspace, select **Workflow States**.
3. Click on the workflow you'd like to modify workflow states for.
4. Click **{{< fa gear >}} Add New Workflow State**.
5. Enter in a **[name]{.smallcaps}** and a **[description]{.smallcaps}**, then select a **[color]{.smallcaps}** for your workflow state.
6. Click **Save** to create the workflow state.

::::