---
title: "Configure model workflows"
date: last-modified
aliases:
  - /guide/set-up-model-workflows.html
  - set-up-model-workflows.html
---

Configure workflows to match your organizational needs throughout your model lifecycles. Workflows can be as simple or as complex as required, with multiple and discrete workflows supported for unique triggers and scenarios.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] Model stages must be fully configured.[^1]
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^2]

:::

## Create custom workflows

To set up a new custom workflow, you'll need to complete these three steps in sequence:

 1. [Add a new workflow](#add-new-workflows)
 2. [Configure the workflow steps](#configure-workflow-steps)
 3. [Link the workflow together](#link-workflow-together)

### Add new workflows

{{< include _add-new-workflows.qmd >}}

### Configure workflow steps

{{< include _configure-workflow-steps.qmd >}}

### Link workflow together

{{< include _link-workflow-together.qmd >}}

## Edit existing workflows

You can edit a workflow in two ways:

::: {.panel-tabset}

#### Via the **{{< fa gear >}} Settings** page

1. In the left sidebar, click **{{< fa gear >}} Settings**.
2. Under Workspace, select **Workflows**.
3. Click on the workflow you'd like to modify to edit the configuration for that workflow.

#### Via a workflow applied to a model

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.
2. Select a model or find your model by applying a filter or searching for it.[^3]
3. On the landing page of your model, locate the [active workflows]{.smallcaps} section.
4. Click on the name of the workflow you'd like to abort to open that specific workflow's details.
5. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa pencil >}} Edit Workflow**.

:::

a. Make your desired changes to step configuration[^4] and step relationships[^5] on your workflow.

b. When you are finished, click **Save Workflow** to apply your changes.

### Delete workflow steps*

::: {.callout-important title="Workflow step deletion is permanent."}
Deleting workflow steps on workflows active on models may result in malfunctioning workflows.
:::

1. Hover over the step until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

2. Select **{{< fa gear >}} Delete**.

    On the confirmation dialogue that appears, select **OK** to confirm deletion.

3. When you are finished, click **Save Workflow** to apply your changes.

### Remove links between steps

1. Hover over a connection until the **{{< fa trash-can >}}** appears.

2. Click **{{< fa trash-can >}}** to delete the connection.

    On the confirmation dialogue that appears, select **OK** to confirm deletion.

3. When you are finished, click **Save Workflow** to apply your changes.

## Delete existing workflows*

::: {.callout-important title="Workflow deletion is permanent."}
- If a workflow is in use on a model, that model will not be impacted.
- Deletion will prevent any future runs of that workflow.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Workflows**.

3. Hover over the workflow you would like to remove until the **{{< fa ellipsis-vertical >}}** appears, then click on it.

4. Select **{{< fa ban >}} Delete Workflow**.

5. After you confirm, the workflow will be removed and inaccessible by models for any future runs.


## What's next

- [Workflows FAQ](/faq/faq-workflows.qmd)
- [Work with workflows](working-with-model-workflows.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage model stages](manage-model-stages.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^4]: [Configure workflow steps](#configure-workflow-steps)

[^5]: [Link workflow together](#link-workflow-together)