---
title: "Configure custom workflows"
date: last-modified
aliases:
  - /guide/set-up-model-workflows.html
  - set-up-model-workflows.html
---

Configure workflows to match your organizational needs throughout your model lifecycles. Workflows can be as simple or as complex as required, with multiple and discrete workflows supported for unique triggers and scenarios.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] Model stages must be fully configured.[^1]
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^2]

:::

## Create a custom workflow

To set up a new custom workflow, you'll need to complete these three steps in sequence:

 1. [Add a new workflow](#add-workflows)
 2. [Configure the workflow steps](#configure-workflow-steps)
 3. [Link the workflow together](#link-workflow-together)

### Add new workflows

{{< include _add-new-workflows.qmd >}}

### Configure workflow steps

{{< include _configure-workflow-steps.qmd >}}

### Link workflow together

{{< include _link-workflow-together.qmd >}}

##### Link approval steps*

{{< fa users >}} Approval steps need to be subsequently linked to both a [Rejected]{.bubble .red .red-bg} and an [Approved]{.bubble .green .green-bg} {{< fa cube >}} Model Stage Change step:[^3]

1. First, configure an **{{< fa users >}} Approval** step.

2. Then, drag two **{{< fa cube >}} Model Stage Change** steps onto the canvas:

    - Assign a stage associated with rejection to one in the **[set model stage to]{.smallcaps}** field.
    - Assign a stage associated with approval to the other in the **[set model stage to]{.smallcaps}** field.

3. Then, from the bottom of your **{{< fa users >}} Approval** step:

    a. Connect the left [**{{< fa circle >}}**]{.red} (red) to your rejection step.[^4]
    b. Connect the right [**{{< fa circle >}}**]{.green} (green) to your approval step.[^5]

## Edit existing workflows

You can edit a workflow in two ways:

1. Via the **{{< fa gear >}} Settings** page:

    a. In the left sidebar, click **{{< fa gear >}} Settings**.
    b. Under Workspace, select **Workflows**.
    c. Click on the workflow you'd like to modify to edit the configuration for that workflow.

2. Via a workflow applied to a model:

    a. In the left sidebar, click **{{< fa cubes >}} Inventory**.
    b. Select a model or find your model by applying a filter or searching for it.[^6]
    c. On the landing page of your model, locate the [active workflows]{.smallcaps} section.
    d. Click on the name of the workflow you'd like to abort to open that specific workflow's details.
    e. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa pencil >}} Edit Workflow**.

### Delete workflow steps

1. Hover over the step until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

2. Select **{{< fa gear >}} Delete**.

    On the confirmation dialogue that appears, select **OK** to confirm deletion.

3. When you are finished, click **Save Workflow** to apply your changes.

### Remove links between steps

1. Hover over a connection until the **{{< fa trash-can >}}** appears.

2. Click **{{< fa trash-can >}}** to delete the connection.

    On the confirmation dialogue that appears, select **OK** to confirm deletion.

3. When you are finished, click **Save Workflow** to apply your changes.

## What's next

- [Workflows FAQ](/faq/faq-workflows.qmd)
- [Work with workflows](working-with-model-workflows.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage model stages](manage-model-stages.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Setting up model workflows](/guide/model-workflows/setting-up-model-workflows.qmd#workflow-step-types)

[^4]: When complete, the workflow arrow will display as [Rejected]{.bubble .red .red-bg}.

[^5]: When complete, the workflow arrow will display as [Approved]{.bubble .green .green-bg}.

[^6]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)