---
title: "Customize resource statuses"
date: last-modified
---

Statuses are manipulated via workflow transitions and are used to track the progress of resources through your organization's processes.

Default statuses are provided for you as suggestions. You can add, edit, remove, and define your own custom statuses in each category:

- **Model documentation**
- **Model lifecycle**

<!-- Model validation statuses are in missing as of May 2024 -->

## Prerequisites

- {{< var link.login >}}

- To work with statuses, you must have permission to read, add, update, and delete resource statuses. By default, the Customer Admin role has all these permissions.[^1]

## Add or edit statuses

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. UnderWorkplace Settings, select **{{< fa arrow-right-arrow-left >}} Statuses**.

3. Under Available Statuses, select the process you'd like to add or edit statuses for:

    - To add a status, click **+ Add New Status**.
    - To edit a status, click on the status itself. 

    On the status detail popup that appears, provide the required information indicated by `*`.

4. When you are done, click **Save** to apply your changes.

## Delete statuses

::: {.callout-important title="Deleting statuses already in use will cause your workflows to no longer function correctly."}
 Make sure that the status you're deleting is not associated with any workflows or active models in your inventory before proceeding. 
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workplace Settings, select **{{< fa arrow-right-arrow-left >}} Statuses**.

3. Under Available Statuses, select the process you'd like to delete a status for.

4. Hover over the status you'd like to delete, and click **{{< fa trash-can >}} Delete**.

    On the confirmation dialogue that appears, select **OK** to confirm deletion.

## What's next

- [Workflows FAQ](/faq/faq-workflows.qmd)
- [Set up model workflows](set-up-model-workflows.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](manage-permissions.qmd)

