---
title: "Customize model lifecycle statuses"
date: last-modified
---

Model lifecycle statuses are manipulated via workflow transitions and are used to track the progress of resources through your organization's processes. 

- Default statuses are provided for you as suggestions. 
- You can add, edit, remove, and define your own custom statuses.

::: {.prereq}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a `Customer Admin` or assigned another role with sufficient permissions to perform the tasks in this guide.[^1] 

:::

## Add or edit statuses

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workplace Settings, select **Model Lifecycle Statuses**:

    - To add a status, click **{{< fa plus >}} Add New Model Lifecycle Status**.
    - To edit a status, click on the status itself. 

3. On the status detail popup that appears:

    a. Provide a status **[name]{.smallcaps}** 
    b. Provide a status **[description]{.smallcaps}** 
    c. Assign a **[color]{.smallcaps}** to the status

4. When you are done, click **Save** to apply your changes.

## Delete statuses

::: {.callout-important title="Deleting statuses already in use will cause your workflows to no longer function correctly."}
 Make sure that the status you're deleting is not associated with any workflows or active models in your inventory before proceeding. 
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workplace Settings, select **Statuses**.

3. Hover over the status you'd like to delete, and click **{{< fa trash-can >}} Delete**.

    On the confirmation dialogue that appears, select **OK** to confirm deletion.

## What's next

- [Workflows FAQ](/faq/faq-workflows.qmd)
- [Set up model workflows](set-up-model-workflows.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

