---
title: "Manage model workflows"
date: last-modified
---

Review workflows associated with your models, and initiate or abort workflows configured for your organization on your models.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model is registered in the model inventory.[^1]
- [x] Workflows have already been set up for use with your models.[^2]
- [x] You are a assigned role with sufficient permissions to view and run workflows on models.[^3]

:::

## Review model workflows

### Review active workflows

{{< include _review-active-workflows.qmd >}}

### Review workflow history

Review a timeline of workflows running or previously run on your model:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^4]

3. On the landing page of your model, locate the Workflows section. If workflows are running or have previously run on your model, you can:

    - Filter the view using the **[show]{.smallcaps}** drop-down menu to display only runs from specific workflows.

    - Click **{{< fa arrow-right-arrow-left >}} See All Workflows** to see records of workflows by status:
        - **Active** — Workflows currently running.
        - **Scheduled** — Workflows slated to run in the future.
        - **Waiting** — Workflows in a {{< fa clock >}} Wait state.[^5]
        - **Finished** — Workflows that have reached an {{< fa circle-stop >}} End state.[^6]
        - **Aborted** — Cancelled workflows.[^7]
        - **Available** — Workflows available to be run manually.[^8]

## Initiate model workflows

::: {.callout}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to manually start model workflows.
:::

To manually start a workflow[^9] for a specific model:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^10]

3. On the landing page of your model, locate the [active workflows]{.smallcaps} section.

4. Click **{{< fa arrow-right-arrow-left >}} See All Workflows**.

5. Select **{{< fa arrow-right >}} Run Workflow** for the workflow you'd like to initiate, then select your desired **[workflow start]{.smallcaps}** option:

    - **Run Now** — Workflow starts instantly.
    - **Scheduled Run** — Set a future date to run the workflow.

6. Click **{{< fa arrow-right >}} Run Workflow Now** to confirm.

### Resume workflows

To manually resume a workflow in a {{< fa clock >}} Wait state:[^11]

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^12]

3. On the landing page of your model, locate the [active workflows]{.smallcaps} section.

4. For the workflow you'd like to manually advance, click **{{< fa arrow-right-arrow-left >}} Resume Workflow** to open up the workflow's step overview.

5. On the **{{< fa clock >}} Wait** step, double-click on **{{< fa arrow-right-arrow-left >}}** to advance the workflow immediately.

## Abort workflows

::: {.callout}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to abort workflows.
:::

To cancel a run of a workflow on a model:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^13]

3. On the landing page of your model, locate the [active workflows]{.smallcaps} section.

4. Click on the name of the workflow you'd like to abort to open that specific workflow's details.

5. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa ban >}} Abort Workflow**.

6. On the confirmation page, leave **[restart workflow after aborting]{.smallcaps}** untoggled, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to abort your workflow.


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Configure custom workflows](configure-model-workflows.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Conditional requirements](setting-up-model-workflows.qmd#conditional-requirements)

[^6]: [Workflow step types](setting-up-model-workflows.qmd#workflow-step-types)

[^7]: [Abort workflows](#abort-workflows)

[^8]: [Initiate model workflows](#initiate-model-workflows)

[^9]:

    ::: {.callout title="Workflows can be set to run automatically on specific triggers."}
    Refer to [Configure custom workflows](configure-model-workflows.qmd) for more details.
    :::

[^10]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^11]: [Conditional requirements](setting-up-model-workflows.qmd#conditional-requirements)

[^12]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^13]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)