---
title: "Manage workflow tasks"
date: last-modified
---

View and interact with workflow transition tasks assigned to your user roles for all workflows on your models.

:::{.callout}
Tasks will only appear in your inbox if the workflow step[^1] is set up to display the action button to your user role.[^2]
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^3]
- [x] Model stages have already been customized for use in workflows.[^4]
- [x] Workflows have already been set up for use with your models.[^5]
- [x] You are a assigned role with sufficient permissions to transition workflows into their next states.[^6]

:::

## View workflow tasks

1. In the left sidebar, click **{{< fa bell >}} Updates**.

2. Select the **Tasks** tab.

3. From the in-{{< var vm.platform >}} task list, view and filter your tasks, access models attached to tasks, and transition model workflows into their next states:

::: {.panel-tabset}

### View and filter tasks

Tasks are listed with the following information:

- The name of the model the workflow is attached to
- The current workflow state of the workflow[^7]
- The name of the workflow attached to the model[^8]
- The due date of the workflow, calculated from the workflow's expected duration
- Action items associated with that task

#### Filter tasks

a. Click **{{< fa filter >}} Filter** to configure whether or not completed tasks are displayed:

    - Toggle **Show competed tasks** to show completed tasks.
    - Untoggle **Show completed tasks** to hide completed tasks.

b. Click **Apply Filters** to narrow down results based on your selection.

#### Show more tasks

To show older tasks, scroll down to the bottom and click **Load More**.

### Access model details

To view the details of a model attached to a workflow task, click the button displaying the name of the model.

### Transition model workflows

If an action is available to your role,[^9] you'll see it appear as an action button under a workflow task:

- Click **{{< fa arrow-right >}}** to open up the transition panel for your selected action. This arrow will be followed by the action name.
- Enter your **[notes]{.smallcaps}** and any other additional inventory fields[^10] then click **Submit**.

Once completed, action buttons will be grayed out.

:::


<!-- FOOTNOTES -->

[^1]: [Workflow step types](setting-up-model-workflows.qmd#workflow-step-types)

[^2]: [Manage roles](/guide/configuration/manage-roles.qmd)

[^3]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^4]: [Manage model stages](manage-model-stages.qmd)

[^5]: [Configure model workflows](configure-model-workflows.qmd)

[^6]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^7]: [Workflow states](setting-up-model-workflows.qmd#workflow-states)

[^8]: [Configure model workflows](configure-model-workflows.qmd)

[^9]: [Transition model workflows](transition-model-workflows.qmd)

[^10]: [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd)