---
title: "Manage model stages"
date: last-modified
aliases:
  - customize-resource-statuses.html
  - /guide/customize-resource-statuses.html
  - customize-model-lifecycle-statuses.html
---

Model stages are manipulated via workflow transitions and are used to track the progress of models through your organization's model lifecycles.

- Default stages are provided for you as suggestions.
- You can add, edit, remove, and define your own custom stages.

::: {.callout}
`Archived` and `Deleted` are [reserved]{.bubble} stages,[^1] meaning they cannot be modified or removed.
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^2] 

:::

## Add model stages

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Models, select **Model Stages**:

    - To add a stage, click **{{< fa plus >}} Add Model Stage**.
    - To edit a stage, click on the stage itself.

3. On the Add New Model Stage modal that appears:

    a. Provide a stage **[name]{.smallcaps}** 
    b. Provide a stage **[description]{.smallcaps}** 
    c. Assign a **[color]{.smallcaps}** to the stage

4. When you are done, click **Save** to apply your changes.

## Edit or delete stages

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Models, select **Model Stages**.

3. Hover over the stage you'd like to modify until the **{{< fa ellipsis-vertical >}}** appears, then click on it:

    - Select **{{< fa pencil >}} Edit Details** to modify that stage.
    - Select **{{< fa trash-can >}} Delete Stage**. On the confirmation dialogue that appears, select **OK** to confirm deletion.

::: {.callout-important title="Deleting stages already in use will cause your workflows to no longer function correctly."}
Make sure that the stage you're deleting is not associated with any workflows or active models in your inventory before proceeding. 
:::

## What's next

- [Workflows FAQ](/faq/faq-workflows.qmd)
- [Set up model workflows](set-up-model-workflows.qmd)


<!-- FOOTNOTES -->

[^1]: [Archive and delete models](/guide/model-inventory/archive-delete-models.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

