---
title: "Setting up model workflows"
date: last-modified
listing:
  - id: model-workflows
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - manage-model-stages.qmd
    - configure-custom-workflows.qmd
    - workflow-configuration-examples.qmd
---

Configure workflows to match your organizational needs for overseeing model development, validation, implementation, ongoing monitoring, auditing, or other risk management activities.

- Models in your model inventory transition through your organization's custom model lifecycles via model stages, which are in turn manipulated via workflows.
- Workflows are comprised of workflow steps,[^1] and have their own states discrete from model stages.[^2]
- Some step types allow you to define conditional requirements,[^3] providing flexible customization.

## Set up workflows

:::{#model-workflows}
:::

## Workflow elements

A workflow is comprised of an interplay of these elements:

- [Workflow step types](#workflow-step-types)
- [Conditional requirements](#conditional-requirements)
- [Workflow states](#workflow-states)

### Workflow step types

::: {.panel-tabset}

### Transitions

#### {{< fa cube >}} Model Stage Change
<span id="stage-change"></span>

- Transitions a model into another stage.
- Requires available model stages associated with the workflow.[^4]

| Field | Description |
|---:|---|
| [when these conditions are met]{.smallcaps} (optional) | Add conditional requirements to qualify for this step.[^5]  |
| [set model stage to]{.smallcaps} | Select the model stage to transition to. |
: **{{< fa cube >}} Model Stage Change** step configuration {.hover tbl-colwidths="[40,60]"}

#### {{< fa wifi >}} Workflow State Change
<span id="state-change"></span>

Transitions the workflow into another workflow state.[^6]

| Field | Description |
|---:|---|
| [set workflow state to]{.smallcaps} | Select or add[^7] the workflow state to transition the workflow to.  |
| [progress]{.smallcaps} | Indicate the progress of the workflow at this transition into the next state. |
: **{{< fa wifi >}} Workflow State Change** step configuration {.hover tbl-colwidths="[30,70]"}

### Actions

#### {{< fa arrow-pointer >}} User Action v2
<span id="user-action"></span>

Creates a button that performs an action on behalf of the user.

| Field | Description |
|---:|---|
| [display action button when]{.smallcaps}  (optional) | Add conditional requirements for displaying this step.[^8]  |
| [action button label]{.smallcaps} | Text that displays on your action button. |
| [request fields]{.smallcaps} | Include required inventory fields alongside your action.[^9]  |
: **{{< fa arrow-pointer >}} User Action v2** step configuration {.hover tbl-colwidths="[40,60]"}

#### {{< fa users >}} Approval
<span id="approval"></span>

When your workflow reaches the approval step, roles or users in the selected **[approval group]{.smallcaps}** will receive a preconfigured message.

- Select from either **User Roles**, **Model Stakeholder Types**,or either **User Role** or **User Type** inventory field.[^10]
- Must be connected to both a rejection and approval {{< fa cube >}} Model Stage Change step.[^11]

::: {.callout}
Please note that roles, stakeholders, or users must be assigned to the indicated **[approval group]{.smallcaps}** before the workflow is transitioned into the **{{< fa users >}} Approval** step in order for the message to be displayed to users in those categories.

:::

| Field | Description |
|---:|---|
| [approval group]{.smallcaps}  | Select the roles, stakeholders, or user fields responsible for approval. |
| [threshold]{.smallcaps} | Percentage of approvers required for approval. |
| Approval Message | When your workflow reaches this {{< fa users >}} Approval step, the selected [approval group]{.smallcaps}  will shown this message.[^12] |
: **{{< fa users >}} Approval** step configuration {.hover tbl-colwidths="[35,65]"}

### Conditional

#### {{< fa maximize >}} Condition Branch
<span id="condition-branch"></span>

- Allows diverging paths based on conditional requirements.
- A `default` branch will be automatically included as a catch-all `else` path to ensure that your conditional logic is complete.

::: {.callout-important}
Workflows cannot be saved until condition branches are connected to other steps.
:::

To configure a condition branch:

1. On the Configure Condition Branch modal, click **{{< fa plus >}} Add Branch**.
2. Enter in the **[path name]{.smallcaps}** and designate the **[conditions]{.smallcaps}**[^13] that apply to this path.
3. Continue with steps 1 and 2 until your conditional branch logic is complete.

    To remove a path, click **{{< fa ellipsis-vertical >}}** and select **{{< fa trash-can >}} Remove Path**.
4. When you are finished setting up all your branch paths, click **Update Step** to save your step.

    Proceed with linking the Condition Branch with your subsequent steps.[^14]

#### {{< fa clock >}} Wait
<span id="wait"></span>

- Creates a time condition for displaying next available action.
- Used to enforce a time delay or a calendar date milestone.

::: {.callout title="Time stamp configuration is in the current user's timezone."}
Other users viewing those fields or the workflow will see the value automatically in their timezone.

:::

To configure a wait step, select when you would like to [resume workflow:]{.smallcaps}

| Option | Required field | Description |
|---:|---|---|
| After Time Interval  | [wait duration]{.smallcaps} | Wait for a set amount of time. Applies to all models under the workflow. |
| At Specified Date | [wait until]{.smallcaps} | Wait until a specific timestamp. Applies to all models under the workflow. If the milestone date inputted is in the past, the next workflow step will display immediately. |
| At Specified Date on Model Field | [model field]{.smallcaps}[^15] | Wait until a specific timestamp as defined by a model inventory field on a per model basis. If the selected field is empty[^16] or the milestone date inputted is in the past, the next workflow step will display immediately. |
: **{{< fa clock >}} Wait** step configuration {.hover tbl-colwidths="[30,15,45]"}

### Workflow Logic

#### {{< fa arrow-right-arrow-left >}} Run Workflow
<span id="run-workflow"></span>

Triggers another workflow indicated by **[select workflow to run]{.smallcaps}**, allowing you to chain workflows.

#### {{< fa circle-stop >}} End
<span id="end"></span>

- Designates the end of your workflow.
- Use this step when all of your other steps have been configured and linked together.[^17]
:::

### Conditional requirements

Configure conditional requirements for the following step types:[^18]

::: {.panel-tabset}
#### {{< fa cube >}} Model Stage Change

[optional]{.smallcaps .pink}

1. Under **[when these conditions are met]{.smallcaps}**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add group** to add a linked group of rules that all must be true to qualify.

#### {{< fa arrow-pointer >}} User Action v2

[optional]{.smallcaps .pink}

1. Under **[display action button when]{.smallcaps}**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add group** to add a linked group of rules that all must be true to qualify.

#### {{< fa users >}} Approval

- Select from either **User Roles**,[^19] **Model Stakeholder Types**,[^20] or either **User Role** or **User Type** inventory field[^21] for your **[approval group]{.smallcaps}**.

- Under **[threshold]{.smallcaps}**, set the minimum percentage of approvers required for the resource to be approved.

#### {{< fa maximize >}} Condition Branch

1. Under each branch's **[conditions]{.smallcaps}**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add group** to add a linked group of rules that all must be true to qualify.

#### {{< fa clock >}} Wait

Select when you would like to [resume workflow:]{.smallcaps}

- **After Time Interval** — Set the **[wait duration]{.smallcaps}** in minutes, hours, or days.
- **At Specified Date** — Set the **[wait until]{.smallcaps}** a specific timestamp.
- **At Specified Date on Model Field** — Set the **[model field]{.smallcaps}**[^22] with a valid `Date` or `Date Time` type model inventory field that defines the specific timestamp on a per model basis.

:::

### Workflow states

Workflow states are statuses unique to a specific workflow, discrete from model stages.[^23]

#### Add workflow states

Add workflow states by either while configuring a **{{< fa wifi >}} Workflow State Change** step,[^24] or via the **{{< fa gear >}} Settings** page:

1. In the left sidebar, click **{{< fa gear >}} Settings**.
2. Under Workspace, select **Workflow States**.
3. Click on the workflow you'd like to modify workflow states for.
4. Click **{{< fa gear >}} Add New Workflow State**.
5. Enter in a **[name]{.smallcaps}** and a **[description]{.smallcaps}**, then select a **[color]{.smallcaps}** for your workflow state.
6. Click **Save** to create the workflow state.

#### Delete workflow states*

::: {.callout-important title="Workflow state deletion is permanent."}
If a state is in use on a workflow within a {{< fa wifi >}} Workflow State Change step, the state cannot be deleted.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.
2. Under Workspace, select **Workflow States**.
3. Click on the workflow you'd like to delete workflow states for.
4. Hover over the workflow state until the **{{< fa trash-can >}}** appears, then click on it.
5. After you confirm, the workflow state will be removed.


## What's next

- [Working with model workflows](working-with-model-workflows.qmd)


<!-- FOOTNOTES -->

[^1]: [Workflow step types](#workflow-step-types)

[^2]: [Workflow states](#workflow-states)

[^3]: [Conditional requirements](#conditional-requirements)

[^4]: [Manage model stages](manage-model-stages.qmd)

[^5]: [Conditional requirements](#conditional-requirements)

[^6]: [Workflow states](#workflow-states)

[^7]: Click **{{< fa plus >}} Add New State** to create a new state unique to this workflow.

[^8]: [Conditional requirements](#conditional-requirements)

[^9]:

    - Select the field, then click **{{< fa plus >}} Add Field** to insert.
    - [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd)

[^10]: [Conditional requirements](#conditional-requirements)

[^11]: **[Configure custom workflows](configure-custom-workflows.qmd#create-custom-workflows):**<br><br>

    1. Configure two **{{< fa cube >}} Model Stage Change** steps for your associated rejection and approval stages.
    2. Then, from the bottom of your **{{< fa users >}} Approval** step:
        a. Connect the left [**{{< fa circle >}}**]{.red} (red) to your rejection step.
        b. Connect the right [**{{< fa circle >}}**]{.green} (green) to your approval step.


[^12]:

    Enter in a **[title]{.smallcaps}** and a **[message]{.smallcaps}** to display.

[^13]: [Conditional requirements](#conditional-requirements)

[^14]: [Configure custom workflows](configure-custom-workflows.qmd#link-workflow-together)

[^15]: [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#inventory-field-types)

[^16]: Make model inventory fields **[required on registration]{.smallcaps}** to ensure necessary fields have valid values.

[^17]: [Configure custom workflows](configure-custom-workflows.qmd#link-workflow-together)

[^18]: [Workflow step types](#workflow-step-types)

[^19]: [Manage roles](/guide/configuration/manage-roles.qmd)

[^20]: [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)

[^21]: [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#inventory-field-types)

[^22]: [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#inventory-field-types)

[^23]: [Manage model stages](manage-model-stages.qmd)

[^24]: [Configure custom workflows](configure-custom-workflows.qmd#configure-workflow-steps)