---
title: "Transition model workflows"
date: last-modified
---

Transition a model's workflow into its next state, or reset a workflow on a model.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model is registered in the model inventory.[^1]
- [x] Model stages have already been customized for use in workflows.[^2]
- [x] Workflows have already been set up for use with your models.[^3]
- [x] You are a assigned role with sufficient permissions to transition the workflow into its next state.[^4]

:::

## Transition model workflows

{{< include _transition-model-workflows.qmd >}}

## Reset your model workflow

::: {.callout}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to reset model workflows.
:::


If you need to reset a model's workflow to the beginning:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^5]

3. On the landing page of your model, locate the [active workflows]{.smallcaps} section.

4. Click on the name of the workflow you'd like to reset to open that specific workflow's details.

5. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa ban >}} Abort Workflow**.

6. On the confirmation page, toggle **[restart workflow after aborting]{.smallcaps}**, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to restart your workflow.


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Manage model stages](manage-model-stages.qmd)

[^3]: [Configure custom workflows](configure-model-workflows.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)
