---
title: "January 17, 2025"
---

## Documentation

<!---
PR #552: Updated workflows/actions to dynamically generate an `.env` file
URL: https://github.com/validmind/documentation/pull/552
Labels: documentation
--->
### Actions to dynamically generate an `.env` file

Valid Mind Academy

- The Valid Mind Academy Developer Fundamentals course has been updated. It now includes an improved version of the Valid Mind Introduction for Model Developers Jupyter Notebook.
 
- You can execute this embedded notebook live within the training. This change allows you to interact with output cells previously omitted, such as when previewing the documentation template.

- This training notebook serves as a reference guide for users. It shows what to expect when you first run the cells.

Jupyter Notebooks

- We've included details on how to initialize ValidMind with credentials stored in an `.env` file in our Jupyter Notebook samples.

- Our documentation guides have also been updated to match this new experience.
 
Generated PR summary: 
 
This update enhances the way Jupyter Notebooks are configured and executed within the project. The environment configuration now includes new variables such as `VM_API_HOST`, `VM_API_KEY`, `VM_API_SECRET`, and `VM_API_MODEL` in the `.env.example` file. GitHub Actions workflows (`demo-notebook`, `prod-notebook`, `staging-notebook`) now require an `env_file` input to ensure a `.env` file is available before running notebooks. Additionally, certain workflow files dynamically create a `.env` file using secrets.

For notebook execution, a new `execute` target in the `Makefile` allows you to run Jupyter Notebooks with specified profiles and paths. Notebooks are duplicated for execution instead of being checked out from the main branch.

Documentation improvements include detailed instructions on storing model credentials in `.env` files in `store-credentials-in-env-file.qmd`, along with examples for enabling monitoring when using these files, as explained in `enable-monitoring.qmd`. These updates enhance flexibility, improve security in environment management, and streamline the execution and monitoring process for Jupyter Notebooks.

<!---
PR #543: Add developer fundamentals videos & training fixes
URL: https://github.com/validmind/documentation/pull/543
Labels: documentation
--->
### Add developer fundamentals videos & training fixes

We created a series of 10 short videos

Learn about the model documentation process as a developer. These videos introduce you to generating model documentation, including tests. You will also learn how to add your tests and edit the content online. Then, you can submit your documentation for approval so that a validator can review the submission.

{{< video https://www.youtube.com/embed/videoseries?si=aP7yLOGO60h4vi8C&amp;list=PL717ZrCoVCCP876aLRCjitZqYif96Whlz title=developer fundamentals >}}
 
Generated PR summary: 
 
This update to the ValidMind project includes several enhancements designed to improve your experience. The titles of training modules in the `internal/templates/videos/index.qmd` file have been updated, with "Documenting Models 101" now titled "Developer Fundamentals" and "Validating Models 101" renamed to "Train a model". Three new SVG files with specific color fills have been added to the `site/assets/img/` directory for visual consistency. In the `site/guide/guides.qmd` file, a new video series called 'Developer Fundamentals', consisting of 10 videos, has been introduced, and a card title has been added to the 'Validating Models 101' series. The `site/notebooks/tutorials/intro_for_model_developers_EXECUTED.ipynb` file now refers to the "ValidMind Library" instead of "ValidMind Developer Framework", affecting various sections such as initialization and testing documentation. Furthermore, adjustments in the `site/training/developer-fundamentals/developer-fundamentals.qmd` file aim to correct section references and enhance interactivity during documentation. A new JSON file, `test-results/.last-run.json`, is also included to track test status, confirming that all tests have passed successfully.

<!---
PR #544: Add login button to docs site
URL: https://github.com/validmind/documentation/pull/544
Labels: documentation
--->
### Add login button to docs site

Added login option  

You can now log in to the ValidMind platform directly from our docs site. This makes it easy for you to find the right login. Click **Login** to try it out.

 
Generated PR summary: 
 
This update enhances the website's navigation by adding a 'Login' section with multiple options for users. You will notice the removal of the search box from the sidebar, making way for a new 'Login' menu on the right side of the navigation bar. This menu provides links to different login portals (US1 and CA1) for accessing the ValidMind platform. Additionally, there is a helpful link titled 'Which login should I use?' that guides you in selecting the appropriate login option for ValidMind. The `styles.css` file has been updated to complement these changes with adjustments to background colors, borders, text color, padding, and hover effects to enhance usability and appearance.



{{< include /releases/_how-to-upgrade.qmd >}}
