name: Fetch Quarto
description: Checks out repo then downloads & installs the latest version of Quarto

inputs: {}

runs: 
  using: "composite"
  steps:
    - name: Get latest Quarto release URL
      id: get-quarto-url
      shell: bash
      run: |
        API_URL="https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest"
        DOWNLOAD_URL=$(curl -s $API_URL | jq -r '.assets[] | select(.name | endswith("linux-amd64.deb")).browser_download_url')
        echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
    
    - name: Download and install Quarto
      shell: bash
      run: |
        wget ${{ env.DOWNLOAD_URL }} -O quarto-latest-linux-amd64.deb
        sudo dpkg -i quarto-latest-linux-amd64.deb