---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "{{< var vm.product >}} community"
date: last-modified
aliases:
  - /about/validmind-community.html
  - /about/contributing/join-community.html
  - /guide/join-community.html
  - /about/join-community.html
---

Work with financial models, in model risk management (MRM), or are simply enthusiastic about artificial intelligence (AI) and machine learning and how these tools are actively shaping our futures within the finance industry and beyond? Congratulations — you're already part of the {{< var vm.product >}} community! Come learn and play with us.

::: {.callout}

### {{< fa brands slack >}}&ensp;Slack, it's time to say goodbye.

Our community Slack channels are being retired **on November 15, 2025**, but our community continues to grow in many other spaces. Explore how you can stay connected with us on this page.
:::

## Engage

::: {.panel-tabset}

#### Blog

:::: {.flex .flex-wrap .justify-around}

::: {.w-90-ns .pr4}
Keep up with the latest news in AI and MRM, as well as announcements and original content from {{< var vm.product >}} on our blog.
:::

::: {.w-10-ns .tr}
[{{< fa blog >}} Blog](https://validmind.com/blog/){target="_blank" .button}
:::

::::

#### Events & workshops

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns .pr4}
Want to connect with other inquiring minds? Find out what exclusive events {{< var vm.product >}} is hosting and attending — we'd be delighted to see you!

Or, join one of our workshops to get free hands-on experience with {{< var vm.product >}}.
:::

::: {.w-20-ns .tr}
[{{< fa calendar-check >}} Events](https://validmind.com/events/){target="_blank" .button}
:::

::::

#### Webinars

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns .pr4}
Join our webinars to learn more about AI risk management and stay up to date with the latest developments in the field.
:::

::: {.w-20-ns .tr}
[{{< fa users-rectangle >}} Webinars](https://validmind.com/webinars/){target="_blank" .button}
:::

::::

#### Newsletter

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns .pr4}
Receive exciting updates from {{< var vm.product >}} and curated material surrounding AI risk management. 
:::

::: {.w-20-ns .tr}
[{{< fa newspaper >}} Subscribe](https://validmind.com/community){target="_blank" .button}
:::

::::

#### LinkedIn

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns .pr4}
Follow us on LinkedIn for the latest updates, news, and insights in AI risk management.
:::

::: {.w-20-ns .tr}
[{{< fa brands linkedin >}} LinkedIn](https://www.linkedin.com/company/validmind){target="_blank" .button}
:::

::::

:::

## Build

::: {.callout}
## {{< var vm.product >}} style guide
The first step towards producing material for {{< var vm.product >}} is to familarize yourself with our [style guide](style-guide/style-guide.qmd). 

Learn about our company vision, get to know our brand's voice and preferred formatting conventions, and find additional resources to strengthen your writing skills. 
:::

Here at {{< var vm.product >}}, we embrace an [open source](https://en.wikipedia.org/wiki/Open_source) ideology. This means that we think expertise is inclusive, and is also open to evolving — there's always an opportunity to learn from each other, and help each other improve. 

As a member of the {{< var vm.product >}} community, we invite you to be part of our process. From our public documentation to the code behind our [{{< var vm.developer >}}](/developer/validmind-library.qmd), we've exposed the wiring for inspection in hopes that great minds think differently and dare to spark change. 

## Contribute

::: {.panel-tabset}

#### Code samples

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns .pr4}
Have a Jupyter Notebook that works perfectly with {{< var vm.product >}}, or covers a sample use case not already provided? Send it to us!

:::

::: {.w-20-ns .tr}

[{{< fa code >}}  Code samples](/developer/samples-jupyter-notebooks.qmd){.button}

:::

::::

#### {{< var validmind.developer >}}

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns .pr4}
Live by the {{< var vm.developer >}}, and have an idea that will streamline the experience for others? Let us know!
:::

::: {.w-20-ns .tr}
[{{< fa circle-check >}} {{< var validmind.developer >}}](https://github.com/validmind/validmind-library/){.button}
:::

::::

#### Product documentation

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns .pr4}
Spot a typo, or have identified a gap in instruction you think would be beneficial for the community to fill? Submit an edit to our GitHub repository! 
:::

::: {.w-30-ns .tr}
[{{< fa brands github >}} validmind/documentation](https://github.com/validmind/documentation){.button}
:::

::::

:::

Please note that all community contributions are subject to review by the {{< var vm.product >}} team. See our [software license agreement](/about/fine-print/license-agreement.qmd) for more details. 

## Join our team

We're always looking for talented individuals to join our team. If you're interested in working with us, check out our [careers page](https://validmind.com/careers/).