# Quarto docker profile configuration
# This profile uses placeholders for dynamic URL configuration

profile:
  default: docker

# Project settings with pre-render and post-render steps for Docker
project:
  type: website
  pre-render: scripts/make_configurable.sh
  post-render: bash -c "git restore _variables.yml _quarto.yml >/dev/null 2>&1 && echo 'Restored _variables.yml and _quarto.yml'"

# HTML format configuration
format:
  html:
    # Include scripts and other resources in the header
    include-in-header: 
      - environments/heap-production.html
