---
title: "Welcome to our documentation"
format: html
sidebar: false
page-layout: custom
---

::: {.grid}

::: {.g-col-1}
:::

::: {.g-col-10}
Find all the information you need to use our platform for model risk management (MRM)
:::

::: {.g-col-1}
:::
:::

::: {.grid}

::: {.g-col-1}
:::

::: {.g-col-3}

### **For Model Developers**

Collect, manage, and automate your model documentation and testing with our developer framework.
:::

::: {.g-col-3}
### **For Model Validators**

Review and evaluate models and model documentation to ensure they comply with organizational and regulatory requirements.
:::

::: {.g-col-3}
### **For Platform Administrators**

Learn how to configure the platform, from setting up connectivity via AWS PrivateLink, to customizing the ValidMind platform to suit your exisiting workflows.
:::

::: {.g-col-1}
:::

:::

::: {.grid}

::: {.g-col-1}
:::

::: {.g-col-3}
### Join our community

Adopt open-source notebooks for your use case or become a contributor.
:::

::: {.g-col-3}
### Training

Learn more about effective model risk management with the ValidMind platform.
:::

::: {.g-col-3}
### Support

Need some help? Try our self-service documentation or email us at <a href="mailto:support@validmind.com?subject=Support request">support@validmind.com</a>.
:::

::: {.g-col-1}
:::

:::
