---
title: "[validmind](/reference/validmind.html).errors"
sidebar: validmind-reference
toc-depth: 4
toc-expand: 4
---

This module contains all the custom errors that are used in the ValidMind Library. The following base errors are defined for others:

- BaseError
- APIRequestError

## [class]{.muted} APIRequestError

<!-- class.qmd.jinja2 - class definition -->

```python
class APIRequestError(BaseError):
```

Generic error for API request errors that are not known.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} BaseError

<!-- class.qmd.jinja2 - class definition -->

```python
class BaseError(Exception):
```

**Inherited members**

- **From builtins.BaseException**: with_traceback, add_note

### [description[()]{.muted}](#description)

<!-- class.qmd.jinja2 - member method signature -->

```python
description(self, args, kwargs)
```

## [class]{.muted} GetTestSuiteError

<!-- class.qmd.jinja2 - class definition -->

```python
class GetTestSuiteError(BaseError):
```

When the test suite could not be found.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InitializeTestSuiteError

<!-- class.qmd.jinja2 - class definition -->

```python
class InitializeTestSuiteError(BaseError):
```

When the test suite was found but could not be initialized.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidAPICredentialsError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidAPICredentialsError(APIRequestError):
```

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

### [description[()]{.muted}](#description)

<!-- class.qmd.jinja2 - member method signature -->

```python
description(self, args, kwargs)
```

## [class]{.muted} InvalidContentIdPrefixError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidContentIdPrefixError(APIRequestError):
```

When an invalid text content_id is sent to the API.

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidInputError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidInputError(BaseError):
```

When an invalid input object.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidMetricResultsError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidMetricResultsError(APIRequestError):
```

When an invalid metric results object is sent to the API.

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidProjectError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidProjectError(APIRequestError):
```

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

### [description[()]{.muted}](#description)

<!-- class.qmd.jinja2 - member method signature -->

```python
description(self, args, kwargs)
```

## [class]{.muted} InvalidRequestBodyError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidRequestBodyError(APIRequestError):
```

When a POST/PUT request is made with an invalid request body.

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidTestParametersError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidTestParametersError(BaseError):
```

When an invalid parameters for the test.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidTestResultsError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidTestResultsError(APIRequestError):
```

When an invalid test results object is sent to the API.

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidTextObjectError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidTextObjectError(APIRequestError):
```

When an invalid Metadat (Text) object is sent to the API.

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidValueFormatterError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidValueFormatterError(BaseError):
```

When an invalid value formatter is provided when serializing results.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} InvalidXGBoostTrainedModelError

<!-- class.qmd.jinja2 - class definition -->

```python
class InvalidXGBoostTrainedModelError(BaseError):
```

When an invalid XGBoost trained model is used when calling init_r_model.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} LoadTestError

<!-- class.qmd.jinja2 - class definition -->

```python
class LoadTestError(BaseError):
```

Exception raised when an error occurs while loading a test

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MismatchingClassLabelsError

<!-- class.qmd.jinja2 - class definition -->

```python
class MismatchingClassLabelsError(BaseError):
```

When the class labels found in the dataset don't match the provided target labels.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingAPICredentialsError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingAPICredentialsError(BaseError):
```

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

### [description[()]{.muted}](#description)

<!-- class.qmd.jinja2 - member method signature -->

```python
description(self, args, kwargs)
```

## [class]{.muted} MissingCacheResultsArgumentsError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingCacheResultsArgumentsError(BaseError):
```

When the cache_results function is missing arguments.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingClassLabelError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingClassLabelError(BaseError):
```

When the one or more class labels are missing from provided dataset targets.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingDependencyError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingDependencyError(BaseError):
```

When a required dependency is missing.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingDocumentationTemplate

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingDocumentationTemplate(BaseError):
```

When the client config is missing the documentation template.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingModelIdError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingModelIdError(BaseError):
```

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

### [description[()]{.muted}](#description)

<!-- class.qmd.jinja2 - member method signature -->

```python
description(self, args, kwargs)
```

## [class]{.muted} MissingOrInvalidModelPredictFnError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingOrInvalidModelPredictFnError(BaseError):
```

When the pytorch model is missing a predict function or its predict method does not have the expected arguments.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingRequiredTestInputError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingRequiredTestInputError(BaseError):
```

When a required test context variable is missing.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingRExtrasError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingRExtrasError(BaseError):
```

When the R extras have not been installed.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

### [description[()]{.muted}](#description)

<!-- class.qmd.jinja2 - member method signature -->

```python
description(self, args, kwargs)
```

## [class]{.muted} MissingTextContentIdError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingTextContentIdError(APIRequestError):
```

When a Text object is sent to the API without a content_id.

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} MissingTextContentsError

<!-- class.qmd.jinja2 - class definition -->

```python
class MissingTextContentsError(APIRequestError):
```

When a Text object is sent to the API without a "text" attribute.

**Inherited members**

- **From APIRequestError**: [class APIRequestError[()]{.muted}](#class-apirequesterror)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} SkipTestError

<!-- class.qmd.jinja2 - class definition -->

```python
class SkipTestError(BaseError):
```

Useful error to throw when a test cannot be executed.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} TestInputInvalidDatasetError

<!-- class.qmd.jinja2 - class definition -->

```python
class TestInputInvalidDatasetError(BaseError):
```

When an invalid dataset is used in a test context.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} UnsupportedColumnTypeError

<!-- class.qmd.jinja2 - class definition -->

```python
class UnsupportedColumnTypeError(BaseError):
```

When an unsupported column type is found on a dataset.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} UnsupportedDatasetError

<!-- class.qmd.jinja2 - class definition -->

```python
class UnsupportedDatasetError(BaseError):
```

When an unsupported dataset is used.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} UnsupportedFigureError

<!-- class.qmd.jinja2 - class definition -->

```python
class UnsupportedFigureError(BaseError):
```

When an unsupported figure object is constructed.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} UnsupportedModelError

<!-- class.qmd.jinja2 - class definition -->

```python
class UnsupportedModelError(BaseError):
```

When an unsupported model is used.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} UnsupportedModelForSHAPError

<!-- class.qmd.jinja2 - class definition -->

```python
class UnsupportedModelForSHAPError(BaseError):
```

When an unsupported model is used for SHAP importance.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## [class]{.muted} UnsupportedRModelError

<!-- class.qmd.jinja2 - class definition -->

```python
class UnsupportedRModelError(BaseError):
```

When an unsupported R model is used.

**Inherited members**

- **From BaseError**: [class BaseError[()]{.muted}](#class-baseerror), [__init__[()]{.muted}](#__init__), [__str__[()]{.muted}](#__str__), [description[()]{.muted}](#description)
- **From builtins.BaseException**: with_traceback, add_note

## raise_api_error[()]{.muted}

<!-- function.qmd.jinja2 - function signature -->

```python
def raise_api_error(error_string):
```

Safely try to parse JSON from the response message in case the API returns a non-JSON string or if the API returns a non-standard error

## should_raise_on_fail_fast[()]{.muted}

<!-- function.qmd.jinja2 - function signature -->

```python
def should_raise_on_fail_fast(error) -> bool:
```

Determine whether an error should be raised when fail_fast is True.
