# get_test_suite { #validmind.get_test_suite }

```python
get_test_suite(test_suite_id=None, section=None, *args, **kwargs)
```

Gets a TestSuite object for the current project or a specific test suite

This function provides an interface to retrieve the TestSuite instance for the
current project or a specific TestSuite instance identified by test_suite_id.
The project Test Suite will contain sections for every section in the project's
documentation template and these Test Suite Sections will contain all the tests
associated with that template section.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type   | Description                                                                                                                                    | Default   |
|---------------|--------|------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| test_suite_id | str    | The test suite name. If not passed, then the project's test suite will be returned. Defaults to None.                                          | `None`    |
| section       | str    | The section of the documentation template from which to retrieve the test suite. This only applies if test_suite_id is None. Defaults to None. | `None`    |
| args          |        | Additional arguments to pass to the TestSuite                                                                                                  | `()`      |
| kwargs        |        | Additional keyword arguments to pass to the TestSuite                                                                                          | `{}`      |