# init_r_model { #validmind.init_r_model }

```python
init_r_model(model_path, input_id='model')
```

Initializes a VM Model for an R model

R models must be saved to disk and the filetype depends on the model type...
Currently we support the following model types:

- LogisticRegression `glm` model in R: saved as an RDS file with `saveRDS`
- LinearRegression `lm` model in R: saved as an RDS file with `saveRDS`
- XGBClassifier: saved as a .json or .bin file with `xgb.save`
- XGBRegressor: saved as a .json or .bin file with `xgb.save`

LogisticRegression and LinearRegression models are converted to sklearn models by extracting
the coefficients and intercept from the R model. XGB models are loaded using the xgboost
since xgb models saved in .json or .bin format can be loaded directly with either Python or R

## Parameters {.doc-section .doc-section-parameters}

| Name       | Type   | Description                                         | Default    |
|------------|--------|-----------------------------------------------------|------------|
| model_path | str    | The path to the R model saved as an RDS or XGB file | _required_ |
| model_type | str    | The type of the model (one of R_MODEL_TYPES)        | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type    | Description                      |
|--------|---------|----------------------------------|
|        | VMModel | vm.vm.Model: A VM Model instance |