# init_model { #validmind.init_model }

```python
init_model(
    model=None,
    input_id='model',
    attributes=None,
    predict_fn=None,
    __log=True,
    **kwargs,
)
```

Initializes a VM Model, which can then be passed to other functions
that can perform additional analysis and tests on the data. This function
also ensures we are creating a model supported libraries.

## Parameters {.doc-section .doc-section-parameters}

| Name       | Type     | Description                                                                                                                                                                                                          | Default   |
|------------|----------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| model      | object   | A trained model or VMModel instance                                                                                                                                                                                  | `None`    |
| input_id   | str      | The input ID for the model (e.g. "my_model"). By default, this will be set to `model` but if you are passing this model as a test input using some other key than `model`, then you should set this to the same key. | `'model'` |
| attributes | dict     | A dictionary of model attributes                                                                                                                                                                                     | `None`    |
| predict_fn | callable | A function that takes an input and returns a prediction                                                                                                                                                              | `None`    |
| **kwargs   |          | Additional arguments to pass to the model                                                                                                                                                                            | `{}`      |

## Raises {.doc-section .doc-section-raises}

| Name   | Type       | Description                        |
|--------|------------|------------------------------------|
|        | ValueError | If the model type is not supported |

## Returns {.doc-section .doc-section-returns}

| Name   | Type    | Description                     |
|--------|---------|---------------------------------|
|        | VMModel | vm.VMModel: A VM Model instance |