# init_dataset { #validmind.init_dataset }

```python
init_dataset(
    dataset,
    model=None,
    index=None,
    index_name=None,
    date_time_index=False,
    columns=None,
    text_column=None,
    target_column=None,
    feature_columns=None,
    extra_columns=None,
    class_labels=None,
    type=None,
    input_id=None,
    __log=True,
)
```

Initializes a VM Dataset, which can then be passed to other functions
that can perform additional analysis and tests on the data. This function
also ensures we are reading a valid dataset type.

The following dataset types are supported:
- Pandas DataFrame
- Polars DataFrame
- Numpy ndarray
- Torch TensorDataset

## Parameters {.doc-section .doc-section-parameters}

| Name            | Type                 | Description                                                                                                                                                                                                                    | Default    |
|-----------------|----------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| dataset         |                      | dataset from various python libraries                                                                                                                                                                                          | _required_ |
| model           | VMModel              | ValidMind model object                                                                                                                                                                                                         | `None`     |
| targets         | vm.vm.DatasetTargets | A list of target variables                                                                                                                                                                                                     | _required_ |
| target_column   | str                  | The name of the target column in the dataset                                                                                                                                                                                   | `None`     |
| feature_columns | list                 | A list of names of feature columns in the dataset                                                                                                                                                                              | `None`     |
| extra_columns   | dictionary           | A dictionary containing the names of the                                                                                                                                                                                       | `None`     |
| class_labels    | dict                 | A list of class labels for classification problems                                                                                                                                                                             | `None`     |
| type            | str                  | The type of dataset (one of DATASET_TYPES)                                                                                                                                                                                     | `None`     |
| input_id        | str                  | The input ID for the dataset (e.g. "my_dataset"). By default, this will be set to `dataset` but if you are passing this dataset as a test input using some other key than `dataset`, then you should set this to the same key. | `None`     |

## Raises {.doc-section .doc-section-raises}

| Name   | Type       | Description                          |
|--------|------------|--------------------------------------|
|        | ValueError | If the dataset type is not supported |

## Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                          |
|--------|-----------|--------------------------------------|
|        | VMDataset | vm.vm.Dataset: A VM Dataset instance |