# run_documentation_tests { #validmind.run_documentation_tests }

```python
run_documentation_tests(
    section=None,
    send=True,
    fail_fast=False,
    inputs=None,
    config=None,
    **kwargs,
)
```

Collect and run all the tests associated with a template

This function will analyze the current project's documentation template and collect
all the tests associated with it into a test suite. It will then run the test
suite, log the results to the ValidMind API, and display them to the user.

## Parameters {.doc-section .doc-section-parameters}

| Name      | Type        | Description                                                                | Default   |
|-----------|-------------|----------------------------------------------------------------------------|-----------|
| section   | str or list | The section(s) to preview. Defaults to None.                               | `None`    |
| send      | bool        | Whether to send the results to the ValidMind API. Defaults to True.        | `True`    |
| fail_fast | bool        | Whether to stop running tests after the first failure. Defaults to False.  | `False`   |
| inputs    | dict        | A dictionary of test inputs to pass to the TestSuite                       | `None`    |
| config    |             | A dictionary of test parameters to override the defaults                   | `None`    |
| **kwargs  |             | backwards compatibility for passing in test inputs using keyword arguments | `{}`      |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                                                             |
|--------|--------|---------------------------------------------------------------------------------------------------------|
|        |        | TestSuite or dict: The completed TestSuite instance or a dictionary of TestSuites if section is a list. |

## Raises {.doc-section .doc-section-raises}

| Name   | Type       | Description                             |
|--------|------------|-----------------------------------------|
|        | ValueError | If the project has not been initialized |