# test { #validmind.test }

```python
test(func_or_id)
```

Decorator for creating and registering custom tests

This decorator registers the function it wraps as a test function within ValidMind
under the provided ID. Once decorated, the function can be run using the
`validmind.tests.run_test` function.

The function can take two different types of arguments:

- Inputs: ValidMind model or dataset (or list of models/datasets). These arguments
  must use the following names: `model`, `models`, `dataset`, `datasets`.
- Parameters: Any additional keyword arguments of any type (must have a default
  value) that can have any name.

The function should return one of the following types:

- Table: Either a list of dictionaries or a pandas DataFrame
- Plot: Either a matplotlib figure or a plotly figure
- Scalar: A single number (int or float)
- Boolean: A single boolean value indicating whether the test passed or failed

The function may also include a docstring. This docstring will be used and logged
as the metric's description.

## Parameters {.doc-section .doc-section-parameters}

| Name    | Type   | Description                                                                | Default    |
|---------|--------|----------------------------------------------------------------------------|------------|
| func    |        | The function to decorate                                                   | _required_ |
| test_id |        | The identifier for the metric. If not provided, the function name is used. | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description             |
|--------|--------|-------------------------|
|        |        | The decorated function. |