name: "Setup R and install packages"
description: "Sets up R and installs required packages for displaying interactive tables from .CSV"
runs:
  using: "composite"
  steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3' # Use the required R version

    - name: Install R packages
      shell: bash
      run: |
        Rscript -e 'install.packages(c("DT", "readr", "lubridate"), repos="https://cran.rstudio.com/")'

    - name: Verify R installation
      shell: bash
      run: |
        Rscript -e 'sessionInfo()'
        which R

    - name: Verify Quarto detects R
      shell: bash
      run: |
        quarto check
