---
title: "Export findings"
date: last-modified
---

Export your tracked model findings as comma-delimited tables (`.csv`) for use outside of the {{< var validmind.platform >}}.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] There are findings logged on any model.[^2]

:::

## Export findings by type

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Findings** for the list of all model findings.

2. Select a finding type[^3] to export from the tabs:

   - Validation Issue
   - Policy Exception
   - Model Limitation

3. (Optional) Narrow down and organize the list of findings and column headers you want to export by:

    - Filtering and sorting findings[^4]
    - Toggling visibility of and reordering column headers[^5]

4. Click **{{< fa download >}} Export** to export a list of your selected finding type with your adjustments applied.

    A `.csv` file will be automatically downloaded with your configuration.


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Add and manage model findings](/guide/model-validation/add-manage-model-findings.qmd)

[^3]: [Manage finding types](/guide/model-validation/manage-finding-types.qmd)

[^4]: [View and filter model findings](/guide/model-validation/view-filter-model-findings.qmd#filter-and-sort-model-findings)

[^5]: [Customize model findings layouts](/guide/model-validation/customize-model-findings-layouts.qmd)



