---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Export documents"
date: last-modified
aliases:
  - /guide/export-documentation.html
  - /guide/model-documentation/export-documentation.html
---

Export model documentation, validation reports, and ongoing monitoring reports as XML-based Microsoft Word (`.docx`) or Adobe Portable Document Format `.pdf` files.

::: {.callout title="Microsoft Word compatibility"}
Documents exported from {{< var vm.product >}} are compatible with Word 365, Word 2019, Word 2016, and Word 2013.
:::


::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] Documents exist and are completed or are in progress for your model.[^2]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

:::

## Export model documentation

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^4]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** or **Saved Versions** tab.[^5]

4. Click on a Documentation type file.[^6]

5. In right sidebar, click **{{< fa download >}} Export Document**.

    - Check off whether or not comments[^7] left on your document should be exported in your document
    - Choose your file format — DOCX,[^8] PDF[^9]

6. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.

## Export validation reports

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^10]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** or **Saved Versions** tab.[^11]

4. Click on a Validation Report type file.[^12]

5. In right sidebar, click **{{< fa download >}} Export Document**.

6. Configure what is exported in your document by checking off the relevant boxes:

   - Include compliance summary[^13]
   - Include validation guidelines information[^14]
   - Include validation guideline adherence details
   - Include comments left on document[^15]

7. Choose your file format:

    - **DOCX** — To update the table of contents, click **Yes** when Word prompts you to update fields.
    - **PDF** — Your document will be exported as a PDF with formatting preserved. The table of contents and links are generated automatically.

8. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.

## Export ongoing monitoring reports

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^16]

1. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** tab.[^17]

1. Click on an Ongoing Monitoring type file.[^18]

4. In right sidebar, click **{{< fa download >}} Export Document**.

    - Check off whether or not comments[^19] left on your document should be exported in your document
    - Choose your file format — DOCX,[^20] PDF[^21]

5. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.



<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^6]: [Working with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)

[^7]: [Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd#commenting)

[^8]: To update the table of contents, click **Yes** when Word prompts you to update fields.

[^9]: Your document will be exported as a PDF with formatting preserved. The table of contents and links are generated automatically.

[^10]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^11]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^12]: [Preparing validation reports](/guide/model-validation/preparing-validation-reports.qmd)

[^13]: [Assess compliance](/guide/model-validation/assess-compliance.qmd)

[^14]: [Manage validation guidelines](/guide/model-validation/manage-validation-guidelines.qmd)

[^15]: [Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd#commenting)

[^16]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^17]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^18]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^19]: [Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd#commenting)

[^20]: To update the table of contents, click **Yes** when Word prompts you to update fields.

[^21]: Your document will be exported as a PDF with formatting preserved. The table of contents and links are generated automatically.

