---
title: "Export artifacts"
date: last-modified
aliases: 
  - export-findings.html
---

Export tracked model artifacts as comma-delimited tables (`.csv`).

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] There are artifacts logged on any model.[^2]

:::

## Export artifacts by type

::: {.panel-tabset}

#### Export validation issues

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Validation Issues** for the list of validation issues across all models.

    (Optional) Narrow down and organize the list of validation issues and column headers you want to export by:

    - Filtering and sorting validation issues[^3]
    - Toggling visibility of and reordering column headers[^4]

2. Click **{{< fa download >}} Export** to export a list of your validation issues with your adjustments applied.

    A `.csv` file will be automatically downloaded with your configuration.

#### Export all other artifact types

1. In the left sidebar, click **{{< fa border-all >}} Artifacts** to view lists of other artifact types across all models.

2. Select an artifact type[^5] to export from the tabs:

   - Policy Exception
   - Model Limitation

    (Optional) Narrow down and organize the list of artifacts and column headers you want to export by:

    - Filtering and sorting artifacts[^6]
    - Toggling visibility of and reordering column headers[^7]

3. Click **{{< fa download >}} Export** to export a list of your selected artifact type with your adjustments applied.

    A `.csv` file will be automatically downloaded with your configuration.

:::


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Add and manage artifacts](/guide/model-validation/add-manage-artifacts.qmd)

[^3]: [View and filter artifacts](/guide/model-validation/view-filter-artifacts.qmd#filter-and-sort-artifacts)

[^4]: [Customize artifact layouts](/guide/model-validation/customize-artifact-layouts.qmd)

[^5]: [Manage artifact types](/guide/model-validation/manage-artifact-types.qmd)

[^6]: [View and filter artifacts](/guide/model-validation/view-filter-artifacts.qmd#filter-and-sort-artifacts)

[^7]: [Customize artifact layouts](/guide/model-validation/customize-artifact-layouts.qmd)




