---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Export analytics"
date: last-modified
---

Export analytics widgets as comma-delimited tables (`.csv`).

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] To export data on models, there must be models registered in the model inventory.[^1]
- [x] To export data on artifacts, there must be artifacts logged on any model.[^2]
- [x] To export data via your personal dashboard, you must have added analytics widgets to your personal dashboard.[^3]

:::

## Export analytics widgets from your personal dashboard

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. (Optional) Narrow down and organize the list of models and column headers you want to export by:

    - Filtering and sorting models[^2]
    - Toggling visibility of and reordering column headers[^3]

3. Click **{{< fa download >}} Export** to export a list of your models with your adjustments applied.

    A `.csv` file will be automatically downloaded with your configuration.

## Export analytics from shared dashboards




<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Add and manage artifacts](/guide/model-validation/add-manage-artifacts.qmd)

[^3]: [Customize your dashboard](/guide/configuration/customize-your-dashboard.qmd#manage-widgets)
