---
title: "Export documentation"
date: last-modified
aliases:
  - /guide/export-documentation.html
  - /guide/model-documentation/export-documentation.html
---

Export your model documentation, validation reports, and ongoing monitoring documentation as Microsoft Word files (`.docx`) for use outside of the {{< var validmind.platform >}}.

::: {.callout}
{{< var vm.product >}} supports Word 365, Word 2019, Word 2016, and Word 2013.
:::


::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] Documents exist and are completed or are in progress for your model.[^2]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

:::

## Export model documentation

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^4]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select a Document type file.^

4. In right sidebar, click **{{< fa download >}} Export Document**.

    Configure whether or not comments[^5] left on your document should be exported in your document.

5. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.

## Export validation report

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^6]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select a Validation Report type file.^

4. In right sidebar, click **{{< fa download >}} Export Document**.

5. Configure what is exported in your document by checking off the relevant boxes:

   - Include compliance summary[^7]
   - Include validation guidelines information[^8]
   - Include validation guideline adherence details
   - Include comments left on document[^9]

6. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.

## Export ongoing monitoring documentation

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^10]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select an Ongoing Monitoring type file.[^11]

4. In right sidebar, click **{{< fa download >}} Export Document**.

    Configure whether or not comments[^12] left on your document should be exported in your document.

5. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.



<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd#commenting)

[^6]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^7]: [Assess compliance](/guide/model-validation/assess-compliance.qmd)

[^8]: [Manage validation guidelines](/guide/model-validation/manage-validation-guidelines.qmd)

[^9]: [Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd#commenting)

[^10]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^11]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^12]: [Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd#commenting)
