---
title: "Manage custom reports"
date: last-modified
---

Add, edit, or remove custom data to your analytics within the {{< var validmind.platform >}}. 

### Visualization configuration options

- A visualization is a custom reporting widget that retrieves data on your metric of choice.
- Depending on the visualization type, the retrieved data can also be grouped and/or filtered.  

::: {.callout-important collapse="true" appearance="minimal"}
#### {{< fa chart-simple >}} Bar Chart

{{< include _reports-metrics.qmd >}}

{{< include _reports-grouping.qmd >}}
    
- Click **Add** to apply a grouping. 
- For bar charts, you are able to group by up to two fields. Click **{{< fa arrows-up-down >}}** to swap the x-axis and y-axis for the groupings.

{{< include _reports-filtering.qmd >}}

[sorting]{.smallcaps}
: Sort your data by your chosen metric or grouping in descending or ascending order.

[bar chart grouping style]{.smallcaps}
: Configure how the groupings are displayed:

- **{{< fa layer-group >}} Stacked** — Groups will display stacked in one vertical column.
- **{{< fa table-columns >}} Grouped** — Groups will display in side-by-side columns.

:::

::: {.callout-important collapse="true" appearance="minimal"}
#### {{< fa chart-pie >}} Pie Chart

{{< include _reports-metrics.qmd >}}

{{< include _reports-grouping.qmd >}}

{{< include _reports-filtering.qmd >}}
:::

::: {.callout-important collapse="true" appearance="minimal"}
#### {{< fa hashtag >}} Counter

{{< include _reports-metrics.qmd >}}

{{< include _reports-filtering.qmd >}}

[color]{.smallcaps}
: Set the display color for the counter. 
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1] 

:::

## Add custom analytics

{{< include /guide/reporting/_add-custom-analytics.qmd >}}

#### Create an analytics page

{{< include /guide/reporting/_create-an-analytics-page.qmd >}}

#### Create a visualization

{{< include /guide/reporting/_create-a-visualization.qmd >}}

## Edit custom analytics

1. On **{{< fa square-poll-vertical >}} Analytics**, click on the tab for your custom page you'd like to edit the visualization for.

2. Hover over the visualization you'd like to modify until the **{{< fa ellipsis-vertical >}}** icon appears, then click on it.

3. Select **{{< fa pencil >}} Edit Visualization**.

4. When you are finished with your adjustments, click **Save Visualization** to apply your changes.

## Remove custom analytics

::: {.callout-important title="Deletion of customized report setup is permanent."}
Removing a custom analytics page or visualization cannot be undone.
:::

You can either delete a entire custom analytics page, or remove a single custom visualization: 

#### Delete an analytics page

1. In the left sidebar, click **{{< fa square-poll-vertical >}} Analytics**.

2. Click on the tab for your custom page you'd like to delete.

3. Click **{{< fa ellipsis-vertical >}}** in the top-right hand corner of the custom page.

4. Select [**{{< fa trash-can >}} Delete Page**]{.red}.

5. After you confirm the deletion, the page will be permanently removed. 


#### Delete a visualization

1. On **{{< fa square-poll-vertical >}} Analytics**, click on the tab for your custom page you'd like to delete a visualization for.

2. Hover over the visualization you'd like to remove until the **{{< fa ellipsis-vertical >}}** icon appears, then click on it.

3. Select [**{{< fa trash-can >}} Remove Visualization**]{.red}.




<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Working with model findings](/guide/model-validation/working-with-model-findings.qmd)

[^3]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd)

[^4]: [Visualization configuration options](#visualization-configuration-options)