---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "View settings activity"
date: last-modified
---

Track information events associated with your organization's settings. Audit a history of administrative updates made on your organization, including changes to users and permissions, workflows and integrations, customization options, and more.

## What is tracked on settings activity?

The organization **{{< fa bolt >}} Activity** page shows a history of updates to configuration settings for the selected organization, such as activity related to:

- Organization settings, including management of business units, authentication configuration, email notifications, and general settings for documents
- Management of groups and group membership, users and invitations, permissions and roles
- Inventory record settings, including management of inventory record types and record fields
- Artifact settings, including management of artifact types, severities, and fields
- Document settings, including management of document types, templates, and library blocks
- Governance settings, including management of regulations or polices and related assessments, as well as risk areas and validation guidelines
- Workflow settings, including workflow creations, publications, and deletions
- Integration settings, including integration setup and secret management
- Webhook settings, including webhook secret management

:::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to view organization settings activity.[^1]

::::

## View settings activity

To review settings activity for your organization:

1. In the left sidebar, click **{{< fa wifi >}} Activity**.

2. Select the **Settings Activity** tab.

3. To narrow down settings activity by category, click:

    - **All** to view all activity.
    - **Artifacts** to view activity related to creation of, updates to, and deletions of artifact types,[^2] severities,[^3] and fields.[^4]
    - **Business Units** to view activity related to business unit creation, updates, and deletions.[^5]
    - **Documents** to view activity related to creation of, updates to, and deletions of document types,[^6] templates,[^7] and library blocks.[^8]
    - **Governance** to view activity related to creation of, updates to, and deletions of regulations or policies,[^9] as well as risk areas and validation guidelines.[^10]
    - **Groups** to view activity related to group creation, updates, deletions, and group membership changes.[^11]
    - **Integration Connections** to view activity related to integration connection creation, update, and removal.[^12]
    - **Integration Secrets** to view activity related to integration secret creation, revocation, and deletion.
    - **Inventory Records** to view activity related to inventory record type[^13] or record field[^14] creation, updates, and deletions.
    - **Organization Settings** to view activity related to authentication configuration, email notifications,[^15] and general settings for documents.[^16]
    - **Permissions** to view activity related to permission changes on roles.[^17]
    - **Roles** to view activity related to role creation, updates, deletions, and user role assignments.[^18]
    - **Users** to view activity related to user information updates and user invitations.[^19]
    - **Webhook Secrets** to view activity related to webhook secret creation, revocation, and deletion.[^20]
    - **Workflows** to view activity related to workflow creation, publications, and deletions.[^21]

    To view more details about specific activity, click {{< fa chevron-down >}} when the option is available on an entry.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Manage artifact types](/guide/validation/manage-artifact-types.qmd)

[^3]: [Manage artifact severities](/guide/validation/manage-artifact-severities.qmd)

[^4]: [Manage artifact fields](/guide/validation/manage-artifact-fields.qmd)

[^5]: [Set up your organization](/guide/configuration/set-up-your-organization.qmd#manage-business-units)

[^6]: [Manage document types](/guide/templates/manage-document-types.qmd)

[^7]: [Manage document templates](/guide/templates/manage-document-templates.qmd)

[^8]: [Manage text block library](/guide/templates/manage-text-block-library.qmd)

[^9]: [Customize {{< var validmind.checker >}}](/guide/templates/customize-document-checker.qmd)

[^10]: [Manage validation guidelines](/guide/validation/manage-validation-guidelines.qmd)

[^11]: [Manage groups](/guide/configuration/manage-groups.qmd)

[^12]: [Managing integrations](/guide/integrations/managing-integrations.qmd)

[^13]: [Manage inventory record types](/guide/inventory/manage-inventory-record-types.qmd)

[^14]: [Manage inventory fields](/guide/inventory/manage-inventory-fields.qmd)

[^15]: [Manage platform notifications](/guide/configuration/manage-platform-notifications.qmd#customize-email-notifications)

[^16]: [Managing documents](/guide/templates/managing-documents.qmd#manage-document-defaults)

[^17]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^18]: [Manage roles](/guide/configuration/manage-roles.qmd)

[^19]: [Manage users](/guide/configuration/manage-users.qmd)

[^20]: [Manage secrets](/guide/integrations/manage-secrets.qmd#webhook-secrets)

[^21]: [Setting up workflows](/guide/workflows/setting-up-workflows.qmd)


