### Post comments

1. In any section of the model documentation, select the portion of text you want to comment on, then click the **{{< fa message >}}** button that appears.

2. Enter your comment and click **Comment**.

3. You can view the comment by clicking the highlighted text. Comments will also appear in the right sidebar.

### Reply to comments

1. Click the highlighted text to view the comment thread.

2. Enter your comment and click **Reply**.

3. You can view the comment thread by clicking the highlighted text.

### Resolve comments

1. Click the highlighted text portion to view the thread, then click <span style="color: green">{{< fa check >}}</span> to resolve the thread.

2. To view the resolved comment thread, click the **{{< fa envelope-circle-check >}} Comments archive** button in the toolbar. 

    You can view a history of all archived comments in the Comment archive.

To reopen a comment thread, reply to the comment thread in the Comment archive or click the **{{< fa reply >}} Reopen** button that appears next to the highlighted text portion.



