<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
::: {.callout}
## Only documentation generated by the {{< var validmind.developer >}} or created in the {{< var validmind.platform >}} include a Document Overview.

PDF uploads are currently considered static documents.
:::

The **Document Overview** shows a section-by-section outline of your model's documentation, as well as summaries of:
      
- Any unresolved conversations^[[Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd)]
- The number of model artifacts^[[Working with artifacts](/guide/model-validation/working-with-artifacts.qmd)]
- The completion status for your model's documentation^[[Assign section statuses](/guide/model-documentation/assign-documentation-section-statuses.qmd)]
- Recent activity on your model^[[View model activity](/guide/model-inventory/view-model-activity.qmd)]

::::

:::: {.content-hidden unless-format="revealjs"}
The **Document Overview** shows a section-by-section outline of your model's documentation, as well as summaries of:

- Any unresolved conversations
- The number of model artifacts
- The completion status for your model's documentation
- Recent activity on your model
   
::::

