---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Assign documentation section statuses"
date: last-modified
aliases:
  - /guide/assign-documentation-section-statuses.html
---

Assign a completion status to individual sections of your model documentation that will be reflected in your Document Overview.

::: {.callout title="Section statuses cannot be assigned on static PDF documents."}
You can only assign section statuses for PDFs converted to editable documents,[^1] documents generated by the {{< var validmind.developer >}}, or documents created in the {{< var validmind.platform >}}.
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model you are documenting is registered in the model inventory.[^2]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

:::

## Steps

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^4]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** tab.[^5]

4. Click on a Documentation type file.[^6]

   Jump to any section of the model documentation by selecting the relevant section you would like to view.

4. Next to the heading of each section, you can assign a status from the drop-down:
    - [**In Progress**]{.bubble}
    - [**Done**]{.bubble}

The documentation completion status summary will then be updated on your Document Overview page.


<!-- FOOTNOTES -->

[^1]: [Manage model documents](/guide/templates/manage-model-documents.qmd#add-model-documents)

[^2]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^6]: [Working with model documentation](working-with-model-documentation.qmd#document-overview)
