---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Collaborate with others"
date: last-modified
aliases:
  - /guide/collaborate-on-documentation-projects.html
  - /guide/collaborate-with-others.html
---

Use the real-time collaboration features to track changes, add comments, and access the revision history for model documents.

::: {.callout title="You cannot interact within static PDF documents."}
You can only track changes, review revision history, and comment in PDFs converted to editable documents,[^1] documents generated by the {{< var validmind.developer >}}, or documents created in the {{< var validmind.platform >}}.

:::

## Feature highlights

- **Real-time collaboration** — Simultaneously edit model documents, leave and respond to comments and suggestions, and access revision history. Changes to model documents are also automatically added to {{< var vm.product >}}'s activity feed.

- **Spell and grammar checker** — Have your content checked automatically by the built-in spell and grammar checker. 

- **Math formulas** — Add math formulas to documents by clicking the **MathType** button and using the toolbar, or switch to handwriting.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^2]
- [x] Documents exist and are completed or are in progress for your model.[^3]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^4] 

:::

## Tracking changes

While working with content blocks in documents,[^5] you can suggest changes instead of editing the text directly.

### Suggest a change

1. Click the **{{< fa file-pen >}} Track changes** button in the toolbar to turn on suggestion mode.

2. Make your changes to the model document. 

    When changes tracking is enabled, other contributors can accept or decline the suggested changes.

### Resolve changes

1. Suggested changes appear in [green]{.green} or [~~red~~]{.red} highlighted text, depending on if the change is adding or removing content respectively.

    - To accept or decline a change, click the highlighted text, then click [{{< fa check >}}]{.green} or [{{< fa xmark >}}]{.red}. 
    - You can also reply to a suggested change.

2. To mass accept or decline suggestions, click the dropdown arrow next to the **{{< fa file-pen >}} Track changes** button and select one of the options:

    - **Accept all suggestions**
    - **Accept all selected suggestions**
    - **Discard all suggestions**
    - **Discard all selected suggestions**

## Revision history

While working with content blocks in documents,[^6] you can save named versions of your edits to retain specific revisions you'd like to keep. 

1. Click the **{{< fa clock-rotate-left >}} Revision history** button in the toolbar.

2. Once you save a version, you can then view revision history, compare versions, rename versions, or restore to a previous version.

3. Select **Save current version** to save your current version:

    a. Optionally, enter a version name.
    b. The default name is the date and time the latest change was made.

::: {.panel-tabset}


### View revision history

a. Click **{{< fa clock-rotate-left >}} Revision history** and select **Open revision history** to view a history of all saved versions as well as your current version.

b. To see the the change made with each version, select the version in the right sidebar. 

    - Changes made in that version are highlighted. 
    - Hover over the highlighted content to see who made the change.

### Compare versions

a. Click **{{< fa clock-rotate-left >}} Revision history** and select **Open revision history**. 

b. Click on the version you would like to compare another version to.

c. Hover over the other version to compare with your first version.

d. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **Compare against selected**.

### Rename a version

a. Click **{{< fa clock-rotate-left >}} Revision history** and select **Open revision history**. 

b. Click on the title of the version you want to rename to change it.

### Restore a version

a. Click **{{< fa clock-rotate-left >}} Revision history** and select **Open revision history**. 

b. Click on the desired version and select **Restore this version**.

c. The restored version will now appear under revision history with the name: `Restored: 'version name'`.

:::

## Commenting 

{{< include _comment-activity.qmd >}}

{{< include _commenting.qmd >}}

### Edit comments

1. Click the highlighted text portion to access the comment thread.

2. Click the **{{< fa ellipsis-vertical >}}** icon for the corresponding comment and select **{{< fa pencil >}} Edit**.

3. Edit your comment and click **Save**.

To edit a comment in a resolved thread, follow the same steps but click the **{{< fa comments >}} Comments archive** button first to access the resolved thread.

### Delete comments

1. Click the highlighted text portion to access the comment thread.

2. Click the **{{< fa ellipsis-vertical >}}** icon for the corresponding comment and select **{{< fa trash-can >}} Remove**.
    
3. After you confirm, the comment will be deleted.

To delete a comment in a resolved thread, follow the same steps but click the **{{< fa comments >}} Comments archive** button first to access the resolved thread.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
---> 


<!-- FOOTNOTES -->

[^1]: [Manage model documents](/guide/templates/manage-model-documents.qmd#add-model-documents)

[^2]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^3]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Work with content blocks](work-with-content-blocks.qmd)

[^6]: [Work with content blocks](work-with-content-blocks.qmd)