---
title: "Document Checker"
date: last-modified
---

Use the Document Checker to review your model documentation against a selected regulation. This helps ensure compliance and identify gaps before submission.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model is already registered in the model inventory.[^1]
- [x] The model must include some documentation.
:::

## Navigate to the Document Checker

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.
2. Select the model you'd like to check.[^2]
3. In the left sidebar that appears for your model, click **{{< fa book-open >}} Documentation**[^3].
4. On the documentation page, click the **Document Checker** tab on the right.

## Select a regulation
1. Use the **Select a regulation** dropdown to choose the regulation you'd like to check against (e.g., SR 11-7, E-23, SS1-23).
2. The Document Checker will use this regulation to evaluate your model’s documentation.

## Run the check
1. A pop-up with a list of regulation-based questions will appear.Scroll to the bottom and click **Check Document**.
3. The system will analyze your documentation and automatically answer the questions using its content.
4. Click **Expand All** to quickly scan through the findings.

## Review and address flagged items
1. Each question includes:
     - A **Finding** – highlighting what’s missing or unclear
     - A **Recommendation** – providing guidance on what to add or revise
2. Use the feedback to identify the appropriate sections of your documentation and fill in the gaps.


## What's next

- Explore [Model Validation tasks](/guide/model-validation/managing-model-validation.qmd) to continue the governance process.
- Learn more about [how LLM features work](https://docs.validmind.com/about/overview-llm-features.html)



<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^3]: [Working with model documentation](working-with-model-documentation.qmd#document-overview)
