---
title: "Export documentation"
date: last-modified
---

Export your model documentation or validation reports as Microsoft Word files (`.docx`) for use outside of the {{< var validmind.platform >}}.

::: {.prereq}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model is already registered in the model inventory.[^1]
- [x] Model documentation is completed or in progress.[^2]
- [x] You are a `Developer` or `Validator`, or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

::: {.callout}
ValidMind supports Word 365, Word 2019, Word 2016, and Word 2013.
:::

:::

## Export Model Documentation

1. In the left sidebar, click **Model Inventory**.

2. Select a model by clicking on it or find your model by applying a filter or searching for it.[^4]

3. In the left sidebar that appears for your model, click **Documentation**.

4. In right sidebar, click **{{< fa download >}} Export Document**.

5. Configure the export options:

   <!--- - Check **Include comment threads** to include comment threads in the exported file.
   - Check **Section activity logs** to include a history of changes in each section of the documentation. --->
   - Choose the file format for export. We currently support exporting to `.docx` for Microsoft Word format.

6. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.

## Export Validation Report

1. In the left sidebar, click **Model Inventory**.

2. Select a model by clicking on it or find your model by applying a filter or searching for it.[^5]

<!--- NR Mar 2024 this option does not yet exist --->
3. In the left sidebar that appears for your model, click **Validation Report**.

4. In right sidebar, click **{{< fa download >}} Export Document**.

5. Configure the export options:

   <!--- - Check **Include comment threads** to include comment threads in the exported file.
   - Check **Section activity logs** to include a history of changes in each section of the documentation. --->
   - Choose the file format for export. We currently support exporting to `.docx` for Microsoft Word format.

6. Click **{{< fa file-arrow-down >}} Download File** to download the file locally on your machine.

## What's next

* [Working with model documentation](working-with-model-documentation.qmd)
* [Collaborate on documentation](collaborate-with-others.qmd)
* [Submit for approval](submit-for-approval.qmd)




<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with model documentation](working-with-model-documentation.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

