---
title: "Submit for approval"
date: last-modified
aliases:
  - /guide/submit-for-approval.html
---

When you're ready, verify your model's status, and then submit your model documentation or validation report for approval.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model you are documenting is registered in the model inventory.[^1]
- [x] The approval workflow has been configured by an administrator.[^2]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

::: {.callout title="To configure workflow states and transitions, you must have sufficient workflow permissions."}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has these permissions.
:::

:::

## Verify model status

{{< include /guide/model-workflows/_model-workflows-see.qmd >}}

## Advance model status

::: {.callout-important title="For you to be able to transition a model through the approval workflow, you must have completed all the previous required workflow steps."}
For example, you cannot submit a validation report for review until the model documentation itself has been submitted. 
:::

{{< include /guide/model-workflows/_model-workflows-transition.qmd >}}

{{< include /guide/model-workflows/_transition-workflow-examples.qmd >}}

## What's next

- [Collaborate with others](collaborate-with-others.qmd)
- [Review model documentation](/guide/model-validation/review-model-documentation.qmd)
- [View model activity](/guide/model-inventory/view-model-activity.qmd)

<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Set up model workflows](/guide/model-workflows/configure-custom-workflows.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)



