---
title: "View documentation activity"
date: last-modified
---

Use the audit trail functionality in the {{< var validmind.platform >}} to track or audit all the information events associated with a specific model.

::: {.prereq}

## Prerequisites

<!-- ::: {.callout}
This topic matters for model developers, model validators, and auditors.
::: -->

- [x] {{< var link.login >}}
- [x] The model you are documenting is registered in the model inventory.[^1]
- [x] Model documentation has already been created for this project.[^2]
- [x] A model developer has started generating documentation, either using the {{< var vm.developer >}}[^3] or via the online UI editor.

:::

## Model Activity

{{< include _view-documentation-activity-overview.qmd >}}

{{< include _view-documentation-activity-steps.qmd >}}

### Filter activity

Use the top tabs to narrow down model activity.

#### All

Default view; shows all activity.

#### Comments

Shows only comments created or replied to; shows all comments by default.[^4]

Toggle mentions
: - Untoggle [**show all comments**]{.smallcaps} to see only comments you're mentioned in.
- Toggle [**show only mentions**]{.smallcaps} to show all comments again.

#### Status updates

Shows model status transitions.[^5]

#### Project updates

Shows project level updates:

- Inventory fields updated on the model[^6]
- Updates to model documentation, validation reports,[^7] or ongoing monitoring reports[^8]
- Test results added to your model[^9]
- Findings added, updated, or removed[^10]


## What's next

- [Working with model documentation](working-with-model-documentation.qmd)
- [Collaborate on documentation](collaborate-with-others.qmd)


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with model documentation](working-with-model-documentation.qmd)

[^3]: [{{< var validmind.developer >}}](/developer/get-started-developer-framework.qmd)

[^4]: [Collaborate with others (Commenting)](/guide/model-documentation/collaborate-with-others.qmd#commenting)

[^5]: [Working with model workflows](/guide/model-workflows/working-with-model-workflows.qmd)

[^6]: [Edit model inventory fields](/guide/model-inventory/edit-model-inventory-fields.qmd)

[^7]: [Working with model documentation](working-with-model-documentation.qmd)

[^8]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^9]: [ValidMind Developer Framework](/developer/get-started-developer-framework.qmd)

[^10]: [Work with model findings](/guide/model-validation/work-with-model-findings.qmd)


