---
title: "View documentation guidelines"
date: last-modified
---

View the guidelines for model documentation associated with a template to ensure that you are compliant with documentation requirements.

## Prerequisites

- You hold the `Developer` role.[^1]
- The model you are documenting is registered in the model inventory.[^2]
- Model documentation has already been created for this project.[^3]
- A model developer has started generating documentation, either using the {{< var validmind_developer >}}[^4] or via the online editor in the {{< var validmind_platform >}}.

::: {.callout-important}
Configuring the documentation guidelines for each template requires the `Customer Admin` role.
:::

## Steps

1. [Log into the {{< var validmind_platform >}}](/guide/configuration/log-in-to-validmind.qmd).

2. In the left sidebar, click **Model Inventory**.

3. Select a model by clicking on it or find your model by applying a filter or searching for it.[^5]

4. In the left sidebar that appears for your model, click **Documentation**.

5. In any section of the documentation for a model, click **ValidMind Insights™** in the top right corner to expand the **ValidMind Insights™** sidebar:

   - The **Documentation Guidelines** tab shows the documentation guidelines associated with this documentation template that have been configured by your model validation team.
   - The **Comments** tab shows the comment threads associated with this section of the model documentation.

## What's next

- [Get started with the {{< var validmind_developer >}}](/developer/get-started-developer-framework.qmd)
- [Working with model documentation](working-with-model-documentation.qmd)
- [Collaborate on documentation](collaborate-with-others.qmd)


<!-- FOOTNOTES -->

[^1]: [Managing users (Supported roles)](/guide/configuration/managing-users.qmd#supported-roles)

[^2]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^3]: [Working with model documentation](working-with-model-documentation.qmd)

[^4]: [{{< var validmind_developer >}}](/developer/get-started-developer-framework.qmd)

[^5]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)