---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Work with document versions"
date: last-modified
---

Save read-only versions of your documents in the {{< var validmind.platform >}} for reference and archival purposes.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] Documents exist and are completed or are in progress for your model.[^2]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

:::

## Save document versions

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^4]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** tab.

4. Click on the document file you want to save a version of.[^5]

5. On the document overview page, click **{{< fa bookmark >}} Save Version**.

6. Enter in your **[notes]{.smallcaps}** for the version.

7. Click **Save Version** to create a read-only version of that document that captures the contents in the current state.

::: {.callout title="Document versions can only be saved once every 5 minutes."}
If you save another version before 5 minutes is up, you'll receive a warning toast message asking you to try again later.
:::

## View saved document versions

1. In the left sidebar, click **{{< fa cubes >}} Inventory**. 

2. Select a model or find your model by applying a filter or searching for it.[^6]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Saved Versions** tab.

4. Click on the document file you want to review the saved version for.[^7]


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^5]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^6]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^7]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

