---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Working with model documentation"
date: last-modified
listing:
  - id: draft-documentation
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - view-documentation-guidelines.qmd
      - work-with-content-blocks.qmd
      - work-with-test-results.qmd
      - work-with-document-versions.qmd
  - id: complete-documentation
    type: grid
    max-description-length: 250
    grid-columns: 2
    sort: false
    fields: [title, description]
    contents:
      - assign-documentation-section-statuses.qmd
      - check-documentation-for-compliance.qmd
      - collaborate-with-others.qmd
      - submit-for-approval.qmd
aliases:
  - /guide/working-with-model-documentation.html
---

After you upload initial model documentation through the {{< var vm.developer >}}, use the {{< var vm.platform >}} to make qualitative edits to model documentation, view guidelines, collaborate with validators, and submit your model documentation for approval. 

::: {.callout}
## Looking to get started as a model developer?

This section describes how to work with model documentation in the {{< var validmind.platform >}}. Typically, you perform the tasks described here **after you have uploaded some initial model documentation** with the {{< var validmind.developer >}}. 

[{{< var validmind.developer >}} {{< fa hand-point-right>}}](/developer/validmind-library.qmd)
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model you are documenting is registered in the model inventory.[^1]
- [x] You have provided some content for the documentation, either by uploading it through the {{< var validmind.developer >}}[^2] or via the {{< var validmind.platform >}}.
- [x] You are a [{{< fa code >}} Developer]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^3] 

:::

## Key concepts

<!-- TO EDIT THESE KEY CONCEPTS, SEE `about/glossary/_model-documentation.qmd` -->

{{< include /about/glossary/model_documentation/_doc-intro.qmd >}}

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}

{{< include /about/glossary/model_documentation/_conceptual-soundness.qmd >}}

{{< include /about/glossary/model_documentation/_data-preparation.qmd >}}


:::

::: {.w-40-ns}

{{< include /about/glossary/model_documentation/_model-development.qmd >}}

{{< include /about/glossary/model_documentation/_monitoring-governance.qmd >}}

:::

::::

## Document Overview

{{< include _document-overview.qmd >}}

{{< include _locate-document-overview.qmd >}}

### Add or edit documentation

Modify the contents of the **Latest** version of your document:[^4]

1. From the **Document Overview**, jump to any section of the model documentation by clicking on the heading you would like to view.

5. In any section of the documentation, click to add or edit content. 

    Use the text editor functions to edit the content of the section. Whenever you make a change, an activity log entry is recorded under **Section activity** on the page, just below the section you are editing. 

6. Save your edits as a revision:

   a. Click on the {{< fa clock-rotate-left >}} icon in the editor toolbar.
   b. Select **Save current revision** and enter a name.
   c. Click {{< fa check >}} to save the current revision.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## Prepare model documentation

Draft, edit, and refine your model documentation, complete with supporting test results:

:::{#draft-documentation}
:::

Wrap up your model documentation, collaborate with other stakeholders, and submit your work for approval:

:::{#complete-documentation}
:::


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [{{< var validmind.developer >}}](/developer/validmind-library.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)