---
title: "[validmind](/validmind/validmind.qmd).vm_models"
sidebar: validmind-reference
toc-depth: 4
toc-expand: 4
# module.qmd.jinja2
---

<!-- docstring.jinja2 -->

Models entrypoint

## R_MODEL_TYPES

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw"></span><span class="name">R_MODEL_TYPES</span><span class="o">=</span> <span class="default_value">\['LogisticRegression', 'LinearRegression', 'XGBClassifier', 'XGBRegressor'\]</span>:

:::

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> VMInput

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">VMInput</span>(<span class="base">ABC</span>):

:::

<!-- docstring.jinja2 -->

Base class for ValidMind Input types.

### with_options<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">with_options</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">\*\*kwargs</span><span class="p">:</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="n">Any</span><span class="p">\]</span></span>)<span class="p"> → </span><span class="return-annotation"><a href="/validmind/validmind/vm_models.qmd#vminput">validmind.vm_models.VMInput</a></span>:

:::

<!-- docstring.jinja2 -->

Allows for setting options on the input object that are passed by the user when using the input to run a test or set of tests.

To allow options, just override this method in the subclass (see VMDataset) and ensure that it returns a new instance of the input with the specified options set.

**Arguments**

- `**kwargs`: Arbitrary keyword arguments that will be passed to the input object.

**Returns**

- A new instance of the input with the specified options set.

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> VMDataset

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">VMDataset</span>(<span class="base">VMInput</span>):

:::

<!-- docstring.jinja2 -->

Base class for VM datasets.

Child classes should be used to support new dataset types (tensor, polars etc.) by converting the user's dataset into a numpy array collecting metadata like column names and then call this (parent) class `__init__` method.

This way we can support multiple dataset types but under the hood we only need to work with numpy arrays and pandas dataframes in this class.

**Arguments**

- `raw_dataset (np.ndarray)`: The raw dataset as a NumPy array.
- `input_id (str)`: Identifier for the dataset.
- `index (np.ndarray)`: The raw dataset index as a NumPy array.
- `columns (Set[str])`: The column names of the dataset.
- `target_column (str)`: The target column name of the dataset.
- `feature_columns (List[str])`: The feature column names of the dataset.
- `feature_columns_numeric (List[str])`: The numeric feature column names of the dataset.
- `feature_columns_categorical (List[str])`: The categorical feature column names of the dataset.
- `text_column (str)`: The text column name of the dataset for NLP tasks.
- `target_class_labels (Dict)`: The class labels for the target columns.
- `df (pd.DataFrame)`: The dataset as a pandas DataFrame.
- `extra_columns (Dict)`: Extra columns to include in the dataset.
- `copy_data (bool, optional)`: Whether to copy the data. Defaults to True.

### VMDataset<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">VMDataset</span>(<span class="params"><span class="n">raw_dataset</span><span class="p">:</span><span class="n">np</span>.<span class="n">ndarray</span><span class="muted">,</span></span><span class="params"><span class="n">input_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">model</span><span class="p">:</span><a href="/validmind/validmind/vm_models.qmd#vmmodel">validmind.vm_models.VMModel</a><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">index</span><span class="p">:</span><span class="n">np</span>.<span class="n">ndarray</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">index_name</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">date_time_index</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">False</span><span class="muted">,</span></span><span class="params"><span class="n">columns</span><span class="p">:</span><span class="nb">list</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">target_column</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">feature_columns</span><span class="p">:</span><span class="nb">list</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">text_column</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">extra_columns</span><span class="p">:</span><span class="nb">dict</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">target_class_labels</span><span class="p">:</span><span class="nb">dict</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">copy_data</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">True</span></span>)

:::

<!-- docstring.jinja2 -->

Initializes a VMDataset instance.

**Arguments**

- `raw_dataset (np.ndarray)`: The raw dataset as a NumPy array.
- `input_id (str)`: Identifier for the dataset.
- `model (VMModel)`: Model associated with the dataset.
- `index (np.ndarray)`: The raw dataset index as a NumPy array.
- `index_name (str)`: The raw dataset index name as a NumPy array.
- `date_time_index (bool)`: Whether the index is a datetime index.
- `columns (List[str], optional)`: The column names of the dataset. Defaults to None.
- `target_column (str, optional)`: The target column name of the dataset. Defaults to None.
- `feature_columns (str, optional)`: The feature column names of the dataset. Defaults to None.
- `text_column (str, optional)`: The text column name of the dataset for nlp tasks. Defaults to None.
- `target_class_labels (Dict, optional)`: The class labels for the target columns. Defaults to None.
- `copy_data (bool, optional)`: Whether to copy the data. Defaults to True.

### add_extra_column<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">add_extra_column</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">column_name</span><span class="muted">,</span></span><span class="params"><span class="n">column_values</span><span class="o">=</span><span class="kc">None</span></span>):

:::

<!-- docstring.jinja2 -->

Adds an extra column to the dataset without modifying the dataset `features` and `target` columns.

**Arguments**

- `column_name (str)`: The name of the extra column.
- `column_values (np.ndarray)`: The values of the extra column.

### assign_predictions<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">assign_predictions</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">model</span><span class="p">:</span><a href="/validmind/validmind/vm_models.qmd#vmmodel">validmind.vm_models.VMModel</a><span class="muted">,</span></span><span class="params"><span class="n">prediction_column</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="nb">str</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">prediction_values</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">List</span><span class="p">\[</span><span class="n">Any</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">probability_column</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="nb">str</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">probability_values</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">List</span><span class="p">\[</span><span class="nb">float</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">prediction_probabilities</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">List</span><span class="p">\[</span><span class="nb">float</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">\*\*kwargs</span><span class="p">:</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="n">Any</span><span class="p">\]</span></span>):

:::

<!-- docstring.jinja2 -->

Assign predictions and probabilities to the dataset.

**Arguments**

- `model (VMModel)`: The model used to generate the predictions.
- `prediction_column (Optional[str])`: The name of the column containing the predictions.
- `prediction_values (Optional[List[Any]])`: The values of the predictions.
- `probability_column (Optional[str])`: The name of the column containing the probabilities.
- `probability_values (Optional[List[float]])`: The values of the probabilities.
- `prediction_probabilities (Optional[List[float]])`: DEPRECATED: The values of the probabilities.
- `**kwargs`: Additional keyword arguments that will get passed through to the model's `predict` method.

### prediction_column<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">prediction_column</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">model</span><span class="p">:</span><a href="/validmind/validmind/vm_models.qmd#vmmodel">validmind.vm_models.VMModel</a><span class="muted">,</span></span><span class="params"><span class="n">column_name</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="nb">str</span></span>:

:::

<!-- docstring.jinja2 -->

Get or set the prediction column for a model.

### probability_column<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">probability_column</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">model</span><span class="p">:</span><a href="/validmind/validmind/vm_models.qmd#vmmodel">validmind.vm_models.VMModel</a><span class="muted">,</span></span><span class="params"><span class="n">column_name</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="nb">str</span></span>:

:::

<!-- docstring.jinja2 -->

Get or set the probability column for a model.

### target_classes<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">target_classes</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Returns the target class labels or unique values of the target column.

### with_options<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">with_options</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">\*\*kwargs</span><span class="p">:</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="n">Any</span><span class="p">\]</span></span>)<span class="p"> → </span><span class="return-annotation"><a href="/validmind/validmind/vm_models.qmd#vmdataset">validmind.vm_models.VMDataset</a></span>:

:::

<!-- docstring.jinja2 -->

Support options provided when passing an input to run_test or run_test_suite

**Arguments**

- `**kwargs`: Options:
- columns: Filter columns in the dataset

**Returns**

- A new instance of the dataset with only the specified columns

### x_df<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">x_df</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Returns a dataframe containing only the feature columns

### y_df<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">y_df</span>(<span class="param"><span class="bp">self</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="n">pd</span>.<span class="n">DataFrame</span></span>:

:::

<!-- docstring.jinja2 -->

Returns a dataframe containing the target column

### y_pred<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">y_pred</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">model</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="n">np</span>.<span class="n">ndarray</span></span>:

:::

<!-- docstring.jinja2 -->

Returns the predictions for a given model.

Attempts to stack complex prediction types (e.g., embeddings) into a single, multi-dimensional array.

**Arguments**

- `model (VMModel)`: The model whose predictions are sought.

**Returns**

- The predictions for the model

### y_pred_df<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">y_pred_df</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">model</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="n">pd</span>.<span class="n">DataFrame</span></span>:

:::

<!-- docstring.jinja2 -->

Returns a dataframe containing the predictions for a given model

### y_prob<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">y_prob</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">model</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="n">np</span>.<span class="n">ndarray</span></span>:

:::

<!-- docstring.jinja2 -->

Returns the probabilities for a given model.

**Arguments**

- `model (str)`: The ID of the model whose predictions are sought.

**Returns**

- The probability variables.

### y_prob_df<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">y_prob_df</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">model</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="n">pd</span>.<span class="n">DataFrame</span></span>:

:::

<!-- docstring.jinja2 -->

Returns a dataframe containing the probabilities for a given model

### df{.property}

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw"></span><span class="name">df</span>():

:::

<!-- docstring.jinja2 -->

Returns the dataset as a pandas DataFrame.

**Returns**

- The dataset as a pandas DataFrame.

### x{.property}

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw"></span><span class="name">x</span>():

:::

<!-- docstring.jinja2 -->

Returns the input features (X) of the dataset.

**Returns**

- The input features.

### y{.property}

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw"></span><span class="name">y</span>():

:::

<!-- docstring.jinja2 -->

Returns the target variables (y) of the dataset.

**Returns**

- The target variables.

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> VMModel

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">VMModel</span>(<span class="base">VMInput</span>):

:::

<!-- docstring.jinja2 -->

An base class that wraps a trained model instance and its associated data.

**Arguments**

- `model (object, optional)`: The trained model instance. Defaults to None.
- `input_id (str, optional)`: The input ID for the model. Defaults to None.
- `attributes (ModelAttributes, optional)`: The attributes of the model. Defaults to None.
- `name (str, optional)`: The name of the model. Defaults to the class name.

### VMModel<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">VMModel</span>(<span class="params"><span class="n">input_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">model</span><span class="p">:</span><span class="nb">object</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">attributes</span><span class="p">:</span><a href="/validmind/validmind/vm_models.qmd#modelattributes">validmind.vm_models.ModelAttributes</a><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">name</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">\*\*kwargs</span></span>)

:::

### predict<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="decorators"><span class="decorator">@<span class="n">abstractmethod</span></span> </span>

<span class="kw">def</span><span class="name">predict</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">\*args</span><span class="muted">,</span></span><span class="params"><span class="n">\*\*kwargs</span></span>):

:::

<!-- docstring.jinja2 -->

Predict method for the model. This is a wrapper around the model's

### predict_proba<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">predict_proba</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">\*args</span><span class="muted">,</span></span><span class="params"><span class="n">\*\*kwargs</span></span>):

:::

<!-- docstring.jinja2 -->

Predict probabilties - must be implemented by subclass if needed

### serialize<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">serialize</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Serializes the model to a dictionary so it can be sent to the API

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> Figure

<!-- signatures.jinja2 -->

::: {.signature}

<span class="decorators"><span class="decorator">@<span class="n">dataclass</span></span> </span>

<span class="kw">class</span><span class="name">Figure</span>:

:::

<!-- docstring.jinja2 -->

Figure objects track the schema supported by the ValidMind API.

### Figure<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">Figure</span>(<span class="params"><span class="n">key</span><span class="p">:</span><span class="nb">str</span><span class="muted">,</span></span><span class="params"><span class="n">figure</span><span class="p">:</span><span class="n">Union</span><span class="p">\[</span><span class="n">matplotlib</span>.<a href="/validmind/validmind/vm_models.qmd#figure">validmind.vm_models.figure</a>.<span class="n">Figure</span><span class="p">, </span><span class="n">go</span>.<span class="n">Figure</span><span class="p">, </span><span class="n">go</span>.<a href="/validmind/validmind/vm_models.qmd#figurewidget">validmind.vm_models.FigureWidget</a><span class="p">, </span><span class="nb">bytes</span><span class="p">\]</span><span class="muted">,</span></span><span class="params"><span class="n">ref_id</span><span class="p">:</span><span class="nb">str</span><span class="muted">,</span></span><span class="params"><span class="n">\_type</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="s1">'plot'</span></span>)

:::

### serialize<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">serialize</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Serializes the Figure to a dictionary so it can be sent to the API.

### serialize_files<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">serialize_files</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Creates a `requests`-compatible files object to be sent to the API.

### to_widget<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">to_widget</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Returns the ipywidget compatible representation of the figure. Ideally we would render images as-is, but Plotly FigureWidgets don't work well on Google Colab when they are combined with ipywidgets.

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> ModelAttributes

<!-- signatures.jinja2 -->

::: {.signature}

<span class="decorators"><span class="decorator">@<span class="n">dataclass</span></span> </span>

<span class="kw">class</span><span class="name">ModelAttributes</span>:

:::

<!-- docstring.jinja2 -->

Model attributes definition.

### ModelAttributes<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">ModelAttributes</span>(<span class="params"><span class="n">architecture</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">framework</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">framework_version</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">language</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">task</span><span class="p">:</span><a href="/validmind/validmind/vm_models.qmd#modeltask">validmind.vm_models.ModelTask</a><span class="o">=</span><span class="kc">None</span></span>)

:::

### from_dict<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="decorators"><span class="decorator">@<span class="n">classmethod</span></span> </span>

<span class="kw">def</span><span class="name">from_dict</span>(<span class="params"><span class="n">cls</span><span class="muted">,</span></span><span class="params"><span class="n">data</span></span>):

:::

<!-- docstring.jinja2 -->

Creates a ModelAttributes instance from a dictionary.

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> ResultTable

<!-- signatures.jinja2 -->

::: {.signature}

<span class="decorators"><span class="decorator">@<span class="n">dataclass</span></span> </span>

<span class="kw">class</span><span class="name">ResultTable</span>:

:::

<!-- docstring.jinja2 -->

A dataclass that holds the table summary of result.

### ResultTable<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">ResultTable</span>(<span class="params"><span class="n">data</span><span class="p">:</span><span class="n">Union</span><span class="p">\[</span><span class="n">List</span><span class="p">\[</span><span class="n">Any</span><span class="p">\]</span><span class="p">, </span><span class="n">pd</span>.<span class="n">DataFrame</span><span class="p">\]</span><span class="muted">,</span></span><span class="params"><span class="n">title</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="nb">str</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span></span>)

:::

### serialize<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">serialize</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> TestResult

<!-- signatures.jinja2 -->

::: {.signature}

<span class="decorators"><span class="decorator">@<span class="n">dataclass</span></span> </span>

<span class="kw">class</span><span class="name">TestResult</span>(<span class="base">Result</span>):

:::

<!-- docstring.jinja2 -->

Test result.

### TestResult<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">TestResult</span>(<span class="params"><span class="n">result_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">name</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="s1">'Test Result'</span><span class="muted">,</span></span><span class="params"><span class="n">result_type</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">ref_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">title</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="nb">str</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">doc</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="nb">str</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">description</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">Union</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><a href="/validmind/validmind/vm_models.qmd#descriptionfuture">validmind.vm_models.DescriptionFuture</a><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">metric</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">Union</span><span class="p">\[</span><span class="nb">int</span><span class="p">, </span><span class="nb">float</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">tables</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">List</span><span class="p">\[</span><a href="/validmind/validmind/vm_models.qmd#resulttable">validmind.vm_models.ResultTable</a><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">raw_data</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><a href="/validmind/validmind/vm_models.qmd#rawdata">validmind.vm_models.RawData</a><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">figures</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">List</span><span class="p">\[</span><span class="n">Figure</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">passed</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="nb">bool</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">params</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="n">Any</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">inputs</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="n">Union</span><span class="p">\[</span><span class="n">List</span><span class="p">\[</span><a href="/validmind/validmind/vm_models.qmd#vminput">validmind.vm_models.VMInput</a><span class="p">\]</span><span class="p">, </span><a href="/validmind/validmind/vm_models.qmd#vminput">validmind.vm_models.VMInput</a><span class="p">\]</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">metadata</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="n">Any</span><span class="p">\]</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">\_was_description_generated</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">False</span><span class="muted">,</span></span><span class="params"><span class="n">\_unsafe</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">False</span><span class="muted">,</span></span><span class="params"><span class="n">\_client_config_cache</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="n">Any</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span></span>)

:::

### add_figure<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">add_figure</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">figure</span><span class="p">:</span><span class="n">Union</span><span class="p">\[</span><span class="n">matplotlib</span>.<a href="/validmind/validmind/vm_models.qmd#figure">validmind.vm_models.figure</a>.<span class="n">Figure</span><span class="p">, </span><span class="n">go</span>.<span class="n">Figure</span><span class="p">, </span><span class="n">go</span>.<a href="/validmind/validmind/vm_models.qmd#figurewidget">validmind.vm_models.FigureWidget</a><span class="p">, </span><span class="nb">bytes</span><span class="p">, </span><span class="n">Figure</span><span class="p">\]</span></span>):

:::

<!-- docstring.jinja2 -->

Add a new figure to the result.

**Arguments**

- `figure`: The figure to add. Can be one of:
- matplotlib.figure.Figure: A matplotlib figure
- plotly.graph_objs.Figure: A plotly figure
- plotly.graph_objs.FigureWidget: A plotly figure widget
- bytes: A PNG image as raw bytes
- validmind.vm_models.figure.Figure: A ValidMind figure object.

**Returns**

- None.

### add_table<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">add_table</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">table</span><span class="p">:</span><span class="n">Union</span><span class="p">\[</span><a href="/validmind/validmind/vm_models.qmd#resulttable">validmind.vm_models.ResultTable</a><span class="p">, </span><span class="n">pd</span>.<span class="n">DataFrame</span><span class="p">, </span><span class="n">List</span><span class="p">\[</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="n">Any</span><span class="p">\]</span><span class="p">\]</span><span class="p">\]</span><span class="muted">,</span></span><span class="params"><span class="n">title</span><span class="p">:</span><span class="n">Optional</span><span class="p">\[</span><span class="nb">str</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span></span>):

:::

<!-- docstring.jinja2 -->

Add a new table to the result.

**Arguments**

- `table (Union[ResultTable, pd.DataFrame, List[Dict[str, Any]]])`: The table to add.
- `title (Optional[str])`: The title of the table (can optionally be provided for pd.DataFrame and List\[Dict\[str, Any\]\] tables).

### check_result_id_exist<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">check_result_id_exist</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Check if the result_id exists in any test block across all sections.

### log<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">log</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">section_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">content_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">position</span><span class="p">:</span><span class="nb">int</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">unsafe</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">False</span><span class="muted">,</span></span><span class="params"><span class="n">config</span><span class="p">:</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="nb">bool</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span></span>):

:::

<!-- docstring.jinja2 -->

Log the result to ValidMind.

**Arguments**

- `section_id (str)`: The section ID within the model document to insert the test result.
- `content_id (str)`: The content ID to log the result to.
- `position (int)`: The position (index) within the section to insert the test result.
- `unsafe (bool)`: If True, log the result even if it contains sensitive data i.e. raw data from input datasets.
- `config (Dict[str, bool])`: Configuration options for displaying the test result. Available config options:
- hideTitle: Hide the title in the document view
- hideText: Hide the description text in the document view
- hideParams: Hide the parameters in the document view
- hideTables: Hide tables in the document view
- hideFigures: Hide figures in the document view

### log_async<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">async def</span><span class="name">log_async</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">section_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">content_id</span><span class="p">:</span><span class="nb">str</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">position</span><span class="p">:</span><span class="nb">int</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">config</span><span class="p">:</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="nb">bool</span><span class="p">\]</span><span class="o">=</span><span class="kc">None</span></span>):

:::

### remove_figure<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">remove_figure</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">index</span><span class="p">:</span><span class="nb">int</span><span class="o">=</span><span class="kc">0</span></span>):

:::

<!-- docstring.jinja2 -->

Remove a figure from the result by index.

**Arguments**

- `index (int)`: The index of the figure to remove (default is 0).

### remove_table<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">remove_table</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">index</span><span class="p">:</span><span class="nb">int</span></span>):

:::

<!-- docstring.jinja2 -->

Remove a table from the result by index.

**Arguments**

- `index (int)`: The index of the table to remove (default is 0).

### serialize<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">serialize</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Serialize the result for the API.

### to_widget<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">to_widget</span>(<span class="param"><span class="bp">self</span></span>):

:::

### validate_log_config<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">validate_log_config</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">config</span><span class="p">:</span><span class="n">Dict</span><span class="p">\[</span><span class="nb">str</span><span class="p">, </span><span class="nb">bool</span><span class="p">\]</span></span>):

:::

<!-- docstring.jinja2 -->

Validate the configuration options for logging a test result

**Arguments**

- `config (Dict[str, bool])`: Configuration options to validate

**Raises**

- `InvalidParameterError`: If config contains invalid keys or non-boolean values

### test_name{.property}

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw"></span><span class="name">test_name</span>():

:::

<!-- docstring.jinja2 -->

Get the test name, using custom title if available.

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> TestSuite

<!-- signatures.jinja2 -->

::: {.signature}

<span class="decorators"><span class="decorator">@<span class="n">dataclass</span></span> </span>

<span class="kw">class</span><span class="name">TestSuite</span>:

:::

<!-- docstring.jinja2 -->

Base class for test suites. Test suites are used to define a grouping of tests that can be run as a suite against datasets and models. Test Suites can be defined by inheriting from this base class and defining the list of tests as a class variable.

Tests can be a flat list of strings or may be nested into sections by using a dict.

### TestSuite<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">TestSuite</span>(<span class="param"><span class="n">sections</span><span class="p">:</span><span class="n">List</span><span class="p">\[</span><a href="/validmind/validmind/vm_models.qmd#testsuitesection">validmind.vm_models.TestSuiteSection</a><span class="p">\]</span><span class="o">=</span><span class="kc">None</span></span>)

:::

### get_default_config<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">get_default_config</span>(<span class="param"><span class="bp">self</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="nb">dict</span></span>:

:::

<!-- docstring.jinja2 -->

Returns the default configuration for the test suite.

Each test in a test suite can accept parameters and those parameters can have default values. Both the parameters and their defaults are set in the test class and a config object can be passed to the test suite's run method to override the defaults. This function returns a dictionary containing the parameters and their default values for every test to allow users to view and set values.

**Returns**

- A dictionary of test names and their default parameters.

### get_tests<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">get_tests</span>(<span class="param"><span class="bp">self</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="n">List</span><span class="p">\[</span><span class="nb">str</span><span class="p">\]</span></span>:

:::

<!-- docstring.jinja2 -->

Get all test suite test objects from all sections.

### num_tests<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">num_tests</span>(<span class="param"><span class="bp">self</span></span>)<span class="p"> → </span><span class="return-annotation"><span class="nb">int</span></span>:

:::

<!-- docstring.jinja2 -->

Returns the total number of tests in the test suite.

<!-- class.qmd.jinja2 -->

## <span class="prefix"></span> TestSuiteRunner

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">TestSuiteRunner</span>:

:::

<!-- docstring.jinja2 -->

Runs a test suite.

### TestSuiteRunner<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="name">TestSuiteRunner</span>(<span class="params"><span class="n">suite</span><span class="p">:</span><a href="/validmind/validmind/vm_models.qmd#testsuite">validmind.vm_models.TestSuite</a><span class="muted">,</span></span><span class="params"><span class="n">config</span><span class="p">:</span><span class="nb">dict</span><span class="o">=</span><span class="kc">None</span><span class="muted">,</span></span><span class="params"><span class="n">inputs</span><span class="p">:</span><span class="nb">dict</span><span class="o">=</span><span class="kc">None</span></span>)

:::

### log_results<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">async def</span><span class="name">log_results</span>(<span class="param"><span class="bp">self</span></span>):

:::

<!-- docstring.jinja2 -->

Logs the results of the test suite to ValidMind.

This method will be called after the test suite has been run and all results have been collected. This method will log the results to ValidMind.

### run<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">run</span>(<span class="params"><span class="bp">self</span><span class="muted">,</span></span><span class="params"><span class="n">send</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">True</span><span class="muted">,</span></span><span class="params"><span class="n">fail_fast</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">False</span></span>):

:::

<!-- docstring.jinja2 -->

Runs the test suite, renders the summary and sends the results to ValidMind.

**Arguments**

- `send (bool, optional)`: Whether to send the results to ValidMind. Defaults to True.
- `fail_fast (bool, optional)`: Whether to stop running tests after the first failure. Defaults to False.

### summarize<span class="suffix"></span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span><span class="name">summarize</span>(<span class="param"><span class="bp">self</span><span class="muted">,</span></span><span class="param"><span class="n">show_link</span><span class="p">:</span><span class="nb">bool</span><span class="o">=</span><span class="kc">True</span></span>):

:::
