---
title: "[validmind](/reference/validmind.html).customer_churn"
sidebar: validmind-reference
---

## simple_preprocess_booleans[()]{.muted}

<!-- module.qmd.jinja2 - module level function alias -->

```python
def simple_preprocess_booleans(
    df,    columns):
```

Preprocess boolean columns.

**Parameters**

- **df** pandas.DataFrame: Dataframe to preprocess.
- **columns** list: List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## simple_preprocess_categoricals[()]{.muted}

<!-- module.qmd.jinja2 - module level function alias -->

```python
def simple_preprocess_categoricals(
    df,    columns):
```

Preprocess categorical columns.

**Parameters**

- **df** pandas.DataFrame: Dataframe to preprocess.
- **columns** list: List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## simple_preprocess_numericals[()]{.muted}

<!-- module.qmd.jinja2 - module level function alias -->

```python
def simple_preprocess_numericals(
    df,    columns):
```

Preprocess numerical columns.

**Parameters**

- **df** pandas.DataFrame: Dataframe to preprocess.
- **columns** list: List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## get_demo_test_config[()]{.muted}

<!-- function.qmd.jinja2 - function signature -->

```python
def get_demo_test_config(
    test_suite = None):
```

Returns input configuration for the default documentation template assigned to this demo model

The default documentation template uses the following inputs:

- raw_dataset
- train_dataset
- test_dataset
- model

We assign the following inputs depending on the input config expected by each test:

- When a test expects a "dataset" we use the raw_dataset
- When a tets expects "datasets" we use the train_dataset and test_dataset
- When a test expects a "model" we use the model
- When a test expects "model" and "dataset" we use the model and test_dataset
- The only exception is ClassifierPerformance since that runs twice: once with the train_dataset (in sample) and once with the test_dataset (out of sample)

## load_data[()]{.muted}

<!-- function.qmd.jinja2 - function signature -->

```python
def load_data(
    full_dataset = False):
```

## preprocess[()]{.muted}

<!-- function.qmd.jinja2 - function signature -->

```python
def preprocess(
    df):
```
