---
title: "[validmind](/reference/validmind.html).taiwan_credit"
sidebar: validmind-reference
toc-depth: 4
toc-expand: 4
# module.qmd.jinja2
---

## simple_preprocess_booleans<span class='muted'>()</span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span> <span class="name">simple_preprocess_booleans</span>(<span class="params"><span class="n">df</span><span class="muted">,</span></span><span class="params"><span class="n">columns</span></span>)

:::

<!-- docstring.jinja2 -->

Preprocess boolean columns.

**Parameters**

- **df** (pandas.DataFrame): Dataframe to preprocess.
- **columns** (list): List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## simple_preprocess_categoricals<span class='muted'>()</span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span> <span class="name">simple_preprocess_categoricals</span>(<span class="params"><span class="n">df</span><span class="muted">,</span></span><span class="params"><span class="n">columns</span></span>)

:::

<!-- docstring.jinja2 -->

Preprocess categorical columns.

**Parameters**

- **df** (pandas.DataFrame): Dataframe to preprocess.
- **columns** (list): List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

## simple_preprocess_numericals<span class='muted'>()</span>

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span> <span class="name">simple_preprocess_numericals</span>(<span class="params"><span class="n">df</span><span class="muted">,</span></span><span class="params"><span class="n">columns</span></span>)

:::

<!-- docstring.jinja2 -->

Preprocess numerical columns.

**Parameters**

- **df** (pandas.DataFrame): Dataframe to preprocess.
- **columns** (list): List of columns to preprocess.

**Returns**

- Preprocessed dataframe.

<!-- function.qmd.jinja2 -->

## load_data[()]{.muted}

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span> <span class="name">load_data</span>()

:::

<!-- function.qmd.jinja2 -->

## preprocess[()]{.muted}

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">def</span> <span class="name">preprocess</span>(<span class="param"><span class="n">df</span></span>)

:::
