---
title: "August 15, 2023"
date: 2023-08-15
aliases: 
  - /releases/2023-aug-15/highlights.html
---

This release includes a number of improvements for the developer experience when using the {{< var validmind.developer >}}, along with a visual redesign of the {{< var validmind.platform >}}.

## {{< fa bullhorn >}} Release highlights

### {{< var validmind.developer >}} (v1.17.0)

<!--- NR commented out the AGPL-3 license update, as these repositories are still set to private
- **Updated LICENSE to AGPL-3**. We added the GNU Affero General Public License version 3 to some of our GitHub repositories. 
--->

<!---John6797/sc 1980/metric test class dx improvements by @johnwalz97 in [#220](https://github.com/validmind/validmind-python/pull/220)--->
#### Improved developer experience for the Metric test class

We made a number of enhancements to the {{< var validmind.developer >}} to improve the experience for developers.

##### Better test organization

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns}
Added a `metadata` and `tags` attribute to the `test` base class for better categorization and filtering of tests.
:::

::: {.w-20-ns .tc}
[test()](/validmind/validmind/tests.qmd#test){.button target="_blank" .button-green}

:::

::::

##### Better filtering

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns}
Added a new `task_type` argument to the `list_tests()` function to allow simple filtering by `task_type` set in a test.

:::

::: {.w-20-ns}
[list_tests()](/validmind/validmind/tests.qmd#list_tests){.button target="_blank" .button-green}

:::

::::


##### Clearer naming

Renamed `required_context` to `required_inputs` across the whole {{< var vm.product >}} {{< var validmind.api >}}.

<!---feat: [sc-1862] User should have a way to discover required context and default config when running tests by @johnwalz97 in [#204](https://github.com/validmind/validmind-python/pull/204)--->
#### Enhancements to test configuration discovery

To make the discovery of required context and default configuration easier, this update includes a number of changes to how `required_context` and `default_parameters` are presented.

##### Preview template expansion

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
With `vm.preview_template()`, you can now view detailed, expandable information for each content block driven by a test. This includes the test's name, description, required context, and default parameters.

:::

::: {.w-30-ns .tc}
[preview_template()](/validmind/validmind.qmd#preview_template){.button target="_blank" .button-green}

:::

::::

##### Simplified test listing

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
The `vm.tests.list_tests()` function has been refined to show only the `ID`, `Name`, and `Description` for each test, making it more user-friendly.

:::

::: {.w-30-ns .tc}
[list_tests()](/validmind/validmind/tests.qmd#list_tests){.button target="_blank" .button-green}

:::

::::

##### Detailed test descriptions

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns}
You can now obtain complete test details, including `required_context` and `default_params`, using the `vm.tests.describe_test()` function.

:::

::: {.w-20-ns}
[describe_test()](/validmind/validmind/tests.qmd#describe_test){.button target="_blank" .button-green}

:::

::::

##### Retrieve test suite

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns}
The new function `vm.get_test_suite()` allows you to access a specific test suite instance via the high-level {{< var validmind.api >}}.

:::

::: {.w-20-ns}
[get_test_suite()](/validmind/validmind.qmd#get_test_suite){.button target="_blank" .button-green}

:::

::::

##### Access to default configuration

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
A new method, `get_default_config()`, is now part of both the TestPlan and TestSuite classes, letting you obtain a dictionary containing all the configuration parameters used by the tests.

:::

::: {.w-30-ns .tc}
[get_default_config()](/validmind/validmind/vm_models.qmd#TestSuite.get_default_config){.button target="_blank" .button-green}

:::

::::

<!-- NR Mar 5 2025 This no longer appears to be in our codebase — closest I can find is a get_context def in a notebook but it exists only in that context -->
<!-- ##### Easier required context

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns}
A complementary new method, `get_context_data()`, now returns a list of all the context variables needed for tests to run, making it easier for you to ensure that everything is set up correctly.
:::

::: {.w-20-ns}
[TestContext](/validmind/validmind/vm_models.qmd#TestContext){.button target="_blank" .button-green}

:::

:::: -->

### {{< var validmind.platform >}} (v1.4.10)

<!---Release 1.4.7 by @cachafla in [#444](https://github.com/validmind/frontend/pull/444)--->
#### Redesigned application and navigation bar layout

- The new application design offers a cleaner, more intuitive interface that enhances user experience. 
- The updated navigation bar layout specifically contributes to easier navigation, allowing users to find what they need with greater efficiency.

{{< include /releases/_how-to-upgrade.qmd >}}