<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or find your record by applying a filter or searching for it.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)]

::: {.panel-tabset}

#### Track resolution of validation issues

a. In the left sidebar that appears for your record, click **{{< fa triangle-exclamation >}} Validation Issues** to view a list of validation issues associated with that record.

a. Go through the open validation issues one-by-one:

    - **If the validation issue has been addressed** —

        - Add any final comments to assess how the issue was resolved.^[[Comment on artifacts](/guide/validation/update-artifacts.qmd#comment-on-artifacts)]
        - Under **Status**, select `Closed`.

    - **If part or all of the validation issue remains to be addressed** —

        - Assess if the issue identified by the validation issue prevents the record from being approved.
        - If a remediation plan is required, enter the details in the **Proposed Remediation Plan** section of the validation issue.

a. Track open issues until all validation issues are resolved or a remediation plan is in place for post-approval issues.

#### Track resolution of other artifact types

a. In the left sidebar that appears for your record, click **{{< fa border-all >}} Artifacts** to view lists of other artifact types associated with that record.

a.  Select an artifact type^[[Manage artifact types](/guide/validation/manage-artifact-types.qmd)] for a list of that artifact type:

    - Policy Exception
    - Limitation

a. Go through the open artifacts one-by-one:

    - **If the artifact has been addressed** —

        - Add any final comments to assess how the issue was resolved.^[[Comment on artifacts](/guide/validation/update-artifacts.qmd#comment-on-artifacts)]
        - Under **Status**, select `Closed`.

    - **If part or all of the artifact remains to be addressed** —

        - Assess if the issue identified by the artifact prevents the record from being approved.
        - Add comments indicating next required steps.

a. Track open artifacts until all artifacts are resolved or plans are in place for post-approval issues.

:::

::::

:::: {.content-hidden unless-format="revealjs"}
1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or find your record [by applying a filter or searching for it](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records){target="_blank"}.

#### Track resolution of validation issues

a. In the left sidebar that appears for your record, click **{{< fa triangle-exclamation >}} Validation Issues** to view a list of validation issues associated with that record.

a. Go through the open validation issues one-by-one:

    - **If the validation issue has been addressed** —

        - Add any final comments to assess how the issue was resolved.
        - Under **Status**, select `Closed`.

    - **If part or all of the validation issue remains to be addressed** —

        - Assess if the issue identified by the validation issue prevents the record from being approved.
        - If a remediation plan is required, enter the details in the **Proposed Remediation Plan** section of the validation issue.

a. Track open issues until all validation issues are resolved or a remediation plan is in place for post-approval issues.

#### Track resolution of other artifact types

a. In the left sidebar that appears for your record, click **{{< fa border-all >}} Artifacts** to view lists of other artifact types associated with that record.

a.  Select an [artifact type](/guide/validation/manage-artifact-types.qmd){target="_blank"} for a list of that artifact type:

    - Policy Exception
    - Limitation

a. Go through the open artifacts one-by-one:

    - **If the artifact has been addressed** —

        - Add any final comments to assess how the issue was resolved.
        - Under **Status**, select `Closed`.

    - **If part or all of the artifact remains to be addressed** —

        - Assess if the issue identified by the artifact prevents the record from being approved.
        - Add comments indicating next required steps.

a. Track open artifacts until all artifacts are resolved or plans are in place for post-approval issues.

::::



