---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Add and manage artifacts"
date: last-modified
aliases:
  - add-update-model-findings.html
  - add-manage-model-findings.html
  - /guide/model-validation/add-manage-artifacts.html
---

Add artifacts at the record or documentation section level, update your artifacts to include proposed remediation plans and supporting documentation, or delete artifacts that no longer need to be tracked.

{{< include /guide/inventory/_reference-field-values.qmd >}}

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The record you want to add or manage artifacts for is registered in the inventory.[^1]
- [x] Development documentation is completed or in progress for your record.[^2]
- [x] Artifact statuses have been set up for use with artifacts.[^3]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^4]

:::

## Add artifacts on documentation

{{< include _add-artifacts-on-documentation.qmd >}}

## Add artifacts on validation reports

When linking artifacts to validation reports,[^5] you can add artifacts as you assess a record's compliance.

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^6]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^7]

4. Click on a Validation type file.[^8]

   Expand any subsection of the validation report you have attached evidence for to autogenerate validation issues or manually link artifacts to your report:

::: {.panel-tabset}

### Autogenerate validation issues

{{< include _autogenerate-validation-issues.qmd >}}

### Manually add artifacts

{{< include _link-artifacts-to-reports.qmd >}}

:::



## Update artifacts

As artifacts get resolved or require other changes during the validation process, you can update them:

1. Locate the artifact you want to update.[^10]

2. Click on a field to make changes.

   You can also add comments to an artifact.

::: {.callout-important}
Most updates are applied immediately but you must click **Save** to make changes to the artifact title, description, proposed remediation plan, and attachments effective.
:::

### Track artifact resolution

{{< include _track-artifact-resolution.qmd >}}

<span id="manage-attachments"></span>

### Manage attachments on artifacts

After an artifact is created, you're able to add supporting documentation to it.

::: {.panel-tabset}

#### Add attachments to artifacts

::: {.callout}
Uploaded files must be less than 50 MB each in size.
:::

1. On the artifacts detail page, click on the **[attachments]{.smallcaps}** header.

{{< include /guide/inventory/_add-attachments.qmd >}}

#### Remove attachments from artifacts

1. On the artifacts detail page, click on the **[attachments]{.smallcaps}** header.

{{< include /guide/inventory/_remove-attachments.qmd >}}

:::

## Delete artifacts

::: {.callout-important title="Artifact deletion is permanent."}
- While artifact deletion will be logged under your {{< fa wifi >}} Activity,[^11] deleted artifacts cannot be retrieved.
- Deleting an artifact will also remove it from any validation reports[^12] it was previously attached to.

:::

If you logged an artifact in error or otherwise no longer need to track that artifact, you can delete it:

1. Locate the artifact you want to delete.[^13]

2. On the artifact's detail page, click **{{< fa trash-can>}} Delete {Artifact Type}**[^14] in the right sidebar.

3. Click **Yes, Delete {Artifact Type}** to confirm permanent deletion of that artifact.


<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^2]: [Working with documentation](/guide/documentation/working-with-documentation.qmd)

[^3]: [Manage artifact types](manage-artifact-types.qmd#manage-artifact-type-statuses)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Link artifacts to reports](/guide/validation/assess-compliance.qmd#link-artifacts-to-reports)

[^6]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^7]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^8]: [Preparing validation reports](/guide/validation/preparing-validation-reports.qmd#validation-overview)

[^9]: [Manage artifact types](manage-artifact-types.qmd)

[^10]: [View and filter artifacts](view-filter-artifacts.qmd)

[^11]: [View record activity](/guide/inventory/view-record-activity.qmd)

[^12]: [Link artifacts to reports](/guide/validation/assess-compliance.qmd#link-artifacts-to-reports)

[^13]: [View and filter artifacts](view-filter-artifacts.qmd)

[^14]: [Manage artifact types](manage-artifact-types.qmd)