---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Assess compliance"
date: last-modified
aliases:
  - /guide/assess-compliance.html
  - /guide/model-validation/assess-compliance.html
includes:
  compliance: true
---

Use the {{< var validmind.platform >}} to assess compliance of your records with guidelines based on analyzing evidence and artifacts.

Compliance assessments provide an unbiased starting point that enables more efficient discussions between validators and developers and involves the following steps:

1. [Link evidence to reports](#link-evidence-to-reports)
2. [Link artifacts to reports](#link-artifacts-to-reports)
3. [Assign compliance assessments](#assign-compliance-assessments)

::: {.callout title="Compliance assessments cannot be performed within static PDF documents."}
You can only assess compliance within PDFs converted to editable documents,[^1] validation reports generated by the {{< var validmind.developer >}}, or validation reports created in the {{< var validmind.platform >}}.
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The record you are validating is registered in the inventory.[^2]
- [x] Documentation has been submitted to you for validation.[^3]
- [x] Assessment options have been configured for the validation report template if required by your organization.[^4]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^5]

:::

## Link evidence to reports

::: {.callout title="Stuck on where to start?"}
Use {{< var vm.product >}}'s AI-assisted tools to automate mapping and assessing evidence.[^6]

:::

Include sections from other documents and logged test results as evidence to validation report, then assess the linked evidence for compliance:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^7]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^8]

4. Click on a Validation type file.[^9]

   Expand any subsection of the validation report you would like to work with.

5. Link evidence to reports in two steps:
   a. [Map evidence](#map-evidence)
   b. [Assess evidence](#assess-evidence)

### a. Map evidence
<span id="map-evidence"></span>

1. In any section of the report where linking evidence is available, click **Evidence** to expand the evidence panel.

2. Click **{{< fa link >}} Link Evidence** and select the [evidence type]{.smallcaps}:

   ::: {.panel-tabset}

   #### Developer Evidence

   Select evidence logged on Development, Monitoring, or custom document types attached to the record:

   i. Select **Developer Evidence** as the [evidence type]{.smallcaps}.
   ii. In the left sidebar, click on the document you want to include evidence from.
   iii. In the right panel, check off the content blocks you want to include as evidence:[^10]
      - Expand a section by clicking **{{< fa chevron-down >}}** to review any sub-sections.
      - If you are not sure if a block is relevant, click on a block to preview the contents.
      - To include all blocks in a section, check off the section header.
   iv. When you are ready to insert the evidence, click **Update Linked Evidence**.

   #### Validator Evidence

   Select evidence logged on the same Validation report:[^11]

   i. Select **Validator Evidence** as the [evidence type]{.smallcaps}.
   ii. Check off the test results you want to include as evidence.
      If you are not sure if a test result is relevant, click on a test result to preview the contents.
   iii. When you are ready to insert the evidence, click **Update Linked Evidence**.

   :::

3. Confirm that the newly linked evidence appears in the Evidence panel:

   ::: {.panel-tabset}

   #### Developer Evidence

   - Verify that the evidence shown under the **Developer Evidence** tab is accurate and is connected to the correct document section from the right document.
   - Evidence that needs your attention gets flagged with [{{< fa triangle-exclamation >}} Requires Attention]{.bubble .yellow-bg}. These sections get flagged automatically whenever a test result is above or below a certain threshold.

   #### Validator Evidence

   - Verify that the evidence shown under the **Validator Evidence** tab is accurate and is connected to the correct test result.
   - Evidence that needs your attention gets flagged with [{{< fa triangle-exclamation >}} Requires Attention]{.bubble .yellow-bg}. These sections get flagged automatically whenever a test result is above or below a certain threshold.

   :::

### b. Assess evidence
<span id="assess-evidence"></span>

Once you have linked evidence to a section of your report, assess the linked evidence for compliance:[^12]

1. In any section of the report where evidence has been linked, click **Evidence Assessment** to expand the evidence assessment panel.

2. Click **Add your assessment** to use the content editing toolbar[^13] to enter in your assessment notes.

3. (Optional) When you are finished editing your assessment notes, hover over the content block and click **{{< fa unlock >}} Lock Assessment** to prevent additional changes.

## Link artifacts to reports

After you have mapped and assessed available evidence, link artifacts to reports to provide additional context and support your assessment:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^15]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^16]

4. Click on a Validation type file.[^17]

   Expand any subsection of the validation report you have attached evidence for to autogenerate validation issues or manually link artifacts to your report:

::: {.panel-tabset}

### Autogenerate validation issues

{{< include _autogenerate-validation-issues.qmd >}}

### Manually link artifacts

{{< include _link-artifacts-to-reports.qmd >}}

:::

## Assign compliance assessments

{{< include _assign-compliance-assessments.qmd >}}


<!-- FOOTNOTES -->

[^1]: [Manage documents](/guide/templates/manage-documents.qmd#add-record-documents)

[^2]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^3]: [Submit for approval](/guide/documentation/submit-documents.qmd)

[^4]: [Configure assessment options](/guide/validation/configure-assessment-options.qmd)

[^5]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^6]: [Map and assess evidence](map-and-assess-evidence.qmd)

[^7]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^8]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^9]: [Preparing validation reports](/guide/validation/preparing-validation-reports.qmd#validation-overview)

[^10]: Only sections with content are available for selection as evidence — empty sections will have their checkboxes disabled and grayed out.

[^11]:  To link validator evidence to a report, you must first log tests on your report with the {{< var validmind.developer >}}: **[{{< var validmind.developer >}}](/developer/validmind-library.qmd)**

[^12]: [a. Map evidence](#map-evidence)

[^13]: [Work with content blocks](/guide/documentation/work-with-content-blocks.qmd#content-editing-toolbar)

[^15]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^16]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^17]: [Preparing validation reports](/guide/validation/preparing-validation-reports.qmd#validation-overview)

