---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Customize artifact overview page"
date: last-modified
aliases:
  - customize-finding-overview-page.html
  - /guide/model-validation/customize-artifact-overview-page.html
includes:
  artifacts: true
---

Configure what and how artifact fields appear when you pull up artifacts logged on records.

:::{.callout title="Changes are automatically saved to your account and do not affect other users."}
Customizations will apply to all artifacts of the same type in your inventory.

:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are records registered in the inventory.[^1]
- [x] There are artifacts logged on records.[^2]

:::

## Organize, show, or hide artifact fields

1. Open an artifact logged on any record.[^3]

2. On the artifact details page, click the **Artifact Fields** tab.

3. Click on **{{< fa pencil >}} Manage Fields**:

   ::: {.panel-tabset}

   #### {{< fa chart-column >}} Show {#} Columns

   Under Show {#} Columns, click {{< fa chevron-up >}} increase or {{< fa chevron-down >}} to decrease the number of columns shown.

   #### {{< fa chart-bar >}} Change Field Configuration

   a. Click **{{< fa chart-bar >}} Change Field Configuration** to configure the artifact fields[^4] that appear:

      - To hide fields or field groups from view: Hover over an artifact field, then click {{< fa eye >}}.
      - To show previously hidden fields or field groups: Hover over an artifact field, then click {{< fa eye-slash >}}.
      - To rearrange the order of fields and field groups: Click and hold, then drag-and-drop.
      - To pin a field to the **Overview** tab: Hover over the field, then click **{{< fa star >}}** to highlight the field.[^5]

      ::: {.callout}
      To narrow down your list of fields:

      - Click **{{< fa filter >}} Search by group or field name** to search for specific artifact fields.
      - To show only highlighted fields, click **Show only highlighted in overview {{< fa star >}}**.
      :::

   b. Click **Save Configuration** to apply your changes to all overview pages for that artifact type.

      Your layout will be saved locally to your browser's session.[^6]

   :::

### Highlight artifact fields

To pin artifact fields to the **Overview** tab for quick access:

1. Open an artifact logged on any record.[^7]

2. On the artifact details page, select either the **Overview** or **Artifact Fields** tab:

   ::: {.panel-tabset}

   #### **Overview** tab

   - If there are no highlighted fields: Click on **{{< fa star >}} Highlight fields**.
   - If there are already highlighted fields: Click on **{{< fa pencil >}} Manage Fields** and select **{{< fa chart-bar >}} Change Field Configuration**.

   #### **Artifact Fields** tab

   Click on **{{< fa pencil >}} Manage Fields** and select **{{< fa chart-bar >}} Change Field Configuration**.

   :::

3. Hover over an artifact field, then click **{{< fa star >}}** and select your Highlight Tone:

    - [**{{< fa star >}} Normal**]{.grey}
    - [**{{< fa star >}} Loud**]{.teal}
    - [**{{< fa star >}} Loudest**]{.pink}

    To unpin a highlighted field: Hover over the field, then click **{{< fa star >}}** and select **{{< fa star >}} Don't highlight**.

4. Confirm that the right artifact fields are pinned to the **Overview** tab with the correct highlight tone.

## Manage artifact field layouts

You can save custom artifact field layouts to reapply at any time for each artifact type:

1. Open an artifact logged on any record.[^8]

2. On the artifact details page, click the **Artifact Fields** tab.

3. Click on **{{< fa pencil >}} Manage Fields** and select **{{< fa chart-bar >}} Change Field Configuration** to organize, show, or hide artifact fields as desired.[^9]

4. Save a personal or publish a shared organization artifact field layout:

### Manage personal artifact field layouts

{{< include /guide/shared/manage-views/_personal-field-views.qmd >}}

### Manage organization artifact field layouts

{{< include /guide/shared/manage-views/_organization-field-views.qmd >}}


<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^2]: [Log artifacts](log-artifacts.qmd)

[^3]: [View and filter artifacts](view-filter-artifacts.qmd)

[^4]: [Manage artifact fields](/guide/validation/manage-artifact-fields.qmd#artifact-field-types)

[^5]: [Highlight artifact fields](#highlight-artifact-fields)

[^6]: To save a named layout for reuse or sharing, refer to: [Manage artifact field layouts](#manage-artifact-field-layouts)

[^7]: [View and filter artifacts](view-filter-artifacts.qmd)

[^8]: [View and filter artifacts](view-filter-artifacts.qmd)

[^9]: [Organize, show, or hide artifact fields](#organize-show-or-hide-artifact-fields)
