---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Log artifacts"
date: last-modified
aliases:
  - add-update-model-findings.html
  - add-manage-model-findings.html
  - /guide/model-validation/add-manage-artifacts.html
  - add-manage-artifacts.html
---

Log artifacts at the record or documentation section level during your validation process.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The record you want to add or manage artifacts for is registered in the inventory.[^1]
- [x] Development documentation is completed or in progress for your record.[^2]
- [x] Artifact statuses have been set up for use with artifacts.[^3]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^4]

:::

## Add artifacts on documentation

{{< include _add-artifacts-on-documentation.qmd >}}

## Add artifacts on validation reports

While assessing a record's compliance,[^5] you can add artifacts as you complete your validation report:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^6]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^7]

4. Click on a Validation type file.[^8]

   Expand any subsection of the validation report you have attached evidence for to autogenerate validation issues or manually link artifacts to your report:

::: {.panel-tabset}

### Autogenerate validation issues

{{< include _autogenerate-validation-issues.qmd >}}

### Manually add artifacts

{{< include _link-artifacts-to-reports.qmd >}}

:::


<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^2]: [Working with documentation](/guide/documentation/working-with-documentation.qmd)

[^3]: [Manage artifact types](manage-artifact-types.qmd#manage-artifact-type-statuses)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Assess compliance](/guide/validation/assess-compliance.qmd#link-artifacts-to-reports)

[^6]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^7]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^8]: [Preparing validation reports](/guide/validation/preparing-validation-reports.qmd#validation-overview)
