---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Map and assess evidence"
date: last-modified
---

Use {{< var vm.product >}}'s AI-assisted tools to streamline your validation workflow by automatically mapping relevant evidence to validation guidelines and drafting compliance assessments based on linked evidence.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The record you are validating is registered in the inventory.[^1]
- [x] Documentation has been submitted to you for validation.[^2]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions.[^3]

:::

{{< include _how-does-mapping-assessment-work.qmd >}}

::: {.callout}
## Currently, automatic mapping and assessment retrieves only Developer Evidence from the default Development document on the record, or Validator Evidence logged on the Validation report you are mapping evidence for.[^4]

To manually add and assess evidence from other document types, refer to [Assess compliance](/guide/validation/assess-compliance.qmd).

:::

{{< include _map-evidence-to-guidelines.qmd >}}

{{< include _assess-evidence-for-compliance.qmd >}}

<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^2]: [Submit for approval](/guide/documentation/submit-documents.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Manage document types](/guide/templates/manage-document-types.qmd)
