---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "View and filter artifacts"
date: last-modified
aliases: 
  - view-filter-model-findings.qmd
  - /guide/model-validation/view-filter-artifacts.html
includes:
   artifacts: true
---

Access a complete list of filterable artifacts logged across all your records in the {{< var validmind.platform >}}, or look at only artifacts linked to a specific record.

::: {.callout}
Within the {{< var validmind.platform >}}, artifacts are split into:[^1]

- Validation issues
- Other artifact types
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are records registered in the inventory.[^2]
- [x] There are artifacts logged on any record.[^3]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^4]

:::

## View artifacts

You can view artifacts for all records at once, or only view artifacts linked to a specific record.

### View all artifacts

{{< include _view-all-artifacts.qmd >}}

### View record-specific artifacts

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^5]

3. View validation issues or other artifact types for that record.

::: {.panel-tabset}

#### View record-specific validation issues

a. In the left sidebar that appears for your record, click **{{< fa triangle-exclamation >}} Validation Issues**.

b. Click on any validation issue for more information, including the proposed remediation plan and any supporting attachments.[^6]

   Attachments are listed with the following information:

   - Filename
   - Icon representing file type
   - Date uploaded
   - The user who uploaded the file
   - File size
   - Notes

   Click on the attachment to view or download the file.

#### View record-specific artifacts of other types

a. In the left sidebar that appears for your record, click **{{< fa border-all >}} Artifacts**.

b. Select an artifact type[^7] to view from the tabs:

   - Policy Exception
   - Limitation

   In the page that opens is a list of all artifacts for that type.

c. Click on any artifact for more information.

:::


## Filter and sort artifacts

- By default, artifacts for all records are listed by creation date in descending order.
- To sort artifacts by a column in ascending ({{< fa angle-down >}}) or descending ({{< fa angle-up >}}) order, click on the column header.

To narrow down artifacts, you can apply some filters:

::: {.panel-tabset}

### Filter all validation issues

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Validation Issues** to view a list of validation issues across all records.

2. Click **{{< fa filter >}} Filter**.

3. On the Select Your Filters dialog that opens, enter your filtering criteria.

<!-- NR This callout requires less negative top margin than the other one ... why?! -->
::: {.callout-button .pl4 .nt3}
::: {.callout-important collapse="true" appearance="minimal"}
### How do I create effective filters?

{{< include /guide/shared/_work-with-filters.qmd >}}
:::
:::

4. Click **Apply Filters**.

<!-- NR Common UI behavior should not be a callout unless there is an issue ... -->
Changes are automatically saved to your account and do not affect other users.

### Filter all other artifacts

1. In the left sidebar, click **{{< fa border-all >}} Artifacts** to view lists of other artifact types across all records.

2. Select an artifact type[^8] to view from the tabs:

   - Policy Exception
   - Limitation

3. Click **{{< fa filter >}} Filter**.

4. On the Select Your Filters dialog that opens, enter your filtering criteria.

::: {.callout-button .pl4 .nt4}
::: {.callout collapse="true" appearance="minimal"}
### How do I create effective filters?

{{< include /guide/shared/_work-with-filters.qmd >}}
:::
:::

5. Click **Apply Filters**.

:::

<!-- FOOTNOTES -->

[^1]: [Manage artifact types](/guide/validation/manage-artifact-types.qmd)

[^2]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^3]: [Log artifacts](log-artifacts.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^6]: [Add and manage artifacts](update-artifacts.qmd#manage-attachments)

[^7]: [Manage artifact types](/guide/validation/manage-artifact-types.qmd)

[^8]: [Manage artifact types](/guide/validation/manage-artifact-types.qmd)
