---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Working with artifacts"
date: last-modified
listing:
  - id: view-artifacts
    type: grid
    max-description-length: 250
    sort: false
    grid-columns: 2
    fields: [title, description]
    contents:
      - view-filter-artifacts.qmd
      - customize-artifact-layouts.qmd
  - id: log-artifacts
    type: grid
    max-description-length: 250
    sort: false
    grid-columns: 3
    fields: [title, description]
    contents:
      - log-artifacts.qmd
      - manage-artifacts.qmd
      - customize-artifact-overview-page.qmd
aliases:
  - work-with-model-findings.html
  - /guide/work-with-model-findings.html
  - working-with-model-findings.html
  - /guide/model-validation/working-with-artifacts.html
---

Use {{< var validmind.platform >}} to log thorough artifacts as you validate your records. From status and severity to proposed remediation plans and due dates, {{< var vm.product >}} allows you to oversee the minutiae to ensure organizational compliance.

## Key concepts

Artifacts (findings) are detailed observations identified during the validation process, highlighting any major or minor issues, deficiencies, limitations, stability and robustness concerns, or needed adjustments.

- These artifacts are critical for understanding the risk exposure and compliance status of records within an organization.
- To make them easier to track, artifacts are typically categorized by risk area, business unit, record status, and individual record, enabling targeted resolution and informed decision-making to mitigate identified risks and ensure record reliability and accuracy.

Good artifacts help explain how well the records such as models perform in terms of predictive accuracy, generalization to new data, and the importance of variables or features used in the modeling process. 

For example, artifacts logged on models typically include:

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}

performance metrics
: Quantitative measures that evaluate how well the model predicts outcomes, such as accuracy, precision, and recall.

feature importance
: The ranking of input variables based on their contribution to the predictive power of the model.

model interpretability, interpretability
: Insights into how the model makes its predictions, which can help in understanding the decision-making process.

:::

::: {.w-40-ns}


validation results
: Artifacts from testing the model on unseen data, for example cross-validation results.

residual analysis
: Investigating the errors or discrepancies between predicted and actual outcomes.


:::

::::



## Manage artifacts

:::{#view-artifacts}
:::

:::{#log-artifacts}
:::


## What's next

- [Preparing validation reports](preparing-validation-reports.qmd)