---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Link external records"
date: last-modified
aliases:
  - /guide/integrations/linking-external-models.html
  - /guide/integrations/link-external-models.html
---

Link records (models) tracked in {{< var vm.product >}} to external systems to keep your inventories synchronized. 

You can link, refresh, edit, and remove these connections as needed.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The record you want to link external records for is registered in the inventory.[^1]
- [x] A connection is configured for the external system you want to link to.[^2]
- [x] You are assigned a role with sufficient permissions to manage record links, such as [{{< fa hand >}} Customer Admin]{.bubble}.[^3]

:::

## Link records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^4]

3. Scroll down until you locate the available connections for integrations in the right sidebar.

4. Hover over the connection.

5. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa link >}} Link Model**.

6. In the modal that opens, pick the external record from the [select model]{.smallcaps} dropdown.

7. Optional: Click **Test Connection** to ensure the connection is working as expected.

   If the test is successful, the message **{{< fa check-circle >}} Connection Test Successful** displays.

8. Click **Link Model**.

After linking, the message **Pending initial sync** displays. This means that the record is linked to the external system, but data hasn't been synchronized yet. If necessary, you can refresh the record data.[^5]

## Refresh record data

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^4]

3. Scroll down until you locate the connection you want to edit in the right sidebar. For example, **Amazon SageMaker**.

4. Hover over the connection.

5. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa sync >}} Refresh**.

## Edit record links

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^4]

3. Scroll down until you locate the connection you want to edit in the right sidebar. For example, **Amazon SageMaker**.

4. Hover over the connection.

5. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa link >}} Edit Link**.

6. In the modal that opens, make your changes. For example, select a different record from the **[select model]{.smallcaps}** dropdown.

7. Click **Update Link** to save your changes.

## Remove record links

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^4]

3. Scroll down until you locate the integration box (for example, **MLflow** or **Amazon SageMaker**) in the right sidebar.

4. Hover over the connection.

5. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa unlink >}} Remove Link**.

6. Click **Yes, Unlink Integration** to confirm removal of the link.

<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^2]: [Configure connections](configure-connections.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^5]: [Refresh record data](#refresh-record-data)
