---
title: "May 30, 2023"
filters:
  - tachyons
---

## Release highlights

This release includes enhanced plots with the Plotly package within the {{< var validmind.developer >}}, as well as support for export of model documentation to Word documents from the {{< var validmind.platform >}}.

### {{< var validmind.developer >}} (v1.13.9)

#### Plots & visual outputs enhanced with Plotly

Plots and visual outputs have been enhanced with the Plotly package. Users can now view how values change when hovering over the following plots:

- Correlations matrix
- Population Stability Index
- Confusion matrices
- ROC curve
- PR curve

#### Support for global test config definitions

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
- Added support for global test config definitions. 
- This allows you to share configuration and parameters across different tests.

:::

::: {.w-30-ns}

<form method="get" action="/developer/model-testing/test-descriptions.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Test descriptions
</button>
</form>

:::

::::

### {{< var validmind.platform >}} (v1.0.19)

#### Export model documentation

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
- You can now export model documentation to Word documents from the {{< var vm.platform >}}. 
- This feature enables you make use of model documentation or validation report files outside of the {{< var validmind.platform >}}. 

:::

::: {.w-30-ns}

<form method="get" action="/guide/model-documentation/export-documentation.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Export documentation
</button>
</form>

:::

::::

#### New time-series forecasting demo model

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
We added a new demo model that allows you to test the {{< var validmind.developer >}} with a time-series forecasting model. 

:::

::: {.w-30-ns}

<form method="get" action="/developer/samples-jupyter-notebooks.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Code samples
</button>
</form>

:::

::::


## Bugfixes

- Fixed the display alignment in certain pages of the UI.
- Fixed display issues related to Helvetica Neue font not available for Windows users.
- Fixed an issue preventing users to drag & drop image files directly in the online editor.
- Adjusted filters for the **Model Inventory** search box.

{{< include /releases/_how-to-upgrade.qmd >}}