---
title: "July 24, 2023"
filters:
  - tachyons
---

## Release highlights

<!---This release introduces several significant enhancements to the {{< var validmind.developer >}}, expanding support for additional use cases and enhancing the developer experience.---> This release improves the developer experience within the {{< var validmind.developer >}} and introduces an updated notebook to demonstrate support for NLP models, now using CatBoost for greater performance. 

Moreover, we've upgraded our {{< var vm.platform >}} with several major new features, including an all-new text editor, the capability to insert new content blocks into model documentation, template swapping for keeping your model documentation  current, and much more.

### {{< var validmind.developer >}} (v1.16.0)

<!--- NR commented out as per Andres' request --->
<!---
- **Support for Credit Risk Scorecard and Probability of Default use cases**. We've enhanced our {{< var vm.developer >}} to be more versatile than ever, so you can now document and validate more model use cases. To demonstrate how you can use ValidMind with these new use cases, we're providing two new interactive Jupyter Notebooks for a hands-on experience. Try them:
    
    - [Credit Risk Scorecard Demo](/notebooks/probability_of_default/credit_risk_scorecard_demo.ipynb)
    - [Probability of Default Model](/notebooks/probability_of_default/probability_of_default_validmind.ipynb)
--->

#### Updated notebook for NLP use case

Now with enhanced performance by using CatBoost compared to the original PyTorch-based notebook, this updated notebook showcases natural language processing (NLP) data analysis and text classification using the {{< var validmind.developer >}} with emphasis on the in-depth analysis and preprocessing of COVID-19 tweets. <!---[Try it ...](/notebooks/code_samples/nlp_and_llm/nlp_sentiment_analysis_catboost_demo.ipynb)--->

#### Improved developer experience when you encounter error conditions

- Unhandled errors now return an error code with a more descriptive message that can help you with looking them up in the troubleshooting section of our documentation. 
- We also improved error handling when tests fail to run and the test results summary widget now display error information for each test that fails to run. 

### {{< var validmind.platform >}} (v1.4.1)

#### New full-featured text editor

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
When collaborating on model documentation in the {{< var vm.platform >}} with others, you now have a new text editor at your disposal. 

:::

::: {.w-30-ns}

<form method="get" action="/guide/model-documentation/collaborate-with-others.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Collaborate with others
</button>
</form>

:::

::::

- The interface should be intuitive and familiar, allowing you to manage model documentation and validation reports with greater ease. 
- In addition to the new editing features, you can use the editor to participate in comment threads, track changes, see the revision history, enter math formulas, and more.


<!--- TO DO screen shot --->

#### Add new content blocks to model documentation

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
You can now add new sections to existing model documentation, providing additional space for text and test results — simply by hovering over the dashed line between sections. 

:::

::: {.w-30-ns}

<form method="get" action="/guide/model-documentation/work-with-content-blocks.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Work with content blocks
</button>
</form>

:::

::::

Supported content block types:

- **Simple text block:** Can be added anywhere on model documentation pages and edited to include additional documentation in text format.
- **Test-driven block:** Can be added to display one of the supported test results collected by the {{< var vm.developer >}}.

<!--- TO DO Need Swap template docs --->

#### Swap templates for model documentation

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns}
We've now enhanced the flexibility of documenting models by allowing you to swap documentation templates.

:::

::: {.w-40-ns}

<form method="get" action="/guide/model-documentation/swap-documentation-templates.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Swap documentation templates
</button>
</form>

:::

::::

- Seamlessly update existing model documentation by either switching to an entirely different template or by simply upgrading to a more recent version of the template currently in use. 
- The ability to swap templates ensures that your model documentation remains up-to-date and aligns with your latest preferred template without the need to start from scratch.

#### {{< var validmind.platform >}} enhancements

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns}
<!-- This rename required a docs update, included in this PR -->
- **Renamed Client Integration page to Getting Started**. To better reflect when you use the credentials to generate model documentation with the {{< var validmind.developer >}}, we have renamed the **Client Integration** page to **Getting Started**. 
- **Improved activity widget.** We enhanced the user interface with new tabs, enabling you to filter events based on activity type.
- **Improved Findings section and Findings Details page.** We made UI enhancements for both model findings and the findings details sections for a better look and feel.
- **Refined Models and Projects lists.**  We refined the user interface, featuring more intuitive default sorting and more user-friendly filtering.

:::

::: {.w-40-ns}

<form method="get" action="/developer/model-documentation/install-and-initialize-client-library.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Install and initialize the client library
</button>
</form>

<form method="get" action="/guide/model-inventory/view-model-activity.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">View model activity
</button>
</form>

<form method="get" action="/guide/model-validation/working-with-model-findings.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Working with model findings
</button>
</form>

<form method="get" action="/guide/model-inventory/working-with-model-inventory.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Working with the model inventory
</button>
</form>

:::

::::

## Documentation

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns}
To make it easier to try out our Jupyter Notebooks, we now provide a download button for all notebooks used in our documentation:

<form method="get" action="/notebooks.zip">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Download Notebooks</button>
</form>

:::

::: {.w-40-ns}
**This download includes:**

- QuickStart notebooks
- Use case notebooks
- Testing notebooks

:::

::::

{{< include /releases/_how-to-upgrade.qmd >}}