---
title: "June 22, 2023"
filters:
  - tachyons
---

## Release highlights

This release includes a number of major enhancements to the {{< var validmind.developer >}} that will make it easier for users to edit templates and add custom tests that can be reused across templates. 

In addition, this release also includes a new notebook to illustrate support for NLP models and PyTorch, as well as the ability to edit templates directly in the {{< var vm.platform >}}. 

### {{< var validmind.developer >}} (v1.15.4)

#### Implement your own custom tests

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
With support for custom tests, you can now go beyond the default set of documentation and testing components provided by ValidMind, and use our {{< var vm.developer >}} to document any type of model or use case. 

:::

::: {.w-30-ns}

<form method="get" action="/notebooks/code_samples/custom_tests/implement_custom_tests.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Implement custom tests
</button>
</form>

:::

::::


#### Integrate external test providers

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns}
With test providers, you can now integrate external test libraries to expand the set of tests available through the {{< var validmind.developer >}}, or create your own test libraries. 

:::

::: {.w-40-ns}

<form method="get" action="/notebooks/code_samples/custom_tests/integrate_external_test_providers.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Integrate external test providers
</button>
</form>

:::

::::

- This enables registering custom tests under a namespace to make them available globally. 
- We provide a couple of demo scenarios with such test providers and show how you can register them with ValidMind so that they can run a template utilizing your tests. 

#### Simplified documentation and testing using templates

:::: {.flex .flex-wrap .justify-around}

::: {.w-70-ns}
Templates now function as dynamic test suites, allowing you to identify all the documentation components and test results mapped to a specific template. This makes it easier to fill a pre-configured template (including boilerplates and spaces designated for documentation and test results) with a single command, instead of running multiple test suites. 

:::

::: {.w-30-ns}

<form method="get" action="/developer/get-started-validmind-library.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Get started with the {{< var validmind.developer >}}
</button>
</form>

:::

::::

<!--- NR Replaced original Pytorch NLP link with CatBoost link, as the original link  has issues in Quarto --->
#### New notebook to illustrate natural language processing (NLP) data analysis and text classification use case

Learn how to use the {{< var validmind.developer >}} to document and test an NLP data analysis and text classification model. The emphasis of this notebook is on documenting and testing the in-depth analysis and preprocessing of the text data, in this case, COVID-19 related tweets. <!---[Learn more ...](/notebooks/code_samples/nlp_and_llm/nlp_sentiment_analysis_catboost_demo.ipynb)--->

### {{< var validmind.platform >}}

#### Editable templates

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns}
You can now edit the documentation templates that get used for model documentation or for validation reports.

:::

::: {.w-40-ns}

<form method="get" action="/guide/model-documentation/customize-documentation-templates.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Customize documentation templates
</button>
</form>

:::

::::

- This feature is relevant for administrators who need to configure templates for specific use cases, or where the existing templates supplied by ValidMind need to be customized.
- Editing allows to configure sections, sub-sections, and content blocks inside a template.

#### Improved search

We improved the search feature in the {{< var vm.platform >}} to make search results more compact.

## Enhancements

:::: {.flex .flex-wrap .justify-around}

::: {.w-80-ns}
We revised our QuickStart guide to be more modular and to highlight that our suggested starting point with the {{< var validmind.developer >}} is now JupyterHub.

:::

::: {.w-20-ns}

<form method="get" action="/get-started/quickstart.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">QuickStart
</button>
</form>

:::

::::


{{< include /releases/_how-to-upgrade.qmd >}}
