---
title: "ValidMind style guide"
date: last-modified
listing:
  - id: style-guide
    type: grid
    max-description-length: 250
    sort: false
    grid-columns: 2
    fields: [title, description]
    contents:
      - voice-and-tone.qmd
      - conventions.qmd
---

A style guide helps create distinct yet unified communication across all areas of a product experience, from in-app interactions to technical documentation and blog posts. 

## Goals
At ValidMind, we value **transparency and accessibility** — we aim to speak simply and effectively. We also believe in **creating community**, by presenting information in a manner that encourages collaboration and feedback from users old and new. 

Our processes reflect a **holistic journey** — accommodating the needs of users begins in the design phase, documentation supplements instead of replaces intuitive or engaging and guided user experiences, and publications should help our audience understand value and maximize their potential with ValidMind. 

The following guidelines are meant to reflect these above principles, and ensure that all of our communications adhere to our vision:

:::{#style-guide}
:::

## Other resources
Google offers [Technical Writing Courses for Engineers](https://developers.google.com/tech-writing) for free. Go forth and write! 

### Additional style guides
This style guide is meant to help get you familiar with speaking in the ValidMind voice, but not be an exhaustive list of conventions or rules you should be following when writing. 

If it’s specified in our guide, follow those instructions — otherwise, you can check out the guides below for more inspiration:

- [Google Style Guides](https://google.github.io/styleguide/)
- [Microsoft Writing Style Guide](https://learn.microsoft.com/en-us/style-guide/welcome/)
- [Apple Style Guide](https://support.apple.com/en-au/guide/applestyleguide/welcome/web)

