---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "{{< var validmind.developer >}} and {{< var validmind.platform >}}"
date: last-modified
listing:
  - id: library-and-platform
    type: grid
    max-description-length: 250
    grid-columns: 2
    sort: false
    fields: [title, description]
    contents:
    - overview-model-documentation.qmd
    - overview-llm-features.qmd
    - deployment-options.qmd
    - system-access-requirements.qmd
---

{{< var validmind.product >}} provides two main product components, the {{< var validmind.developer >}} and the {{< var validmind.platform >}}.

::: {.panel-tabset}

#### 1. {{< var validmind.developer >}}

The *{{< var validmind.developer >}}* is a Python library of tools and methods designed to automate generating model documentation and running validation tests. The {{< var vm.developer >}} is designed to be platform agnostic and integrates with your existing development environment. 

   For Python developers, a single installation command provides access to all the functions:
    
   ```python
   %pip install validmind
   ```

#### 2. {{< var validmind.platform >}}

The *{{< var validmind.platform >}}* is an easy-to-use web-based interface that enables you to track the model lifecycle:

- Customize workflows to adhere to and oversee your governance processes.
- Review and edit the documentation and test metrics generated by the {{< var vm.developer >}}.
- Collaborate with and capture feedback from model developers and model validators.
- Generate validation reports and approvals.

:::

::: {.callout-important collapse="true" appearance="minimal"}
## Key {{< var vm.product >}} concepts

{{< include /about/glossary/key_concepts/_key-concepts.qmd >}}
:::

## Product highlights

:::{#library-and-platform}
:::

<!-- ## How do I get started? 

On the {{< var validmind.platform >}}, everything starts with the inventory — you first register a new model or AI system and then manage the lifecycle through the different activities that are part of your existing governance processes. -->

<!-- ### Approval workflow

A typical high-level approval workflow looks like this: -->

<!-- 
```{mermaid}
graph LR
    A[Registration] --> B[Initial<br>validation]
    B --> C[Validation<br>approval]
    C --> D[In production]
    D --> E[Periodic review<br>and revalidation]
    E --> B
``` 
-->

<!-- Registration[^1]
: Select a documentation template when registering a new inventory model to start your documentation. You then use the inventory to manage the metadata associated with the model or AI system, including all compliance and regulatory attributes. 

Initial validation
: Triggers a new workflow[^2] to yield a model that will be ready for production deployment after its documentation and validation reports have been approved. 

Validation approval
: Perform validation to ensure that the model or AI system meets the needs for which it was designed. You can also connect to third-party systems to send events when a model has been approved for production.

In production
: Use the model or AI system in production while ensuring its ongoing reliability, accuracy, and compliance with regulations by monitoring performance.

Periodic review and revalidation
: As part of regular performance monitoring or change management, you follow a process similar to that seen in the **Initial validation** step. -->

<!-- FOOTNOTES -->

<!-- [^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with workflows](/guide/workflows/working-with-workflows.qmd) -->
