---
title: "Large language model features"
date: last-modified
filters:
  - tachyons
  - preview
---

<!-- Title alternatives: 
- AI-driven features and capabilities
- Advanced AI and LLM features
- LLM-powered tools and features
-->
{{< var vm.product >}} offers several specialized features that use large language models (LLMs) to streamline model risk management and ensure regulatory compliance. Here's how we approach these features and what you need to know. 

## Our philosophy

At ValidMind, our approach to AI features, particularly in testing and risk management, reflects a philosophy of _drinking our own champagne_ or using our own products. This means that, while we create risk management tools for our users, we also rigorously apply these tools and practices within our own product development.

Our testing methodologies and philosophy around testing are readily available,[^1] and we openly share information about our approach. Specific test results are also available on request, allowing us to demonstrate the same standards of robustness and compliance that we promote for our users.

## Our features

{{< var vm.product >}} enhances model documentation, testing, and compliance workflows, providing your team with tools for effective model governance.

::: {.attn}
:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns .pr4}
### Test interpretation

Interprets results from tests run within {{< var vm.product >}}. This feature generates a description of the tests, highlights key insights from the outcomes, and provides a summary with actionable takeaways.

**Why it matters** — Test interpretation makes it easier for developers and validators to understand the implications of each test.


### Risk assessment

Using data from test results, generates a tailored risk assessment for each section of model documentation. This feature aids in identifying potential risks based on the model’s performance and results.

**Why it matters** — Risk assessment provides a foundation for better-informed decision-making.
:::

::: {.w-50-ns .pl4}
### Qualitative checks

Leverages metadata from the model inventory, test outcomes, and additional data provided to create qualitative sections within model documentation. 

**Why it matters** — Qualitative checks ensure that essential contextual information is accurately documented and aligned with the model's purpose and scope.

### Document checker

Reviews model development documentation to ensure it aligns with relevant regulatory requirements. 

**Why it matters** — Document checks help teams maintain compliance with specific regulations by flagging areas that may need revision.

<!-- NR Nov 2024 Uncomment when available -->
<!-- ### Section checker

Assesses each part of the model documentation for adherence to internal guidelines and policies. This tool supports consistent documentation standards across the organization, promoting uniformity in compliance practices. -->
:::

::::
:::


:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns .pr4}
### A commitment to transparency

We believe in transparency across all our practices — not just because it’s essential to earn your trust, but because it’s the right thing to do. 

Understanding our policies shouldn’t feel like deciphering code, so we’ve made our legal texts as clear and accessible as possible. These documents cover the details of our practices, including data handling, privacy, responsible AI use, and regulatory compliance. 

:::

::: {.w-50-ns .pt4}

:::{.preview source="https://validmind.com/about/legal" height="230"}
:::

:::

::::

We invite you to explore our policies, including our AI usage policy,[^2] and see how we put transparency into action every step of the way. 

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns .pr4}
### Find out more

Find out which ValidMind deployment is right for you by getting in touch.

:::

::: {.w-50-ns .pt4}

:::{.preview source="https://validmind.com/contact/" height="230"}
:::

:::

::::

<!-- FOOTNOTES -->

[^1]: [Run tests and test suites](//developer/model-testing/testing-overview.qmd)

[^2]: ValidMind: [AI Usage Policy](https://validmind.com/about/legal/ai-usage-policy/)