<!-- VISIBLE IN USER GUIDES ONlY -->

:::: {.content-visible unless-format="revealjs"}
::: {.panel-tabset}

### Add record types

a. Click **{{< fa plus >}} Add Inventory Record Type**.

b. Enter a **[name]{.smallcaps}** for your record type.

c. Include optional information for your record type:

    - Enter a **[description]{.smallcaps}** to indicate the purpose of the record type displayed on the list of record types.
    - Enter a URL-safe **[slug]{.smallcaps}** where a list of records of this type will be accessible in your {{< var validmind.platform >}} URL under the inventory path.[^2]
    - Select the **[document types]{.smallcaps}** available to be created for this record type.[^3]
    - Select the **[artifact types]{.smallcaps}** available to be logged on this record type.[^4]
    - Select the **[stakeholder types]{.smallcaps}** that should be displayed on this record type.[^5]
    - Select the **[default stakeholder types]{.smallcaps}** that should be displayed by default on this record type.

d. When you are satisfied with the setup of your record type, click **Create**.

### Edit record types

To edit an existing record type:

a. Click on the record type you want to edit.

a. Make your desired changes to your record type, then click **Update**.

:::

::::

<!-- VISIBLE IN TRAINING SLIDES ONLY -->

:::: {.content-hidden unless-format="revealjs"}
1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or [find your record by applying a filter or searching for it](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records){target="_blank"}.

1. In the expanded sidebar that appears for your record, click **{{< fa wifi >}} Activity**.

::::