---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Archive and delete records"
date: last-modified
aliases:
  - /guide/model-inventory/archive-delete-models.html
  - /guide/inventory/archive-delete-models.html
---

Archive records within the {{< var vm.product >}} inventory when they are decommissioned or delete records that you no need to track, keeping your inventory accurate and up to date with your organization's current resources.

::: {.callout}
## By default, only the Customer Admin role[^1] can access archived records.

- Archived records are read-only, and do not contribute to sub-data, statistics or reports.
- Artifacts from archived records will not be displayed, and reports will not include data from archived records.
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are records registered in the inventory.[^2]
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

:::

## Change record stages

::: {.callout}
##  Instead of manually modifying your records' stages,[^4] we recommend manipulating stages via customized workflows.[^5]

Workflows increase oversight over the stage transitions of records by providing a more extensive audit history,[^6] and also allow you to wrap other organization policies into your transitions — such as inclusion of specific stakeholder approval.
:::

The inventory within the {{< var validmind.platform >}} should reflect the state of governed records within your organization:

- If you decommission a record, you can archive it in the inventory.
- Conversely, if there is renewed business need for an archived record, you can activate it again.

To change a record's stage:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Under the [record type]{.smallcaps} drop-down, select the type of record you want change the stage for.[^7]

3. Select a record or find your record by applying a filter or searching for it.[^8]

4. Click on the [{record} stage]{.smallcaps} section where `{record}` is the type of record.

5. You can then select the appropriate stage for the record.

6. Click **Save** to transition the record into your selected stage.

::: {.panel-tabset}

#### Archive records

a. Select **Archived** from the [{record} stage]{.smallcaps} drop-down menu where `{record}` is the type of record.

b. Click **Save** to proceed with archival.

c. Click **Yes, Archive Record** to confirm archival of that record.

Archived records can be reactivated to make them available for use again in the inventory.

#### Activate records

a. Select any stage other than Archived from the [{record} stage]{.smallcaps} drop-down menu where `{record}` is the type of record.

b. Click **Save** to proceed with activation.

:::

## Delete records

If a record was created in error, or you otherwise no longer require a record to be tracked in the inventory, you can delete it.

::: {.callout-important}
## Record deletion is also permanent and cannot be undone.
:::

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Under the [record type]{.smallcaps} drop-down, select the type of record you want delete.[^9]

3. Select a record or find your record by applying a filter or searching for it.[^10]

4. Under the [{record} stage]{.smallcaps} section where `{record}` is the type of record, select **Deleted**.

5. Click **Yes, Delete Record** to confirm permanent deletion of that record.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Register records in the inventory](register-records-in-inventory.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Manage model stages](/guide/workflows/manage-model-stages.qmd)

[^5]: [Setting up workflows](/guide/workflows/setting-up-workflows.qmd)

[^6]: [Working with workflows](/guide/workflows/working-with-workflows.qmd)

[^7]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^8]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^9]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^10]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)
