---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Customize record overview page"
date: last-modified
aliases:
  - /guide/model-inventory/customize-model-overview-page.html
includes:
  inventory: true
---

Configure what and how inventory fields appear when you open a record’s details in the inventory.

:::{.callout title="Changes are automatically saved to your account and do not affect other users."}
Customizations will apply to all records of the same type in your inventory.

:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are records registered in the inventory.[^1]

:::

## Organize, show, or hide record fields

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Under the [record type]{.smallcaps} drop-down, select the type of record you want to customize the overview page for.[^2]

3. Select a record or find your record by applying a filter or searching for it.[^3]

4. On the record details page, click the **Inventory Fields** tab.

5. Click on **{{< fa pencil >}} Manage Fields**:

   ::: {.panel-tabset}

   #### {{< fa chart-column >}} Show {#} Columns

   Under Show {#} Columns, click {{< fa chevron-up >}} increase or {{< fa chevron-down >}} to decrease the number of columns shown.

   #### {{< fa chart-bar >}} Change Field Configuration

   a. Click **{{< fa chart-bar >}} Change Field Configuration** to configure the inventory fields[^4] that appear:

      - To hide fields or field groups from view: Hover over an inventory field, then click {{< fa eye >}}.
      - To show previously hidden fields or field groups: Hover over an inventory field, then click {{< fa eye-slash >}}.
      - To rearrange the order of fields and field groups: Click and hold, then drag-and-drop.
      - To pin a field to the Overview tab: Hover over the field, then click **{{< fa star >}}** to highlight the field.[^5]

      ::: {.callout}
      To narrow down your list of fields:

      - Click **{{< fa filter >}} Search by group or field name** to search for specific inventory fields.
      - To show only highlighted fields, click **Show only highlighted in overview {{< fa star >}}**.
      :::

   b. Click **Apply Configuration** to apply your changes to all overview pages for that record type.

      Your layout will be saved locally to your browser's session.[^6]

   :::

### Highlight inventory record fields

To pin inventory record fields to the **Overview** tab for quick access:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Under the [record type]{.smallcaps} drop-down, select the type of record you want to edit fields for.[^7]

3. Select a record or find your record by applying a filter or searching for it.[^8]

4. On the record details page, select either the **Overview** or **Inventory Fields** tab:

   ::: {.panel-tabset}

   #### **Overview** tab

   - If there are no highlighted fields: Click on **{{< fa star >}} Highlight fields**.
   - If there are already highlighted fields: Click on **{{< fa pencil >}} Manage Fields** and select **{{< fa chart-bar >}} Change Field Configuration**.

   #### **Inventory Fields** tab

   Click on **{{< fa pencil >}} Manage Fields** and select **{{< fa chart-bar >}} Change Field Configuration**.

   :::

5. Hover over an inventory field, then click **{{< fa star >}}** and select your Highlight Tone:

    - [**{{< fa star >}} Normal**]{.grey}
    - [**{{< fa star >}} Loud**]{.teal}
    - [**{{< fa star >}} Loudest**]{.pink}

    To unpin a highlighted field: Hover over the field, then click **{{< fa star >}}** and select **{{< fa star >}} Don't highlight**.

6. Confirm that the right inventory fields are pinned to the **Overview** tab with the correct highlight tone.

## Manage record field layouts

You can save custom record field layouts to reapply at any time for each record type:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Under the [record type]{.smallcaps} drop-down, select the type of record you want to save a personal layout for.[^9]

3. Select a record or find your record by applying a filter or searching for it.[^10]

4. On the record details page, click the **Inventory Fields** tab.

5. Click on **{{< fa pencil >}} Manage Fields** and select **{{< fa chart-bar >}} Change Field Configuration** to organize, show, or hide record fields as desired.[^11]

6. Save a personal or publish a shared organization record field layout:

### Manage personal record field layouts

{{< include /guide/shared/manage-views/_personal-field-views.qmd >}}

### Manage organization record field layouts

{{< include /guide/shared/manage-views/_organization-field-views.qmd >}}


<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](register-records-in-inventory.qmd)

[^2]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^3]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^4]: [Manage inventory fields](manage-inventory-fields.qmd#inventory-field-types)

[^5]: [Highlight inventory record fields](#highlight-inventory-record-fields)

[^6]: To save a named layout for reuse or sharing, refer to: [Manage record field layouts](#manage-record-field-layouts)

[^7]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^8]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^9]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^10]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^11]: [Organize, show, or hide record fields](#organize-show-or-hide-record-fields)