---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Customize inventory layout"
date: last-modified
aliases:
  - /guide/customize-model-inventory-layout.html
  - /guide/model-inventory/customize-model-inventory-layout.html
includes:
   inventory: true
---

Swap between inventory views or configure the information that displays by default on the {{< var vm.product >}} inventory.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are records registered in the inventory.[^1]

:::

## Swap between views

:::{.callout}
Changes are automatically saved to your account and do not affect other users.
:::

In the left sidebar, click **{{< fa cubes >}} Inventory**:

::: {.panel-tabset}

#### Card view
- To display the inventory in card view, click **{{< fa grip >}} Display Cards**.
- By default, the record name, purpose, tier, owner, and status are displayed on each card.

#### Table view
- To display the inventory in table view, click **{{< fa table >}} Display Table**.
- Columns on the table view can be customized.[^2]

:::

## Customize table view

:::{.callout}
Changes are automatically saved to your account and do not affect other users.
:::

In addition to sorting and filtering the inventory,[^3] you can add or remove columns and customize the order the columns appear on your table view:[^4]

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Click **{{< fa table >}} Manage Columns**. To use this feature, make sure you're in table view.

  - Search for a column name in the list to narrow down results.
  - Toggle visibility for each item and drag each option to change the order.
  - Available columns are determined by your inventory fields.[^5]

Once customized, you can save views for later application for each type of record in your inventory.[^6]

### Manage custom inventory views

#### Manage personal inventory views

::: {.panel-tabset}

#### Save personal views

You can save custom table configurations as a view to reapply at any time:

1. Customize a table view for the **[record type]{.smallcaps}** you want to save a view for.[^7]

    You can also apply filters or sorting before saving your view to include them in the view.[^8]

{{< include _save-layout-view.qmd >}}

Once you've created a saved personal view, you can share it with others in your organization.^

#### Edit or remove saved personal views

::: {.callout-important}
Deletion of saved views is permanent.
:::

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

{{< include _remove-layout-view.qmd >}}

:::

#### Manage organization inventory views

::: {.callout}
To publish a saved personal view to your organization, you must have permissions to manage shared inventory views.^

:::

::: {.panel-tabset}

### Share views with your organization

1. Save a personal inventory view.[^6]

2. Select **My Views (#)**.

3. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

4. Hover over the name of the view you want to share with your organization.

5. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa upload >}} Publish to Organization**.

6. (Optional) Edit the [view name]{.smallcaps} and [description]{.smallcaps} for your shared view.

7. Click **{{< fa upload >}} Publish View** to share your view with your organization.

### Unshare or remove saved organization views

#### Unshare saved organization views

To unshare a saved organization view:

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the view you want to remove from shared organization access.

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa download >}} Unpublish**.

5. Click **Yes, Unpublish View** to confirm removal of the view from shared organization access.

#### Remove saved organization views

To remove a saved organization view:

::: {.callout-important}
Deletion of saved views is permanent.
:::

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the view you want to remove from your organization.

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa trash-can >}} Remove View**.

5. Click **Yes, Remove View** to confirm permanent deletion of that view.

:::



<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](register-records-in-inventory.qmd)

[^2]: [Customize table view](#customize-table-view)

[^3]: [Working with the inventory](working-with-the-inventory.qmd)

[^4]: [Swap between views](#swap-between-views)

[^5]: [Manage inventory fields](manage-inventory-fields.qmd)

[^6]: [Manage custom inventory views](#manage-custom-inventory-views)

[^7]: [Customize table view](#customize-table-view)

[^8]: [Working with the inventory](working-with-the-inventory.qmd)