---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Edit inventory fields"
date: last-modified
aliases:
  - /guide/edit-model-inventory-fields.html
  - /guide/model-inventory/edit-model-inventory-fields.html
includes:
  inventory: true
---

Edit individual detail fields on a record to ensure that record details are accurate and up-to-date.

Changes you make to inventory fields are automatically logged to the associated record's activity.[^1]

::: {.callout title="You can reference record field values in your content blocks within documents."}
Learn more: [Work with content blocks](/guide/documentation/work-with-content-blocks.qmd#reference-field-values)

:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The record you want to edit fields for is registered in the inventory.[^2]
- [x] You are the record owner[^3] for the record you want to edit, a [{{< fa hand >}} Customer Admin]{.bubble}, or assigned another role or stakeholder type with sufficient permissions to perform the tasks in this guide.[^4]

:::


## Edit fields on individual records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select the type of `{Record}` you want to edit fields for by clicking on **{Record} Inventory**.[^5]

3. Select a record or find your record by applying a filter or searching for it.[^6]

4. On the record details page:

   :::: {.panel-tabset}

   ### **Overview** tab

   Select the **Overview** tab to click on highlighted fields to make changes, or to manage inventory record stakeholders.[^7]

   ### **Inventory Fields** tab

   Select the **Inventory Fields** tab to click on additional fields to make changes:

      - Enter keywords into the **{{< fa magnifying-glass >}} Search fields by title** bar to narrow down your list of fields to the field you want to edit.
      - Click on an attachment field header to manage files for that field.[^8]

   ::: {.callout title="Aggregation and Calculation field types are auto-computed and read-only."}
   To modify how these fields are calculated, update their configuration: [Manage inventory fields](manage-inventory-fields.qmd#inventory-field-types)

   :::

   ### Right sidebar

   Click on the core fields in the right sidebar to make changes.

   ::::

5. Click **Save** to apply your changes to the field.

### Manage inventory record stakeholders

::: {.panel-tabset}

#### Manage stakeholder types on records

{{< include /guide/configuration/_manage-stakeholders-on-records.qmd >}}

#### Add or remove stakeholders

1. On the record's detail page, click on the inventory record stakeholder type[^9] you'd like to add users to.

2. Select your desired users from the drop-down menu.

    To remove a user from a stakeholder type, click on the **{{< fa x >}}** to the right of their name.

3. Click **Save** to apply your changes.

:::

### Manage attachments on records
<span id="manage-attachments"></span>

::: {.callout title="The default maximum upload size is 100 MB per file."}
The limit shown in {{< var vm.product >}} may differ depending on your deployment configuration.

- To work with attachments on records, first add an attachment inventory field.[^10]
- Select attachments in `.pdf` format as context documents when generating text blocks with AI within your documents.[^11]
:::

::: {.panel-tabset}

#### Add attachments to a record

1. Click on the header of your attachment field.

{{< include _add-attachments.qmd >}}

#### Remove attachments from a record

1. Click on the header of your attachment field.

{{< include _remove-attachments.qmd >}}

:::

## Edit fields in bulk for multiple records

In addition to editing individual fields on a per record basis, you can edit fields in bulk for a specific record type:

1. First, make sure you're in table view for the record type you want to edit fields for.[^12]

2. Select the records you want to edit fields for by:

    - Clicking {{< fa square >}} in the header column to select all records shown on that page.
    - Clicking {{< fa square >}} next to a specific record.

    To view more records for selection, scroll down to the bottom of the table view and click **Next {{< fa arrow-right >}}**.

3. At the bottom of the page, review the count of records selected to verify that the correct number of records are selected for editing, then click **{{< fa pencil >}} Edit**.

4. Make your changes to the inventory fields for the selected records.

5. Click **Continue {#}** where `{#}` is the number of fields to be edited.

6. Review the changes to be applied to the inventory fields for the selected records to verify that the changes are correct, then click **Save {#} Changes**.



<!-- FOOTNOTES -->

[^1]: [View record activity](/guide/reporting/view-record-activity.qmd)

[^2]: [Register records in the inventory](register-records-in-inventory.qmd)

[^3]: [Manage inventory record stakeholders](/guide/inventory/edit-inventory-fields.qmd#manage-inventory-record-stakeholders)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^6]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^7]: [Manage inventory record stakeholders](#manage-inventory-record-stakeholders)

[^8]: [Manage attachments on records](#manage-attachments)

[^9]: [Manage record stakeholder types](/guide/configuration/manage-record-stakeholder-types.qmd)

[^10]: [Manage inventory fields](manage-inventory-fields.qmd#inventory-field-types)

[^11]: [Work with content blocks](/guide/documentation/work-with-content-blocks.qmd#generate-content)

[^12]: [Customize inventory layout](/guide/inventory/customize-inventory-layout.qmd#swap-between-views)





