---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage inventory record types"
date: last-modified
---

Configure the record types available in your inventory. Each record type has associated fields and stakeholder types that can be customized for your organization's unique requirements.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Add or edit record types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa cube >}} Inventory, select **Inventory Record Types**.

    Here you can edit existing inventory record types, or add a new one:

::: {.panel-tabset}

### Add record types

a. Click **{{< fa plus >}} Add Inventory Record Type**.

b. Enter a **[name]{.smallcaps}** for your record type.

c. Include optional information for your record type:

    - Enter a **[description]{.smallcaps}** to indicate the purpose of the record type displayed on the list of record types.
    - Enter a URL-safe **[slug]{.smallcaps}** where a list of records of this type will be accessible in your {{< var validmind.platform >}} URL under the inventory path.[^2]
    - Select the **[document types]{.smallcaps}** available to be created for this record type.[^3]
    - Select the **[artifact types]{.smallcaps}** available to be logged on this record type.[^4]
    - Select the **[stakeholder types]{.smallcaps}** that should be displayed on this record type.[^5]
    - Select the **[default stakeholder types]{.smallcaps}** that should be displayed by default on this record type.

d. When you are satisfied with the setup of your record type, click **Create**.

### Edit record types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under **{{< fa cube >}} Inventory**, select **Inventory Record Types**.

3. Select the record type you want to change.

4. Update **[name]{.smallcaps}**, **[description]{.smallcaps}**, and any other available properties for that type.

5. Click **Save** to apply your changes. The updates apply to everyone in your organization who can view or work with that record type in the **{{< fa cubes >}} Inventory**.

:::

## Enable or disable record types


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]:

    - For example, `ai-agents` would be accessible at `/model-inventory/ai-agents`.
    - If left blank, a slug will be automatically generated in `kebab-case` format.

[^3]: [Manage document types](/guide/templates/manage-document-types.qmd)

[^4]: [Manage artifact types](/guide/artifacts/manage-artifact-types.qmd)

[^5]: [Manage record stakeholder types](/guide/configuration/manage-record-stakeholder-types.qmd)
