---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Register records in the inventory"
date: last-modified
aliases:
  - /guide/register-models-in-model-inventory.html
  - /guide/model-inventory/register-models-in-inventory.html
tbl-cap-location: bottom
---

Register records with {{< var vm.product >}} as the first step towards streamlining your organization's risk management oversight.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are the record owner.[^1]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^2]

:::

## Register new records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select the type of `{Record}` you want to register by clicking on **{Record} Inventory**.[^3]

3. Click **Register {Record}** to create a new entry in the inventory.

4. Depending on whether or not your organization has additional fields[^4] required on record registration, input the following information:

::: {.panel-tabset}

#### 1. Basic Record Information

If no additional fields are required on creation for your records:

a.  Provide the information outlined in the basic record information fields table below:

    | Field | Description |
    |---:|---|
    | **Record Name** | The name of your record. |
    | **Group**  | (conditional) If you belong to multiple user groups,[^5] select the group that can see the record. |
    | **Business Unit**  | Business unit[^6] associated with the record. |
    | **Is it a Vendor Record?**  (optional) | Toggle whether or not the record is a vendor record.[^7] |
    | **Purpose**  | Explain what the record will be used for. |
    | **Preliminary Risk Tier**  | Assign a preliminary risk tier. |
    : **Basic record information** fields {.hover tbl-colwidths="[30,70]"}

b. Click **Next {{< fa angle-right >}}** to continue to assignment of record stakeholders.[^8]

#### 2. Record Stakeholders

a. Select the record stakeholders to add to the record upon registration.

  - By default, only **Owner**s are required.
  - Additional optional or required record stakeholders can be configured by your customer admin.

b. Click **Next {{< fa angle-right >}}** to continue to additional record information (if required), or **Register {Record}** to create a new entry in the inventory.

#### 3. Additional Record Information

If additional fields are required on record registration for your organization:

a. First enter the basic record information and assign record stakeholders, then click **Next {{< fa chevron-right >}}**.

b. Fill in your organization's required additional fields.

c. Click or **Register {Record}** to create a new entry in the inventory.

:::


<!-- FOOTNOTES -->

[^1]: [Manage inventory record stakeholders](/guide/inventory/edit-inventory-fields.qmd#manage-inventory-record-stakeholders)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^4]: [Manage inventory fields](manage-inventory-fields.qmd)

[^5]: [Manage groups](/guide/configuration/manage-groups.qmd)

[^6]: [Manage business units](/guide/configuration/set-up-your-organization.qmd#manage-business-units)

[^7]: [Vendor record](/about/glossary/glossary.qmd#vendor-model)

[^8]: [Manage record stakeholder types](/guide/configuration/manage-record-stakeholder-types.qmd)
