---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Working with the inventory"
date: last-modified
listing:
  - id: working-with-the-inventory
    type: grid
    max-description-length: 250
    grid-columns: 2
    sort: false
    fields: [title, description]
    contents:
      - register-records-in-inventory.qmd
      - customize-inventory-layout.qmd
      - edit-inventory-fields.qmd
      - customize-record-overview-page.qmd
aliases:
  - /guide/working-with-model-inventory.html
  - /guide/model-inventory/working-with-model-inventory.html
includes:
   inventory: true
---

Use the {{< var vm.product >}} inventory to track comprehensive details for all your records throughout their lifecycles. The inventory is customizable and extensible, with a layout that can be configured to suit each user's needs.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There is at least one record in the inventory.[^1]

:::

## Search, filter, and sort records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select the type of `{Record}` you want to view by clicking on **{Record} Inventory**.[^2]

3. Use the top buttons to narrow down records and organize the inventory to your preference:

   - **{{< fa magnifying-glass >}} Search** — Search for records using keywords in the record name.
   - **{{< fa filter >}} Filter** — Filter records using different criteria.
   - **{{< fa arrow-up-wide-short >}} Sort** — Reorder the list using different criteria in ascending or descending order.[^3]

::: {.callout-button .pl4 .nt4}
::: {.callout collapse="true" appearance="minimal"}
### How do I create effective filters?

{{< include /guide/shared/_work-with-filters.qmd >}}
:::
:::

Changes are automatically saved and affect only your account.

::: {.callout title="Note that searching, filtering, and sorting of fields stack."}
For example, if you first search by keyword for `ValidMind` without clearing that search, any additional filtering and sorting applied will only apply to the results returned by the previous criteria.
:::

## Using the {{< var vm.product >}} inventory

:::{#working-with-the-inventory}
:::

## What's next

- [Managing the inventory](managing-the-inventory.qmd)
- [View record activity](view-record-activity.qmd)


<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](register-records-in-inventory.qmd)

[^2]: [Manage inventory record types](manage-inventory-record-types.qmd)

[^3]:

- **[name]{.smallcaps}**
- [**[business unit]{.smallcaps}**](/guide/configuration/set-up-your-organization.qmd#manage-business-units)
- [**[use]{.smallcaps}**](/guide/configuration/set-up-your-organization.qmd#manage-use-cases)
- **[tier]{.smallcaps}**
- [**[stage]{.smallcaps}**](/guide/workflows/manage-record-stages.qmd)
- **[creation date]{.smallcaps}**
- [**[vendor name]{.smallcaps}**](/about/glossary/glossary.qmd#vendor-model)
- **[updated date]{.smallcaps}**
- [**[documentation updated date]{.smallcaps}**](/guide/documentation/working-with-documentation.qmd)