### Run the quickstart notebook

::: {.callout title="Do you have your code snippet?"}

To initialize the {{< var validmind.developer >}} which connects your environment to the correct model in the {{< var validmind.platform >}}, you'll need your unique code snippet!^[[Get your code snippet](#get-your-code-snippet)]
:::

1. Follow the instructions to run the first two code cells in the notebook,[^run-cells] which sets the stage by installing and initializing {{< var vm.product >}}.^[[Install and initialize the {{< var validmind.developer >}}](/developer/model-documentation/install-and-initialize-validmind-library.qmd)]

1. Under the cell at bottom of the **Get your code snippet** section, confirm that you see a success message verifying that you've connected to the right model.

   This message verifies that the {{< var vm.developer >}} works as expected as is connected to the correct model and document type within the {{< var vm.platform >}}.


<!-- FOOTNOTES -->

[^run-cells]:

   - Hover over each cell and click the {{< fa circle-play >}} **icon**; OR
   - Press `Shift + Enter` on Windows or `Cmd + Enter` if you are on a Mac