<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
See the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-hidden unless-format="revealjs"}
{{< include /guide/configuration/_use-cases.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under Models, select **Model Inventory Fields**.

1. In the Default Fields group, click on the **Use Case** field to add use cases and use case groups.
::::


#### Add use case group

To add a grouping for use cases:

a. Type in your group title under **[options and groups]{.smallcaps}**.

a. Click **{{< fa chevron-down >}}** next to {{< fa plus >}} Add Option.

a. Select **{{< fa plus >}} Add Group** then click **{{< fa plus >}} Add Group** to insert the group.

a. Click **Save Configuration** to save the inserted use case group.

   After you save, confirm that the use case group was added as a new entry at the bottom of the group list.

#### Add use case option

To add an individual use case option:

a. Type in your use case name under **[options and groups]{.smallcaps}**.

a. Click **{{< fa plus >}} Add Option** to add the use case to the list.

a. (Optional) Hover over your use case, then click and hold to drag and drop the use case to a group.

a. Click **Save Configuration** to save the inserted use case.