<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa users >}} Users & Access, select **Groups**.

::: {.panel-tabset}

### Add members

a. Click on the group you want to add members to.

a. Click **{{< fa user-plus >}} Add Member**.

a. Select members by checking the boxes next to their names.

a. Click **Add # User(s) Group**.

   Confirm that the new members are added to the correct group.

### Remove members

Click on the group you want to remove members from.

#### Remove a single member

a. Hover over the member you want to remove from that group.

a. Under the Actions column, click **{{< fa ellipsis-vertical >}}** and select **{{< fa user-minus >}} Remove Member**.

a. Click **{{< fa user-minus >}} Remove 1 member** to confirm removal of the selected member from that group.

#### Remove multiple members

a. Select several members to be removed from the group by checking the boxes next to their names.

a. Review the number of selected members to be removed, then click **{{< fa user-minus >}} Remove**.

a. Click **{{< fa user-minus >}} Remove # member(s)** to confirm removal of selected members from that group.

:::

::::


:::: {.content-hidden unless-format="revealjs"}
1. Click on the group you want to add members to.

1. Click **{{< fa user-plus >}} Add Member**.

1. Select members by checking the boxes next to their names.

1. Click **Add # User(s) Group**

   Confirm that the new members are added to the correct group.

::::