:::: {.content-visible unless-format="revealjs"}
1. Under User Permissions, select **{{< fa user-group >}} Roles**.

1. Click **{{< fa plus >}} Add New Role**. 

1. Enter the unique **[name]{.smallcaps}** and **[description]{.smallcaps}** for the role.^[Role names and model stakeholder type names cannot be duplicated to reduce confusion.]

1. Once you click **{{< fa plus >}} Add Role**, you can proceed with managing the user permissions and users associated with that role.

#### Manage role permissions

1. Click on the role whose user permissions you want to change.

1. Select the **Permissions** tab, where you can: 

      - View the current user permissions assigned to that role.
      - Select user permissions to be assigned to that role.

1. Select **Edit Permissions** to to add or remove user permissions to or from that role. 

1. Toggle specific user permissions for that role by checking or unchecking the boxes next to the permission. 

1. Click **Save Permissions** to apply your changes. 

#### Manage role users

1. Click on the role whose users you want to manage.

1. Select the **Users** tab, where you can:

      - View a list of users assigned to that role.
      - Add a role to users on that list.

##### Add role to user

   1. Click **+** to open the Assign Roles menu for that user. 

   1. Click **+** next to the role for each role to be assigned.  

   1. Click **{{< fa puzzle-piece >}} Assign Roles to User** to save changes.

##### Delete role from user

1. Click **{{< fa x >}}** to delete a role from a user.

1. Once you confirm, that role will be removed from the user.

::::

:::: {.content-hidden unless-format="revealjs"}
1. Under User Permissions, select **{{< fa user-group >}} Roles**.

1. Click **{{< fa plus >}} Add New Role**. 

1. Enter the unique **[name]{.smallcaps}** and **[description]{.smallcaps}** for the role.

1. Once you click **{{< fa plus >}} Add Role**, you can proceed with managing the user permissions and users associated with that role.

#### Manage role permissions

1. Click on the role whose user permissions you want to change.

1. Select the **Permissions** tab, where you can: 

      - View the current user permissions assigned to that role.
      - Select user permissions to be assigned to that role.

1. Select **Edit Permissions** to to add or remove user permissions to or from that role. 

1. Toggle specific user permissions for that role by checking or unchecking the boxes next to the permission. 

1. Click **Save Permissions** to apply your changes. 

#### Manage role users

1. Click on the role whose users you want to manage.

1. Select the **Users** tab, where you can:

      - View a list of users assigned to that role.
      - Add a role to users on that list.

##### Add role to user

   1. Click **+** to open the Assign Roles menu for that user. 

   1. Click **+** next to the role for each role to be assigned.  

   1. Click **{{< fa puzzle-piece >}} Assign Roles to User** to save changes.

##### Delete role from user

1. Click **{{< fa x >}}** to delete a role from a user.

1. Once you confirm, that role will be removed from the user.

::::