<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa users >}} Users & Access, select **User Directory**.

::: {.panel-tabset}

#### Assign new roles to a user

a. Next to any individual user, click the {{< fa circle-plus >}} icon to assign roles for that user.

a. Click **{{< fa plus >}}** next to the role for each role to be assigned.

a. Click **Assign Roles to User** to save changes.

#### Remove roles from a user

a. Click the {{< fa xmark >}} next to the role for the user that you want to remove.

a.  After you confirm, that role will be removed from the user.

:::

::::



:::: {.content-hidden unless-format="revealjs"}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa users >}} Users & Access, select **User Directory**.

1. Next to any individual user, click the {{< fa circle-plus >}} icon to assign roles for that user.

#### Assign new roles to a user

a. Click **{{< fa plus >}}** next to the role for each role to be assigned.

a. Click **Assign Roles to User** to save changes.

#### Remove roles from a user

a. Click the {{< fa xmark >}} next to the role for the user that you want to remove.

a. After you confirm, that role will be removed from the user.

::::