#### Add risk area

:::: {.content-hidden unless-format="revealjs"}
A risk area is a specific domain within an organization that requires monitoring and management to ensure factors like data quality, model performance, and regulatory compliance are addressed effectively.

1. Under Workplace Settings, select **Risk Areas & Validation Guidelines**.
::::

1. click **{{< fa plus >}} Add Risk Area**.

1. Provide a **Name** and **Description** for your risk area:

    - Click **Add Risk Area** to save your changes
    - Click **x** to cancel and return to the previous menu.

:::: {.content-hidden unless-format="revealjs"}
Once a risk area is added, you can then manage guidelines associated with that risk area and add those guidelines to validation templates: [Manage validation guidelines](/guide/model-validation/manage-validation-guidelines.qmd)
::::

:::: {.content-visible unless-format="revealjs"}
#### Edit risk area

1. Hover over the title of a risk area until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

1. Select **{{< fa pencil>}} Edit Risk Area**.

1. Make your desired changes to the risk area's **Name** and **Description**:

    - Click **Save Risk Area** to save your changes.
    - Click **x** to cancel and return to the previous menu.

#### Delete risk area

::: {.callout-important}
Any guidelines associated with a risk area will need to be deleted before the risk area can be removed.
:::

1. Hover over the title of a risk area until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

1. Select **{{< fa trash-can>}} Delete Risk Area**.

1. Once you confirm, that risk area will be removed.
::::