#### Add use cases

:::: {.content-hidden unless-format="revealjs"}
{{< include /guide/configuration/_use-cases.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under Workplace Settings, select **{{< fa building-columns >}} Organization**.

1. Click **{{< fa plus >}} Add New Use Case** under Use Cases.

1. Enter in the **[title]{.smallcaps}** and select a **[category]{.smallcaps}** for your use case.

1. Click **{{< fa plus >}} Add Use Case** to save your changes.

   After you save, the use case will be added as a new entry in alphabetical order.
::::

:::: {.content-visible unless-format="revealjs"}
1. Click **{{< fa plus >}} Add New Use Case** under Use Cases.

1. Enter in the **[title]{.smallcaps}** and select a **[category]{.smallcaps}** for your use case.

1. Click **{{< fa plus >}} Add Use Case** to save your changes.

   After you save, the use case will be added as a new entry in alphabetical order.

#### Remove use cases

::: {.callout-important}
In order to delete a use case, there must be no models associated with it.
:::

1. Hover over the use case until the **{{< fa ellipsis-vertical >}}** appears and click on it.

2. If you are sure you want to remove the use case, click **{{< fa trash-can >}} Delete Use Case** to delete it.

::::