<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

Record stakeholders determine specific responsibilities and access levels for review and approval processes for each record in your inventory, such as read or edit access to inventory fields.

:::: {.content-visible unless-format="revealjs"}
<br>

::: {.callout-button .pl4 .nt4}
::: {.callout collapse="true" appearance="minimal"}
### What permissions do record stakeholders have?

Each record stakeholder also belongs to user groups which determine which records they can see, and have user roles with attached role permissions which define the level of access they have to overarching {{< var validmind.platform >}} features.
:::
:::

::::


:::: {.content-hidden unless-format="revealjs"}
Each record stakeholder also belongs to [user groups](/guide/configuration/manage-groups.qmd){target="_blank"} which determine which records they can see, and have [user roles](/guide/configuration/manage-roles.qmd){target="_blank"} with attached [role permissions](/guide/configuration/manage-permissions.qmd){target="_blank"} which define the level of access they have to overarching {{< var validmind.platform >}} features.

::::
