---
title: "Log into ValidMind"
date: last-modified
listing:
  - id: whats-next-listing
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - ./configure-aws-privatelink.qmd
      - ./configure-google-private-service-connect.qmd
---

Log into our cloud-hosted {{< var validmind_platform >}} to work with your model documentation, prepare validation reports, or to configure ValidMind for your organization.

ValidMind supports the following methods for logging in:

- [Public internet](#public-internet) — easiest, less secure
- [Private network endpoints](#private-network-endpoints) — requires additional configuration, more secure

## Prerequisites

- A valid email address registered with the {{< var validmind_platform >}} and your password.
- Alternatively, your SSO credentials.

<!-- For most users, someone with the Customer Admin role will invite you to your organization.  -->

::: {.callout title="Need an account for ValidMind?"}
Signing up is FREE — **[Create your account]({{< var vm_url_us1 >}})**.
:::

## Public internet

To log in: 

1. In a web browser, open one of the the URLs for the {{< var validmind_platform >}}:
   
   | Name | Provider | Region | URL |
   |--|--|--|----------|
   | US1 | AWS | us-east-1 | [{{< var vm_url_us1 >}}]({{< var vm_url_us1 >}}) |
   | CA1 | AWS | ca-west-1 | [{{< var vm_url_ca1 >}}]({{< var vm_url_ca1 >}}) |
   
   If unsure which URL to use, we recommend US1 or consult your organization for data stewardship requirements. For instance, if your data must stay in Canada, use CA1.

2. Click **I already have an account** and choose one of the login options:

   - Enter your email address and password, and click **Continue**.
   - Select one of the single sign-on (SSO) login options, such as Google, GitHub, or Microsoft, and complete the login steps. 

After successful login, you are redirected to the main dashboard of the {{< var validmind_platform >}}.

## Private network endpoints

To configure and log in through a private endpoint for your company VPC using a supported service:

<!---
## What's next

[Summarize the task and provide any next steps or resources for the user to continue their learning or work.]
--->
