---
# USING THE VARIABLE IN THE TITLE MESSES UP THE BREADCRUMB
title: "Log in to ValidMind"
date: last-modified
listing:
  - id: private-networks
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - configure-aws-privatelink.qmd
      - configure-google-private-service-connect.qmd
aliases:
  - log-into-validmind.html
---

Log in to our cloud-hosted {{< var validmind.platform >}} to work with your model documentation, prepare validation reports, or to configure {{< var vm.product >}} for your organization.

{{< var vm.product >}} supports the following methods for logging in:

- [Public internet](#public-internet) — minimal configuration needed
- [Private network endpoints](#private-network-endpoints) — requires additional configuration

::: {.attn}

## Prerequisites

- [x] A valid email address registered with the {{< var validmind.platform >}} and your password.
- [x] Alternatively, your SSO credentials.

<!-- For most users, someone with the Customer Admin role will invite you to your organization.  -->

::: {.callout}
## To log in, you'll need access to a {{< var vm.product >}} account.

{{< var link.register >}} 
:::

:::

## Public internet

{{< include _validmind-public-internet.qmd >}}

1. Click **Sign in to {{< var vm.product >}}**. 

1. Choose one of the login options:

   - Enter your email address and password, and click **Continue**.
   - Select one of the single sign-on (SSO) login options, such as Google, GitHub, or Microsoft, and complete the login steps. 

    After successful login, you will be redirected to the main dashboard of the {{< var validmind.platform >}}.

## {{< var vm.product >}} access

When you sign in to {{< var vm.product >}} for the first time, what you can access depends on whether user self-onboarding is enabled for your environment.

### If user self-onboarding is enabled

One of the following two options will apply:

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns .pr5}
#### Were you invited to an organization?

- Your invitation is accepted automatically. 
- You are logged in to the organization with the roles defined in the invitation.
:::

::: {.w-50-ns}
#### Were you not invited and do not belong to an organization?

- You can create a new organization.
- You will automatically be assigned the following roles for that organization:

::: {.pl4}
[{{< fa hand >}} Customer Admin]{.bubble}[{{< fa code >}} Developer]{.bubble}
:::

:::

::::

### If user self-onboarding is disabled

- You might have only the [{{< fa wrench >}} Basic User]{.bubble} role with very limited access.
- You will see a message prompting you to contact an administrator. 
- An administrator must invite you to an organization[^2] and grant appropriate roles.[^3] 

Once you belong to an organization and have the necessary roles, you can access models and workflows and perform actions such as editing documentation, running tests, or completing validations.


## {{< var validmind.vpv >}}

To configure and log in through a private link for your company VPC using a supported service:


:::{#private-networks}
:::

## What's next

- [Personalize {{< var vm.product >}}](personalize-validmind.qmd)

<!-- FOOTNOTES -->

<!-- NR
[^1] is defined in _validmind-public-internet.qmd, FYI. 
-->
[^2]: [Manage users](/guide/configuration/manage-users.qmd)
[^3]: [Manage roles](/guide/configuration/manage-roles.qmd)
