---
title: "Manage your profile"
date: last-modified
aliases:
  - view-your-profile.html
---

Personalize your user experience and ensure you have access to the necessary tools and information. View your profile details, manage your onboarding preferences, enable dark mode, access your API keys, and more.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}

:::

## Access your profile

1. In the left sidebar, click **{{< fa gear >}} Settings**. 

2. Under Your Account, select **Profile**. 

   You can find the following on your profile page:

   - Profile details
   - Roles attached to your account
   - Groups assigned to your account
   - Onboarding and user interface preferences
   - Terms of service agreements statuses
   - Localization preferences
   - Access keys
   - Password reset
   - Custom base URL override

### Onboarding
The {{< var vm.platform >}} provides an interactive onboarding journey right in the interface. You can toggle the onboarding wizard on or off at any time, as well as restart the onboarding tasks after you've completed them:

::: {.panel-tabset}

#### Getting started guide

- Toggle [**getting started guide**]{.smallcaps} on to display the interactive onboarding guide.

- Toggle [**getting started guide**]{.smallcaps} off to disable the interactive onboarding guide.

#### Restart onboarding

1. Under Onboarding, ensure that [**getting started guide**]{.smallcaps} is toggled on.

2. Click **Restart** to reset your onboarding progress.

:::

### User Interface Preferences

Under User Interface Preferences, you can switch between the dark and light modes of the {{< var validmind.platform >}}:

- Toggle [**enable dark mode**]{.smallcaps} on to use dark mode.

- Toggle [**enable dark mode**]{.smallcaps} off to use light mode.

The selected theme setting is saved to your user profile and applied across all devices where you log in.

### Terms

Review or accept our terms and conditions and AI terms of use.[^1]

### Localization

Set the **[date format]{.smallcaps}** for date and date time fields[^2] under localization.

### Access Keys

View your [api key]{.smallcaps} and [secret key]{.smallcaps} under Access Keys:

::: {.panel-tabset}

#### [api key]{.smallcaps}

To copy your API key, click **{{< fa clipboard >}} Copy to Clipboard**.

#### [secret key]{.smallcaps}

- To copy your secret key, click **{{< fa clipboard >}} Copy to Clipboard**.

- To reveal your secret key, click **{{< fa eye >}} Reveal**.

:::

::: {.callout}

## To revoke and regenerate keys, click **Revoke & Regenerate Keys**.

When you refresh your API and secret keys,[^3] any instances using your old keys will need to be updated.

:::

### Change Password

To change your password:

1. Enter a new password in **[new password]{.smallcaps}**, or click **Generate strong password** to automatically generate a suggested password.

2. Click **Update Password** to apply the new password.

### Email Base URL Override

Set a custom base URL for links to the ValidMind Platform sent in notification emails.

::: {.callout-important}
## Only enter a custom base URL if instructed by your organization administrators.

Setting a custom base URL affects only you.
:::

1. Enter your custom URL in **[custom base url]{.smallcaps}**.

    Review the URL preview to confirm that the URL is correct.

2. Click **Update Base URL** to apply the new custom base URL.


<!-- FOOTNOTES -->

[^1]: [Legal Ease.](https://validmind.com/about/legal/)

[^2]: [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#inventory-field-types)

[^3]: Keys will automatically expire, or can be revoked by organization administrators on an as needed basis. The default automatic expiry for keys is `999` days.
