---
title: "Manage permissions"
date: last-modified
tbl-cap-location: bottom
---

Permissions dictate user access controls within the {{< var validmind.platform >}}, and are associated with specific roles. Assign granular permissions to roles according to your organization's custom requirements.

::: {.prereq}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a `Customer Admin` or assigned another role with sufficient permissions to perform the tasks in this guide.[^1] 

:::

## Steps

::: {.callout-important title="When assigning permissions to roles, ensure they align with the role's intended responsibilities and access requirements."}
Please note that the `Customer Admin` role has the highest level of access and as such its permissions cannot be modified.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**. 

{{< include _manage-permissions.qmd >}}

### Default permissions

The following tables outline the default roles and stock permissions provided by ValidMind:  

#### Workflow

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Create Workflow | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Read Workflow | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked />  |
| Delete Workflow | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled />  |
| Update Workflow | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled />  |
: **Workflow** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Role

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Create Role | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Update Role | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Delete Role | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Read Role | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Role** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Model

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Log Tracking | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Update Model | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Download VR | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Delete Model | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Download Doc | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Read Model | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked />| <input type="checkbox" disabled checked /> |
| Create Model | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
: **Model** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Severity

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Severity | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Severity** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Assessment Option

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Assessment Option | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Add Assessment Option | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Delete Assessment Option | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Update Assessment Option | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Assessment Option** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Guideline

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Guideline | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Add Guideline | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Delete Guideline | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Update Guideline | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Guideline** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Business Unit

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Business Unit | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Add Business Unit | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Update Business Unit | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Delete Business Unit | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
: **Business Unit** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Status

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Status | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Add Status | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Update Status | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Delete Status | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
: **Status** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Group

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Create Group | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Read Group | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Update Group | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Delete Group | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Group** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Use Case

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Use Case | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Add Use Case | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Update Use Case | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Delete Use Case | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
: **Use Case** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Risk Area

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Risk Area | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Update Risk Area | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Delete Risk Area | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Add Risk Area | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
: **Risk Area** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Template

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Duplicate Template | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Update Template | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Read Template | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Create Template | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Delete Template | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Template** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### User

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Create User | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Update User | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Delete User | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Read User | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **User** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Organization

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Read Organization | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Update Organization | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled />  |
| Invite User Organization | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Create Organization | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled />  |
| Delete Organization | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |<input type="checkbox" disabled />  |
: **Organization** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Validation Report

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Add Block VR | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked />  |
| Remove Block VR | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked />  |
| Update VR | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked />  |
| Add Comment VR | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked />  |
| Swap Template VR | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Read VR | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked />  | <input type="checkbox" disabled checked />  |
| Assess Guideline | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Validation Report** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Documentation

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Add Block Doc | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Remove Block Doc | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Update Doc | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Add Comment Doc | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Swap Template Doc | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> |
| Read Doc | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
: **Documentation** permissions {.hover tbl-colwidths="[40,20,20,20]"}

#### Finding

| Permission | Customer Admin | Developer | Validator |
|---|:---:|:---:|:---:|
| Delete Finding | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
| Add Finding | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Add Finding Comment | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled checked /> |
| Update Finding | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled checked /> |
| Read Finding | <input type="checkbox" disabled checked /> | <input type="checkbox" disabled /> | <input type="checkbox" disabled /> |
: **Finding** permissions {.hover tbl-colwidths="[40,20,20,20]"}


<!-- FOOTNOTES -->

[^1]: [Default permissions](#default-permissions)