---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage users"
date: last-modified
aliases:
  - /guide/manage-users.html
---

Invite new users and review your current users from within the user directory. Users belong to groups which determine which records they can see, and have roles with attached permissions which define the level of access they have to features.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1] 

:::

## View and search for users

View a list of users in your organization that have access to the {{< var validmind.platform >}}: 

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa users >}} Users & Access, select **User Directory**.

    Search the list of Organization Users by typing a keyword into the **{{< fa magnifying-glass >}} Search by name, email, title, or role...** box.

## Manage user invitations

Invite users in your organization to the {{< var validmind.platform >}}:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa users >}} Users & Access, select **Invite New Users**.

::: {.panel-tabset}

### Invite new users

{{< include _invite-users.qmd >}}

### Monitor user invitations

{{< include _monitor-invitations.qmd >}}

:::

## Manage user roles

Adjust the roles[^2] users from your organization have within the {{< var validmind.platform >}}:

{{< include _manage-user-roles.qmd >}}

## Disable users

::: {.callout-important title="Disabling users is permanent and cannot be undone."}
To allow users access to your organization again, including providing valid API keys and secrets, you must re-invite them.[^3]

:::

To remove a user from your organization, revoking their access and any API keys and secrets:[^4]

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa users >}} Users & Access, select **User Directory**.

3. Hover over the user you want to remove from your organization.

4. Under the Actions column, click **{{< fa ellipsis-vertical >}}** and select **{{< fa user-minus >}} Disable**.

5. Select **Disable** to confirm removal of the selected user from your organization.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Manage roles](/guide/configuration/manage-roles.qmd)

[^3]: [Manage user invitations](#manage-user-invitations)

[^4]: [Manage your profile](/guide/configuration/manage-your-profile.qmd#access-keys)