---
title: "Manage model stakeholder types"
date: last-modified
---

{{< include /guide/configuration/_model-stakeholder-types.qmd >}}

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Add or edit model stakeholder types

::: {.callout-important}
Please note that the stock **Model Developer**, **Model Owner**, and **Model Validator** stakeholder types are required by default for all models, and as such cannot be cannot be modified.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**. 

2. Under User Permissions, select **{{< fa users >}} Model Stakeholder Types**.

3. Click **{{< fa plus >}} Add New Stakeholder Type**. 

4. Enter the unique **[name]{.smallcaps}** and **[description]{.smallcaps}** for the stakeholder type.[^2]

5. Once you click **{{< fa plus >}} Add Type**, you can proceed with managing the model inventory field[^3] permissions associated with that type.

#### Manage stakeholder type permissions

1. Click on the stakeholder type whose permissions you want to change.

1. On the **Permissions** tab, you can: 

   - View the current model inventory field permissions assigned to that type.
   - Select model inventory field permissions to be assigned to that type.

1. Select **Edit Permissions** to to add or remove model inventory field permissions to or from that type. 

1. Toggle specific permissions for that stakeholder type by checking or unchecking the boxes next to the permission. 

1. Click **Save Permissions** to apply your changes.

## Manage stakeholder types on models

::: {.callout-important title="Changes will only apply to individual models."}
Adding a model stakeholder type on one model in your inventory will not affect the stakeholder types on the other models within your inventory.
:::

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^4]

3. Click **{{< fa user-plus >}} Manage Model Stakeholders**.

4. Toggle the stakeholder types you would like to display for that model.

5. Add at least one user to each of your desired custom stakeholder types to save the display settings for that model:

    a. Click on your model stakeholder type.
    b. Select your users from the drop-down menu.
    c. Click **Save** to apply your changes.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: Role names and stakeholder type names cannot be duplicated to reduce confusion.

[^3]: [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd)

[^4]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)