---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage record stakeholder types"
date: last-modified
aliases:
  - /guide/configuration/manage-model-stakeholder-types.html
---

{{< include /guide/configuration/_stakeholder-types.qmd >}}

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Add record stakeholder types

{{< include /guide/configuration/_add-stakeholder-types.qmd >}}

## Edit record stakeholder types

::: {.callout-important}
Please note that the stock **Developer**, **Owner**, and **Validator** stakeholder types are required by default for all records, and as such cannot be cannot be modified.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa cube >}} Inventory, select **Inventory Record Stakeholder Types**.

3. Click on the stakeholder type you want to edit.

4. Make your changes to:

    - **[name]{.smallcaps}** — Click on the name to edit, then click **Save** to apply your changes.
    - **[description]{.smallcaps}** — Click on the description to edit, then click **Save** to apply your changes.
    - Inventory record types the stakeholder type is available on[^2]
    - Display availability of the stakeholder type during record registration[^3]
    - Inventory field, document, and artifact permissions associated with the stakeholder type[^4]

### Assign stakeholder types to inventory record types

1. Under **[inventory record types]{.smallcaps}**, select the inventory record types the stakeholder type is available on.

2. Under **[default on inventory record types]{.smallcaps}**, select which inventory record types should display this stakeholder type by default.

3. Click **Save Inventory Record Type Links** to apply your changes.

### Configure stakeholder types on registration

{{< include /guide/configuration/_stakeholder-type-on-registration.qmd >}}

### Manage stakeholder type permissions

{{< include /guide/configuration/_manage-stakeholder-type-permissions.qmd >}}

## Manage stakeholder types on records

{{< include /guide/configuration/_manage-stakeholders-on-records.qmd >}}


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Assign stakeholder types to inventory record types](#assign-stakeholder-types-to-inventory-record-types)

[^3]: [Configure stakeholder types on registration](#configure-stakeholder-types-on-registration)

[^4]: [Manage stakeholder type permissions](#manage-stakeholder-type-permissions)
