---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage roles"
aliases:
  - /guide/manage-roles.html
---

{{< include /guide/configuration/_user-roles.qmd >}}

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Add or update roles

::: {.callout-important}
## Two special default roles provided by {{< var vm.product >}} have unique characteristics.

1. **[{{< fa hand >}} Customer Admin]{.bubble}** — The <sup>[{{< fa lock >}} Locked]{.bubble}</sup> role with the highest level of access and, as such, cannot be modified.

2. **[{{< fa wrench >}} Basic User]{.bubble}** — The <sup>[Basic]{.bubble}</sup> role with the lowest level of access, providing only limited access until an administrator grants additional optional permissions or roles to users.[^2]

:::

{{< include _add-roles.qmd >}}

### Manage role permissions

{{< include _manage-role-permissions.qmd >}}

### Manage role users

1. Click on the role whose users you want to manage.

1. Select the **Users** tab, where you can:

      - View a list of users assigned to that role.
      - Add a role to users already on that list.[^3]

::: {.panel-tabset}

#### Add roles to users

a. Click **{{< fa circle-plus >}}** to the right of a user's name to assign roles to that user.

a. Click **{{< fa plus >}}** next to the role for each role to be assigned.

a. Click **Assign Roles to User** to save changes.

#### Delete roles from users

a. Click **{{< fa x >}}** to delete a role from a user.

a. Click **Yes, Remove Role** to confirm removal of that role from the user.

:::

### Rename existing roles

To rename a role after it has been created:

1. Click on the role you want to rename.

2. On the role's detail view, click on the title of the role.

3. Type in the new name of the role.

4.  Click **Save** to apply your changes.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: Since every user must be a [{{< fa wrench >}} Basic User]{.bubble} to sign in, this role is not available for selection on role assignment menus or shown on the list of roles a user holds, but you can still edit the role's name and permissions.

[^3]: **To add users to roles, refer to:** [Manage users](/guide/configuration/manage-users.qmd#manage-user-roles)