---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Managing your organization"
date: last-modified
listing:
  - id: guides-configuration
    type: grid
    max-description-length: 250
    grid-columns: 2
    sort: false
    fields: [title, description]
    contents:
    - set-up-your-organization.qmd
    - configure-aws-privatelink.qmd
    - configure-google-private-service-connect.qmd
    - configure-azure-private-link.qmd
---

Access to the {{< var validmind.platform >}} is associated with an organization, which encompasses all your users, groups, and business units. As a user, you can belong to multiple organizations.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}

:::

## Switch between organizations

You will see the option to switch between organizations only if you belong to more than one organization via two methods:

::: {.panel-tabset}

#### Via the left sidebar

1. In the left sidebar, locate your name near the bottom.

2. Click on the name of your currently active organization.[^1]

3. Select the organization you'd like to switch to.[^2]

#### Via your settings

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Organization**.

3. Under **Organization**, select the organization you'd like to switch to.[^3]

:::

## Change names of organizations

::: {.callout title="To change your organization's name, you must have sufficient organization permissions."}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has these permissions.[^4]
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**. 

2. Under Workspace, select **Organization**.

3. Under **Organization Name**, type in your new name and click **Update** to save your changes.

## Organization setup

:::{#guides-configuration}
:::



<!-- FOOTNOTES -->

[^1]: Your active organization is displayed under your name and roles in the left sidebar.

[^2]:  Once selected, this will become your active organization.

[^3]:

  - Once selected, this will become your active organization.
  - Your active organization is displayed under your name and roles in the left sidebar.

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)
