---
title: "Set up your organization"
date: last-modified
aliases:
  - /guide/set-up-your-organization.html
---

This task involves managing organizations within {{< var vm.product >}}, allowing for effective business unit control.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Manage business units

{{< include _business-units.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under Workspace, select **Organization**.

1. Add, rename and delete business units as required.

::: {.panel-tabset}

#### Add business units

{{< include _add-business-units.qmd >}}

#### Rename business units

a. Hover over the business unit you want to rename.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa pencil >}} Edit Details** to rename the business unit.

c. Click **Save** to apply your changes.

::: {.callout-important}
In order to delete a business unit, there must be no models attached to that unit.
:::

#### Delete business units

a. Hover over the business unit you want to delete.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select [**{{< fa trash-can >}} Delete Business Unit**]{.red} to remove the business unit.

::: {.callout-important}
In order to delete a business unit, there must be no models attached to that unit.
:::

:::

## Manage use cases

{{< include _use-cases.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under Models, select **Model Inventory Fields**.

1. In the Default Fields group, hover over the **Use Case** field.

1. Under the [actions]{.smallcaps} column, click **{{< fa ellipsis-vertical >}}** and select **{{< fa pencil >}} Edit Details** to add or delete use cases and use case groups as required.[^2]

::: {.panel-tabset}

### Add use cases and use case groups

{{< include _add-use-cases.qmd >}}

### Remove use cases and use case groups

::: {.callout-important title="Use case and use case group deletion is permanent and cannot be undone."}
- In order to delete a use case, there must be no models associated with it.
- Deleting a use case group will not delete use cases under that group — use cases will be categorized as ungrouped.
:::

a. Hover over the use case or use case group you want to delete.

b. If you are sure you want to remove the use case, click **{{< fa trash-can >}} Delete Use Case** to delete it.

:::

## Manage risk areas

{{< include /guide/model-validation/_risk-areas.qmd >}}

::: {.callout title="Risk areas are set up together with your validation guidelines attached to validation reports."}
{{< include /guide/model-validation/_validation-guidelines.qmd >}}

[Set up validation guidelines](/guide/model-validation/manage-validation-guidelines.qmd#set-up-validation-guidelines){.button}
:::

## What's next

- [Managing users](managing-users.qmd)
- [Personalize {{< var vm.product >}}](personalize-validmind.qmd)
- [Manage validation guidelines](/guide/model-validation/manage-validation-guidelines.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: To edit the display behavior of this field on models and model registration, refer to: [Manage model inventory fields](/guide/model-inventory/manage-model-inventory-fields.qmd#add-or-edit-inventory-fields)
