---
title: "View your profile"
date: last-modified
---

Managing your profile is essential for personalizing your user experience and ensuring you have access to the necessary tools and information. View your profile details, manage your onboarding preferences, enable dark mode, and access your API keys.

## Steps

1. [Log into the {{< var validmind_platform >}}](/guide/configuration/log-into-validmind.qmd).

2. Go to **{{< fa gear >}} Settings** in the sidebar. 

3. Select **Profile**. You can find the following on your profile page:

   - Profile details 
   - Roles attached to your account
   - Groups assigned to your account
   - Onboarding and user interface preferences
   - Access keys

#### Onboarding
The {{< var platform >}} provides an interactive onboarding journey right in the interface. You can toggle the onboarding wizard on or off at any time, as well as restart the onboarding tasks after you've completed them:

Getting started guide
: - Toggle **Getting Started Guide** on to display the interactive onboarding guide.  
- Toggle **Getting Started Guide** off to disable the interactive onboarding guide. 

Restart onboarding
: 1. Under Onboarding, toggle **Getting Started Guide** to on.
2. Click **Restart** to reset your onboarding progress. 

#### Dark mode

Under User Interface Preferences, you can switch between the dark and light modes of the {{< var validmind_platform >}}.

- Toggle **Enable dark mode** on to use dark mode.
- Toggle **Enable dark mode** off to use light mode.

#### Access keys

View your API and secret keys under Access Keys:

API key
: To copy your API key, click **{{< fa clipboard >}} Copy to Clipboard**.

Secret key
: - To copy your secret key, click **{{< fa clipboard >}} Copy to Clipboard**.
- To reveal your secret key, click **{{< fa eye >}} Reveal**.

## What's next
- [Get started](/get-started/get-started.qmd)
- [Set up your organization](set-up-your-organization.qmd)
- [Onboarding users](managing-users.qmd)