<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->


<!-- VISIBLE IN USER GUIDES ONlY -->

:::: {.content-visible unless-format="revealjs"}
To create a new text block via the block library:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Documents, select **Block Library**.

3. Click **Add Block** and enter:

    - The **[name]{.smallcaps}** of your text block
    - (Optional) A **[description]{.smallcaps}** for your text block
    - The templated **[content]{.smallcaps}** for your text block

::: {.panel-tabset}

### Reference field values

While composing content for a library text block, you can reference values in the form of variables from model inventory fields. When the text block is inserted into a document, values from the associated model's inventory fields will automatically be populated in the content block if not empty.

{{< include /guide/model-documentation/content_blocks/_reference-field-values.qmd >}}

### Insert mathematical formulas

While composing content for a library text block, you can insert math equations using the formula editor:

{{< include /guide/model-documentation/content_blocks/_insert-mathematical-formulas.qmd >}}


:::

4. Select a **[sharing]{.smallcaps}** option:

    - **Private** — Visible only to you
    - **Shared** — Accessible across your organization

5. Click **Add Block** to save your text block.

::::


<!-- VISIBLE IN TRAINING SLIDES ONLY -->

:::: {.content-hidden unless-format="revealjs"}
To create a new text block via the block library:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under Documents, select **Block Library**.

1. Click **Add Block** and enter:

    - The **[name]{.smallcaps}** of your text block
    - (Optional) A **[description]{.smallcaps}** for your text block
    - The templated **[content]{.smallcaps}** for your text block

1. Select a **[sharing]{.smallcaps}** option:

    - **Private** — Visible only to you
    - **Shared** — Accessible across your organization

1. Click **Add Block** to save your text block.

::::
