Manually add assessment questions, or generate questions from a PDF upload:

:::: {.content-visible unless-format="revealjs"}

#### Manually add questions

a. Click **{{< fa plus >}} Add Question(s)** to create a new question.

a. Enter in the **[questions]{.smallcaps}**:

    - Each line without a break (enter) is considered one complete question.^[Empty lines will be ignored.]
    - To add a separate question, press enter to start a new line.
    - Questions will be added in the order they appear.

    As you enter questions, the count of questions will update.

a. Click **Add # Question(s)** to insert questions into the assessment.

#### Generate questions from PDF uploads

::: {.callout-important}
Uploading a PDF document will replace all previously existing questions, including any custom questions inserted manually.
:::

a. Click **{{< fa plus >}} Add Document** to upload a PDF, or **{{< fa plus >}} Change Document** to replace an existing PDF.

a. On the Upload Document modal, drag and drop a PDF into the upload box, or click on the upload box to select a file.

a. Click **Upload Document** to automatically generate questions based on your PDF upload.

a. After questions are generated, review and edit them to ensure that they adhere to your upload's requirements.

::::




:::: {.content-hidden unless-format="revealjs"}
#### Manually add questions

a. Click **{{< fa plus >}} Add Question(s)** to create a new question.

a. Enter in the **[questions]{.smallcaps}**:

    - Each line without a break (enter) is considered one complete question. Empty lines will be ignored.
    - To add a separate question, press enter to start a new line.
    - Questions will be added in the order they appear.

    As you enter questions, the count of questions will update.

a. Click **Add # Question(s)** to insert questions into the assessment.

#### Generate questions from PDF uploads

a. Click **{{< fa plus >}} Add Document** to upload a PDF, or **{{< fa plus >}} Change Document** to replace an existing PDF.

a. On the Upload Document modal, drag and drop a PDF into the upload box, or click on the upload box to select a file.

a. Click **Upload Document** to automatically generate questions based on your PDF upload.

a. After questions are generated, review and edit them to ensure that they adhere to your upload's requirements.

::::