<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
<!-- VISIBLE ONLY ON PAGES THAT HAVE A CUSTOM METADATA TAG:

```includes:
    custommize: true
``` -->

:::: {.content-visible when-format="html" when-meta="includes.customize"}
Edit document templates from **{{< fa gear >}} Settings** or directly on documents where a template is applied:

::: {.panel-tabset}

#### From **{{< fa gear >}} Settings**

Editing document templates from **{{< fa gear >}} Settings** will create a new version of the template that can be applied to documents:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2.  Under {{< fa file >}} Documents, select **Templates**.

3. Select one of the tabs for the type of template you want to edit:

   - **Development**^[[Working with documentation](/guide/documentation/working-with-documentation.qmd)]
   - **Validation**^[[Preparing validation reports](/guide/validation/preparing-validation-reports.qmd)]
   - **Monitoring**^[[Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)]
   - **Custom**^[[Manage document types](/guide/templates/manage-document-types.qmd)]

4. Click the template to edit and on the template details page, click **{{< fa pencil >}} Edit Template**.^[[Visual editor options](customize-document-templates.qmd#visual-editor-options)]

<!-- {{< include /guide/templates/_template-editing-mode.qmd >}} -->

5. When you're done, click **Create New Version** to view a side-by-side comparison of your changes with the previous version:
   - Add a description in **Version Notes** to track your changes.
   - Click **Save Template** to save the new version.

   Once saved, your new template version becomes available for use.

#### On documents

Editing outlines for templates on documents will only apply changes to that document's active template:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or find your record by applying a filter or searching for it.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)]

1. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** or **Saved Versions** tab.^[[Work with document versions](/guide/documentation/work-with-document-versions.qmd)]

1. Click on the document you would like to customize the template outline for.^[[Manage documents](/guide/templates/manage-documents.qmd)]

1. On the template details page, click  **{{< fa pencil >}} Edit Outline**.

<!-- {{< include /guide/templates/_template-editing-mode.qmd >}} -->

1. When you're done, click **Done Editing** to apply your changes to that specific document's active template.

:::

### Visual editor options

{{< include /guide/templates/_template-editing-mode.qmd >}}

::::

<!-- VISIBLE ONLY ON PAGES THAT **DO NOT** HAVE A CUSTOM METADATA TAG:

```includes:
    customize: true
``` -->

:::: {.content-visible when-format="html" unless-meta="includes.customize"}
Edit outlines for templates directly on documents to only apply changes to that document's active template:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or find your record by applying a filter or searching for it.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)]

1. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** or **Saved Versions** tab.^[[Work with document versions](/guide/documentation/work-with-document-versions.qmd)]

1. Click on the document you would like to customize the template outline for.^[[Manage documents](/guide/templates/manage-documents.qmd)]

1. On the template details page, click  **{{< fa pencil >}} Edit Outline**.

<!-- {{< include /guide/templates/_template-editing-mode.qmd >}} -->

1. When you're done, click **Done Editing** to apply your changes to that specific document's active template.

::::


::::

:::: {.content-hidden unless-format="revealjs"}
Customize {{< var vm.product >}}'s templates for documents to fit your specific case-by-case needs, such as type or complexity of record or record use case.

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1.  Under {{< fa file >}} Documents, select **Templates**.

1. Select one of the tabs for the [type of template you want to edit](/guide/templates/manage-document-types.qmd){target="_blank"}.

1. Click the template to edit and on the template details page, click **{{< fa pencil >}} Edit Template**.

1. In visual editing mode, you can:

   ::: {.panel-tabset}

   #### Work with existing sections

   a. **Expand sections** — Expand the menu for any sections with subsections by clicking **{{< fa chevron-down >}}**.
   a. **Rename sections** — Hover over a section until the **{{< fa pencil >}}** appears, then click on it to change the name. Save by clicking **{{< fa check >}}**.
   a. **Remove sections** — Hover over the section you want to delete. When the **{{< fa trash-can >}}** appears, click on it. Click **Yes, Delete Section** to confirm deletion of that section.
   a. **Reorder sections** — Click **{{< fa ellipsis-vertical >}}{{< fa ellipsis-vertical >}}** and hold firmly to drag to reorder sections.

   #### Add new sections and content

   a. **Insert new sections** — Click **{{< fa plus >}}** to add a new section or subsection to the template:
      - To add a section above the current section, select **{{< fa arrow-up >}} Section Before**.
      - To add a section below the current section, select **{{< fa arrow-down >}} Section After**.
      - To add a subsection within the current section, select **{{< fa arrow-right >}} Subsection**.
   a. **Add content to sections** — In any section of a template that does not have child sections, click **{{< fa plus >}}** to add additional **Content**:
      - **{{< fa align-justify >}} Summary Block** [validation reports only]{.smallercaps .pink}
      - [**{{< fa circle-check >}} Guideline Block**](/guide/validation/manage-validation-guidelines.qmd#add-guidelines-to-templates){target="_blank"} [validation reports only]{.smallercaps .pink}
      - [**{{< fa align-left >}} Text Block**](/guide/templates/customize-document-templates.qmd#add-text-blocks-to-templates){target="_blank"}

   :::

1. When you're done, click **Create New Version** to view a side-by-side comparison of your changes with the previous version:
   - Add a description in **Version Notes** to track your changes.
   - Click **Save Template** to save the new version.

   Once saved, your new template version becomes available for use.

::::

