<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
To duplicate an existing template and start with version one of that new template:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa file >}} Documents, select **Templates**.

3. Select one of the tabs for the type of template you want to duplicate:

   - **Development**^[[Working with documentation](/guide/documentation/working-with-documentation.qmd)]
   - **Validation**^[[Preparing validation reports](/guide/validation/preparing-validation-reports.qmd)]
   - **Monitoring**^[[Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)]
   - **Custom**^[[Managing documents](/guide/templates/managing-documents.qmd)]

4. Duplicate the template from the list or from template details:

::: {.panel-tabset}

### From the templates list

a. Hover over the template until the **{{< fa ellipsis-vertical >}}** menu appears under **Actions**, then click on it.

b. Select **{{< fa copy >}} Duplicate**.

### From template details

a. Click the template to open it.

b. Select **{{< fa copy >}} Duplicate Template**.

:::

5. In the Duplicate Template modal that opens, give your copy a **Template Name** and a **Template Description**.

6. Click **Duplicate Template** to create a copy of your template.

Once duplicated, customize your new template to your needs, making it available for use with your documents.

::::


:::: {.content-hidden unless-format="revealjs"}
To duplicate an existing template and start with version one of that new template:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa file >}} Documents, select **Templates**.

3. Select one of the tabs for the [type of template you want to duplicate](/guide/templates/managing-documents.qmd){target="_blank"}.

4. From the list **{{< fa ellipsis-vertical >}}** menu, select **{{< fa copy >}} Duplicate**, or open the template and select **{{< fa copy >}} Duplicate Template**.

5. In the Duplicate Template modal that opens, give your copy a **Template Name** and a **Template Description**.

6. Click **Duplicate Template** to create a copy of your template.

Once duplicated, customize your new template to your needs, making it available for use with your documents.

::::
