---
title: "Customize {{< var validmind.checker >}}"
date: last-modified
listing:
  - id: check-documents
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../../model-documentation/check-documentation-for-compliance.qmd
    - ../../about/overview-llm-features.qmd
---

Manage the regulations and policies and their attached assessments available when you use the {{< var vm.product >}} {{< var validmind.checker >}}.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Manage regulations and policies

::: {.callout}
Default regulations provided by {{< var vm.product >}} cannot be edited.[^2]
:::

Regulations or policies contain assessments, a set of questions against which your document is checked.

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Regulations & Policies**.

3. Add or edit a regulation or policy:

::: {.panel-tabset}

#### Add regulations or policies

a. Click **{{< fa plus >}} Add** to create a new regulation or policy.

b.  Provide the details for your regulation or policy:

    - **[regulation or policy name]{.smallcaps}**
    - (Optional) **[description]{.smallcaps}**

c. Click **Add** to create your regulation or policy.

d. Once created, manage your regulation or policy assessments.[^3]

#### Edit regulations or policies

a. Hover over the regulation or policy you want to edit.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa pencil >}} Edit** to make changes to the:

    - **[regulation or policy name]{.smallcaps}**
    - (Optional) **[description]{.smallcaps}**

c. Click **Update Regulation or Policy** to save your edits.

:::

## Manage assessments

::: {.callout}
## Default assessments provided by {{< var vm.product >}} cannot be edited, only cloned.

Cloned assessments can then be edited.
:::

Regulations and policies can contain multiple assessments. Assessments are composed of questions against which your document is checked.

To manage an assessment:

1. [Add or clone an assessment](#add-or-clone-assessments)
2. [Add or edit assessment questions](#add-or-edit-assessment-questions)

### Add or clone assessments

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Regulations & Policies**.

3. Select the regulation or policy you want to add or clone an assessment for by clicking on it.

4. Add or clone an assessment:

::: {.panel-tabset}

#### Add assessments

a. Click **{{< fa plus >}} Add** to create a new assessmemt.

b.  Provide the details for your assessment:

    - **[assessment name]{.smallcaps}**
    - (Optional) **[description]{.smallcaps}**

c. Click **Add** to create your assessment.

d. Once created, add or edit the assessment questions.[^4]

#### Clone assessments

a. Hover over the assessment you want to clone.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa copy >}} Clone** to make changes to the:

    - **[regulation or policy name]{.smallcaps}**
    - (Optional) **[description]{.smallcaps}**

c. Click **Clone Assessment** to save a copy of the assessment.

d. Once cloned, add or edit the assessment questions.[^5]

:::

### Add or edit assessment questions

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Regulations & Policies**.

3. Select the regulation or policy you want to add or clone an assessment for by clicking on it.

4. Select the assessment you want to modify by clicking on it.

5. Add or edit assessment questions:


::: {.panel-tabset}

### Add assessment questions

Manually add assessment questions, or generate questions from a PDF upload:

#### Manually add questions

a. Click **{{< fa plus >}} Add Question(s)** to create a new question.

b. Enter in the **[questions]{.smallcaps}**:

    - Each line without a break (enter) is considered one complete question.[^6]
    - To add a separate question, press enter to start a new line.
    - Questions will be added in the order they appear.

    As you enter questions, the count of questions will update.

c. Click **Add # Question(s)** to insert questions into the assessment.

#### Generate questions from PDF uploads

::: {.callout-important}
Uploading a PDF document will replace all previously existing questions, including any custom questions inserted manually.
:::

a. Click **{{< fa plus >}} Add Document** to upload a PDF, or **{{< fa plus >}} Change Document** to replace an existing PDF.

b. On the Upload Document modal, drag and drop a PDF into the upload box, or click on the upload box to select a file.

c. Click **Upload Document** to automatically generate questions based on your PDF upload.

d. After questions are generated, review and edit them to ensure that they adhere to your upload's requirements.

### Edit assessment questions

::: {.callout title="How do I locate a specific question?"}
Click **{{<fa magnifying-glass >}} Search** to enter in your keywords, then press **Search** to narrow down results.
:::

a. Hover over the question you want to edit.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa pencil >}} Edit** to make changes to the **[question text]{.smallcaps}**.

c. Click **Update Question** to save your changes.

:::

## Learn more

::: {#check-documents}
:::

<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Check documentation for compliance](/guide/model-documentation/check-documentation-for-compliance.qmd#what-is-the)

[^3]: [Manage assessments](#manage-assessments)

[^4]: [Add or edit assessment questions](#add-or-edit-assessment-questions)

[^5]: [Add or edit assessment questions](#add-or-edit-assessment-questions)

[^6]: Empty lines will be ignored.

