---
title: "Manage document templates"
date: last-modified
aliases:
  - /guide/swap-documentation-templates.html
  - /guide/model-documentation/swap-documentation-templates.html
  - /guide/templates/swap-documentation-templates.html
  - /guide/view-documentation-templates.html
  - /guide/model-documentation/view-documentation-templates.html
  - /guide/templates/view-documentation-templates.html
---

View and swap between different document templates or template versions, or duplicate and delete templates.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] To swap between templates or template versions, more than one template or version must exist for that document type.[^1]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^2]

:::

## View document templates

{{< include /guide/templates/_view-document-templates.qmd >}}

## Swap document templates

::: {.callout title="When swapping templates, only the document structure is changed."}

- Any modifications that you might have made to content is preserved inside each content block or section.
- If you are not sure which template or which version of a template your document is using, you can also check and compare between different templates and versions of templates.
:::

Switch a document to a completely different template, or apply another version of your current template:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^3]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** tab.[^4]

4. Select the document you want to view the template for:

   - Click **{{< fa magnifying-glass >}} Search** to search for documents by keywords in the document title.
   - Click **{{< fa arrow-up-wide-short >}} Sort** to reorder the list using different criteria in ascending or descending order.[^5]

   <!-- ::: {.column-margin}
   **Note that searching and sorting of fields stack.**

   For example, if you first search by keyword for `ValidMind` without clearing that search, any additional sorting applied will only apply to the results returned by that initial search.

   ::: -->

5. On your document's detail page, locate [document template]{.smallcaps}.

6. View the currently applied template and version, or swap to another template or version:

::: {.panel-tabset}

### View currently applied templates

a. Click on the named version of the template.

b. Select **{{< fa eye >}} View Template Details** to open the details for the template applied to that document.

### Swap between templates

a. Click on the named version of the template.

b. Select **{{< fa sync >}} Update Document Template** to swap to a different template or template version:

   - Under **[template]{.smallcaps}**, choose a new template to switch to.
   - Under **[version]{.smallcaps}**, choose a different version of the same template to switch to.

c. Review the differences between the switched templates or template versions to confirm that you want to apply those changes.

d. Click **Apply Changes to Template** to complete the swap.

:::

## Duplicate document templates

{{< include /guide/templates/_duplicate-template.qmd >}}

## Delete document templates

::: {.callout-important title="Template deletion is permanent and cannot be undone."}

- Deleting a template deletes all versions of that template.[^6]
- Templates can only be deleted if they are not in use by any documents.
:::

Delete templates no longer required by your organization:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Documents, select **Templates**.

3. Select one of the tabs for the document type with the templates you want to view:

   - **Documentation**[^7]
   - **Validation Report**[^8]
   - **Ongoing Monitoring**[^9]
   - **Custom**[^10]

4. Select the template you would like to delete by clicking on it.

   Review the details of the template to confirm the template is no longer required.[^11]

5. Click **Delete Template** to remove that template.

   Once you confirm, the template will be deleted.


<!-- FOOTNOTES -->

[^1]: [Manage document types](manage-document-types.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^4]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^5]:

   - **[title]{.smallcaps}** — Sort by title alphabetically.
   - **[type]{.smallcaps}** — Sort by document type alphabetically.
   - **[date created]{.smallcaps}** — Sort by creation date.
   - **[date updated]{.smallcaps}** — Sort by last update date.

      **Searching and sorting of fields stack.**<br>

      For example, if you first search by keyword for `ValidMind` without clearing that search, any additional sorting applied will only apply to the results returned by that initial search.

[^6]: [Customize document templates](customize-document-templates.qmd#edit-template-outlines)

[^7]: [Working with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)

[^8]: [Preparing validation reports](/guide/model-validation/preparing-validation-reports.qmd)

[^9]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^10]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^11]:

   [View document templates](#view-document-templates)<br></br>

    **To delete a template without reviewing template details:**<br></br>

    a. Hover over the template until the **{{< fa ellipsis-vertical >}}** appears, then click on it.
    b. Select [**{{< fa trash-can >}} Delete**]{.red}.