---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Managing documents"
date: last-modified
listing:
  - id: documents
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - manage-document-types.qmd
      - manage-documents.qmd
      - manage-applied-document-templates.qmd
aliases:
  - /guide/templates/working-with-documents.html
  - /guide/templates/working-with-model-documents.html
---

Set up and manage documents and document types, categories of record-related content, for use on records across your organization within the {{< var validmind.platform >}}.

## Manage document defaults

To change the default settings for all documents within your organization:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa file >}} Documents, select **General** to enable or disable tracked changes by default or numbered table and figure captions:

   :::: {.panel-tabset}

   ### Tracked changes

   ::: {.callout-important}
   Enabling tracked changes by default for your organization will disable the following within simple text blocks:[^1]

   - The ability to reference field values in the form of variables
   - Content draft generation with AI

   :::

   Under Document Defaults, toggle whether you would like to **Enable Track Changes by Default**[^2] for all content blocks within documents for your current active organization.

   ### Numbered table and figure captions

   Under Document Defaults, toggle whether you would like to **Enable Numbered Table and Figure Captions** for test results inserted within documents[^3] for your current active organization.

   ::::

## Manage document types and documents

:::: {#documents}
::::

## What's next

- [Documents and templates FAQ](/faq/faq-documentation.qmd)
- [Customize {{< var validmind.checker >}}](customize-document-checker.qmd)


<!-- FOOTNOTES -->

[^1]: [Work with content blocks](/guide/documentation/work-with-content-blocks.qmd#add-content-blocks)

[^2]: [Collaborate with others](/guide/documentation/collaborate-with-others.qmd#tracking-changes)

[^3]: [Work with test results](/guide/documentation/work-with-test-results.qmd)
