---
title: "Manage text block library"
date: last-modified
---

Build a library of reusable text blocks to insert into your documentation templates. Reusable text blocks can be private, visible only to the user, or shared, accessible across your organization.

::: {.callout}
## By default, only the [{{< fa hand >}} Customer Admin]{.bubble} role[^1] is able to add, edit, or delete shared text blocks.

Private blocks can be modified by any user role and are unique to that user.
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}

:::

## Add text blocks

To create a new text block via the block library:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workplace Settings, select **{{< fa align-left >}} Block Library**.

3. Click **Add New Block** and enter:
 
    - The **[name]{.smallcaps}** of your text block
    - (Optional) A **[description]{.smallcaps}** for your text block
    - The templated **[content]{.smallcaps}** for your text block

4. Select a **[sharing]{.smallcaps}** option:

    - **Private** — Visible only to you
    - **Shared** — Accessible across your organization

5. Click **Add Block** to save your text block.

### Add existing text blocks to library

To transform an existing text block into a reusable block:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^2]

3. In the left sidebar that appears for your model, click **{{< fa book-open >}} Documentation**, **{{< fa shield >}} Validation Report**, or **{{< fa desktop >}} Ongoing Monitoring** and select the relevant section containing the text block you want to make reusable.

4. Hover your mouse over the text block you want to add to your block library, and click **{{< fa plus >}} Add to Library** to enter the details for your block:

    - The **[name]{.smallcaps}** of your text block
    - (Optional) A **[description]{.smallcaps}** for your text block
    - The templated **[content]{.smallcaps}** for your text block
    - Whether the block **[sharing]{.smallcaps}** permissions are **Private** or **Shared**

5. Click **Add Block** to save your text block.

After you've added a reusable text block, you can then insert it into your model documentation, validation reports, or ongoing monitoring reports.[^3]

## Duplicate text blocks

To make a copy of an existing text block in your block library:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workplace Settings, select **{{< fa align-left >}} Block Library**.

3. To the right of the text block you want to edit, click **{{< fa ellipsis-vertical >}}** and select **Duplicate Text Block**.

4. Make your desired changes to the following fields:

    - The **[name]{.smallcaps}** of your text block
    - (Optional) A **[description]{.smallcaps}** for your text block
    - The templated **[content]{.smallcaps}** for your text block
    - Whether the block **[sharing]{.smallcaps}** permissions are **Private** or **Shared**

5. Click **Duplicate Block** to save the copy of your text block.

## Edit text blocks

::: {.callout title="Editing a text block within the block library will not update inserted instances of that block."}
Previously inserted instances of text blocks within model documentation, validation reports, or ongoing monitoring reports will not be updated.
:::

To modify an existing text block in your block library:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workplace Settings, select **{{< fa align-left >}} Block Library**.

3. To the right of the text block you want to edit, click **{{< fa ellipsis-vertical >}}** and select **Edit Details**.

4. Make your desired changes to the following fields:

    - The **[name]{.smallcaps}** of your text block
    - (Optional) A **[description]{.smallcaps}** for your text block
    - The templated **[content]{.smallcaps}** for your text block
    - Whether the block **[sharing]{.smallcaps}** permissions are **Private** or **Shared**

5. Click **Save Block** to apply your changes.

## Delete text blocks

::: {.callout-important title="Text block deletion is permanent."}
While previously inserted instances of text blocks will not be affected, the text block will no longer be available for future use via the block library.
:::

To remove an existing text block from your block library:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workplace Settings, select **{{< fa align-left >}} Block Library**.

3. To the right of the text block you want to remove, click **{{< fa ellipsis-vertical >}}** and select **[{{< fa trash-can >}} Delete Text Block]{.red}**.

4. Once you confirm, the text block will be removed from your block library.



<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^3]: [Work with content blocks](/guide/model-documentation/work-with-content-blocks.qmd#add-content-blocks)



