---
title: "Manage regulations and policies"
date: last-modified
listing:
  - id: check-documents
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents: 
    - ../../model-documentation/check-documentation-for-compliance.qmd
---

Customize the regulations and policies available for selection when you use the {{< var vm.product >}} {{< var validmind.checker >}} to review your model documentation for compliance.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Manage regulations and policies

Regulations or policies contain assessments, a set of questions against which your document is checked.

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Regulations & Policies**.

3. Add or edit a regulation or policy:

::: {.panel-tabset}

#### Add regulations or policies

a. Click **{{< fa plus >}} Add** to create a new regulation or policy.

b.  Provide the details for your regulation or policy:

    - **[regulation or policy name]{.smallcaps}**
    - (Optional) **[description]{.smallcaps}**

c. Click **Add** to create your regulation or policy.

d. Once created, manage your regulation or policy assessments.

#### Edit regulations or policies

a. Hover over the regulation or policy you want to edit.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa pencil >}} Edit** to make changes to the:

    - **[regulation or policy name]{.smallcaps}**
    - (Optional) **[description]{.smallcaps}**

c. Click **Update Regulation or Policy** to save your edits.

:::

## Manage assessments

### Add assessment questions

## Learn more

::: {#check-documents}
:::

<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

