---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage applied document templates"
date: last-modified
aliases:
  - /guide/swap-documentation-templates.html
  - /guide/documentation/swap-documentation-templates.html
  - /guide/templates/swap-documentation-templates.html
---

Edit template outlines and swap between different templates or template versions applied to your documents.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] To swap between templates or template versions, more than one template or version must exist for that document type.[^1]
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^2]

:::

## Apply document templates

If a document was created and no default template was applied automatically, select a template for the document:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Select a record or find your record by applying a filter or searching for it.^

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** or **Saved Versions** tab.^
4. Click on the document you would like to apply a template for.^

5. Select from a document template within the {{< var validmind.platform >}},^ or upload an existing PDF:^

   {{< include _apply-document-template.qmd >}}

## View applied templates

To view the template currently applied to a document:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Select a record or find your record by applying a filter or searching for it.[^3]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** or **Saved Versions** tab.[^4]

4. Click on the document you would like to review the applied template for.[^5]

5. On the template details page under Template in the right sidebar, click on the name of the template.

6. Select **{{< fa eye >}} View Details** for information on the:

   ::: {.panel-tabset}

   ### Active Template

   - Who the active template was last edited by
   - Notes submitted when that version of the active template was saved

   ### Base Template

   - The base template's name — Click on the name to view the details for the base template.
   - When the base template was created
   - Who the base template was created by

   :::


## Edit applied template outlines

::: {.callout}
Permissions for directly editing document template outlines are defined by document type and determined by your organization's setup.[^6]

:::

{{< include _customize-document-templates.qmd >}}

## Swap applied templates

::: {.callout title="When swapping templates, only the document structure is changed."}

- Any modifications that you might have made to content is preserved inside each content block or section.
- If you are not sure which template or which version of a template your document is using, you can also check and compare between different templates and versions of templates.
:::

Switch a document to a completely different template, or apply another version of your current template:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^7]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^8]

4. Click on the document you want to view the template for.[^9]

5. On your document's detail page, locate **Template**.

6. Click on the named version of the template.

7. Select **{{< fa sync >}} Update Template** to swap to a different template or template version:

   - Under **Template**, choose a new template to switch to.
   - Under **Version**, choose a different version of the same template to switch to.

8. Review the differences between the switched templates or template versions to confirm that you want to apply those changes.

9. Click **Apply Changes to Template** to complete the swap.


<!-- FOOTNOTES -->

[^1]: [Manage document types](manage-document-types.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^4]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^5]: [Manage documents](/guide/templates/manage-documents.qmd)

[^6]: [Manage document types](/guide/templates/manage-document-types.qmd)

[^7]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^8]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^9]: [Manage documents](/guide/templates/manage-documents.qmd)

