---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage document types"
date: last-modified
---

Customize the document types available to your organization. Document types have their own configurable and reusable templates.

::: {.callout title="Development, Validation, and Monitoring document types are provided by default."}
These stock document types cannot be deleted, only edited:

- **Development** — Development documentation, such as model documentation
- **Validation** — Validation reports
- **Monitoring** — Ongoing monitoring reports

:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1] 

:::

## Add document types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa file >}} Documents, select **Document Types**.

3. Click **{{< fa plus >}} Add Document Type**.

4. Enter the document type details:

    - Provide a **[name]{.smallcaps}** and an optional **[description]{.smallcaps}**.
    - Toggle whether this document type should be automatically created **[when record is registered]{.smallcaps}**.
    - Select the **[inventory record types]{.smallcaps}** that should have access to this document type.[^2]
    - (Optional) Under **[default on inventory record types]{.smallcaps}**, select which inventory record types should display this document type by default.
    - (Optional) Toggle a **[default template]{.smallcaps}** for this document type.[^3]
    - Select the inventory record stakeholder types[^4] that should have **[update document]{.smallcaps}** permissions for this document type.[^5]
    - (Optional) Select the inventory record stakeholder types that should have **[update document outline]{.smallcaps}** permissions for this document type.[^6]

5. Click **Create Document Type** to add your document type.

::: {.callout}
Once created, customize the available templates for your document type.[^7]

:::

## Edit or delete document types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa file >}} Documents, select **Document Types**.

3. Edit or delete document types as desired.

::: {.panel-tabset}

#### Edit document types

a. Hover over the document type you want to edit.

b. When the **{{< fa ellipsis-vertical >}}** appears under the Actions column, click on it and select **{{< fa pencil >}} Edit** to change your document type's details.

c. Click **Update Document Type** to apply your changes.

#### Delete document types

a. Hover over the document type you want to delete.

b. When the **{{< fa ellipsis-vertical >}}** appears under the Actions column, click on it and select [**{{< fa trash-can >}} Delete**]{.red} to remove the document type.

c. Click **Yes, Delete Document Type** to confirm permanent deletion of that document type.

::: {.callout-important}
## Development, Validation, and Monitoring document types are stock types and cannot be deleted.

In order to delete a document type, there must be no records using that document type.

:::

:::

<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Manage inventory record types](/guide/inventory/manage-inventory-record-types.qmd)

[^3]: Select a template to be assigned as default from the drop-down menu.

[^4]: [Manage record stakeholder types](/guide/configuration/manage-record-stakeholder-types.qmd)

[^5]: [Manage documents](manage-documents.qmd#edit-record-documents)

[^6]:

    -  At least one inventory record stakeholder type must be assigned to **[update document]{.smallcaps}** permissions in order to adjust **[update document outline]{.smallcaps}** permissions.
    - [Manage document templates](/guide/templates/manage-document-templates.qmd#edit-document-template-outlines)

[^7]: [Customize document templates](customize-document-templates.qmd)




