---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage document template library"
date: last-modified
aliases:
  - /guide/view-documentation-templates.html
  - /guide/documentation/view-documentation-templates.html
  - /guide/templates/view-documentation-templates.html
  - /guide/templates/manage-document-templates.html
---

View, create, or delete the templates available for each document type. Once you've created a template, customize the template for your organization's requirements.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## View document templates

{{< include /guide/templates/_view-document-templates.qmd >}}

## Create document templates

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa file >}} Documents, select **Templates**.

1. Select one of the tabs for the type of template you want to create:

   - **Development**[^2]
   - **Validation**[^3]
   - **Monitoring**[^4]
   - **Custom**[^5]

::: {.panel-tabset}

### Add document templates

{{< include /guide/templates/_add-document-templates.qmd >}}

### Duplicate document templates

{{< include /guide/templates/_duplicate-document-templates.qmd >}}

:::

Once you've created a template, customize your new template to your needs, making it available for use with your documents.[^6]

## Delete document templates

::: {.callout-important title="Template deletion is permanent and cannot be undone."}
- Deleting a template deletes all versions of that template.[^7]
- Templates can only be deleted if they are not in use by any documents.[^8]

:::

Delete templates no longer required by your organization:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2.  Under {{< fa file >}} Documents, select **Templates**.

3. Select one of the tabs for the document type with the templates you want to remove:

   - **Development**[^9]
   - **Validation**[^10]
   - **Monitoring**[^11]
   - **Custom**[^12]

4. Select the template you would like to delete by clicking on it.

   Review the details of the template to confirm the template is no longer required.

5. Click **Delete Template** to remove that template.

6. Click **Yes, Delete Template** to confirm permanent deletion of that template.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Working with documentation](/guide/documentation/working-with-documentation.qmd)

[^3]: [Preparing validation reports](/guide/validation/preparing-validation-reports.qmd)

[^4]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^5]: [Manage document types](/guide/templates/manage-document-types.qmd)

[^6]: [Customize document templates](customize-document-templates.qmd#using-the-template-editor)

[^7]: [Customize document templates](customize-document-templates.qmd#using-the-template-editor)

[^8]: [Manage applied document templates](/guide/templates/manage-applied-document-templates.qmd)

[^9]: [Working with documentation](/guide/documentation/working-with-documentation.qmd)

[^10]: [Preparing validation reports](/guide/validation/preparing-validation-reports.qmd)

[^11]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^12]: [Manage document types](/guide/templates/manage-document-types.qmd)