---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage documents"
date: last-modified
aliases:
  - /guide/templates/manage-model-documents.html
---

Add or delete documents available on individual records in your inventory.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The record you want to manage documents for is registered in the inventory.[^1]
- [x] Document types[^2] and document templates[^3] have been set up for use.
- [x] You are assigned a role with sufficient permissions to create or modify documents on records.[^4]

:::

## Add record documents

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^5]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^6]

4. Click **{{< fa plus >}} Create Document**.

5. Enter the document details:

    - **Document Title** — Title of your document.[^7]
    - **Document Type**[^8] — The type of your document.

6. Click **Create Document** to select from a document template within the {{< var validmind.platform >}},[^9] or upload an existing PDF:[^10]

{{< include _apply-document-template.qmd >}}

## Edit record documents

::: {.callout title="Static PDF documents cannot be edited."}
You can view static PDF documents within {{< var validmind.platform >}} but you cannot modify their structure or contents.[^11]

:::

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^12]

3.  In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^13]

4. Click on the document you'd like to edit:

   - Click **{{< fa magnifying-glass >}} Search** to search for documents by keywords in the document title.
   - Click **{{< fa arrow-up-wide-short >}} Sort** to reorder the list using different criteria in ascending or descending order.

5. Jump to any section of the document by clicking on a heading you would like to view.

6. In any section of the document, click to add or edit content.[^14]

    Use the text editor functions to edit the content of the section.

## Delete record documents

::: {.callout-important}
Deletion of documents on records is permanent and cannot be undone.
:::

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^15]

3. In the left sidebar that appears for your record, click **{{< fa file >}} Documents** and select the **Latest** tab.[^16]

4. Hover over the document you want to delete.

5. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select [**{{< fa trash-can >}} Delete**]{.red} to remove the document.

6. Click **Yes, Delete Document** to confirm permanent deletion of that document from the record.

## What's next

Learn more about how to work with the default document types within the {{< var validmind.platform >}}:

- [Working with documentation](/guide/documentation/working-with-documentation.qmd)
- [Preparing validation reports](/guide/validation/preparing-validation-reports.qmd)
- [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)


<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^2]: [Manage document types](manage-document-types.qmd)

[^3]: [Customize document templates](customize-document-templates.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^6]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^7]: A unique document ID will automatically be created from the title.

[^8]: [Manage document types](manage-document-types.qmd)

[^9]: [Managing document templates](/guide/templates/managing-document-templates.qmd)

[^10]:

    ::: {.callout title="You can only upload PDFs to new, empty documents."}
    Documents with a template already applied can not be replaced with a PDF.
    :::

[^11]: [Add record documents](#add-record-documents)

[^12]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^13]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)

[^14]: [Work with content blocks](/guide/documentation/work-with-content-blocks.qmd)

[^15]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^16]: [Work with document versions](/guide/documentation/work-with-document-versions.qmd)






