---
title: "Swap document templates"
date: last-modified
aliases:
  - /guide/swap-documentation-templates.html
  - /guide/model-documentation/swap-documentation-templates.html
  - /guide/templates/swap-documentation-templates.html
---

Swap between different versions of your model documentation or validation report templates within the {{< var validmind.platform >}}. Switch to a completely different template, or apply another version of your current template.

- When swapping templates, only the document structure is changed. Any modifications that you might have made to content is preserved inside each content block or section. 
- If you are not sure which template or which version of a template your model documentation or validation report is using, you can also check and compare between different templates and versions of templates.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## View current templates

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^2]

3. In the left sidebar that appears for your model, click **{{< fa book-open >}} Documentation**, **{{< fa shield >}} Validation Report**, or **{{< fa desktop >}} Ongoing Monitoring**.

4. On your Document Overview. Validation Report Overview, or Ongoing Monitoring page, locate: 

   - **[document template]{.smallcaps}** — Lists the template used for model documentation.[^3]
   - **[validation report template]{.smallcaps}** — Lists the template used for validation reports.[^4]
   - **[ongoing monitoring template]{.smallcaps}** — Lists the template used for ongoing monitoring plans.[^5]  

5. Click on the named version of the template, then select **{{< fa eye >}} View Template Details** to open the details for the template applied to that model.

## Swap templates

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^6]

3. In the left sidebar that appears for your model, click **{{< fa book-open >}} Documentation**, **{{< fa shield >}} Validation Report**, or **{{< fa desktop >}} Ongoing Monitoring**.

4. On your Document Overview, Validation Report Overview, or Ongoing Monitoring page click on the named version of the template under:
   
   - Document Overview — **[document template]{.smallcaps}**[^7]
   - Validation Report — **[validation report template]{.smallcaps}**[^8]
   - Ongoing Monitoring — **[ongoing monitoring template]{.smallcaps}**[^9]

5. Select **{{< fa sync >}} Update Document Template**:

   - Under **[template]{.smallcaps}**, choose a new template to switch to.
   - Under **[version]{.smallcaps}**, choose a different version of the same template to switch to.

6. Review the differences between the switched templates or template versions to confirm that you want to apply those changes.

7. Click **Apply Changes to Template** to complete the swap.

## What's next

- [Customize document templates](customize-document-templates.qmd)
- [Working with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^3]: [Working with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)

[^4]: [Preparing validation reports](/guide/model-validation/preparing-validation-reports.qmd)

[^5]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

[^6]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^7]: [Working with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)

[^8]: [Preparing validation reports](/guide/model-validation/preparing-validation-reports.qmd)

[^9]: [Ongoing monitoring](/guide/monitoring/ongoing-monitoring.qmd)

<!-- [^10]: [Customize document templates](customize-document-templates.qmd) -->
