---
title: "View documentation templates"
date: last-modified
aliases:
  - /guide/view-documentation-templates.html
  - /guide/model-documentation/view-documentation-templates.html
---

View the structure and configuration of existing documentation templates within the {{< var vm.platform >}}. {{< var vm.product >}} provides default templates for documentation, validation reports, and ongoing monitoring plans.  

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1] 

:::

## Steps

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace Settings, select **{{< fa clone >}} Templates**.

3. Select one of the following template types from the tabs:

   - **Documentation**
   - **Validation Report**
   - **Ongoing Monitoring**

4. Click on one of the available templates. 

   In the page that opens, you can view information about the template, such as: 

   - Template name
   - Template type
   - Template description
   - Template owner
   - Template version
   - Models using that template version
   - Template outline —
      - Sections in the template and how they are structured
      - Guidelines associated with each section
      - Tests from the {{< var vm.developer >}} that feed into the template

## What's next

- [{{< var validmind.developer >}}](/developer/validmind-library.qmd)
- [Collaborate on documentation](/guide/model-documentation/collaborate-with-others.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)
