---
title: "Risk Governance <br>Fundamentals"
subtitle: "docs.validmind.ai/training<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
lightbox: true
search: false
format:
  revealjs:
    include-in-header:
      - text: |
          <script src="/training/assets/vmurl-settings.js"></script>
    controls: true
    controls-tutorial: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /favicon.svg
    footer: "{{< var validmind.training >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/training/training.qmd)"
  html:
    output-file: _risk-governance-fundamentals.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

# Learning objectives

_"Use the {{< var validmind.platform >}} to effectively monitor and control model risks. Understand how to customize workflows for the validation process and ensure compliance. Explore reports to facilitate better decision-making and risk mitigation."_

## In this course

1. Model tracking
2. Compliance review
3. Remediation tracking
4. Risk assessment
5. Executive summaries

{{< include /training/assets/_revealjs-navigation.qmd >}}

## Can you log in?

To try out this course, you need to have been [onboarded](/training/training.qmd#onboarding) onto {{< var validmind.training >}}.

<br>Log in to check your access:

::: {.tc}
[Log in to {{< var vm.product >}}](https://app.prod.validmind.ai/){.button target="_blank"}

<br>
Be sure to return to this page afterwards.

:::


## 1. Model tracking 

Get insights into validation findings, highlighting major issues.

## 2. Compliance review

Ensure adherence to regulatory requirements and internal policies.

## 3. Remediation tracking

Monitor actions taken to address validation findings.

## 4. Risk assessment 

Summarize risks, including model limitations and needed adjustments.

## 5. Executive summaries

Get overviews for validation activities and risk exposure.

# About model risk governance

TBD. 

::: {.tc}
[Learn more ...](/about/overview-model-risk-management.qmd){.button target="_blank"}
:::

Or, find your next learning resource on [{{< var validmind.training >}}](/training/training.qmd).
