---
title: "[validmind](/reference/validmind.html).classifier"
sidebar: validmind-reference
---

Test suites for sklearn-compatible classifier models Ideal setup is to have the API client to read a custom test suite from the project's configuration

## [class]{.muted} ClassifierDiagnosis

<!-- class.qmd.jinja2 - class definition -->

```python
class ClassifierDiagnosis(TestSuite):
```

Test suite for sklearn classifier model diagnosis tests

**Inherited members**

## [class]{.muted} ClassifierFullSuite

<!-- class.qmd.jinja2 - class definition -->

```python
class ClassifierFullSuite(TestSuite):
```

Full test suite for binary classification models.

**Inherited members**

## [class]{.muted} ClassifierMetrics

<!-- class.qmd.jinja2 - class definition -->

```python
class ClassifierMetrics(TestSuite):
```

Test suite for sklearn classifier metrics

**Inherited members**

## [class]{.muted} ClassifierModelValidation

<!-- class.qmd.jinja2 - class definition -->

```python
class ClassifierModelValidation(TestSuite):
```

Test suite for binary classification models.

**Inherited members**

## [class]{.muted} ClassifierPerformance

<!-- class.qmd.jinja2 - class definition -->

```python
class ClassifierPerformance(TestSuite):
```

Test suite for sklearn classifier models

**Inherited members**

## [class]{.muted} TabularDataQuality

<!-- class.qmd.jinja2 - class definition -->

```python
class TabularDataQuality(TestSuite):
```

Test suite for data quality on tabular datasets

**Inherited members**

## [class]{.muted} TabularDatasetDescription

<!-- class.qmd.jinja2 - class definition -->

```python
class TabularDatasetDescription(TestSuite):
```

Test suite to extract metadata and descriptive statistics from a tabular dataset

**Inherited members**
