All users associated with a model, such as model developers and model validators, will see notifications  about comments in their **Recent Activity** feed, found on the main dashboard.

### Post comments

1. In any section of the model documentation, select the portion of text you want to comment on, and click the **Comment** button in the toolbar.

2. Enter your comment and click **Comment**.

3. You can view the comment by clicking the highlighted text. Comments will also appear in the right sidebar.

### Reply to an existing comment

1. Click the highlighted text portion to view the comment thread.

2. Enter your comment and click **Reply**.

3. You can view the comment thread by clicking the highlighted text.

### Resolve comment threads and viewing archived comments

1. Click the highlighted text portion to view the thread, then click <span style="color: green">{{< fa check >}}</span> to resolve the thread.

2. To view the resolved comment thread, click the **Comment archive** button in the toolbar. You can view a history of all archived comments in the Comment archive.

3. To reopen a comment thread, reply to the comment thread in the Comment archive or click the **Reopen** button that appears next to the highlighted text portion.

### Editing and deleting comments

1. Click the highlighted text portion to access the comment thread.

2. To edit a comment in the thread, click the **More options** icon for the corresponding comment and click **Edit**.

3. Edit your comment and click **Save**.

4. To edit a comment in a resolved thread, follow the same steps but click the **Comments archive** button first to access the resolved thread.
