### Add use cases

:::: {.content-visible unless-format="revealjs"}
1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

1. Click **Settings**. 

1. Select **Organization** under **Workspace Settings**.

1. Click **+ Add** at the **Use Cases** sidebar menu.

1. Fill in the use case title and description and click **+ Add Use Case** to confirm.
::::

:::: {.content-hidden unless-format="revealjs"}
A use case is a specific application of analytics and management techniques within an organization, such as attrition management, call routing, and regulatory compliance processes like BSA/AML, CCAR, and CECL.

1. Select **Organization** under **Workspace Settings**.

1. Click **+ Add** at the **Use Cases** sidebar menu.

1. Fill in the use case title and description and click **+ Add Use Case** to confirm.
::::

:::: {.content-visible unless-format="revealjs"}
### Remove use cases

1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

1. Click **Settings**. 

1. Select **Organization** under **Workspace Settings**.

1. Hover over the use case to:
   - Click the trash icon to delete the use case.
::::