### Add risk areas

:::: {.content-visible unless-format="revealjs"}
1. Log in to the {{< var vm_login >}}.

1. Click **{{< fa gear >}} Settings**. 

1. Select **Organization** under **Workspace Settings**.

1. Click **+ Add** at the **Risk Areas** sidebar menu.

1. Fill in the risk title and description and click **+ Add Risk Area** to confirm.
::::

:::: {.content-hidden unless-format="revealjs"}
A risk area is a specific domain within an organization that requires monitoring and management to ensure factors like data quality, model performance, and regulatory compliance are addressed effectively.

1. Select **Organization** under **Workspace Settings**.

1. Click **+ Add** at the **Risk Areas** sidebar menu.

1. Fill in the risk title and description and click **+ Add Risk Area** to confirm.
::::

:::: {.content-visible unless-format="revealjs"}
### Remove risk areas

1. Log in to the {{< var vm_login >}}.

1. Click **{{< fa gear >}} Settings**. 

1. Select **Organization** under **Workspace Settings**.

1. Hover over the risk area to:
   - Click the trash icon to delete the risk area.
::::