---
title: "Add a content block to documentation"
keywords: "new block, model risk management, ValidMind"
---

Learn how to add a new content block to your documentation project, to write and update your model's documentation.

## Prerequisites

- You are a registered user on the ValidMind Platform
- The model you are documenting is [registered in the model inventory](register-models.qmd)
- You are logged into the ValidMind Platform

## Steps

1. Navigate to the relevant model documentation project:

    a. In the **Documentation Projects** page, select the project you want to edit.
    b. Inside your documentation project, navigate to the **Documentation** page.

2. In your documentation, hover your mouse over the space where you want your new block to go until the option to insert a new block appears.

3. Clicking **Insert Block** will give you the option to choose between a **Simple text Block** and a **Test-driven block**.
    - A **Simple text Block** allows you to write and edit plain text.
    - A **Test-driven block** grants you access to an array of test-specific options for your content block.

## Related topics

- [Create documentation projects](create-documentation-project.qmd)
- [Document models with the Validmind UI](document-models-with-ui.qmd)