---
title: "Assign documentation section statuses"
date: last-modified
---

Assign a completion status to individual sections of your model documentation that will be reflected in your Document Overview.

## Prerequisites
- You hold the `Developer` role^1^
- The model is already registered in the model inventory^2^

::: {.column-margin}
**Learn more:**

^1^ [Users (Supported roles)](onboarding-users.qmd#supported-roles)

^1^ [Manage users (User roles)](manage-users.qmd#user-roles)

^2^ [Register models in the inventory](register-models-in-model-inventory.qmd)
:::

## Steps

1. Log in to the {{< var vm_login >}}.

2. In the left sidebar, click **Model Inventory**.

3. Select a model by clicking on it or find your model by applying a filter or searching for it^3^.

4. In the left sidebar that appears for your model, click **Documentation**.

   Jump to any section of the model documentation by selecting the relevant section you would like to view.

5. Next to the heading of each section, you can assign a status from the drop-down:
    - In Progress
    - Done

::: {.column-margin}
^3^ [Working with the model inventory](working-with-model-inventory.qmd#search-filter-and-sort-models)
:::

The documentation completion status summary will then be updated on your Document Overview page.


## What's next
- [View documentation activity](view-documentation-activity.qmd)
- [Collaborate with others](collaborate-with-others.qmd)
