---
title: "Collaborate with others"
date: last-modified
---

Use the real-time collaboration features to track changes, add comments, and access the revision history for model documentation and validation reports.

## Feature highlights

- **Real-time collaboration**. Simultaneously edit model documentation, leave and respond to comments suggestions, and access revision history. Changes to model documentation are also automatically added to ValidMind's activity feed.

- **Spell and grammar checker**. Have your content checked automatically by the built-in spell and grammar checker. 

- **Math formulas**. Add math formulas to documentation by clicking the **MathType** button and using the toolbar, or switch to handwriting.


## Prerequisites

- You are logged into the {{< var vm_login >}}
- You hold the `Developer` or `Validator` role^1^
- The model you are documenting is registered in the model inventory^2^
- Model documentation has submitted for review or validation by the model validation team^4^ 

::: {.column-margin}
**Learn more:**

- ^1^[Users (Supported roles)](onboarding-users.qmd#supported-roles)
- ^1^[Manage users (User roles)](manage-users.qmd#user-roles)
- ^2^[Register models in the inventory](register-models-in-model-inventory.qmd)
- ^4^[Working with model documentation](working-with-model-documentation.qmd)
:::

## Tracking changes

### Suggest a change

1. Click the **Track changes** button in the toolbar to turn on suggestion mode.

2. Make your changes to the model documentation. When changes tracking is enabled, other contributors can accept or decline the suggested changes.

### Resolve changes

1. Suggested changes appear in green or red highlighted text, depending on if the change is adding or removing content. To accept or decline a change, click the highlighted text, then click <span style="color: green">{{< fa check >}}</span> or <span style="color: red">{{< fa xmark >}}</span>. You can also reply to a suggested change.

2. To mass accept or decline suggestions, click the dropdown arror next to the **Track changes** button and click the desired option.

## Revision history

### Save a version

1. Click the **Revision history** button in the toolbar.

2. In the dropdown, click **Save current version**. Optionally, enter a version name. The default name is the date and time the latest change was made.

### View revision history

1. Click the **Revision history button** in the toolbar, then click **Open revision history**. Here, you can view a history of all saved versions and your current version.

2. To see the the change made with each version, select the version in the right sidebar. Changes made in that version are highlighted. Hover over the highlighted content to see who made the change.

### Restore a version

1. To restore a version, select the desired version and click **Restore this version**.

2. The restored version will now appear under revision history with the name: "Restored: 'version name'". To exit revision history without restoring a version, click **Back to editing**.

## Commenting 

{{< include _collaborate-with-others-comments.qmd >}}

### Edit or delete comments

1. Click the highlighted text portion to access the comment thread.

2. To edit a comment in the thread, click the **More options** icon for the corresponding comment and click **Edit**.

3. Edit your comment and click **Save**.

4. To edit a comment in a resolved thread, follow the same steps but click the **Comments archive** button first to access the resolved thread.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
---> 

## What's next

* [Preparing validation reports](preparing-validation-reports.qmd)
* [Work with model findings](work-with-model-findings.qmd)
