---
title: "Collaborate on documentation projects"
keywords: "Collaborate on documentation projects, model risk management, ValidMind"
---

Learn how ValidMind enhances collaboration between model validators and developers on documentation projects. This topic is relevant for model validators who want to track changes across projects, add comments, and access revision history for real-time collaboration with model developers.


## Prerequisites

* You are a registered user on the ValidMind Platform
* The model you are documenting is registered in the model inventory
* A documentation project has submitted for review or validation by the model validation team 
* You are logged into the ValidMind Platform

## Commenting

### Posting comments to the documentation

1. In any section of the model documentation, highlight the portion of text you would like to comment on, and click the **Comment** button in the toolbar.

2. Enter your comment and click **Comment**.

3. You can view the comment by clicking the highlighted text. Comments will also appear in the right sidebar.

### Responding to an existing comment

1. Click the highlighted text portion to view the comment thread.

2. Enter your comment and click **Reply**.

3. You can view the comment thread by clicking the highlighted text.

### Resolving comment threads and viewing archived comments

1. Click the highlighted text portion to view the thread, then click <span style="color: green">{{< fa check >}}</span> to resolve the thread.

2. To view the resolved comment thread, click the **Comment archive** button in the toolbar. You can view a history of all archived comments in the Comment archive.

3. To reopen a comment thread, reply to the comment thread in the Comment archive or click the **Reopen** button that appears next to the highlighted text portion.

### Editing and deleting comments

1. Click the highlighted text portion to access the comment thread.

2. To edit a comment in the thread, click the **More options** icon for the corresponding comment and click **Edit**.

3. Edit your comment and click **Save**.

4. To edit a comment in a resolved thread, follow the same steps but click the **Comments archive** button first to access the resolved thread.

::: {.column-margin}
::: {.callout-tip}
<!--replace this later -->
All users associated with a project, such as model developers and model validators, will see a notification that a comment has been posted in their **Recent Activity** feed, accessible via the ValidMind **Home** page.
:::
:::

## Tracking changes

### Suggesting a change

1. Click the **Track changes** button in the toolbar to turn on suggestion mode.

2. Make your changes to the documentation project. When changes tracking is enabled, other project contributers can accept or decline the suggested changes.

### Resolving changes

1. Suggested changes appear in green or red highlighted text, depending on if the change is adding or removing content. To accept or decline a change, click the highlighted text, then click <span style="color: green">{{< fa check >}}</span> or <span style="color: red">{{< fa xmark >}}</span>. You can also reply to a suggested change.

2. To mass accept or decline suggestions, click the dropdown arror next to the **Track changes** button and click the desired option.

## Revision history

### Saving a version

1. Click the **Revision history** button in the toolbar.

2. In the dropdown, click **Save current version**. Optionally, enter a version name. The default name is the date and time the latest change was made.

### Viewing revision history

1. Click the **Revision history button** in the toolbar, then click **Open revision history**. Here, you can view a history of all saved versions and your current version.

2. To see the the change made with each version, select the version in the right sidebar. Changes made in that version are highlighted. Hover over the highlighted content to see who made the change.

### Restoring a version

1. To restore a version, select the desired version and click **Restore this version**.

2. The restored version will now appear under revision history with the name: "Restored: 'version name'". To exit revision history without restoring a version, click **Back to editing**.

## Real-time collaboration

Users can simultaneously edit the documentation project, leave and respond to comments suggestions, and access revision history. CKEditor is also integrated with ValidMind's activity feed, so changes to the documentation project are automatically added to the activity feed.

## Additional features

- **Spell and grammar checker**.

- **Math formulas**. Add math formulas to documentation by clicking the **MathType** button and using the toolbar, or switch to handwriting.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
---> 

## Related topics

* [Work with Validation Reports](work-with-validation-reports.qmd)
<!---* [Create project findings](create-project-findings.qmd)
* [Manage project findings](manage-project-findings.qmd)--->
* [Comment on Documentation Projects](comment-on-documentation-projects.qmd)
