---
title: "Configure models in the inventory"
---

Filter, sort and search the model inventory. Also, configure the inventory's appearance by managing columns and using card view.

## Prerequisites

There are models registered in the model inventory.

## Steps

1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

2. Navigate to the **Model Inventory**.

3. Use the top buttons to organize the model inventory to your preference:
   - Search for models using **{{< fa magnifying-glass >}} Search**. 
   - Use **{{< fa filter >}} Filter** to filter models by business units, developers, model tiering, model status, owners, use, validators, or vendor model.
   - Click **{{< fa table >}} Manage Columns** to manage column visibility and order. You can toggle visibility for each category and drag the option to change the order.
   - Use **{{< fa arrow-up-wide-short >}} Sort** to sort results by certain criteria.
   - Click **{{< fa table >}} Display table** or **{{< fa grid-2 >}} Display cards** to toggle between table and card view.

Changes are automatically saved for your account.

## What's next

- [Register models in the inventory](register-models-in-model-inventory.qmd)