---
title: "Create documentation projects"
keywords: "create projects, documentation, model developer, model validator, model risk management, ValidMind"
---

Learn how to create a new documentation project in the ValidMind Platform. You can use this new project to upload tests and documentation to the ValidMind Platform, review and validate models, and generate validation reports. 

## Prerequisites

- You are a registered user on the ValidMind Platform
- The model you are documenting is [registered in the model inventory](register-models.qmd)

## Steps

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).
   
2. On the **Documentation Projects** page, click **Create new project**.
   
3. Select the relevant details in the form:

   - Select the relevant model 
   - Select the relevant type of documentation you are looking to generate 
   - Enter a name for the project 

4. Click **Create Project**.

::: {.column-margin}
::: {.callout-tip}
The documentation template is automatically applied based on the selected model details and documentation requirements configured by an administrator, such as your model risk management team.
:::
:::

ValidMind has now created an empty documentation project associated with the model. You can access this project from the UI on the **Documentation Projects** page or by navigating to the relevant model details page in the **Model Inventory** page.

<!--- TO DO I believe this will move, so we need to revisit this --->
4. Locating the project identifier, API key and secret:
   
   On the **Client Integration** page of the newly created project, you can find the initialization code that enables the client library to associate documentation and tests with the appropriate project. The initialization code configures the following arguments: 

- `api_host`: The location of the ValidMind API
- `api_key`: The account API key
- `api_secret`: The account secret key
- `project`: The project identifier

The code snippet can be copied and pasted directly into your developer source code to integrate the ValidMind Developer Framework and to be able to upload to the ValidMind Platform.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
---> 

## Related topics

- [Install and initialize the Developer Framework](install-and-initialize-developer-framework.qmd)
- [Document models with the Developer Framework](document-models-with-framework.qmd)
- [Document models with the ValidMind UI](document-models-with-ui.qmd)
