---
title: "Customize resource statuses"
date: last-modified
---

Statuses can be manipulated via workflow transitions and are used to track the progress of resources through your organization's processes.

Default statuses are provided for you as suggestions. You can add, edit, remove, and define your own custom statuses in each category:

- **Model documentation**
- **Model lifecycle**

<!-- Model validation statuses are in missing as of May 2024 -->

## Prerequisites

To add, edit, or delete statuses, you must hold the `Customer Admin` or `Developer` role.

## Add or edit statuses

1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

2. In the left sidebar, click [**{{< fa gear >}} Settings**]({{< var vm_url >}}/settings).

3. Under Workplace Settings, select **{{< fa arrow-right-arrow-left >}} Statuses**.

4. Under available statuses, select the process you'd like to add or edit statuses for:

    - To add a status, click **+ Add New Status**.
    - To edit a status, click on the status itself. 

    On the status detail popup that appears, provide the required information indicated by `*`.

5. When you are done, click **Save** to apply your changes.

## Delete statuses

::: {.callout-warning title="Deleting statuses already in use will cause your workflows to no longer function correctly."}
 Make sure that the status you're deleting is inactive and not associated with any workflows or models in your inventory before proceeding. 
:::

1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

2. In the left sidebar, click [**{{< fa gear >}} Settings**]({{< var vm_url >}}/settings).

3. Under Workplace Settings, select **{{< fa arrow-right-arrow-left >}} Statuses**.

4. Under available statuses, select the process you'd like to delete a status for.

5. Hover over the status you'd like to delete, and click **{{< fa trash-can >}} Delete**.

    - A confirmation dialogue will appear. Select **OK** to continue. 
    - A toast will indicate that your status has been successfully deleted.

## What's next

- [Workflows FAQ](../faq/faq-workflows.qmd)
- [Set up workflows](set-up-workflows.qmd)

