---
title: "Developer framework"
keywords: "developer framework, Python library, API, model risk management, ValidMind"
---

The ValidMind developer framework allows model developers and validators to automatically
document different aspects of the model development lifecycle.

This Python library provides the following high level features:

- Log qualitative and quantitative data about datasets and models
- Log documentation metadata to be displayed on the ValidMind platform
- Run data and model validation test plans

## Installing the client library

The Python library can be installed with the following command:

```
pip install validmind
```

## Initializing the client library

Every validation project has a project identifier that allows the client library to
associate documentation and tests with the appropriate project. In order to initialize
the client, we need to provide the following arguments:

| Argument | Description |
| --- | --- |
| api_host | Location of the ValidMind API. |
| api_key | Account API key. |
| api_secret | Account Secret key. |
| project | The project identifier. |


The following code snippet shows how to initialize a ValidMind client instance:

```python
import validmind as vm

vm.init(
  api_host = "<API_HOST>",
  api_key = "<API_KEY>",
  api_secret = "<API_SECRET>",
  project = "<PROJECT_ID>"
)
```

