---
title: "Document models with the ValidMind UI"
keywords: "document models, model developer, ai risk, model risk management, ValidMind"
date: last-modified
---

Learn how to use the ValidMind UI editor to edit the content of a documentation project. This topic is relevant for model developers who want to view make qualitative edits to their model documentation.


## Prerequisites

* The model is already [registered in the model inventory](register-models-in-model-inventory.qmd)
* A model developer has provided some content on the documentation, either using the Developer Framework or via the online UI editor
* You have already located the project identifier, API keuy and secret
* You have already initialized the Developer Framework for your model
* You are logged into the ValidMind Platform

## Steps

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. Navigate to the relevant model documentation project:

   a. In the **Documentation Projects** page, select the project corresponding to the model for which you want to view documentation.
   b. On the **Project Overview** page, select Documentation on the left-hand side.
   c. You can now jump to any section of the model documentation by expanding the table of contents on the left and selecting the relevant section you would like to view.

3. In any section of the documentation, hover over text content and click the {{< fa edit >}} edit icon that appears on the right of the textbox. 
<!--- **Need image** --->

    You can now use the text editor functions to edit the content of the section.

4. Save your edits when done by clicking on the {{< fa save >}} save icon to the right of the textbox to save your changes.

::: {.column-margin}
::: {.callout-tip}
The section activity at the bottom of the page records a new event every time edits are made to the contents of the page.
:::
:::

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## Related topics

* [Review and comment on documentation projects](review-documentation-project.qmd)
* [Submit project for approval](submit-for-approval.qmd)
* [Export documentation](export-documentation.qmd)
