---
title: "Document models with the Developer Framework"
keywords: "document models, model developer, model risk management, ValidMind"
---

Learn how to generate model documentation by using the ValidMind Developer Framework. This topic is relevant for model developers who want to document information about their data and model in accordance to template requirements configured by model validators. 

## Prerequisites

* You are a registered user on the ValidMind Platform
* The model is already [registered in the model inventory](register-models.qmd)
* A model developer has provided some content on the documentation, either using the Developer Framework or via the online UI editor
* You have already located the project identifier, API key and secret
* You have already installed the ValidMind client library in your developer environment
* You are logged into the ValidMind Platform

## Document dataset and data quality metrics

1. Initialize the ValidMind library in your developer source:

   Use the project identifier from the associated model documentation project, accessible through the **Client Integration** page.

2. Run the {...} test plan. 

3. View results in the UI.

<!-- TO DO for steps 3 & 4, is there more detail, esp. 4 --->

## Document model description and model performance metrics

1. Initialize the ValidMind library in your developer source:

   Use the project identifier from the associated model documentation project, accessible through the **Client Integration** page.

2. Run the {...} test plan.

3. View the results in the UI.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
---> 

## Related topics

* [Review and comment on documentation projects](review-documentation-project.qmd)
* [Submit project for approval](submit-for-approval.qmd)
* [Export documetnation](export-documentation.qmd)
