---
title: "Editions and features"
keywords: "Editions, features, model risk management, ValidMind"
---

ValidMind offers its solution in multiple editions to choose from. Each edition is priced on an annual subscription basis, depending on the number of models registered on the platform and your support requirements.

## Editions

### Developer Edition

The Developer Edition is the ideal training ground for developers to play around with ValidMind's automated model documention and test robustness of our developer framework, doocumentation and testing features. The Developer edition is free, allowing developers, who are new to model documentation and Model Risk Management, build, implement, test, and maintain higher quality models and model documentation. 

The Developer Edition is only for personal testing purposes and cannot be used as a regular Model Documentation or Model Risk Management solution.

### Essential Edition

With the Essential edition, you get an advanced model risk management (MRM) solution. It offers your organization all features and services of the Developer Edition, plus additional features tailored to the needs of larger-scale organizations.

### Business Critical

Provides the highest level of security for organizations requiring a stricter trust model, such as financial services organizations handling highly sensitive data. This edition encompasses all features and services of the Essential Edition but within a separate ValidMind environment, isolated from other ValidMind accounts via Virtual Private ValidMind (VPV). VPV accounts do not share resources with non-VPV accounts.

## Features 

:::{.column-screen-inset-right}

| **Model development & documentation**             | Developer           | Essential           | Business Critical   |
|---------------------------------------------------|:-------------------:|:-------------------:|:-------------------:|
| Automated model documentation                     | {{< fa check >}}    | {{< fa check >}}    | {{< fa check >}}    |
| Platform-independent developer framework          | {{< fa check >}}    | {{< fa check >}}    | {{< fa check >}}    |
| Online documentation editing                      | {{< fa check >}}    | {{< fa check >}}    | {{< fa check >}}    |
| Advanced editing & readability assistance         |                     | {{< fa check >}}    | {{< fa check >}}    |
| Documentation quality measurement                 |                     | {{< fa check >}}    | {{< fa check >}}    |
| Offline document ingestion                        |                     | {{< fa check >}}    | {{< fa check >}}    |
| Feedback capture on online document               |                     | {{< fa check >}}    | {{< fa check >}}    |
| Documentation version history management          | {{< fa check >}}    | {{< fa check >}}    | {{< fa check >}}    |
| Grammarly integration                             |                     | {{< fa check >}}    | {{< fa check >}}    |
| Standard tests & validation libraries             | {{< fa check >}}    | {{< fa check >}}    | {{< fa check >}}    |
| Configure / customize tests & validation libraries  |                     | {{< fa check >}}    | {{< fa check >}}    |
| Support for customer-provided tests               |                     | {{< fa check >}}    | {{< fa check >}}    |
| Developer workflow management                     |                     | {{< fa check >}}    | {{< fa check >}}    |
| Pre-configured documentation templates & boilerplates | {{< fa check >}}    | {{< fa check >}}    | {{< fa check >}}    |
| Configurable documentation templates & boilerplates   |                     | {{< fa check >}}    | {{< fa check >}}    |
| **Model validation & audit**                      |                     |                     |                     |
| Model validation report automation                |                     | {{< fa check >}}    | {{< fa check >}}    |
| Findings / issues & remediation actions tracking  |                     | {{< fa check >}}    | {{< fa check >}}    |
| Configurable approval workflows                   |                     | {{< fa check >}}    | {{< fa check >}}    |
| MRM workflows & validation lifecycle tracking     |                     | {{< fa check >}}    | {{< fa check >}}    |
| MRM resource & workflow management                |                     | {{< fa check >}}    | {{< fa check >}}    |
| Central model inventory                           |                     | {{< fa check >}}    | {{< fa check >}}    |
| Historical documentation repository /<br>documentation CMS |                     | {{< fa check >}}    | {{< fa check >}}    |
| Grammarly integration                             |                     | {{< fa check >}}    | {{< fa check >}}    |
| Executive reporting                               |                     |                     | {{< fa check >}}    |
| **Platform integration & support**                |                     |                     |                     |
| Data lake integration, such as Evidence Store<br>and monitoring data |                  | {{< fa check >}} | {{< fa check >}} |
| SSO integration                                   |                     | {{< fa check >}}    | {{< fa check >}}    |
| Customer managed encryption                       |                     |                     | {{< fa check >}}    |
| Support 8/5 (one timezone)                        |                     | {{< fa check >}}    | {{< fa check >}}    |
| Support 24/7 (global)                             |                     |                     | {{< fa check >}}    |
| **Platform deployment**                           |                     |                     |                     |
| Multi-tenant SaaS                                 | {{< fa check >}}    | {{< fa check >}}    | {{< fa check >}}    |
| Virtual private ValidMind (VPV)                   |                     | {{< fa check >}}    | {{< fa check >}}    |
| Self-managed VPV                                  |                     |                     | {{< fa check >}}    |
|                                                   | {{< var contact >}} | {{< var contact >}} | {{< var contact >}} |

<!---| AI-generated guidelines & recommendations on<br>documentation compliance and potential model risks | | | {{< fa check >}}    | --->

:::
