---
title: "Edit validation reports"
keywords: "edit validation reports, findings, validators, model risk management, ValidMind"
---

Learn how to use the ValidMind UI editor to create, edit, and publish a validation report for a given model. This topic is relevant for: 

* Model validators who want to capture their observations and conclusions on the model documentation prepared by a model developer

## Prerequisites

* You are a registered user on the ValidMind Platform
* The model you are documenting is registered in the model inventory
* A model developer has marked their model documentation project as "Ready for Validation"
* You are logged into the ValidMind Platform

## View the Validation Report

1. Navigate to the relevant model documentation project
   - In the **Documentation Projects** page, select the project corresponding to the model for which you want to view documentation

2. From the Overview page, select Validation Report on the left-hand side

3. You can now jump to any section of the Validation Report by expanding the table of contents on the left and selecting the relevant section you would like to view

## Add content to / editing the Validation Report

1. In any section of the validation report, hover over text content and click the **edit icon** that appears on the right of the textbox 
<!--- **Need image** --->


2. You can now use the text editor functions to edit the content of the section

3. When done, click the **save icon** to the right of the textbox to save your changes

## Post a comment on the validation report

1. In any section of the validation report, select a portion of text that you would like to comment on, and click the **Add comment** button that appears 
<!--- **Need image** --->


2. Enter your comment and click **Submit**

3. You can now view the comment by highlighting the corresponding portion of text, or by clicking the **Comments** tab in the **ValidMind Insights** right sidebar

## View Validation guidelines and Comments

1. In any section of the validation report, click the **ValidMind Insights** button on the top-right corner to expand the **ValidMind Insights** right sidebar 
<!--- **Need image** --->

   - The "Validation Guidelines" tab shows the validation report guidelines associated with this template, which have been configured by the Model Validation team
   - The **Comments** tab shows the comment threads associated with this section of the model documentation


## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]

## What's Next

* Submit for approval

