---
title: "Edit templates"
keywords: "editing templates, model risk management, ValidMind"
---

Learn how to edit templates that get used for model documentation or for validation reports. This topic is relevant for administrators who need to configure templates for specific use cases or where the existing templates supplied by ValidMind need to be customized.

Documentation templates are stored as YAML files that you edit directly in the online editor. These templates are versioned and saving a documentation template after making changes or reverting to a previous version state will create a new version. 

## Prerequisites

The template you want to edit must have been added to the ValidMind Platform already.

If you are not sure which template or which version of a template a documentation project is using, check the **Project Overview** page of your documentation project. The **Documentation Template** section in the right sidebar lists the information.

## Steps

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. From the side navigation, select **Templates**.

3. Select one of the tabs for the type of template you want to edit: 

   - **Documentation Templates** 
   - **Validation Report Templates**

4. Locate the template to edit and, at the bottom of the template card, click **Edit Template**. 

5. In the YAML editor that opens, make your changes. 

   - Use **See changes** to view a side-by-side comparison of your changes with the latest version of the template
   - Use  **Reset changes** to delete your changes and return to the latest version of the template

6. Click **Prepare new version** to save your changes.

   - Add a description in **Version notes** to track the changes that were made once the version is saved

After you have saved a new version, it becomes available for use with model documentation or validation reports. 

## Troubleshooting

The documentation template editor validates the YAML changes you make and flags any errors that it finds. If you make a change that the editor cannot parse correctly, the editor will not let you save the changes until you correct the YAML. 

Common issues with YAML include incorrect indenting, imbalanced quotes, or missing colons between keys and values. If you run into issues with incorrect YAML, check the error message provided by the template editor, as it might provide a line and column number where the error occurs. 

## What's Next

You can see which version of a template is used in the **Project Overview** page of each documentation project. 

<!--- TO CHECK What is the behavior for projects that use a template, do they automatically get the latest version? Describe the behavior so our users know what to expect. --->
