---
title: "Edit model inventory fields"
date: last-modified
---

Edit individual model detailed fields in the model inventory to customize them to your needs or to ensure that model details are accurate and up to date. 

## Prerequisites

- The model is already registered in the model inventory^1^.
- You are the model owner for the specific model you would like edit the details of, or an administrator^2^.

::: {.column-margin}
**Learn more:**

^1^ [Register models in the inventory](register-models-in-model-inventory.qmd)

^2^ [Users (Supported roles)](onboarding-users.qmd#supported-roles)

^2^ [Manage users (User roles)](manage-users.qmd#user-roles)
:::

## Steps

<!--- NR TO DO Check with Mehdi: these steps didn't work for me, can't edit. Wrong permissions maybe? --->

1. Log in to the {{< var vm_login >}}.

2. Click **Model Inventory** in the left sidebar. 

3. Select a model by clicking on it or find your model by applying a filter or searching for it^3^.

4. Hover over a field until the **{{< fa pencil >}}** appears, then click to make your changes:  

   a. Click **Save** to apply your changes.
   b. Click **Cancel** to discard your changes.

::: {.column-margin}
^3^ [Working with the model inventory](working-with-model-inventory.qmd#search-filter-and-sort-models)
:::

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

- [Register models in the inventory](register-models-in-model-inventory.qmd)
- [Manage inventory custom fields](manage-inventory-custom-fields.qmd)
