---
title: "Editions"
keywords: "Editions, model risk management, ValidMind"
---

ValidMind offers its solution in multiple editions to choose from. Each edition is priced on an annual subscription basis, depending on the number of models registered on the platform and your support requirements.

## Standard Edition

Standard Edition serves as our entry-level offering and includes all related features.

## Enterprise Edition

Enterprise Edition includes all features and services of the Standard Edition, plus additional features tailored to the needs of large-scale organizations.

## Virtual Private ValidMind (VPV)

Virtual Private ValidMind (VPV) provides the highest level of security for organizations requiring a stricter trust model, such as financial services organizations handling highly sensitive data. It encompasses all features and services of the Enterprise Edition but within a separate ValidMind environment, isolated from other ValidMind accounts (VPV accounts do not share resources with non-VPV accounts).

## Related Topics

For early program access, refer to [Pilot release](release-pilot.qmd)