---
title: "Export documentation"
date: last-modified
---

If you need access to your model model documentation or validation reports outside of the ValidMind platform, you can export your model documentation and validation report as Word or PDF files.

## Prerequisites

* You hold the `Developer` or `Validator` role
* The model is already [registered in the model inventory](register-models-in-model-inventory.qmd)
* Model documentation is completed or in progress
* You are logged into the ValidMind Platform

ValidMind supports Word 365, Word 2019, Word 2016, and Word 2013.

## Export Model Documentation

1. In the left sidebar, click [**Model Inventory**](https://app.prod.validmind.ai/model-inventory).

2. Select a model by clicking on it or find your model by applying a filter or searching for it.

3. In the left sidebar that appears for your model, click **Documentation**.

3. In right sidebar, click **Export Document**.

4. Configure the export options:

   <!--- - Check **Include comment threads** to include comment threads in the exported file.
   - Check **Section activity logs** to include a history of changes in each section of the documentation. --->
   - Choose the file format for export. We currently support exporting to .docx for Microsoft Word format.

5. Click **Download file** to download the file locally on your machine.

## Export Validation Report

1. In the left sidebar, click [**Model Inventory**](https://app.prod.validmind.ai/model-inventory).

2. Select a model by clicking on it or find your model by applying a filter or searching for it.

<!--- NR Mar 2024 this option does not yet exist --->
3. In the left sidebar that appears for your model, click **Validation Report**.

3. In right sidebar, click **Export Document**.

4. Configure the export options:

   <!--- - Check **Include comment threads** to include comment threads in the exported file.
   - Check **Section activity logs** to include a history of changes in each section of the documentation. --->
   - Choose the file format for export. We support exporting to .docx for Microsoft Word and .pdf for PDF format.

5. Click **Download file** to download the file locally on your machine.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

* [Working with model documentation](working-with-model-documentation.qmd)
* [Collaborate on documentation](collaborate-on-model-documentation.qmd)
* [Submit for approval](submit-for-approval.qmd)
