---
title: "Model registration"
keywords: "faq, model registration, configuration, customization, model risk management, ValidMind"
---

## How do models get registered in ValidMind?

Models get registered into ValidMind via the Model Inventory. To add a model into the Inventory, you need to fill out a customizable registration questionnaire capturing the required registration metadata, such as:

- Model Name
- Model Use
- Model Owner
- Model Dependencies
- And more

## Can the fields for project registration questionnaires be configured?

ValidMind enables you to configure project registration fields, including dropdown options for model risk tiers, model use cases, and documentation templates. 

You can modify these fields as needed and on an ongoing basis. See @sec-introduction

## Can we leverage content from historical documentations? 

ValidMind is in the process of developing features that allow you to benefit from content in historical documentation by:

- Allowing users to select definitions and specific documentation artifacts from previous model documentation for particular model use cases
- Offering users AI-generated content suggestions for specific areas of the documentation (e.g., qualitative sections) based on high-quality historical documentation

These features are currently on the roadmap and under research, no release schedule is set yet.

## What is the cost to configure or customize the solution?

ValidMind offers its solution in multiple editions:

- Standard Edition serves as our entry-level offering.
- Enterprise Edition includes all features and services of the Standard Edition, plus additional features tailored to the needs of large-scale organizations.
- Virtual Private ValidMind (VPV) provides the highest level of security for organizations requiring a stricter trust model, such as financial services organizations handling highly sensitive data. It encompasses all features and services of the Enterprise Edition but within a separate ValidMind environment, isolated from other ValidMind accounts (VPV accounts do not share resources with non-VPV accounts).

Each edition is priced on an annual subscription basis, depending on the number of models on the platform and support requirements.

The platform is designed to allow customers to configure it directly using a user-friendly SaaS UI. Functionality includes user and role-based administration, documentation template configuration, workflow configuration, test-kit customization, and more.

## Can we customize illustrations?

ValidMind utilizes open-source libraries (such as Seaborn and Matplotlib) to generate plots and illustrations. We are working on implementing the ability for model developers to customize styling parameters for these libraries directly within the Developer Framework.

This feature is currently scheduled for Q4 2023.

Additionally, ValidMind is developing a feature that enables developers to create custom visualization widgets by writing JavaScript-based rendering code.

## Can ValidMind manage complex model hierarchies or use cases with multiple models?

ValidMind is enhancing support for complex or modular models in two ways:

- By adding parent/sub-model relational attributes to the model inventory. This is a roadmap item currently scheduled for Q2’2023.
- By enabling tests to run on multiple models simultaneously and aggregating the results. This is a roadmap item currently scheduled for Q3’2023.
