---
title: "Documentation"
keywords: "faq, documentation, model risk management, ValidMind"
---

## Can documentation templates be configured per model use case or to match our existing templates?

ValidMind's platform allows you to configure multiple templates based on documentation requirements for each model use case. During the model registration process, the platform automatically selects the template based on the provided model use case information.

Documentation templates can be modified by configuring a YAML file in the backend.

ValidMind is working on a UI feature that will enable User Administrators (such as the Model Validation team) to modify existing templates and upload new templates to the platform (target roadmap item – Q3 2023).

## Can the documentation be exported?

ValidMind supports exporting documentation and validation reports in Word (.docx) or PDF formats.

## Can we attach files to the documentation on the UI? What file formats are supported?

You can attach image files to documentation cells and comments on the UI. The following file formats are supported:

- JPEG
- PNG
- GIF
- TIFF
- BMP
- SVG
- RAW
- WebP
- HEIF
- PSD

Additionally, ValidMind is working on enabling you to attach Excel, CSV, Word, and PDF files to the documentation in the UI (Roadmap item – Q2 2023).

## Can the documentation be initialized from the UI instead of the Developer Framework?

ValidMind allows you to writr documentation directly in the online UI editor, without having to use the Developer Framework.

From the online UI editor, you can edit text and tables and upload your test results, including images. Using the Developer Framework, you can execute test plans and generate the corresponding documentation.

## Can we export the documentation produced by ValidMind to the storage/workflow system used by the model validation team?

Documentation and validation reports produced in ValidMind can be exported to Word and PDF formats. Depending on the integration requirements of the systems used by your validation teams, such as connectivity via API, SharePoint, and more, ValidMind can work with you to automate the export and storage of documentation into these systems.
