---
title: "Features"
keywords: "Features, model risk management, ValidMind"
---

The platform is designed to allow customers to configure it directly using a user-friendly UI. Functionality includes user and role-based administration, documentation template configuration, workflow configuration, test-kit customization, and more.


|                                                |   Developer   |  Essential  | Business Critical |
|------------------------------------------------|:-------------:|:-----------:|:-----------------:|
| Model development & documentation              |               |             |                   |
| Automated model documentation                  | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Platform independent developer framework       | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Online documentation editing                   | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Advanced editing & readability assistance    |               | {{< fa check >}} | {{< fa check >}} |
| Documentation quality measurement              |               | {{< fa check >}} | {{< fa check >}} |
| Offline document ingestion                     |               | {{< fa check >}} | {{< fa check >}} |
| Feedback capture on online document            |               | {{< fa check >}} | {{< fa check >}} |
| Documentation version history management       | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Grammarly integration                          | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Standard tests & validation library            | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Configure/customize of tests & validation library | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Support for customer-provided tests            | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Developer workflow management                  | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Pre-configured documentation templates & boilerplates | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Configurable documentation templates & boilerplates | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |

<!---
|                                                |   Developer   |  Essential  | Business Critical |
|------------------------------------------------|:-------------:|:-----------:|:-----------------:|
| Model validation & audit                       |               |             |                   |
| Model validation report automation             |               | {{< fa check >}} | {{< fa check >}} |
| Findings/issues & remediation actions tracking |               | {{< fa check >}} | {{< fa check >}} |
| Configurable approval workflows                |               | {{< fa check >}} | {{< fa check >}} |
| MRM workflows & validation lifecycle tracking|               | {{< fa check >}} | {{< fa check >}} |
| MRM resource & workflow management           |               | {{< fa check >}} | {{< fa check >}} |
| Central model inventory                        |               | {{< fa check >}} | {{< fa check >}} |
| Historical documentation repository / documentation CMS|      | {{< fa check >}} | {{< fa check >}} |
| Grammarly integration                          |               | {{< fa check >}} | {{< fa check >}} |
| Executive reporting                            |               |             | {{< fa check >}} |
| AI-generated guidelines & recommendations on documentation compliance and potential model risks | | | {{< fa check >}} |

|                                                |   Developer   |  Essential  | Business Critical |
|------------------------------------------------|:-------------:|:-----------:|:-----------------:|
| Platform integration & support                 |               |             |                   |
| Data lake integration, such as Evidence Store and monitoring data | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| SSO integration                                | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Customer managed encryption                    |               |             | {{< fa check >}}  |
| Support 8/5 (one timezone)                     | {{< fa check >}} | {{< fa check >}} |                   |
| Support 24/7 (global)                          |               |             | {{< fa check >}}  |
| Platform deployment                            |               |             |                   |
| Multi-tenant SaaS                              | {{< fa check >}} | {{< fa check >}} | {{< fa check >}} |
| Virtual private ValidMind (VPV)                |               | {{< fa check >}} | {{< fa check >}} |
| Self-managed VPV                               |               |             | {{< fa check >}}  |
|                                                |               |             |                   |
|                                                |               |             |                   |
|                                                | {{< var contact >}} | Contact Us  | Contact Us        |
--->