---
title: "Get started"
keywords: "get started, model risk management, ValidMind"
---

The easiest way to get started with ValidMind is to try out our developer framework and explore the SaaS platform UI. 

## Try out the developer framework

For model developers, we recommend that you try our introductory notebooks to learn how you initialize the developer framework, use a demo dataset, run test plans, train a model, and send information to the ValidMind SaaS platform.

See the notebooks in action:

- [ValidMind Python Library Introduction](../notebooks/intro.ipynb)
- [ValidMind Python Library Introduction (for R users)](../notebooks/intro-r.ipynb)

<!-- TO DO we need to add the correct download link here --->

Try it yourself:

::: {.column-margin}
::: {.callout-important}
## Getting a 404? Log into GitHub.
 
Until we provide a public location for our notebooks, this link points to our private documentation repo.
:::
:::

```{=html}
<!DOCTYPE html>
<html>
<head>
    <title>Download notebook</title>
    <style>
        button {
            display: inline-block;
            background-color: #DE257E;
            color: white;
            border: none;
            padding: 12px 24px;
            font-size: 16px;
            font-weight: bold;
            border-radius: 4px;
            cursor: pointer;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
            transition: all 0.3s ease-in-out;
            margin-bottom: 20px;
        }

        button:hover {
            background-color: #c71e6b;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }
    </style>
</head>
<body>
    <a href="https://github.com/validmind/documentation/tree/main/site/notebooks" download>
        <button>Download notebook source</button>
    </a>
</body>
</html>

```

After you download the source for the introductory notebooks, you can make changes locally in your own developer environment and run the notebooks with Python 3.8+.

## Explore the SaaS platform

You use the SaaS UI to collaborate with model developers, owners, validators, and others involved in the on the model lifecycle.

Here's how to get started: 

1. [Log in](login.qmd).

2. For model developers:
    a. [Check the documentation, metrics, and test results uploaded by the developer framework](check-developer-framework-uploads.qmd).
    b. Create a new project to learn what the initial workflow looks like.

3. For model validators:
    a. Review model documentation.
    b. Add findings / generate a model validation report


<!---
https://app.dev.vm.validmind.ai/model-inventory
https://app.dev.vm.validmind.ai/projects
https://app.dev.vm.validmind.ai/templates
https://app.dev.vm.validmind.ai/templates


Track your model inventory — Manage the model lifecycle, track the workflow status for models, plan for upcoming validation dates, and more.
Work on validation projects — Collaborate with developers and validators to review documentation, add findings, keep track of review statuses, and generate validation reports.
Configure workflows — Set up ValidMind to follow your existing model risk management processes, manage statuses for different parts of the workflow, and get an end-to-end view of workflows and who is involved.
Work with templates — Configure required validation tests and standardize the documentation table of contents for specific model use cases.
Integrate with your stack — Import and export model documentation and validation reports.

--->
<!---
Generating & Editing a new online document
Creating a new online document for a model use case
Importing the Developer Framework
Generating model documentation using the Developer Framework
Editing the documentation in the ValidMind online UI assistance

Incorporating feedback from MRGR / Model validation team 
Reviewing the model documentation as a Model Validator
Providing feedback as a Model Validator
Reviewing and addressing feedback as a Model Developer

Configuring ValidMind
BLANK Configuring approval workflows and procedures
BLANKConfiguring model documentation templates & boilerplates
--->

## What's next

Ready to configure ValidMind for production with your own use cases? [Our guide has you covered](guide.qmd).

