---
title: "Welcome to the ValidMind sandbox!"
date: last-modified
---

Gain hands-on experience and explore what ValidMind has to offer with our sandbox. 

The sandbox mimics a production environment and includes comprehensive resources such as notebooks with sample code you can run, sample models registered in the model inventory, and draft documentation and validation reports.

Most of our model documentation features are available for you to test in the sandbox, including automated model testing & documentation, preparing model validation reports, and large language model (LLM) support. 

These features provide a rich context for testing and evaluation, using models and datasets provided by ValidMind and hosted in our own environment. 

## Onboarding

Step-by-step instructions: 

1. Get your access credentials from ValidMind. 

   If you haven't reached out to us yet, email <info@validmind.ai> to enquire about access to the sandbox.

<!--- FUTURE step for self-signup
1. Get your access credentials for the Platform UI by signing up with ValidMind: <https://app.prod.validmind.ai/>
   
   This is the login URL for our Platform UI where you can look at the model inventory for the different models. 
--->

2. When you receive your access credentials, make sure you can log in:

   - ValidMind Jupyter Hub: <https://jupyterhub.validmind.ai/>
   - ValidMind Platform UI: <https://app.prod.validmind.ai/>

3. Join a kick-off session with ValidMind to get a free instructor-led hands-on demo.

   After we have received your request to try out the sandbox, we will contact you to set up a kick-off session.

4. Try the sandbox: [Getting started](#getting-started)

::: {.callout-tip}
Need anything else? [Please provide feedback or ask for help](#provide-feedback-or-get-help).
:::

### Sample models

Sample models registered in the model inventory include:

- Customer churn
- Credit scorecard model
- Large language model (LLM)

### Sample notebooks 

Each interactive notebook includes the sample code needed to automatically document a model: 

Notebook | Inventory model |
----------|-----------------|
| **[Quickstart for model documentation](https://jupyterhub.validmind.ai/hub/user-redirect/lab/tree/quickstart_customer_churn_full_suite.ipynb)**<br>Gets you started with the basic process of documenting models with ValidMind, from the developer framework to the Platform UI. | Customer Churn Model Documentation — Full Suite
| **[Prompt validation for large language models (LLMs)](https://jupyterhub.validmind.ai/hub/user-redirect/lab/tree/nlp_and_llm/foundation_models_integration_demo.ipynb)**<br>Run and document prompt validation tests for a large language model (LLM) specialized in sentiment analysis for financial news. | Foundation Model - Text Sentiment Analysis
| **[Credit score card demo](https://jupyterhub.validmind.ai/hub/user-redirect/lab/tree/credit_risk/application_scorecard_demo.ipynb)**<br>Guides you through building and documenting an application scorecard model using the Lending Club sample dataset from Kaggle. | Credit Risk Model
<!--- | Yes<br> | N/A | Credit Risk Model --->

## Getting started

What you try out first in the sandbox depends on your interests: 

::: {.grid}

::: {.g-col-6}

### Automated model testing & documentation 

- Explore the sample notebooks
- Run tests and test suites
- Generate model documentation

<form method="get" action="https://jupyterhub.validmind.ai/" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">ValidMind Jupyter Hub</button>
</form>

<!---Also try out our cloud-based Platform UI to get your model documentation ready for validation.--->
:::

::: {.g-col-6}

### Model risk management & governance

- Explore the validation report experience
- Assess compliance and link evidence
- View reports to identify risk areas

<form method="get" action="https://app.prod.validmind.ai/" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">ValidMind Platform UI</button>
</form>

<!---Also collaborate with model developers, edit draft validation reports, and view workflows.--->
:::

:::

## Provide feedback or get help
 
### Join our Slack community

Have feedback or questions? We sponsor a Slack community where you can provide feedback or ask questions: [Join Our Community Slack](https://docs.validmind.ai/guide/join-community.html).

There is a dedicated channel for support: [#community-support](https://validmind.slack.com/archives/C05FUFY9C4S). 

Our growing Slack community is not just for our products but also aims to foster discussions between AI risk practitioners and those involved in model risk management (MRM). Feel free to take a look around the other channels that are available and stay a while. 

### Get support 

To get help from a human, send an email to <support@validmind.ai>.

## Related topics 

- [Get started with the ValidMind Developer Framework](get-started-developer-framework.qmd)
- [Working with model documentation](working-with-model-documentation.qmd)
- [Preparing validation reports](preparing-validation-reports.qmd)