---
title: "Glossary"
keywords: "glossary, model risk management, ValidMind"
---

This glossary of terms provides short definitions for technical terms you find commonly used in our product documetnation grouped by terms related to:

- [The ValidMind platform](#validmind-platform)
- [Developer tools](#developer-tools)
- [AI and model risk management](#ai-and-model-risk-management)

## ValidMind platform

automation, documentation automation
: A key feature and core benefit of the ValidMind platform that allows for the automatic creation of model documentation using predefined templates and test plans.

client library, Python client library
: Enables the interaction of your development environment with the ValidMind platform as part of the Developer Framework.

model inventory <span id="platform-model-inventory">
: A feature in the ValidMind platform where you can track, manage, and oversee the lifecycle of models. Provides the features required by model risk management inventories that cover the full model lifecycle, including customizable documentation and approval workflows for different user roles, status and activity tracking, and periodic revalidation.

project, documentation project
: Acts as a container for the model documentation and validation report of your model into which all documentation work in ValidMind is organized. Enables developers and validators to collaborate on model documentation review, status tracking, and generating validation reports. Each stage of a model’s lifecycle constitutes a new project is  configurable with its own templates and workflows.

template, documentation template
: Functions as a test suite and lays out the structure of model documentation, segmented into various sections and sub-sections. ValidMind templates come with pre-defined sections, similar to test placeholders, including boilerplates and spaces designated for documentation and test results. When rendered, produces a document that model developers can use for model validation. A template is represented as a YAML file.

ValidMind Developer Framework <span id="developer-framework">
: Provides a suite of documentation tools and test plans, from documenting descriptions of your dataset to testing your models for weak spots and overfit areas. The Developer Framework helps you automate the generation of model documentation by feeding the ValidMind platform with documentation artifacts and test results to the ValidMind platform. For specific functionality, such as model testing functions or automating documentation, check [ValidMind Developer Framework](https://docs.validmind.ai/validmind/validmind.html)

ValidMind Platform UI <span id="platform">
: ValidMind's hosted multi-tenant architecture that includes the cloud-based web interface, APIs, databases, documentation and validation engine, and various internal services. Also see [Developer Framework](#developer-framework).

## Developer tools

pip
: A package manager for Python, used to install and manage software packages written in the Python programming language. An acronym for "Pip Installs Packages" or "Preferred Installer Program." Used to install the Python client library that is part of the ValidMind Developer Framework so that model developers can make use of its features.

JupyterHub
: A multi-user server that manages and proxies multiple instances of the single-user Jupyter notebook server. JupyterHub provides a platform for users to interactively work with data science and scientific computing tools in a collaborative environment. ValidMind uses JupyterHub to share live code, how-to instructions, and visualizations via notebooks as part of our getting started experience for new users.

Jupyter notebook
: Allows users to create and share documents containing live code, data visualizations, and narrative text. Jupyter notebooks support various programming languages, most notably Python, and are widely used for data analysis, machine learning, scientific research, and educational purposes. ValidMind uses notebooks to share sample code and how-to instructions for our Developer Framework.

GitHub
: A cloud-based platform that provides hosting for software development and version control using Git. GitHub offers collaboration tools such as bug tracking, feature requests, task management, and continuous integration pipelines. ValidMind uses GitHub to share the code base for our open-source software.

## AI and model risk management

1st line of defense
: Consists of business units responsible for model development, validation, and implementation. They ensure that models are accurate, robust, and fit for purpose. As the 1st line of defense against model risk, model developers have a strong incentive and obligation to document and test the models they build, especially when they are subject to regulations.

2nd line of defense
: An independent model risk oversight function that provides a governance framework and guidance for model risk management. As the 2nd line of defense, model validators must independently validate models and ensure that model risk management principles are implemented at all stages of the model lifecycle.

model developer
: Responsible for developing, implementing, and maintaining risk models. Model developers are typically subject matter experts in their domain and are responsible for ensuring that the model is fit-for-purpose, accurate, and aligned with the business requirements. Model developers collaborate with model validators and business units to ensure that models are conceptually sound, robust, and fit for their intended purpose, ultimately contributing to effective Model Risk Management and reliable decision-making.

model documentation
: Provides a comprehensive record and description of a quantitative model. This documentation should encompass all relevant information about the model in accordance with regulatory requirements, model risk policies, assumptions, methodologies, data and inputs, model performance, evaluation, limitations, and intended use.

model inventory
: A comprehensive documentation of all models used by an organization, their purpose, and their associated risks, essential for effective model lifecycle management. Also check the [ValidMind model inventory](#platform-model-inventory)

model risk management (MRM)
: The process of identifying, assessing, and controlling risks associated with models used in financial institutions. Governance and risk management functions oversee the MRM process and ensure compliance with policies.

model risk
: The potential for financial loss, incorrect decisions, or unintended consequences resulting from errors or inaccuracies in AI/ML models. Model risk typically arises from incorrect or inappropriate use of models, inaccurate assumptions, or limitations in data quality. Consequences of unmitigated model risk can include financial losses, reputational damage, and regulatory penalties, among others. Effective model risk management is essential to minimizing these risks.

model governance
: The policies, procedures, and controls put in place by financial institutions to manage and monitor the use of models.

model validation
: The process of evaluating and testing models to ensure that they are accurate, reliable, and effective with the help of our platform.

model validator
: Responsible for the independent evaluation of a model's conceptual soundness, performance, and compliance with regulatory requirements. Their role is to ensure the model's assumptions, methodologies, and data quality are appropriate, and that the model is fit for its intended use. Model validators collaborate with business units and model developers to identify and address potential issues, ultimately helping to minimize model risk and enhance the reliability of model-driven decisions.

three lines of defense
: A structured approach to model risk management, consisting of three independent functions. The first line consists of business units responsible for model development, validation, and implementation. They ensure that models are accurate, robust, and fit for purpose. The second line is an independent model risk oversight function that provides a governance framework and guidance for model risk management. The third line is the internal or external audit function, which assesses the effectiveness of MRM practices and controls.

validation report
: A comprehensive document that evaluates the performance, accuracy, and reliability of a financial or computational model. It provides detailed findings from the validation process, which aims to ensure that the model is functioning as intended, is fit for its purpose, and meets regulatory and organizational standards.
