---
title: "Guides"
keywords: "guides, how-to, ai risk, model risk management, ValidMind"
date: last-modified
listing:
  - id: guide-platform-administrators-setup
    type: grid
    max-description-length: 500
    sort: false
    fields: [title, description]
    contents:
    - manage-users-and-roles.qmd
    - configure-workflows.qmd
    - configure-documentation-project-templates.qmd
    - configure-aws-privatelink.qmd
  - id: guide-model-developers-get-started
    type: grid
    max-description-length: 500
    sort: false
    fields: [title, description]
    contents: 
    - register-models-in-model-inventory.qmd
    - create-documentation-project.qmd
  - id: guide-documentation-project-templates
    contents: 
    - view-documentation-guidelines.qmd
    - work-with-content-blocks.qmd
    - collaborate-on-documentation-projects.qmd
    type: grid
    max-description-length: 500
    sort: false
    fields: [title, description]
  - id: guide-model-validators
    contents: 
    - work-with-validation-reports.qmd
    - ../guide/*valida*
    - collaborate-on-documentation-projects.qmd
    - add-documentation-project-findings.qmd
    type: grid
    max-description-length: 500
    sort: false
    fields: [title, description]
---

<!--- 
listing:
  - id: guide-documentation-project-templates
    contents: "../guide/*documentation-project-templates**"
    type: grid
    max-description-length: 250
    fields: [title, description]
  - id: model-validation
    type: grid
    contents: "../tests/model_validation/**"
    max-description-length: 250
    fields: [title, description]
  - id: guide-documentation-projects
    contents: "../tests/prompt_validation/**"
    type: grid
    max-description-length: 250
    fields: [title, description]  
--->

Whether you're new to ValidMind or an experienced user, our guides provide how-to instructions for tasks that you perform in the [Platform UI](https://app.prod.validmind.ai/). 

To make it easier to find the right guide, the most common tasks are categorized by user role:

- [Platform administrators](#platform-administrators)
- [Model developers](#model-developers)
- [Model validators](#model-validators)

::: {.callout-tip}
This section primarily covers tasks you perform in the Platform UI. To get started with documenting models in your own development environment, refer to the [Developer Framework](get-started-developer-framework.qmd) section.
:::

## Platform administrators

Tasks for platform administrators typically involve configuring ValidMind for use by other members of your organization, both for the initial setup and for ongoing platform administration. 

<!---
FUTURE: 

- User management: Learn how to manage users, user groups, and roles & permissions with role-based access control (RBAC).
- Workflow configuration: Learn how to set up 
--->

:::{#guide-platform-administrators-setup}
:::


## Model developers 


Guides to get you started:

:::{#guide-model-developers-get-started}
:::


Already have a documentation project on the go?  

:::{#guide-documentation-project-templates}
:::

:::{#guide-documentation-projects}
:::



## Model validators

:::{#guide-validation-reports}
:::
