---
title: "Guides"
date: last-modified
aliases:
  - solutions.html
listing:
  - id: guides-login
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - access/accessing-validmind.qmd
  - id: guides-configuration
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - configuration/managing-your-organization.qmd
    - configuration/managing-users.qmd
  - id: guides-customize
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - configuration/personalize-validmind.qmd
    - configuration/manage-platform-notifications.qmd
  - id: guides-model-workflows
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - model-workflows/setting-up-workflows.qmd
    - model-workflows/working-with-model-workflows.qmd
  - id: guides-model-inventory
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents: 
    - model-inventory/working-with-model-inventory.qmd
    - model-inventory/managing-model-inventory.qmd
    - model-inventory/view-model-activity.qmd
  - id: guides-model-documentation
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents: 
    - model-documentation/working-with-model-documentation.qmd
  - id: guides-templates
    type: grid
    max-description-length: 250
    sort: false
    contents: 
    - templates/working-with-model-documents.qmd
    - templates/working-with-document-templates.qmd
    - templates/manage-text-block-library.qmd
    fields: [title, description]
  - id: guides-docs-templates
    type: grid
    max-description-length: 250
    sort: false
    contents: 
    - templates/working-with-document-templates.qmd
    - templates/manage-text-block-library.qmd
    fields: [title, description]
  - id: guides-developer
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents: 
    - ../developer/validmind-library.qmd
    - ../developer/samples-jupyter-notebooks.qmd
  - id: guides-validator
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents: 
    - model-validation/managing-model-validation.qmd
    - templates/working-with-document-templates.qmd
    - templates/manage-text-block-library.qmd
  - id: guides-model-validation
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents: 
    - model-validation/preparing-validation-reports.qmd
    - model-validation/working-with-model-findings.qmd
  - id: guides-reports
    contents: 
    - reporting/working-with-analytics.qmd
    - reporting/generating-exports.qmd
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
  - id: guides-monitoring-templates
    type: grid
    max-description-length: 250
    sort: false
    contents: 
    - templates/working-with-document-templates.qmd
    - templates/manage-text-block-library.qmd
    fields: [title, description]
  - id: guides-monitoring
    contents:
    - monitoring/ongoing-monitoring.qmd
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
  - id: guides-attestation
    contents:
    - attestation/working-with-attestations.qmd
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
---

Our guides offer step-by-step instructions for frequent tasks you perform within the {{< var validmind.platform >}}, organized by category.

::: {.callout-important collapse="true" appearance="minimal"}
## {{< fa building-columns >}} Key {{< var vm.product >}} concepts

{{< include /about/glossary/key_concepts/_key-concepts.qmd >}}

:::

## Access

Before you begin, let's make sure you're able to access {{< var vm.product >}}:

:::{#guides-login}
:::

## Configuration

Onboard your organization, teams or business units, and users onto the {{< var validmind.platform >}}:

:::{#guides-configuration}
:::

Then, customize your model document types, templates, and reusable blocks:

:::{#guides-templates}
:::

Further customize your personal user experience within the {{< var validmind.platform >}}:

:::{#guides-customize}
:::

## Model workflows

Use workflows within the {{< var vm.platform >}} to match your organizational needs for overseeing the review and approval of models throughout the model lifecycle:

:::{#guides-model-workflows}
:::

## Model inventory 

Use the {{< var validmind.platform >}} model inventory to thoroughly track your models and audit activity:

:::{#guides-model-inventory}
:::

## Model documentation

First, customize your model documentation templates and reusable blocks:

:::{#guides-docs-templates}
:::

Then, document and test your models in your own model development environment with the {{< var validmind.developer >}}:

:::{#guides-developer}
:::

Finally, refine your model documentation, and collaborate with model validators all within the {{< var validmind.platform >}}:

:::{#guides-model-documentation}
:::

## Model validation

First, set up your organization for validation, and customize reusable report templates and blocks:

:::{#guides-validator}
:::

Then, prepare validation reports, work with findings and evidence, and collaborate with model developers within the {{< var validmind.platform >}}:

:::{#guides-model-validation}
:::

## Reporting

Review analytics or export your documents, model inventoru, and findings for external records:

:::{#guides-reports}
:::

## Monitoring

First, customize your ongoing report templates and reusable blocks:

:::{#guides-monitoring-templates}
:::


Then, regularly evaluate the ongoing accuracy, robustness, and stability of a model after it has been deployed:

:::{#guides-monitoring}
:::

## Attestation

Document and certify model attributes at specific points in time, supporting compliance and governance processes:

:::{#guides-attestation}
:::
