---
title: "Manage model inventory custom fields"
date: last-modified
---

Create and edit custom fields that will appear in all models in the model inventory 

## Prerequisites

* You hold the **Customer Admin** role.

## Steps

1. [Log in to the ValidMind UI]({{< var vm_url >}}).

2. Click **Settings** on the left sidebar.

3. Click **Custom Fields** under **Workspace Settings**. Here you can edit existing custom fields, or add a new one.

4. To add a new field, click **+ Add new field**. To edit an existing field, select **Edit** under the **Actions** column for the desired field.

5. Fill in the fields as desired. If you want to create a template using rich text formatting, select **Long text** under **Type**

6. Then, toggle **Enable rich text formatting**

7. Create a template using the rich text editor. It will appear in all models in the Model Inventory.

8. Within a model, you can [edit fields](edit-model-inventory-fields.qmd) to fill out the template you created.


## What's next

- [Register models in the inventory](register-models-in-model-inventory.qmd)
- [Edit model inventory fields](edit-model-inventory-fields.qmd)
- [Generate documentation for your model](generate-model-documentation.qmd)
