---
title: "Example notebooks"
keywords: "Jupyter, notebooks, model risk management, ValidMind"
---

Our example notebooks are designed to showcase the capabilities and features of the Developer Framework and ValidMind Platform, while also providing you with useful examples that you can build on and adapt for your own use cases. 

After you check out the Jupyter notebooks in this section, you can try the notebook source yourself:

* Learn how to use dataset and model documentation function on a simple Customer Churn model: View page | Run on Colab
* Dive deeper into ValidMind's data validation function with an advanced Time Series Forecasting model: View page | Run on Colab
* Dive deeper into ValidMind's model evaluation function with an advanced Time Series Forecasting model: View page | Run on Colab
* Get detailed information about all test plans and tests available: View Page

   [Find the source on Google Colaboratory (Colab)](https://colab.research.google.com/)

Google Colaboratory (Colab) is a free Jupyter notebook environment that runs in the cloud. There, you can work with our Jupyter notebooks, write and execute code, share your work to collaborate in real-time, and export our notebooks to try them out locally in your own developer environment.

## Related topics

For an introductory example, take a look at the Jupyter notebook in the [Quickstart](try-developer-framework.qmd).
