---
title: "Manage users"
---

Managing users is fundamental to maintaining access control and efficient user management in the ValidMind system. This task topic will guide you through the process of inviting new users, assigning them to specific groups, and configuring their roles and permissions. Whether you're a group administrator or a superuser, understanding these steps is crucial for ensuring the right individuals have the appropriate access and permissions within the system.

## Viewing your account profile

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).
quart

2. Go to **Settings** in the sidebar and select **Profile**.

3. You can find the following on your profile page.
   - Profile details 
   - Roles attached to your account
   - Groups assigned to your account
   - Values for API Key and Secret Key

## Prerequisites

To perform these next steps, you must be a group administrator or a superuser.

## User invitations

### Invite new users

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. Click **Settings**. 

   a. Navigate to **User Permissions** in the sidebar. 
   b. Click **Invite New Users**.
   c. Enter the user's email address.
   d. Assign the user to a group from the **Group** dropdown menu.
   e. Add roles to the user by clicking the {{< fa circle-plus >}} icon and selecting the appropriate roles from the list.
   f. Click **Assign Roles to invitee**.
   
   Users now will have the option to accept the invitation through the email they receive.

### Monitor user invitations

1. Monitor the status of invitations in the **Invites** section. Look for **Pending** status for users who haven’t accepted their invites yet.

2. Confirm that the new user is successfully added and that their group and roles are correctly configured to meet your access control requirements.

3. Review the history of previously accepted invitations in the **Invite History** section.

## User roles

### Assign new roles to a user

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. Click **Settings**. 

3. Under **User Permissions** in the sidebar, select **User Directory**. 

4. Use one of these methods to assign roles to users:
   - Select the checkbox next to one or more users and click **Assign New Role** or **Assign New Role to _n_ Users**; OR
   - Next to any individual user, click the {{< fa circle-plus >}} icon. 

5. On the pop-up that appears, select the roles to be assigned and click **Assign Roles to User**.

### Remove roles from a user

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. Click **Settings**. 

3. Under **User Permissions** in the sidebar, select **User Directory**. 

4. Click the {{< fa xmark >}} in the pill next to the role for the user that you want to remove.

## User groups

### View group members

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. Click **Settings**. 

3. Under **User Permissions** in the sidebar, select **Groups**. 

4. Expand **See Details** to:
   - view the complete list of members in any group
   - scroll further down to view the list of models visible to this group


## Add or remove group members

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. Click **Settings**. 

3. Under **User Permissions** in the sidebar, select **Groups**. 

4. To add a member to a group:

   a. Click **See Details**.
   b. Click {{< fa circle-plus >}} **Add New Member**.
   c. Select members by checking the boxes next to their names in the pop-up.
   d. Click {{< fa circle-plus >}} **Add to Group**.

5. To remove a member from a group:

   a. Click **See Details**.
   b. Select members by checking the boxes next to their names.
   c. Click **Remove Member**.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]

## What's next

[Summarize the task and provide any next steps or resources for the user to continue their learning or work.]
--->
