---
title: "Model evaluation tests"
keywords: "model evaluation tests, model risk management, ValidMind"
---

This article provides an examples of how to run model evaluation test plans, and provides a reference to other model evaluation tests and test plans available in the Developer Framework. 

## Prerequisites:

* The model is already [registered in the model inventory](register-models.qmd)
* There is an active documentation project for the model
* You have already located the project identifier, API key and secret
* You have already installed the ValidMind client library in your developer environment
* You are logged into the ValidMind Platform

## Examples

Please refer to the following notebooks for examples of how to run model evaluation test plans: 
* Binary Classifier model example: ***Customer Churn notebook example***
* Time Series Forecasting model example: ***Time Series Data Validation*** 

## List of all model evaluation test plans and tests: 

***need a list referring to the API Reference pages***

## Related Topics

Provide links or references to related topics that users might find useful or interesting. These could be other articles, resources, or tools related to the main topic.
