---
title: "Next steps"
date: last-modified
---

Ready to use ValidMind for production with your own use cases? Our documentation includes how-to instructions for the following user roles:

- [**For platform administrators**](guides.qmd) — Learn how to configure the platform, from setting up connectivity via AWS PrivateLink, to customizing the ValidMind Platform to suit your existing workflows, and more. 

- [**For model developers**](get-started-developer-framework.qmd) — Find information for ValidMind tests and test suites, additional Jupyter notebooks, and the ValidMind Developer Framework reference.

   We have more [code samples](samples-jupyter-notebooks.qmd) available that you can download and try out yourself.

   Also check the [**Guides**](guides.qmd) for how to integrate the Developer Framework in your own environment, add documentation, and collaborate with model validators.

- [**For model validators**](guides.qmd) — Learn how to step through the approval process after review and generate validation reports as you collaborate with model developers.

   [Collaborate on documentation projects](collaborate-on-documentation-projects.qmd)

### Have more questions?

We curate several lists of frequently asked questions (FAQs) that might be of help: 

- [Model registration, configuration, and customization](faq-models.qmd)
- [Model inventory, tracking, and reporting](faq-inventory.qmd)
- [Documentation and templates](faq-documentation.qmd)
- [Workflows and collaboration](faq-workflows.qmd)
- [Testing and thresholds](faq-testing.qmd)
- [Integrations and support](faq-integrations.qmd)
- [Data handling and privacy](faq-privacy.qmd)

Don't see what you are looking for? Email [support@validmind.com](mailto:support@validmind.com) to get help from a human.

### Need help?

If you would like help from a human, check our [Support](support.qmd) page. You can also send us your feedback on product features or our documentation.
