---
title: "ValidMind Overview"
keywords: "overview, platform, developer framework, SaaS, model risk management, ValidMind"
---

The ValidMind platform is a suite of tools helping model developers and model validators automatically document, validate, and make sure models perform and deliver on expected commercial and regulatory outcomes.

ValidMind is designed to be platform-independent, seamlessly integrating into existing model development workflows without causing disruptions. The platform is also easy to use, with an intuitive interface that allows users to view, edit, and manage their model documentation with ease. 

ValidMind is a cloud-based and flexible platform that enables organizations to conduct their model documentation and model validation activities more efficiently. The platform is designed to be easy to integrate, configure, and scale according to the organization's requirements. It includes automated documentation and testing capabilities, making it easier for model developers to generate model documentation and identify potential areas of risks in their models. 

The platform promotes more efficient collaboration and communication between 1st and 2nd line teams, enabling model developers to easily capture and incorporate feedback from model validation teams to ensure more effective model documentation and validation activities.

## Components
The ValidMind platform contains two major architectural components - the Developer Framework and the Software-as-a-Service (SaaS)-based platform.

### Developer framework
ValidMind’s Developer Framework is collection of standalone libraries (Python, R) that customers set up into their existing development environment. The Developer Framework requires access to the data sources where datasets (training, test, and other applicable datasets) and trained model files are stored to run model documentation and validation tests, and to ValidMind’s SaaS-based platform to populate the model documentation and validation report.

Our Developer Framework automatically generates documentation for algorithmic models and proactively identifies potential risks for both traditional and machine-learning models, thus enabling effective model validation according to compliance and regulatory requirements, while saving teams hundreds of hours of work writing documents today.

### SaaS-based platform

The SaaS-based platform implements a multi-tenant architecture to host its SaaS-based components (application, APIs, databases, and other internal services). Connection to ValidMind’s SaaS-based platform is done via AWS PrivateLink/Azure Private Link. This network configuration allows customers to consume the ValidMind API services and access ValidMind’s SaaS-based application as if they were local services to their network. 

AWS PrivateLink/Azure Private Link provides private connectivity between ValidMind and your on-premises networks without exposing your traffic to the public Internet. Additionally, ValidMind only collects metadata used to generate documentation and present test results for the model developer and validation teams.

<!--
## Related Topics

Provide links or references to related topics that users might find useful or interesting. These could be other articles, resources, or tools related to the main topic.

ValidMind is a cloud-based and flexible platform that enables organizations to conduct their model documentation and model validation activities more efficiently. The platform is designed to be easy to integrate, configure, and scale according to the organization's requirements. It includes automated documentation and testing capabilities, making it easier for model developers to generate model documentation and identify potential areas of risks in their models. 
-->