---
title: "Preparing validation reports"
date: last-modified
listing:
  - id: validation-reports-listing
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - view-validation-guidelines.qmd
      - assess-compliance.qmd
      - work-with-content-blocks.qmd
      - collaborate-with-others.qmd
      - submit-for-approval.qmd
---

As part of preparing validation reports, you can view the guidelines, collaborate with model developers, add or edit content to your draft validation report, link to evidence, or work with project findings.

## Prerequisites

- You hold the `Validator` role 
- The model you are documenting is registered in the model inventory
- A model developer has marked their model documentation as **Ready for Validation**

## Key concepts

A validation report is a comprehensive review that evaluates a model's accuracy, performance, and suitability for its intended purpose. It encompasses the process of model risk assessment, identifying areas of potential error or risk within the model's components, such as data inputs and algorithms. The report follows established validation guidelines to ensure consistency and adherence to internal and regulatory standards. 

::: {.grid}

::: {.g-col-6}
Model risk assessment
: The process of identifying and evaluating risks associated with the use and potential errors in a financial model.

Model risk areas
: Specific components or aspects of a model where risk might be present, such as data inputs, algorithms, or implementation.

Validation guidelines
: Established standards or procedures for conducting thorough and consistent model validations, usually aligned with principles within specific model or AI risk frameworks.

Findings
: Observations or issues identified during model validation, including any deviations from expected performance or standards.
:::

::: {.g-col-6}
Actions
: Recommended steps or measures to address findings from model validation or risk assessments.

Evidence
: Material provided by the developer and reviewed by the validator, such as model documentation, source code, datasets, monitoring reports or previous validation reports.

Ongoing Monitoring Report
: A periodic report assessing the model's performance and compliance over time, ensuring it remains valid under changing conditions.
:::

:::

## Get started

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. In the left sidebar, click [**Model Inventory**](https://app.prod.validmind.ai/model-inventory).

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Validation Report**.

   You can now jump to any section of the validation report by expanding the table of contents on the left and selecting the relevant section you would like to view.

5. In any section of the documentation, hover over text content and click the {{< fa edit >}} edit icon that appears on the right of the textbox. 

     You can now use the text editor functions to edit the content of the section. Whenever you make a change, an activity log entry is recorded under **Section activity** on the page, just below the section you are editing. 

6. Save your edits:

   a. Clicking on the {{< fa clock-rotate-left >}} icon in the editor toolbar.
   b. Select **Save current revision** and enter a name.
   c. Click {{< fa check >}} to save the revision.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

:::{#validation-reports-listing}
:::

