---
title: "Quickstarts"
keywords: "get started, model risk management, ValidMind"
---

The easiest way to get started with ValidMind is to try out our Developer Framework in Jupyter Hub and to explore the ValidMind Platform UI online. 

## Before you begin

::: {.callout-tip}
## Don't have access?
[Request a trial](https://validmind.com/demo) to try out ValidMind for free. 
:::

To try out ValidMind, you need to be a registered user on the ValidMind Platform.

To connect the ValidMind Developer Framework to the ValidMind Platform and to access the web user interface, you must be able to access our domains:

- validmind.ai
- validmind.com

If necessary, ask a network administrator to add these domains to your firewall allowlist (whitelist). 

If your company has strict security requirements and requires you to connect via VPN or AWS PrivateLink, please contact your IT/InfoSec team. For additional help setting up a VPN or PrivateLink with ValidMind's MRM platform please visit [configure AWS PrivateLink](configure-aws-privatelink.qmd) or send an email to <support@validmind.ai>.

### Quickstart requirements

To follow the Quickstart, you need access to ONE of the following:

- [Jupyter Hub](try-developer-framework-with-jupyter.qmd) (recommended)
- [Google Colaboratory (Colab)](try-developer-framework-with-colab.qmd)
- [Docker Desktop](try-developer-framework-with-docker.qmd)

To run our sample Jupyter notebooks locally, your developer environment must support Python 3.8+.

<!--- If you download the sample notebooks from Colab, [sample Jupyter notebooks](jupyter-notebooks.qmd), for use To use ourlocally requires Python 3.8+.  ---> 

### Access to the ValidMind Platform UI

You need to be able to access our ValidMind Web UI from a modern browser such as Microsoft Edge, Google Chrome, Apple Safari, or Mozilla Firefox.

## Steps

1. [Try the Developer Framework](try-developer-framework-with-jupyter.qmd) (10 minutes)

   Try our introductory Jupyter notebook to see the Developer Framework in action. 

2. [Explore the Platform UI](create-your-first-documentation-project.qmd) (15 minutes)

    Explore our Platform UI to work with a documentation project and see the results of tests you run.

## Next Steps

Ready to use ValidMind for production with your own use cases? Our documentation includes how-to instructions for the following user roles:

- [**For platform administrators**](guide.qmd) — Learn how to configure the platform, from setting up connectivity via AWS PrivateLink, to customizing the ValidMind Platform to suit your exisiting workflows, and more. 

- [**For model developers**](developer-framework.qmd) — Find information for ValidMind test plans and tests, additional Jupyter notebooks, and the ValidMind Developer Framework reference.

   Also check the [**Guides**](guide.qmd) for how you integrate the Developer Framework in your own environment, add documentation, and collaborate with model validators.

- [**For model validators**](guide.qmd) — Learn how to step through the approval process after review and generate validation reports as you collaborate with model developers.

### Have more questions?

We curate several lists of frequently asked questions (FAQs) that might be of help: 

- [Model registration, configuration, and customization](faq-models.qmd)
- [Model inventory, tracking, and reporting](faq-inventory.qmd)
- [Documentation and templates](faq-documentation.qmd)
- [Workflows and collaboration](faq-workflows.qmd)
- [Testing and thresholds](faq-testing.qmd)
- [Integrations and support](faq-integrations.qmd)
- [Data handling and privacy](faq-privacy.qmd)

Don't see what you are looking for? Email [support@validmind.com](mailto:support@validmind.com) to get help from a human.

### Need help?

If you would like help from a human, check our [Support](support.qmd) page. You can also send us your feedback on product features or our documentation.

### Related topics

- [Additional Jupyter notebooks](jupyter-notebooks.qmd) 
- [Introduction to the ValidMind Developer Framework](developer-framework-introduction.qmd)
- [Review and comment on documentation projects](review-documentation-project.qmd)
