---
title: "Register models in the Inventory"
keywords: "register models, model inventory, model risk management, ValidMind"
---

This topic addresses how to register a model you are documenting in the model inventory. It is relevant for Model Owners who want to enbale their model development teams to use ValidMind's model documentation and validation features.  

## Prerequisites

* You are a registered user on the ValidMind Platform
* You are logged into the ValidMind Platform

## Steps

1. Navigate to the Model Inventory page on the left sidebar. **Need screenshot**
   
2. In the **Model Inventory** page, click on "Register new Model" 
   
3. Fill in the required information in the new model registration form
   - Provide a Model Name
   - Select the relevant Business Unit
   - Select the relevant Model Methodology being used**
   - Select the relevant Model Use Case**
   - Provide a Purpose statement to explain what the model will be used for**
   - Select the Preliminary Risk Tier for the model

**Screenshot**
   
4. Click "Register New Model" to create a new entry in the Model Inventory
   - You can now access the model details page from the Model Inventory

## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]

## What's Next

* Edit Model details in the Inventory
* Create a new documentation project
