---
title: "Register your first model"
date: last-modified
---

Let's learn how to upload tests and documentation with the Quickstart notebook you looked at earlier.

## Steps

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. In the left sidebar, navigate to **Model Inventory** and click **+ Register new model**.

3. Enter the model details and click **Continue**.

   To register a model for use with the Quickstart notebook, select:
   
   - Documentation template: `Binary classification`
   - Use case: `Marketing/Sales - Attrition/Churn Management`

   You can fill in other options according to your preference. 
   
   After the model is registered, you get initial draft of model documentation and validation report based on the documentation template. 

4. In the left sidebar, go to **Getting Started**.

   The page that opens provides you with a _code snippet_ to use with the ValidMind Developer Framework.

   - `api_host`: The location of the ValidMind API
   - `api_key`: The account API key
   - `api_secret`: The account secret key
   - `project`: The project identifier

   The code snippet can be copied and pasted directly into your developer source code to integrate the ValidMind Developer Framework and to be able to upload to the ValidMind Platform. 
   
   To follow best practices, you can also [store the credentials in a `.env` file](store-credentials-in-env-file.qmd) and pass them in via environment variables.

::: {.callout-tip}
### Missing the API_SECRET?
Use the  {{< fa copy >}} **icon** to copy the `API_SECRET` to your clipboard.
:::

## What's next

Continue with [Generate documentation for your model](generate-documentation-for-your-model.qmd) to learn about how you can use the ValidMind Platform for your projects.