---
title: "Register models in the inventory"
date: last-modified
---

To be able to document models using ValidMind's model documentation and validation features, you need to register them in the model inventory first.

## Prerequisites

* You are the model owner
* You hold the `Developer` role 

## Steps

1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

2. Click **Model Inventory** in the left sidebar. 
<!--- **Need screenshot** --->
   
3. Click **Register new model**.
   
4. Fill in the required information on the registration form:

   - Provide a model name
   - Select the relevant business unit
   - Select the relevant model methodology being used
   - Select the relevant model use case
   - Provide a purpose statement to explain what the model will be used for
   - Select the preliminary risk tier for the model
   - If the model is a vendor model, toggle **Is Vendor Model** and provide the vendor name.

<!--- TO DO **Screenshot** --->
   
5. Click **Register new model** to create a new entry in the model inventory.

   You can now access the model details from the **Model Inventory** page.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

* [Edit model inventory fields](customize-model-inventory-fields.qmd)
* [Generate documentation for your model](quickstart-generate-documentation-for-your-model.qmd)
