---
title: "July 24, 2023"
keywords: "release notes, model risk management, ValidMind"
---

## Release highlights

This release introduces several significant enhancements to the ValidMind Developer Framework, expanding support for additional use cases and enhancing the developer experience. Moreover, we've upgraded our Platform UI with pivotal new features, including an all-new text editor, the capability to insert new content blocks into documentation projects, template swapping for keeping your documentation projects current, and much more.

### ValidMind Developer Framework (v1.16.0)

- **Support for Credit Risk Scorecard and Probability of Default use cases**. We've enhanced our Developer Framework to be more versatile than ever, so you can now document and validate more model use cases. To demonstrate how you can use ValidMind with these new use cases, we're providing two new interactive Jupyter notebooks for a hands-on experience. Try them:
    
    - [Credit Risk Scorecard Demo](../notebooks/probability_of_default/credit_risk_scorecard_demo.ipynb)
    - [Probability of Default Model](../notebooks/probability_of_default/probability_of_default_validmind.ipynb)

- **Updated notebook for NLP use case**. Now with enhanced performance by using CatBoost compared to the original PyTorch-based notebook, this updated notebook showcases natural language processing (NLP) data analysis and text classification using the ValidMind Developer Framework with emphasis on the in-depth analysis and preprocessing of COVID-19 tweets. [Try it ...](../notebooks/nlp/nlp_sentiment_analysis_catboost_demo.ipynb)

- **Improved developer experience when you encounter error conditions**. Unhandled errors now return an error code with a more descriptive message that can help you with looking them up in the troubleshooting section of our documentation. We also improved error handling when tests fail to run and the test results summary widget now display error information for each test that fails to run. 

### ValidMind Platform UI (v1.4.1)

- **Improved, Word-like text editor**. When collaborating on documentation projects in the Platform UI with others, you now have an improved text editor at your disposal. The look and feel should be familiar if you previously used Microsoft Word to manage model documentation and validation reports. In addition to the new editing features, you can user the editor to participate in comment threads, track changes, see the revision history, enter math formulas, and more. [Try it ...](collaborate-on-documentation-projects.qmd)

<!--- TO DO screen shot --->

- **Add new content blocks to documentation projects**. For model developers and model validators who want to add new sections to a documentation project, you can now do just that. The new content blocks feature provide you with additional sections that you fill in with text, metrics, and test results. Supported content block types:

- _Simple text block_: Can be added anywhere on model documentation pages and edited to include additional documentation in text format.
- _Test-driven block_: Can be added to display one of the supported metrics or threshold test results collected by the Developer Framework.

You can add new content block to an existing documentation project simply by hovering over the dashed line between sections. [Try it ...](add-content-blocks.qmd) 

<!--- TO DO Need Swap template docs --->

- **Swap templates for documentation projects**. This feature is designed to enhance the flexibility of documenting models. With it, you can seamlessly update an existing documentation project by either switching to an entirely different template or by simply upgrading to a more recent version of the template currently in use. This new feature ensures that your documentation projects can remain up-to-date and align with the latest preferred template without the need to start from scratch. [Try it ...](swap-documentation-project-templates.qmd)

- **Platform UI enhancements**:
    <!-- This rename required a docs update, included in this PR -->
    - **Renamed Client Integration page to Getting Started**. To better reflect when you use the credentials for a newly created documentation project with the ValidMind Developer Framework, we have renamed the **Client Integration** page to **Getting Started**. 
    - **Improved activity widget**: We enhanced the user interface with new tabs, enabling you to filter events based on activity type.
    - **Improved Findings section and Findings Details page**: We made UI enhancements for both project findings and the findings details sections for a better look and feel.
    - **Refined Models and Projects lists** : We refined the user interface, featuring more intuitive default sorting and more user-friendly filtering.

## Documentation

To make it easier to try out our Jupyter notebooks, we now provide a download button for all notebooks used in our documentation:

<form method="get" action="../notebooks.zip">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 16px; padding: 6.25px 12.5px; margin-left: 16px; margin-bottom: 20px;">Download Notebooks</button>
</form>

 This download includes:

- Quickstart notebooks
- Use case notebooks
- Testing notebooks

## How to upgrade

To access the latest version of the [ValidMind Platform UI](http://app.prod.validmind.ai/), reload your browser tab.

To upgrade the ValidMind Developer Framework:

- [Using Jupyter Hub](try-developer-framework-with-jupyterhub.qmd): reload your browser tab and re-run the `!pip install --upgrade validmind` cell.

- [Using Docker](try-developer-framework-with-docker.qmd): pull the latest Docker image:
    
    ```jsx
    docker pull validmind/validmind-jupyter-demo:latest
    
    ```
    
- [In your own developer environment](install-and-initialize-developer-framework.qmd): restart your notebook and re-run:
    
    ```python
    !pip install validmind
    ```
