---
title: "May 30, 2023"
---

## Release highlights

### ValidMind Developer Framework (v1.13.9)

- Plots and visual outputs have been enhanced with the Plotly package. Users can now view how values change when hovering over the following plots:
    - Correlations matrix
    - Population Stability Index
    - Confusion matrices
    - ROC curve
    - PR curve
- Added support for Global test config definition. This allows you to share configuration and parameters across different tests.

### ValidMind Platform UI (v1.0.19)

- You can now export documentation projects to Word documents from the Platform UI. This feature enables you make use of model documentation or validation report files outside of the ValidMind Platform. [Learn more ...](export-documentation.qmd)

- We added a new demo model that allows you to test the ValidMind developer framework with a time-series forecasting model. [Learn more ...](samples-jupyter-notebooks.qmd)

## Bugfixes

- Fixed the display alignment in certain pages of the UI.
- Fixed display issues related to Helvetica Neue font not available for Windows users.
- Fixed an issue preventing users to drag & drop image files directly in the online editor.
- Adjusted filters for **Model Inventory** and **Documentation Projects** search boxes.

## How to upgrade

To access the latest version of the [ValidMind Platform UI](http://app.prod.validmind.ai/), refresh your browser.

To upgrade the ValidMind Developer Framework:

- [Using Docker](try-developer-framework-with-docker.qmd): pull the latest Docker image:
    
    ```jsx
    docker pull validmind/validmind-jupyter-demo:latest
    
    ```
    
- [In your own developer environment](install-and-initialize-developer-framework.qmd): restart your notebook and re-run:
    
    ```python
    !pip install validmind
    ```