---
title: "Releases"
keywords: "pilot release, model risk management, ValidMind"
---

Welcome to the {{< var version >}} for ValidMind. On this page you will find important information to help you get started.

## Get access

Want to try out this ValidMind release but don't have access? Email [info@validmind.ai](info@validmind.ai).

In order to access ValidMind from your company network, the following prerequisits apply:

- To use the Developer Framework and to access the ValidMind user interface, add the `validmind.ai` domain to your allowlist (whitelist).
- If you require VPC access from your company network to ValidMind, you can [configure AWS PrivateLink](configure-aws-privatelink.qmd).

## Access URLs

| Service    | URL                                                                  |
|------------|----------------------------------------------------------------------|
| ValidMind UI login | [https://app.dev.vm.validmind.ai/](https://app.dev.vm.validmind.ai/) |



## Users & roles

To ensure the security of our services, user names and passwords are supplied separately. If you do not already have this information, please contact [support@validmind.ai](support@validmind.ai).

ValidMind supports user roles for: 

- model developers
- model validators
- platform administrators

For the pilot, the initial roles will have been set up for you already. In the future, we will allow you to [manage users and roles](manage-users-and-roles.qmd) yourself.

## Related topics 

Ready to try out ValidMind? Take a look at the [Quickstart](get-started.qmd).