---
title: "Pilot access"
keywords: "pilot release, model risk management, ValidMind"
---

Welcome to our pilot access program for ValidMind. On this page you will find important information to help you get started.

## Access URLs

| Service    | URL                                                                  |
|------------|----------------------------------------------------------------------|
| SaaS login | [https://app.dev.vm.validmind.ai/](https://app.dev.vm.validmind.ai/) |

## Users & roles

To ensure the security of our services, user names and passwords are supplied separately. If you do not already have this information, please contact[support@validmind.ai](support@validmind.ai).

ValidMind supports user roles for: 

- model developers
- model validators
- platform administrators

To learn more, see [Manage users and roles](manageusersandroles.qmd).


## Prerequisites

In order to access ValidMind from your company network, the following prerequisits apply:

<!--- TO CHECK If this is correct --->

- To use the developer framework and to access the SaaS user interface, you must add the `validmind.ai` domain to your allowlist (whitelist).

- If you require VPC access from your company network to ValidMind, [configure AWS PrivateLink](configure-aws-privatelink.qmd).

## Related topics 

Ready to try out ValidMind? [Get started](getstarted.qmd).