---
title: "July 20, 2023"
keywords: "release notes, model risk management, ValidMind"
---

## Release highlights

This release includes a number of major enhancements to the ValidMind Developer Framework to support additional use cases and improve the developer experience when you encounter error conditions. In addition, this release includes an updated notebook to illustrate support for NLP models with CatBoost, along with a greatly improved, Word-like text editor experience when collaborating on documentation projects online.

### ValidMind Developer Framework (v1.16.0)

- **Added support for documenting and validating credit risk scorecard and PD models**. Making our Developer Framework more versatile than ever before and letting you do more with ValidMind, these use cases are available as Jupyter notebooks you can explore and adapt for production. Try it:
    
    - [Credit Risk Scorecard Demo](../notebooks/probability_of_default/credit_risk_scorecard_demo.ipynb)
    - [Probability of Default Model](../notebooks/probability_of_default/probability_of_default_validmind.ipynb)

- Added example notebooks demonstrating how to document a NLP model built with CatBoost. [Try it ...](../notebooks/nlp/nlp_sentiment_analysis_catboost_demo.ipynb)

- Unhandled errors now return an error code with a more descriptive message. Error codes can be looked up on the troubleshooting section of our documentation. We also improved handling of errors when tests fail to run. The test results summary widget now display error information for each of the tests that fails to run. 

### ValidMind Platform UI (v1.4.1)

- Upgraded text editor experience. [Try it ...](collaborate-on-documentation-projects.qmd)

- Added new "add content block" feature. [Try it ...](add-content-blocks.qmd)
    - "Add text block" feature allows adding new text boxes anywhere on model documentation pages
    - "Add test driven block" feature allows adding new content blocks to display metrics and test results collected by the developer framework

- Added new "swap template" feature that allows updating a project to a different template or a newer version of its current template

- Improved activity widget UI. Added new tabs to filter events by activity type
- Overall UI improvements to findings and finding details page
- General improvements to model and projects list UI. Better sorting by default, easier filtering UX

--->
- Renamed "Client Integration" section link to "Getting Started"
<!-- TO DO This requires a docs update -->


## How to upgrade

To access the latest version of the [ValidMind Platform UI](http://app.prod.validmind.ai/), reload your browser tab.

To upgrade the ValidMind Developer Framework:

- [Using Jupyter Hub](try-developer-framework-with-jupyterhub.qmd): reload your browser tab and re-run the `!pip install --upgrade validmind` cell.

- [Using Docker](try-developer-framework-with-docker.qmd): pull the latest Docker image:
    
    ```jsx
    docker pull validmind/validmind-jupyter-demo:latest
    
    ```
    
- [In your own developer environment](install-and-initialize-developer-framework.qmd): restart your notebook and re-run:
    
    ```python
    !pip install validmind
    ```
