---
title: "June 19, 2023"
keywords: "release notes, model risk management, ValidMind"
---

## Release highlights

### ValidMind Developer Framework (v1.2.0)

- **You can now implement custom tests using our Developer Framework.** These custom tests allow you to extend the default set of metrics provided by ValidMind and provide full flexibility for documenting any type of model or use case. Metrics and threshold tests are similar in that they both provide a way to evaluate a model. [Learn more ...](../notebooks/how_to/implementing_custom_tests.ipynb)

### ValidMind Platform UI (v1.2.0)

- **You can now edit the documentation templates that get used for model documentation or for validation reports**. This feature is relevant for administrators who need to configure templates for specific use cases or where the existing templates supplied by ValidMind need to be customized. [Learn more ...](edit-templates.qmd)

- We improved the search feature in the Platform UI to make search results more compact.

<!---
## Bugfixes

- TBD
--->

## How to upgrade

To access the latest version of the [ValidMind Platform UI](http://app.prod.validmind.ai/), refresh your browser.

<!---
To upgrade the ValidMind Developer Framework:

- [Using Docker](try-developer-framework-with-docker.qmd): pull the latest Docker image:
    
    ```jsx
    docker pull validmind/validmind-jupyter-demo:latest
    
    ```
    
- [In your own developer environment](install-and-initialize-developer-framework.qmd): restart your notebook and re-run:
    
    ```python
    !pip install validmind
    ```
--->