---
title: "June 22, 2023"
keywords: "release notes, ai risk, model risk management, ValidMind"
---

## Release highlights

This release includes a number of major enhancements to the ValidMind Developer Framework that will make it easier for users to edit templates and add custom tests that can be reused across templates. In addition, this release also includes a new notebook to illustrate support for NLP models and PyTorch, as well as the ability to edit templates directly in the Platform UI. 

### ValidMind Developer Framework (v1.15.4)

- **Implement your own custom tests.** With support for custom tests, you can now go beyond the default set of documentation and testing components provided by ValidMind, and use our Developer Framework to document any type of model or use case. [Learn more ...](../notebooks/how_to/implementing_custom_tests.ipynb)

- **Integrate external test providers**. With test providers, you can now integrate external test libraries to expand the set of tests available through the ValidMind Developer Framework, or create your own test libraries. This enables registering custom tests under a namespace to make them available globally. We provide a couple of demo scenarios with such test providers and show how you can register them with  Validmind so that they can run a template utilizing your tests. [Learn more ...](../notebooks/code_samples/custom_tests/external_test_providers_demo.ipynb)

- **Simplified documentation and testing using templates**. Templates now function as dynamic test suites, allowing you to identify all the documentation components & test results mapped to a specific template. This makes it easier to fill a pre-configured template (including boilerplates and spaces designated for documentation and test results) with a single command, instead of running multiple test suites. [Learn more ...](get-started-developer-framework.qmd)

<!--- NR Replaced original Pytorch NLP link with CatBoost link, as the original link  has issues in Quarto --->
- **New notebook to illustrate natural language processing (NLP) data analysis and text classification use case**. Learn how to use the ValidMind Framework to document and test an NLP data analysis and text classification model. The emphasis of this notebook is on documenting and testing the in-depth analysis and preprocessing of the text data, in this case, COVID-19 related tweets. [Learn more ...](../notebooks/code_samples/LLM_and_NLP/nlp_sentiment_analysis_catboost_demo.ipynb)

### ValidMind Platform UI

- **You can now edit the documentation templates that get used for model documentation or for validation reports**. This feature is relevant for administrators who need to configure templates for specific use cases, or where the existing templates supplied by ValidMind need to be customized. Editing allows to configure sections, sub-sections, and content blocks inside a template. [Learn more ...](configure-documentation-project-templates.qmd)

- We improved the search feature in the Platform UI to make search results more compact.

## Enhancements

We revised our Quickstart guide to be more modular and to highlight that our suggested starting point with the ValidMind Developer Framework is now Jupyter Hub. [Learn more ...](quickstart.qmd)

## How to upgrade

To access the latest version of the [ValidMind Platform UI](http://app.prod.validmind.ai/), reload your browser tab.

To upgrade the ValidMind Developer Framework:

- [Using Jupyter Hub](try-developer-framework-with-jupyterhub.qmd): reload your browser tab and re-run the `!pip install --upgrade validmind` cell.

- [Using Docker](try-developer-framework-with-docker.qmd): pull the latest Docker image:
    
    ```jsx
    docker pull validmind/validmind-jupyter-demo:latest
    
    ```
    
- [In your own developer environment](install-and-initialize-developer-framework.qmd): restart your notebook and re-run:
    
    ```python
    !pip install validmind
    ```
