---
title: "Review and comment on documentation projects"
keywords: "review model documentation, comment, editing, model validator, model risk management, ValidMind"
---

This topic describes how to use the ValidMind UI editor to review, edit, and comment on a documentation project. This topic is relevant for: 
* model developers who want to view and edit their model documentation on the ValidMind UI
* model validators and reviewers who want to review and provide feedback on model documentation prepared by a model developer

## Prerequisites

* You are a registered user on the ValidMind platform
* The model you are documenting is registered in the model inventory
* A documentation project has already been created for this project
* A model developer has started generating documentation, either using the Developer Framework or via the online UI editor
* You are logged in to the ValidMind platform

## Steps - Viewing the model documentation

1. Navigate to the relevant model documentation project
   - In the Documentation Projects page, select the project corresponding to the model for which you want to view documentation
2. From the Overview page, select Documentation on the left-hand side
3. You can now jump to any section of the model documentation by expanding the table of contents on the left-side and selecting the relevant section you would like to view

## Steps - Editing the model documentation (for Model Developers only)

1. In any section of the documentation, hover over text content and click the "edit" icon that appears on the right of the textbox **Need image**
2. You can now use the text editor functions to edit the content of the section
3. When done, click the "Save" icon to the right of the textbox to save your changes

*Note: The section activity at the bottom of the page will record a new event every time edits are made to the content of the page.*

## Steps - Posting a comment on the documentation (for Model Developers or Model Validators)

1. In any section of the documentation, select a portion of text that you would like to comment on, and click on the "Add comment" button that appears **Need image**
2. Enter your comment and press "Submit"
3. You can now view the comment by highlighting the corresponding portion of text, or by clicking the "Comments" tab in the ValidMind Insights right-hand side bar

## Steps - View Documentation guidelines and Comments (for Model Developers or Model Validators)

1. In any section of the documentation, click on the "ValidMind Insights" button on the top-right corner to expand the ValidMind Insights right-hand side bar **Need image**
   - The "Documentation Guidelines" tab shows the documentation guidelines associated with this documentation template, and have been configured by the Model Validation team
   - The "Comments" tab shows the comment threads associated with this section of the model documentation

## Steps - Submit Model Documentation for review / validation (for Model Developers only)

1. In the Overview page (accessible from the left-hand side bar), click on the "Ready for Validation" button under "Actions" to initiate the transition from the current state (e.g. "In Documentation") to the next workflow state (e.g. "In Validation") **Need image**

*Note: workflow states and transitions can be configured by an Administrator.*


## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]

## What's Next

[Summarize the task and provide any next steps or resources for the user to continue their learning or work.]

