---
title: "Review model documentation"
date: last-modified
---

You review the model documentation provided by a model developer as part of the formal validation process.

## Prerequisites

- You hold the `Validator` role 
- A model developer has submitted model documentation for review 

## Document Overview

1. [Log in to the ValidMind UI]({{< var vm_url >}}).

2. In the left sidebar, click [**Model Inventory**]({{< var vm_url >}}/model-inventory).

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Documentation**. 

   This is the **Document Overview**. This page shows a section-by-section outline of your project's documentation, as well as summaries of: 

   - Any [unresolved conversations](collaborate-with-others.qmd#commenting)
   - The number of [model findings](work-with-model-findings.qmd)
   - The [completion status](assign-documentation-section-statuses.qmd) for your model's documentation

#### Unresolved conversations

Here on this documentation overview page, hover over the **{{< fa comment-dots >}} #** icon to see a preview of the unresolved conversation associated with the documentation section. 

::: {.callout-tip appearance="minimal"}
Resolve conversations directly from this popup, or click to expand the conversation.
:::

#### Model findings
Here on this documentation overview page, hover over over the **{{< fa triangle-exclamation >}} #** icon to see a preview of model findings associated with the documentation section. 

::: {.callout-tip appearance="minimal"}
Click to expand the finding.
:::

#### Recent activity

At the bottom of the Document Overview page, you will also see quick view of any documentation activity. 

::: {.callout-tip appearance="minimal"}
Click on **{{< fa eye >}} See all Activity** to be taken to the **[Model Activity](view-documentation-activity.qmd)** page.
:::

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->
