---
title: "Set up your organization"
date: last-modified
---

This task involves managing organizations within ValidMind, allowing for effective business unit control.

## Prerequisites

To perform these steps, you must be a group administrator or a superuser. 

## Business units

A business unit is a distinct segment within an organization that focuses on a specific function, product, or market, operating semi-independently while aligning with the overall organizational goals.

<<<<<<< HEAD
1. Login to the {{< var vm_login >}}.

2. Click **Settings**. 

3. Select **Organization** under **Workspace Settings**.

4. Type the new business unit name in the dialog box under **Business Units**, then click **+ Add** to confirm.

### Editing business units

1. Login to the {{< var vm_login >}}.

2. Click **Settings**. 

3. Select **Organization** under **Workspace Settings**.

4. Hover over the business unit to:
   - Click {{< fa pencil >}} to rename the business unit. Click {{< fa check >}} to save your changes, or {{< fa xmark >}} to discard them.
   - Click {{< fa trash-can >}} to remove the business unit.
=======
{{< include _set-up-your-organization-business-units.qmd >}}
>>>>>>> 92d29f8c72378a64cf82bcb7441cc43d12a75752

::: {.callout-important}
In order to delete a business unit, there must be no models attached to that unit.
:::

## Risk areas

A risk area is a specific domain within an organization that requires monitoring and management to ensure factors like data quality, model performance, and regulatory compliance are addressed effectively.

<<<<<<< HEAD
1. Login to the {{< var vm_login >}}.

2. Click **Settings**. 

3. Select **Organization** under **Workspace Settings**.

4. Click **+ Add** at the **Risk Areas** sidebar menu.

5. Fill in the risk title and description and click **+ Add Risk Area** to confirm.

### Remove a risk area

1. Login to the {{< var vm_login >}}.

2. Click **Settings**. 

3. Select **Organization** under **Workspace Settings**.

4. Hover over the risk area to:
   - Click the trash icon to delete the risk area.
=======
{{< include _set-up-your-organization-risk-areas.qmd >}}
>>>>>>> 92d29f8c72378a64cf82bcb7441cc43d12a75752

## Use cases

A use case is a specific application of analytics and management techniques within an organization, such as attrition management, call routing, and regulatory compliance processes like BSA/AML, CCAR, and CECL.

<<<<<<< HEAD
1. Login to the {{< var vm_login >}}.

2. Click **Settings**. 

3. Select **Organization** under **Workspace Settings**.

4. Click **+ Add** at the **Use Cases** sidebar menu.

5. Fill in the use case title and description and click **+ Add Use Case** to confirm.

### Remove a use case

1. Login to the {{< var vm_login >}}.

2. Click **Settings**. 

3. Select **Organization** under **Workspace Settings**.

4. Hover over the use case to:
   - Click the trash icon to delete the use case.
=======
{{< include _set-up-your-organization-use-cases.qmd >}}
>>>>>>> 92d29f8c72378a64cf82bcb7441cc43d12a75752

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]

## What's next

[Summarize the task and provide any next steps or resources for the user to continue their learning or work.]
--->
