---
title: "Set up workflows"
date: last-modified
---

Workflows can be configured to match your organizational needs for overseeing model development, validation, or implementation activities.

Default workflows are provided for you as suggestions. You can customize the following default workflows:

- **Model documentation:** When documentation is created
- **Inventory model:** When the model is created

::: {.callout-warning title="Adjustments to workflows are not retroactive."}
When a workflow is edited, the new flow will only apply to new models created after the adjustment. 
:::

## Prerequisites

To customize workflows, you must hold the `Customer Admin` or `Developer` role.

## Add workflow steps

1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

2. In the left sidebar, click [**{{< fa gear >}} Settings**]({{< var vm_url >}}/settings).

3. Under Workplace Settings, select **{{< fa arrow-right-arrow-left >}} Workflows**.

4. Under available workflows, select the process you'd like to add or edit the workflow for.

5. Drag and drop a step onto the canvas to configure it.

::: {.callout-tip appearance="minimal"}
- Refer to [Available step types](#available-step-types) for information on available step types. 
- Refer to [Conditional requirements](#conditional-requirements) for details on how to configure conditional requirements.
:::

6. To link your newly configured step to an existing step, click **{{< fa circle >}}** above or below the previous step and drag it to connect to a **{{< fa circle >}}** on the new step.

6. When you are done, click **Save workflow** to apply your changes.

## Available step types

| Type | Description | Setup |
|---:|---|---|
| Status Change | Transitions statuses based on conditional requirements. | Requires [available resource statuses](customize-resource-statuses.qmd) associated with the workflow. |
| User Action | Creates a button that performs an action on behalf of the user. | Can be configured to display based on conditional requirements. |
| Approval | When your resource reaches the approval step, users in the selected Approval Group will receive your configured message. | Requires an [available Approval Group](manage-groups.qmd) within your User Permission [**Groups**]({{< var vm_url >}}/settings/groups). |
: Step type summaries {.hover tbl-colwidths="[20,40,40]"}

#### Status Change

#### User Action

#### Approval

### Conditional requirements

Conditional requirements can be configured for all three available step types.

#### Status change conditionals
- Under `When these conditions are met`, you are able to set both `AND` and `OR` conditions. 
- You can also add a single condition **+ Rule** or a condition **+ Group**.

#### User action conditionals
- Under `Display action button when`, you are able to set both `AND` and `OR` conditions. 
- You can also add a single condition **+ Rule** or a condition **+ Group**.

#### Approval conditional
Under `Threshold`, you are able to set the minimum percentage of approvers required for the resource to be approved.

## What's next

- [Workflows FAQ](../faq/faq-workflows.qmd)
- [Preparing validation reports](preparing-validation-reports.qmd)

