---
title: "Submit for approval"
keywords: "submit for approval, submit for review, workflow, ai risk, model risk management, ValidMind"
date: last-modified
---

Learn how to use the ValidMind UI to view the approval workflow configured by an administrator and to submit projects for review and approval according to that workflow. This topic is relevant for: 

* Model developers who want to submit their documentation for review
* Model validators who want to submit their validation report for review

## Prerequisites

* The model you are documenting is registered in the model inventory
* For Model Developers submitting their documentation for review: model documentation is complete
* For Model Validators submitting their validation report for review: validation report is complete

## View the current status and workflow

1. On the **Documentation Projects** page, select a project.

   On the **Overview** page, the current status of the project is displayed under **Status**.
<!--- **Need image** --->

3. Click **See workflow** under **Status** to visualize the entire workflow that this project will go through.
<!--- **Need image** --->

## Submit for review, for validation, or to advance to a workflow

1. On the **Documentation Projects** page, select a project.

2. Under **Actions** on the right, initiate the transition from the current state to the next workflow state. 

   For example, change the state from `In Documentation` to `In Validation` to indicate that a model developer has completed the initial model documentation  and is ready to go through the model validation step. 
<!--- **Need image** --->

::: {.column-margin}
::: {.callout-tip}
Workflow states and transitions can only be configured by an administrator.
:::
:::

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]

## Related topics

* [Configure Workflows](configure-workflows.qmd)
--->
