---
title: "Support"
keywords: "support, ai risk, model risk management, ValidMind"
date: last-modified
---

Our support team can provide you with quick and easy access to the resources you need to troubleshoot technical issues and help you get the most out of the ValidMind Platform.

<!--- TO DO ZenDesk support email --->

## Check the FAQs

We curate several lists of frequently asked questions (FAQs) that might be of help: 

- [Model registration, configuration, and customization](faq-models.qmd)
- [Model inventory, tracking, and reporting](faq-inventory.qmd)
- [Documentation and templates](faq-documentation.qmd)
- [Workflows and collaboration](faq-workflows.qmd)
- [Testing and thresholds](faq-testing.qmd)
- [Integrations and support](faq-integrations.qmd)
- [Data handling and privacy](faq-privacy.qmd)

<!---
## Check out the troubleshooting content

Additional troubleshooting content might be available in the [Help Center](https://support.validmind.com/).
--->

## Get help 

Don't see what you are looking for? Email [support@validmind.com](mailto:support@validmind.com) to get help from a human.
