---
title: "Swap documentation project templates"
keywords: "swap templates, ai risk, model risk management, ValidMind"
date: last-modified
---

Learn how to swap documentation templates for projects in the ValidMind Platform UI. By swapping templates, you can keep your documentation projects up-to-date without starting a new project from scratch. This topic is useful for:

- Model developers who need to update the documentation template for a model.
- Model validators who need to update the validation report template for their report.

Swapping templates allows you to switch to a completely different template, upgrade to a more recent version of your current template, or make changes to both the template and its version at the same time. 

## Prerequisites

If you are not sure which template or which version of a template a documentation project is using, check the **Project Overview** page of your documentation project. The **Documentation Template** section in the right sidebar lists the information.

## Steps

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. Click **Documentation Projects**.

3. Open the documentation project that you want to update the template for. The right sidebar lists the templates currently in use.

4. Select the template currently in use under one of the following:
   
   - **Documentation Template** 
   - **Validation Report Template**
   
   The window pane that opens shows the JSON for the current template along with other information, such as the name and the current version.

4. Click **Swap Template**. 
   
   The window pane now shows the JON for two templates side-by-side:
   
      - On the left, your current template is shown.
      - On the right, you can select a different template and version.
   
   Initially, both templates are the same. 

5. On the right, select a different template or version:
   
   - **Template**: Change to a different template entirely
   - **Version**: Change to a different version of the template you selected
   
   For example: Select a previous version of the template currently in use to revert to that version. 
   
   After you select a different template or version, the JSON differences between the templates are highlighted. 

6. Click **Prepare Swap**.

7. Enter a note to enable completing the swap and click **Swap Template**.

After your model documentation template has been swapped successfully, you can now continue to work on your documentation project.

::: {.column-margin}
::: {.callout-info}
## About swapping templates
<!--- NR Can we explain this a bit better for people who are not yet familiar with editing content blocks?  --->
When swapping templates, only the document structure is changed. Any modifications that you might have made to content will be preserved  inside each content block or section.
<br><br>
If you added a simple text block to your old template and want to reuse the content, you can temporarily switch back to the old template,  copy the content, swap back to the new template, and then paste in the content.
:::
:::


<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

You can see which version of a template is used in the **Project Overview** page of each documentation project. 

## Related topics

* [Create documentation projects](create-documentation-project.qmd)
* [Document models with the Developer Framework](document-models-with-framework.qmd)
