---
title: "Swap documentation templates"
date: last-modified
---

Swapping templates allows you to switch to a completely different template, upgrade to a more recent version of your current template, or make changes to both the template and template version at the same time.

When swapping templates, only the document structure is changed. Any modifications that you might have made to content is preserved inside each content block or section. If you are not sure which template or which version of a template your model documentation or validation report is using, you can also check and compare between different templates and versions of templates.

## Prerequisites

- You must hold the `Developer` role to update the template for model documentation.
- You must hold the `Validator` role to update the template for validation reports.

## View current templates

1. Login to the {{< var vm_login >}}.

2. In the left sidebar, click [**Model Inventory**]({{< var vm_url >}}/model-inventory).

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Documentation**.

5. Check the right sidebar: 

   - `Document Template` — lists the template used for model documentation
   - `Validation Report Template` — lists the template used for validation reports

## Swap templates

1. Login to the {{< var vm_login >}}.

2. In the left sidebar, click [**Model Inventory**]({{< var vm_url >}}/model-inventory).

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Documentation**.

5. In the right sidebar, select one of the templates currently in use under one of the following:
   
   - **Document Template** 
   - **Validation Report Template**
   
   The window pane that opens shows the YAML for the current template along with other information, such as the name and the current version, and which models are using this template.

6. Click **Swap Template**. 
   
   The window pane now shows the YAML for two templates side-by-side:
   
      - On the left, your current template is shown.
      - On the right, you can select a different template and version.
   
   Initially, both templates are the same. 

7. On the right, select a different template or version:
   
   - **Template**: Change to a different template entirely
   - **Version**: Change to a different version of the template you selected
   
   For example: Select a previous version of the template currently in use to revert to that version. 
   
   After you select a different template or version, the YAML differences between the templates are highlighted. 

8. Click **Prepare Swap**.

9. Enter a note to enable completing the swap and click **Swap Template**.

After your model documentation template has been swapped successfully, you can continue to work on your model documentation

#### Reusing old content

If you added a simple text block to your old template and want to reuse the content, you can temporarily switch back to the old template, copy the content, swap back to the new template, and then paste in the content.


<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]


## What's next

- [Get started with the {{< var vm_framework >}}](get-started-developer-framework.qmd)
--->
