---
title: "Troubleshooting"
keywords: "troubleshooting, model risk management, ValidMind"
---

Learn how to resolve commonly encountered issues with the Developer Framework.

## Cannot install the ValidMind Developer Framework

**Issue:** You cannot run `pip install validmind` or `import validmind as vm` in the ValidMind Developer Framework notebooks.

**Fix:** Make sure you are installing the latest version of the Developer Framework by running this command:

`%pip install --upgrade validmind`

## Cannot initialize ValidMind client library

**Issue:** When you run `vm.init()`, you encounter an error message like this: 

```
MissingAPICredentialsError: API key and secret must be provided either as environment variables or as arguments to init.
```

or

```
InvalidProjectError: Invalid project ID. Please ensure that you have provided a project ID that belongs to your organization.
```

**Fix:** Make sure that you are using the correct initialization credentials for the project you are trying to connect to. 

Follow the steps in [Install and initialize the Developer Framework](install-and-initialize-developer-framework.qmd) for detailed instructions on how to integrate the Developer Framework and upload to the ValidMind Platform.

## Additional resources

Check out our [FAQ](faq.qmd) page to browse through common questions, or [contact our support team](support.qmd) for more help troubleshooting technical issues.
