---
title: "Try it with Jupyter Hub (Recommended)"
keywords: "try developer framework, jupyter hub, model risk management, ValidMind"
---

Learn how to access our introductory Jupyter notebook with Jupyter Hub (recommended).

## Prerequisites

You must have [Jupyter Notebook](https://jupyter.org/install) installed on your machine. 

## Steps

1. In a web browser, go to <https://jupyterhub.validmind.ai>.

2. Click **Sign in with Auth0**, enter your email address and password, and click **Continue**.

3. In the sidebar, double click the **Quickstart_Customer Churn_full_suite.ipynb** notebook.

4. After the notebook opens, run the first few cells in the notebook:

   - Hover over each cell and click the {{< fa circle-play >}} **icon**; OR
   - Press `Shift + Enter` on Windows or `Cmd + Enter` if you are on a Mac
   
   The notebook will install the ValidMind library and then connect to your own documentation project in the ValidMind Platform.
   
   Near the bottom of the **Initialize ValidMind** section, you should see a message like this:
   
   ```bash
   Connected to ValidMind. Project: Customer Churn Model - Initial Validation (xxxxxxxxxxxxxxxxxxxxxxxxx)
   ```
   
   This message confirms that the Developer Framework works as expected. 

You can now continue running the rest of the cells if you want to see how the demo notebook works or, to save some time, you can move on to the next section to explore the Platform UI. 

<!--- TO DO Screenshot --->

## What's Next

Continue with the [Explore the Platform UI](explore-example-documentation-project.qmd) Quickstart to learn how you can use the sample notebook.
