---
title: "Try out the ValidMind developer framework"
keywords: "try out validmind developer framework, model risk management, ValidMind"
---

For model developers, we recommend that you check out the running sample Jupyter notebooks and then try modifying our the notebooks yourself:

These notebooks show you how to initialize the developer framework, prepare a demo dataset, run test plans, train a model, and then upload to the ValidMind platform. 

Check out the running notebooks:

- [ValidMind Python Library Introduction](../notebooks/intro.ipynb) — {{< fa brands python >}}
- [ValidMind Python Library Introduction](../notebooks/intro-r.ipynb) — {{< fa brands r-project >}}

<!-- TO DO we need to add the correct download link here --->

Try it yourself (requires Python 3.8+):

::: {.column-margin}
::: {.callout-important}
## Getting a 404?
**You need to log into GitHub.**
<br><br>
This link currently points to a private repository that requires authentication.
:::
:::

```{=html}
<!DOCTYPE html>
<html>
<head>
    <title>Notebook Download Button</title>
    <style>
        .download-button {
            display: inline-block;
            background-color: #DE257E;
            color: white;
            border: none;
            padding: 12px 24px;
            font-size: 16px;
            font-weight: bold;
            border-radius: 4px;
            cursor: pointer;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
            transition: all 0.3s ease-in-out;
            margin-bottom: 24px;
        }

        .download-button:hover {
            background-color: #c71e6b;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }
    </style>
</head>
<body>
    <a href="https://github.com/validmind/documentation/tree/main/site/notebooks" download>
        <button class="download-button">Download notebook source</button>
    </a>
</body>
</html>
```

After you download the notebook source, you can try out changes locally in your own developer environment and run the notebooks from there.

## What's Next

Next, you can try [exploring our Validmind platform UI](explore-validmind-ui.qmd).

