---
title: "When to use test plans and tests"
keywords: "when to use test plans and tests, model risk management, ValidMind"
---

## Brief Introduction

This article provides an overview of the following topics: 

- What Test and Test Plans are in the Developer Framework

- When to use Test Plans and Tests, and typical scenarios

## What Tests, Test plans, and Test suites are

* **Tests** are designed to run a specific quantitative test on the dataset or model. Test results are sent to the ValidMind Platform to generate the model documentation according to the relevant templates. 
 * Example:  

* **Test plans** are collections of tests which are meant to be run simultaneously to address specific aspects of the documentation.
 * Example: the "tabular_dataset" test plan runs several descriptive and data quality tests on a structured dataset, and documents the results in the ValidMind UI.

* **Test suites** are collection of test plans which are meant to run together to automate generate model documentation end-to-end for specific use-cases.
 * Example: the "binary_classifier_full_suite" test suite runs the "tabular_dataset" and "binary_classifier" test plans to fully document the Data and Model sections for binary classification model use-cases. 


## When to use ValidMind Tests, Test plans, and Test suites

ValidMind provides many built-in Tests and Test Plans which make it easy for a model developer to document their work, at any point during the model development lifecycle when they need to validate that their work satisfies Model Risk Management requirements. 

While the model developer has the flexibility to decide when to use ValidMind tests, we have identified a few typical scenarios which have their own characteristics and needs:

* When you want to document and validatae your dataset:
  * For generic tabular datasets: **tabular_dataset** test plan
  * For time-series datasets: **time_series_dataset** test plan

* When you want to document and validate about your model:
  * For binary classification models: **binary_classifier** test plan
  * For time series models: **timeseries** test plan

* When you want to document a binary classification model and the relevant dataset end-to-end: **binary_classifier_full_suite** test suite

## API Reference

You can refer to the following pages for a list of all of the built-in tests and test plans for datasets and models:


## Related Topics

Provide links or references to related topics that users might find useful or interesting. These could be other articles, resources, or tools related to the main topic.
