---
title: "Verify uploads"
keywords: "check uploads, model developer, model risk management, ValidMind"
---

Check the documentation, metrics, and test results uploaded to the platform by the developer framework.

## Prerequisites

These steps require that you have already uploaded some information from the developer framework to the ValidMind platform. To simplify the getting started experience, these steps use an existing project. 

## Steps

1. [Log into the ValidMind UI](login.qmd).

2. From the side navigation, select **Model Inventory**.

3. Locate or search for the `Customer Churn Model` and select it.

   The model page shows some important information about the model, such as:

    - The ID of the model and its use
    - The owners, developers, and validators associated with the model
    - The approval route for the validation workflow 
    - The risk tier, current version, and the last and next validation dates
    - And more

4. [Step 4]
   - [Include any sub-steps or details needed to complete this step]

## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]

## What's Next

[Summarize the task and provide any next steps or resources for the user to continue their learning or work.]

