---
title: "View documentation activity"
date: last-modified
---

Learn how to access and use the audit trail functionality in the ValidMind Platform. This topic matters for model developers, model validators, and auditors who are looking to track or audit all the information events associated with a specific project.

## Prerequisites

* The model you are documenting is registered in the model inventory
* Model documentation has already been created for this project
* A model developer has started generating documentation, either using the developer framework or via the online UI editor
* You are logged into the ValidMind Platform


## Steps

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. In the left sidebar, click [**Model Inventory**](https://app.prod.validmind.ai/model-inventory).

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Model Activity**.

The table in this page shows a record of all activities, including: 

- Project updates generated by the developer framework (`API Client`) 
- Actions performed on the project by users in your organization 

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

* [Collaborate on documentation](collaborate-on-documentation.qmd)
