---
title: "View all test suites"
keywords: "view all test suites, ai risk, model risk management, ValidMind"
date: last-modified
---
Learn how to use `list_suites()`, `list_tests()`, and `describe_suites()` methods to view and describe test suites and tests available in the Developer Framework. 

## Prerequisites

* You are a registered user on the ValidMind Platform
* You are working on an active documentation project
* You have already installed the ValidMind client library in your developer environment

## Steps

1. [Initialize the client library](install-and-initialize-developer-framework.qmd).

2. Use `list_suites()` and `list_tests()` to view the list of all available test suites and tests. 

   Examples: 

   - List all available test suites currently available in the the Developer Framework: 

      ```python
      vm.test_suites.list_suites()
      ```

   - List all available individual tests currently available in the Developer Framework: 

      ```python
      vm.tests.list_tests() 
      ```

3. Use `describe_testsuite()` to list all the tests included in a specific test suite: 

   Example: The following code will list tests included in the tabular_data_quality test suite: 

   ```python
   vm.test_suites.describe_suite("tabular_data_quality") 
   ```

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## Related topics

* [Document models with the Developer Framework](document-models-with-framework.qmd)
* [ValidMind Developer Framework API Reference](reference.qmd)

