---
title: "View validation guidelines"
date: last-modified
---

View the guidelines for validation reports associated with a template to ensure that you are compliant with the requirements for validation reports.

## Prerequisites

- You hold the `Validator` role^1^
- The model you are documenting is registered in the model inventory^2^
- Model documentation has already been submitted for review by the model validation team for this project^3^

::: {.column-margin}
**Learn more:**

- ^1^[Users (Supported roles)](onboarding-users.qmd#supported-roles)
- ^1^[Manage users (User roles)](manage-users.qmd#user-roles)
- ^2^[Register models in the inventory](register-models-in-model-inventory.qmd)
- ^3^[Working with model documentation](working-with-model-documentation.qmd)
:::

::: {.callout-important}
Configuring the validation guidelines for each template requires the `Customer Admin` role.
:::

## Steps

1. Log in to the {{< var vm_login >}}.

2. In the left sidebar, click **Model Inventory**.

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Validation Report**.

<!--- NR TO DO This looks to be no longer shown in the UI as of March 2024? --->
5. In any section of the validation report, click **ValidMind Insights™** in the top-right corner to expand the **ValidMind Insights™** sidebar:

   - The **Validation Report Guidelines** tab shows the guidelines associated with this model that have been configured by the model validation team.
   - The **Comments** tab shows the comment threads associated with this section of the validation report.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

<!---* [Create project findings](create-project-findings.qmd)--->
* [Work with validation reports](preparing-validation-reports.qmd)
