---
title: "View reports"
date: last-modified
---

View reports on model validation, organized by risk area, business unit, status, and individual model. These reports highlight validation findings, assess risks, track compliance, and outline remediation steps for informed decision-making

## Prerequisites

You should hold the model validator role or be a risk officer who needs to get a quick overview for findings related to model validation, including the severity of these findings.

## Steps

1. [Log in to the ValidMind UI]({{< var vm_ui >}}).

2. In the left sidebar, click **Reports**.

   In the Reports page that opens, you can see bar charts for different types of findings, including:

   - Findings by risk area
   - Findings by business 
   - Findings by status
   - Findings by model

3. For each of the bar charts, you can click on the individual bars to get a more detailed view. 

   For example: To see all inventory models where there are findings related to data quality:

   a. Under **Findings by Risk Area**, click on **Data Quality**. 
   b. On the page that opens, the applicable findings are listed, including the inventory model they apply to, the severity of the finding and its current status, and who the finding has been assigned to.
   c. To get more details on the finding itself, click on the title of the finding to take you to the **Model Findings** section for the specific model the finding applies to.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

Working with reports in the ValidMind Platform UI is closely related to [working with model findings](work-with-model-findings.qmd).