---
title: "View documentation templates"
date: last-modified
---

Learn how to view the structure and configuration of existing documentation templates on the {{< var vm_platform >}}. 

## Prerequisites

To configure templates, you must hold the `Customer Admin` role^1^. 

::: {.column-margin}
**Learn more:**

^1^ [Users (Supported roles)](onboarding-users.qmd#supported-roles)

^1^ [Manage users (User roles)](manage-users.qmd#user-roles)
:::

## Steps

1. Log in to the {{< var vm_login >}}.

2. In the left sidebar, click **{{< fa gear >}} Settings** and then **Templates**.

2. Click on one of the available templates. 

   In the page that opens, you can view information about the template, such as: 

   - Name and description of the template
   - Version of the templates
   - Sections in the template and how they are structured
   - Guidelines associated with each section 
   - Metrics from the {{< var vm_dev >}} that feed into the template


<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

- [Get started with the {{< var vm_framework >}}](get-started-developer-framework.qmd)
- [Collaborate on documentation](collaborate-with-others.qmd)
