---
title: "View documentation project activity"
keywords: "review data streams and audit trails, ai risk, model risk management, ValidMind"
date: last-modified
---

Learn how to access and use the audit trail functionality in the ValidMind Platform. This topic matters for for model developers, model validators, and auditors who are looking to track or audit all the information events associated with a specific project.

## Prerequisites

* You are a registered user on the ValidMind Platform
* The model you are documenting is registered in the model inventory
* A documentation project has already been created for this project
* A model developer has started generating documentation, either using the Developer Framework or via the online UI editor
* You are logged into the ValidMind Platform


## Steps

1. In the ValidMind platform, navigate to the relevant model documentation project.

2. From the **Overview** page, select **Project Activity** on the left.

The table in this page shows a record of all activities generated from the Developer Framework (`API Client`) and actions performed by users in the organization related to this specific project. 

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

* [Review and comment on documentation projects](review-documentation-project.qmd)
