---
title: "View templates"
keywords: "view templates, ai risk, model risk management, ValidMind"
---

Learn how to view the structure and configuration of existing documentation templates on the ValidMind Platform. 

## Prerequisites

* You are a registered user on the ValidMind Platform
* You are logged into the ValidMind Platform

## Steps

1. From the ValidMind Platform homepage, go to **Templates** on the left.

2. Click on one of the available templates to view the YAML configuration file. 

   In the configuration file that opens, you can view information about the template, such as: 

   - Name and description of the template
   - Version of the templates
   - Sections in the template and how they are structured
   - Guidelines associated with each section 
   - Metrics from the Developer Framework that feed into the template

::: {.column-margin}
::: {.callout-tip}
Templates can only be configured by an administrator. 
:::
:::

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## Related topics

* [Create documentation projects](create-documentation-project.qmd)
* [Document models with the Developer Framework](document-models-with-framework.qmd)
* [Review and comment on documentation projects](review-documentation-project.qmd)
