---
title: "View documentation guidelines"
date: last-modified
---

View the guidelines for model documentation associated with a template to ensure that you are compliant with documentation requirements.

## Prerequisites

- You hold the `Developer` role^1^
- The model you are documenting is registered in the model inventory^2^
- Model documentation has already been created for this project^3^
- A model developer has started generating documentation, either using the {{< var vm_framework >}}^4^ or via the online editor in the {{< var vm_platform >}}

::: {.column-margin}
**Learn more:**

^1^ [Users (Supported roles)](onboarding-users.qmd#supported-roles)

^1^ [Manage users (User roles)](manage-users.qmd#user-roles)

^2^ [Register models in the inventory](register-models-in-model-inventory.qmd)

^3^ [Working with model documentation](working-with-model-documentation.qmd)

^4^ [{{< var vm_framework >}}](get-started-developer-framework.qmd)
:::

::: {.callout-important}
Configuring the documentation guidelines for each template requires the `Customer Admin` role.
:::

## Steps

1. Log in to the {{< var vm_login >}}.

2. In the left sidebar, click **Model Inventory**.

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Documentation**.

5. In any section of the documentation for a model, click **ValidMind Insights™** in the top right corner to expand the **ValidMind Insights™** sidebar:

   - The **Documentation Guidelines** tab shows the documentation guidelines associated with this documentation template that have been configured by your model validation team.
   - The **Comments** tab shows the comment threads associated with this section of the model documentation.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

- [Get started with the {{< var vm_framework >}}](get-started-developer-framework.qmd)
- [Working with model documentation](working-with-model-documentation.qmd)
- [Collaborate on documentation](collaborate-with-others.qmd)
