---
title: "View your profile"
date: last-modified
---

Managing your profile is essential for personalizing your user experience and ensuring you have access to the necessary tools and information. View your profile details, manage your onboarding preferences, enable dark mode, and access your API keys.

## Steps

1. Log in to the {{< var vm_login >}}.

2. Go to **{{< fa gear >}} Settings** in the sidebar. 

3. Select **Profile**. You can find the following on your profile page:

   - Profile details 
   - Roles attached to your account
   - Groups assigned to your account

4. Under Onboarding, toggle the **Getting started guide** depending on your preferences^1^.

::: {.column-margin}
**Learn more:**  

^1^ [Getting started](./get-started.qmd) 
:::

5. Under User Interface Preferences, toggle **Enable dark mode** to use the dark version of the {{< var vm_ui >}}.

6. Under Access keys, view your API key and Secret key. To copy the key, select **{{< fa clipboard >}} Copy to Clipboard**.

## What's next
- [Manage users](./manage-users.qmd)
- [Manage roles](./manage-roles.qmd)