---
title: "Working with model documentation"
date: last-modified
listing:
  - id: model-documentation-listing
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - view-documentation-guidelines.qmd
      - work-with-content-blocks.qmd
      - assign-documentation-section-statuses.qmd
      - collaborate-with-others.qmd
      - view-documentation-activity.qmd
      - submit-for-approval.qmd
---

After you upload initial model documentation through the {{< var vm_dev >}}, use the {{< var vm_ui >}} to make qualitative edits to model documentation, view guidelines, collaborate with validators, and submit your model documentation for approval. 

::: {.callout}
## Looking to get started as a model developer?

This section describes how to work with model documentation in the {{< var vm_platform >}}. Typically, you perform the tasks described here **after you have uploaded some initial model documentation** with the {{< var vm_framework >}}. 

[Get started with the {{< var vm_framework >}} {{< fa hand-point-right>}}](get-started-developer-framework.qmd)
:::

## Prerequisites

- You hold the `Developer` role 
- The model is already [registered in the model inventory](register-models-in-model-inventory.qmd)
- You have provided some content for the documentation, either [by uploading it through the {{< var vm_framework >}}](get-started-developer-framework.qmd) or via the online UI editor

## Key concepts

<!-- TO EDIT THESE KEY CONCEPTS, SEE `about/glossary/_model-documentation.qmd` -->

{{< include ../about/glossary/model_documentation/_doc-intro.qmd >}}

::: {.grid}

::: {.g-col-6}
{{< include ../about/glossary/model_documentation/_conceptual-soundness.qmd >}}

{{< include ../about/glossary/model_documentation/_data-preparation.qmd >}}

:::

::: {.g-col-6}
{{< include ../about/glossary/model_documentation/_model-development.qmd >}}

{{< include ../about/glossary/model_documentation/_monitoring-governance.qmd >}}

:::

:::

## Document Overview

1. Login to the {{< var vm_login >}}.

2. In the left sidebar, click [**Model Inventory**]({{< var vm_url >}}/model-inventory).

3. Select a model by clicking on it or find your model by applying a filter or searching for it.

4. In the left sidebar that appears for your model, click **Documentation**. 

   This is your **Document Overview**. This page shows a section-by-section outline of your project's documentation, as well as summaries of: 

   - Any [unresolved conversations](collaborate-with-others.qmd#commenting)
   - The number of [model findings](work-with-model-findings.qmd)
   - The [completion status](assign-documentation-section-statuses.qmd) for your model's documentation

#### Unresolved conversations

Here on this documentation overview page, hover over the **{{< fa comment-dots >}} #** icon to see a preview of the unresolved conversation associated with your documentation section. 

::: {.column-margin}
Resolve conversations directly from this popup, or click to expand the conversation.
:::

#### Model findings
Here on this documentation overview page, hover over over the **{{< fa triangle-exclamation >}} #** icon to see a preview of model findings associated with your documentation section. 

::: {.column-margin}
Click to expand the finding.
:::

#### Recent activity

At the bottom of the Document Overview, you will also see quick view of any documentation activity. 

::: {.column-margin}
Click on **{{< fa eye >}} See all Activity** to be taken to the **[Model Activity](view-documentation-activity.qmd)** page.
:::

### Add or edit documentation

1. From the **Document Overview**, jump to any section of the model documentation by selecting the relevant section you would like to view.

5. In any section of the documentation, hover over text content and click to add or edit content. 

    You can now use the text editor functions to edit the content of the section. Whenever you make a change, an activity log entry is recorded under **Section activity** on the page, just below the section you are editing. 

6. Save your edits as a revision:

   a. Click on the {{< fa clock-rotate-left >}} icon in the editor toolbar.
   b. Select **Save current revision** and enter a name.
   c. Click {{< fa check >}} to save the current revision.

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## What's next

:::{#model-documentation-listing}
:::