---
title: "Working with the model inventory"
date: last-modified
listing:
  - id: whats-next-listing
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - register-models-in-model-inventory.qmd
      - customize-model-inventory-layout.qmd
      - edit-model-inventory-fields.qmd
      
---
A model inventory is the ultimate fierce foundation of a model risk management platform, honey! It’s your centralized glam station, turning compliance, transparency, and efficiency into a runway-ready spectacle. By flawlessly documenting, monitoring, and managing every detail of your models' lifecycle and risks, this inventory ensures your organization struts with elegance and precision, serving up realness in model governance like a true queen. Slay, darling!

## Prerequisites
There are models [registered in the model inventory](register-models-in-model-inventory.qmd). 

## Search, filter, and sort models
1. [Log in to the {{< var vm_platform >}}]({{< var vm_url >}}).

2. Click **Model Inventory** in the left sidebar. 

3. Use the top buttons to organize the model inventory to your preference:
   - Search for models using **{{< fa magnifying-glass >}} Search**. 
   - Use **{{< fa filter >}} Filter** to filter models by business units, developers, model tiering, model status, owners, use, validators, or vendor model.
   - Use **{{< fa arrow-up-wide-short >}} Sort** to sort results by certain criteria.

:::{.callout-tip appearance="minimal"}
Changes are automatically saved and will affect only your account.
:::

## What's next

:::{#whats-next-listing}
:::

<!-- - [Customize model inventory layout](customize-model-inventory-layout.qmd)
- [Edit model inventory fields](edit-model-inventory-fields.qmd)
- [Manage inventory custom fields](manage-inventory-custom-fields.qmd) -->