---
title: "Learning paths"
sidebar: validmind-training
toc-expand: true
---

Each path provides a structured, hands-on approach to mastering key {{< var vm.product >}}’s features that you can apply in your work.

<!-- {{< var vm.product >}} offers role-based learning paths designed to help professionals quickly build the skills they need.  -->

# End-to-end courses

Develop role-based expertise for your entire organization.

## Developer Fundamentals

As a developer who is new to ValidMind, learn how to generate model documentation, add your own tests, edit the content, and then submit your documentation for approval.

::: {.attn-yellow}
:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns}
{{< fa check >}} **Course content**

- Split 3 modules -> 4 modules
- Expand process overview content
- Expand template content to include editing templates and adding tests
- Rename "Module 2: Start Documenting & Testing" to "Module 2: Start Documenting"
- Add missing content for "Register a model" in Module 1
:::

::: {.w-30-ns}
{{< fa check >}} **Videos **

- 10 videos
- Minor update to collaboration video (multi-person comment threads)
:::

::: {.w-30-ns .pl4 .bl}
**Notes**

- FUTURE: 1 intro notebook -> 4 notebooks that progressively build on each other
:::

::::
:::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 1: Initialize the ValidMind Library

- Install the ValidMind Library {{< fa check >}}
- Initialize your development environment {{< fa check >}}
- Register a model {{< fa minus >}}
- Get your code snippet {{< fa check >}}
- Work with documentation templates {{< fa minus >}}
:::

::: {.w-50-ns}
### Module 2: Start Documenting & Testing

- Initialize your datasets {{< fa check >}}
- Run tabular data tests {{< fa check >}} 
- Utilize test output {{< fa check >}}
- Document results based on datasets {{< fa check >}}
- Test your model {{< fa check >}}
<!-- - Initialize model evaluation objects and assigning predictions  -->
- Run the model evaluation tests {{< fa check >}}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 3: Implement Custom Tests

- Create a confusion matrix plot {{< fa check >}}
- Add parameters to custom tests {{< fa check >}}
- Pass parameters to custom tests {{< fa check >}}
- Log the confusion matrix results {{< fa check >}}
- Using external test providers {{< fa check >}}
- Initializing a local test provider {{< fa check >}}
:::

::: {.w-50-ns}
### Module 4: Finalize Testing & Documentation

- Include custom test results in your documentation {{< fa check >}}
- Viewing and updating the configuration for the entire model documentation template {{< fa check >}}
- Update the config {{< fa check >}}
:::

::::

## Validator Fundamentals

As a validator who is new to ValidMind, learn how to review model documentation, prepare your validation report, track issues, and submit your report for approval.

::: {.attn-yellow}


:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns}
{{< fa check >}} **Course content**

- Split 2 modules -> 3 modules
- Add missing content:
   - Preview templates for validation reports
   - How to work with validation reports
  - Expand process overview content
:::

::: {.w-30-ns}
{{< fa minus >}} **Video** 

- 5 videos
- Replace stale '101' intro
- Review for stale content
:::

::: {.w-30-ns}
<!-- **Notes**

- TBD -->
:::

::::
:::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 1: Reviewing & Analyzing Models 

- Access validation reports {{< fa check >}}
- Preview templates for validation reports {{< fa x >}}
- How to work with validation reports {{< fa x >}}
:::

::: {.w-50-ns}
### Module 2: Reviewing & Analyzing Models 

- Reviewing model documentation {{< fa check >}}
- Analyzing test results {{< fa check >}}
- Add findings {{< fa check >}}
- Link evidence {{< fa check >}}
- Assessing compliance {{< fa check >}}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 3: Issue Resolution & Submission

- Tracking issue resolution {{< fa check >}}
- Submitting validation reports for approval {{< fa check >}}
:::

::: {.w-50-ns}

:::

::::

## Administrator Fundamentals

As an administrator who is new to ValidMind, learn how to onboard your organization, manage users and roles, and manage permissions for specific roles.

::: {.attn-orange}

:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns}
{{< fa check >}} **Most course content exists**

- Split 2 modules -> 4 modules
- Expand workflow content section
- Add model inventory content
- Add missing content:
  - Assigning users to workflows
  - Mapping users to groups and roles
:::

::: {.w-30-ns}
{{< fa x >}} **No videos**

- Create 4 videos, one per module
:::

::: {.w-30-ns .pl4 .bl}
**Notes**

- FUTURE: Add admin UI coverage
:::

::::

:::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 1: Onboarding

- Setting up an organization {{< fa check >}}
- Inviting users via email {{< fa check >}}
:::

::: {.w-50-ns}
### Module 1: User Management

- Managing roles, permissions, and groups {{< fa check >}}
- Mapping users to groups and roles {{< fa minus >}}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 2: Workflows

- Configuring workflows {{< fa minus >}}
- Assigning users to workflows {{< fa minus >}}
:::

::: {.w-50-ns}
### Module 2: Templates & Model Inventory

- Customize templates {{< fa check >}}
- Configure model inventory fields {{< fa x >}}
:::

::::

## Monitoring Fundamentals

As a monitoring user who is new to ValidMind, learn how to generate ongoing monitoring documentation, schedule monitoring runs, and review the results.

::: {.attn-red}
:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns}
{{< fa x >}} **No course**

- Create complete course with 3 modules
- Create course registration page & add to training portal
:::

::: {.w-30-ns}
{{< fa x >}} **No videos**

- Create 3 videos
:::

::: {.w-30-ns .pl4 .bl}
**Notes**

- Based on [ongoing monitoring notebook](https://jupyterhub.validmind.ai/hub/user-redirect/lab/tree/code_samples/ongoing_monitoring/application_scorecard_ongoing_monitoring.ipynb)
:::

::::
:::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 1: Ongoing Monitoring of Models

- How monitoring integrates with model documentation {{< fa x >}}
- Enable monitoring for a model {{< fa check >}}
- Preview the monitoring template {{< fa check >}}
:::

::: {.w-50-ns}
### Module 2: Monitoring Setup

- Load the reference and monitoring datasets {{< fa check >}}
- Load the production model {{< fa check >}}
- Initialize datasets and a model object {{< fa check >}}
- Assign predictions to the datasets {{< fa check >}}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 3: Scheduling & Execution

- Run the ongoing monitoring tests {{< fa check >}}
- Conduct target and feature drift testing {{< fa check >}}
- Model performance monitoring tests {{< fa check >}}
- How to schedule quarterly or monthly monitoring runs {{< fa x >}}
:::

::: {.w-50-ns}
:::

::::



# Standalone courses

Useful skills for anyone who wants to use ValidMind. 

## {{< var vm.product >}} Guided Tour

As a new user of ValidMind, learn how to navigate the platform's key features and understand how they work together to support AI governance and compliance with regulations like the EU AI Act.

::: {.attn-orange}

:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns}
{{< fa check >}} **Most course content exists**

- Create course with 4 modules

- Create course registration page & add to training portal
:::

::: {.w-30-ns}
{{< fa x >}} **No videos**

- Create 1 video
:::

::: {.w-30-ns .pl4 .bl}
**Notes**

- Derived from [EU AI Act (V0)](https://docs-demo.vm.validmind.ai/product-demos/eu-ai-act/v0/index.html#/title-slide)
- Switch to training template
- Fix display issues using V1 fix (don't use absolute negative placement for columns) 
:::

::::
:::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 1: Getting Started with the Model Inventory

- Understand how the model inventory serves as your central hub for registered models {{< fa check >}}
- Learn to register new models with appropriate templates {{< fa check >}}
- Configure custom inventory fields and business units {{< fa check >}}
- Calculate risk classifications for AI systems {{< fa check >}}
:::

::: {.w-50-ns}
### Module 2: Model Documentation and Testing

- Navigate the documentation templates and structure {{< fa check >}}
- Explore the library of 250+ out-of-the-box tests {{< fa check >}}
- Learn to use AI-powered documentation features {{< fa check >}}
- Understand how to customize workflows for your needs {{< fa check >}}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 3: Validation and Collaboration

- Create and manage validation reports {{< fa check >}}
- Learn to assess compliance and link evidence {{< fa check >}}
- Create and track findings with severity and due dates {{< fa check >}}
- Use collaboration features for developer-validator interaction {{< fa check >}}
:::

::: {.w-50-ns}
### Module 4: Monitoring and Governance

- Set up ongoing monitoring for production models {{< fa check >}}
- Track model performance and identify data drift {{< fa check >}}
- Access and interpret governance analytics {{< fa check >}}
- Generate reports for non-technical stakeholders {{< fa check >}}
:::

::::

## {{< var vm.product >}} Content Features

As a content author who is new to ValidMind, learn how to use the content features to enhance my documentation, and to enable or disable text generation with GenAI.

::: {.attn-red}

:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns}
{{< fa x >}} **No course**

- Create course with 2 modules
- Create course registration page & add to training portal
:::

::: {.w-30-ns}
{{< fa x >}} **No videos**

- Create 2 videos
:::

::: {.w-30-ns}
<!-- **Notes**

- TBD -->
:::

::::
:::

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}
### Module 1: Using text generation

- When to use GenAI to draft content {{< fa x >}}
- How to turn GenAI on and off {{< fa x >}}
::: 

::: {.w-50-ns}
### Module 2: Enhancing content

- How to edit content {{< fa x >}}
- Write optional assessment prompts {{< fa x >}}
:::

::::

## 'Michael-in-a-Box' (TBD)

As a solutions architect who is new to {{< var vm.product >}}, learn how to set up a demo account and walk your customer through the platform.

::: {.attn-red}

:::: {.flex .flex-wrap .justify-around}

::: {.w-30-ns}
{{< fa x >}} **No course**

- TBD
:::

::: {.w-30-ns}
{{< fa x >}} **No videos**

- TBD
:::

::: {.w-30-ns}
**Notes**

- Need to talk to Michael and Hannes
- Borrows from [these notebooks](https://docs.validmind.ai/releases/2025/2025-jan-31/release-notes.html#document-credit-risk-scorecard-models-using-xgboost)
:::

::::
:::

#### Module 1: TBD

- Notebooks that show running tests, test suites, single-function documentation
- LaTex formulas in JSON templates



