---
title: "Where do I find &hellip;?"
sidebar: validmind-training
---

Here's what professionals like you have asked us about ValidMind and where to find answers.

## Model inventory
<!-- [→ Administrator Fundamentals](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html){.button-green} -->

- How do I configure the model inventory? [→ Docs](https://docs.validmind.ai/guide/model-inventory/managing-model-inventory.html){.button-pink} 
- How do I add model inventory fields? [→ Docs](https://docs.validmind.ai/guide/model-inventory/manage-inventory-custom-fields.html){.button-pink}

## User management and roles
<!-- [→ Administrator Fundamentals](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html){.button-green} -->

- How do I create new users and roles? [→ Training (Users)](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-4){.button-green}  [→ Training (Roles)](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-6){.button-green} [→ Docs](https://docs.validmind.ai/guide/managing-users/manage-users.html){.button-pink}
- How do I add users to roles? [→ Training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-4){.button-green} [→ Docs](https://docs.validmind.ai/guide/managing-users/manage-roles.html){.button-pink}
- How do I map users to specific groups? [→ Training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-4){.button-green} [→ Docs](https://docs.validmind.ai/guide/managing-users/manage-groups.html){.button-pink}

## Workflows for model lifecycle management
<!-- [→ Administrator Fundamentals](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html){.button-green} -->

- How do I modify or configure workflows for my use case? [→ Training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-12){.button-green} [→ Docs](https://docs.validmind.ai/guide/model-workflows/working-with-model-workflows.html){.button-pink}
- How do I configure workflows for MRM? [→ Training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-12){.button-green} [→ Docs](https://docs.validmind.ai/guide/model-workflows/set-up-model-workflows.html){.button-pink}
- How do I add users into workflows? [→ Docs](https://docs.validmind.ai/guide/managing-users/manage-roles.html){.button-pink}

## Templates for model documentation & validation reports
<!-- [→ Administrator Fundamentals](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html){.button-green} -->

- How do I edit templates? [→ Docs](https://docs.validmind.ai/guide/model-documentation/customize-documentation-templates.html){.button-pink}
- How do I add tests to templates? [→ Docs](https://docs.validmind.ai/guide/model-documentation/customize-documentation-templates.html){.button-pink}
- How do I swap templates? [→ Docs](https://docs.validmind.ai/guide/model-documentation/customize-documentation-templates.html){.button-pink}

## Model documentation
<!-- [→ Training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} -->

- How do I register a model with existing template? [→ Training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} [→ Docs](https://docs.validmind.ai/guide/model-inventory/register-models-in-inventory.html){.button-pink}
- How do I generate documentation for models? [→ Training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} [→ Docs](https://docs.validmind.ai/developers/documenting-models.html){.button-pink}
- How do I submit my model documentation for validation? [→ Training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} [→ Docs](https://docs.validmind.ai/guide/model-documentation/submit-for-approval.html){.button-pink}

## ValidMind content features, incl. GenAI
<!-- [→ ValidMind Content Features](https://docs.validmind.ai/training/validmind-content-features/validmind-content-features.html){.button-green} -->

<!-- - How do I use GenAI to enhance content? [→ ValidMind Content Features](https://docs.validmind.ai/training/validmind-content-features/validmind-content-features.html){.button-green} -->
<!-- - Where and how to enhance content [→ ValidMind Content Features](https://docs.validmind.ai/training/validmind-content-features/validmind-content-features.html){.button-green} -->
<!-- - How do I turn GenAI generation on/off [→ ValidMind Content Features](https://docs.validmind.ai/training/validmind-content-features/validmind-content-features.html){.button-green} -->

## Model testing
<!-- [→ Developer Fundamentals](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} -->

- How do I create custom tests? [→ Training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} [→ Docs](https://docs.validmind.ai/developers/run-tests-and-test-suites.html){.button-pink}
- How do I reuse existing tests for comparison tests? [→ Training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} [→ Docs](https://docs.validmind.ai/developers/run-tests-and-test-suites.html){.button-pink}

## Model validation
[→ Training](https://docs.validmind.ai/training/validator-fundamentals/validator-fundamentals.html){.button-green}

- How do I work with validation reports? [→ Training](https://docs.validmind.ai/training/validator-fundamentals/validator-fundamentals.html){.button-green} [→ Docs](https://docs.validmind.ai/guide/model-validation/working-with-model-findings.html){.button-pink}
- How do I submit validation reports for approval? [→ Training](https://docs.validmind.ai/training/validator-fundamentals/validator-fundamentals.html){.button-green} [→ Docs](https://docs.validmind.ai/guide/model-documentation/submit-for-approval.html){.button-pink}

## Monitoring
<!-- [→ Monitoring Fundamentals](https://docs.validmind.ai/training/monitoring-fundamentals/monitoring-fundamentals.html){.button-pink} (FORTHCOMING) -->

- How do I set up monitoring? [→ Docs](https://docs.validmind.ai/guide/monitoring/ongoing-monitoring.html){.button-pink}
- How do I integrate monitoring with documentation process? [→ Docs](https://docs.validmind.ai/guide/monitoring/ongoing-monitoring.html){.button-pink} 
- How do I schedule quarterly/monthly runs [**TBD**]<!-- [→ Docs](https://docs.validmind.ai/training/monitoring-fundamentals/monitoring-fundamentals.html){.button-pink} (FORTHCOMING)-->
 
## Data management
<!-- [→ Developer Fundamentals](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-green} -->

- How do I work with reference datasets? [→ Docs](https://docs.validmind.ai/developers/documenting-models.html){.button-pink}
- Can we connect to external data sources? [Part of using Pandas, not specific to ValidMind]