---
title: "Mapping the curriculum"
---

## Nik: Customer questions
- How to add tests to the template?
- How to add model inventory fields?
- How to modify workflows?
- How to map a particular user to a particular group?
- How to set up a new user, role, and add that user into the workflow?
- How to edit templates?
- Why couldn’t I edit a chart in the output?
- How to use GenAI to enhance content?
    - Where and how to enhance content?
- Can we connect to data sources?  [Not supported]
- Walk me through the reference data set creation
- How does monitoring integrate with documentation process?
    - How to schedule quarterly or monthly runs?

## Mehdi: Customer questions
Training topics — training brings pieces together, is scenario-based and end-to-end
- How to configure the model inventory?
- How to configure workflows for MRM
- How to create new users, new roles and add users to role
- How to create/edit/swap templates
- How to register a model with existing template
- How to generate documentation for my model and submit for validation
- How to play with content
    - How to change GenAI, turn it on and off
    - How to create custom test 
    - How to reuse existing tests to create new comparison tests
- How to use validation report
- How to set up monitoring 
