# init { #validmind.init }

```python
init(
    project=None,
    api_key=None,
    api_secret=None,
    api_host=None,
    model=None,
    monitoring=False,
)
```

Initializes the API client instances and calls the /ping endpoint to ensure
the provided credentials are valid and we can connect to the ValidMind API.

If the API key and secret are not provided, the client will attempt to
retrieve them from the environment variables `VM_API_KEY` and `VM_API_SECRET`.

## Parameters {.doc-section .doc-section-parameters}

| Name       | Type   | Description                                                       | Default   |
|------------|--------|-------------------------------------------------------------------|-----------|
| project    | str    | The project CUID. Alias for model. Defaults to None. [DEPRECATED] | `None`    |
| model      | str    | The model CUID. Defaults to None.                                 | `None`    |
| api_key    | str    | The API key. Defaults to None.                                    | `None`    |
| api_secret | str    | The API secret. Defaults to None.                                 | `None`    |
| api_host   | str    | The API host. Defaults to None.                                   | `None`    |
| monitoring | bool   | The ongoing monitoring flag. Defaults to False.                   | `False`   |

## Raises {.doc-section .doc-section-raises}

| Name   | Type       | Description                                |
|--------|------------|--------------------------------------------|
|        | ValueError | If the API key and secret are not provided |