# log_metric { #validmind.log_metric }

```python
log_metric(key, value, inputs=None, params=None, recorded_at=None)
```

Logs a unit metric

Unit metrics are key-value pairs where the key is the metric name and the value is
a scalar (int or float). These key-value pairs are associated with the currently
selected model (inventory model in the ValidMind Platform) and keys can be logged
to over time to create a history of the metric. On the ValidMind Platform, these metrics
will be used to create plots/visualizations for documentation and dashboards etc.

## Parameters {.doc-section .doc-section-parameters}

| Name        | Type   | Description                                                                | Default    |
|-------------|--------|----------------------------------------------------------------------------|------------|
| key         | str    | The metric key                                                             | _required_ |
| value       | float  | The metric value                                                           | _required_ |
| inputs      | list   | A list of input IDs that were used to compute the metric.                  | `None`     |
| params      | dict   | Dictionary of parameters used to compute the metric.                       | `None`     |
| recorded_at | str    | The timestamp of the metric. Server will use current time if not provided. | `None`     |