<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
::: {.panel-tabset}
#### Add artifact statuses

a. Click **{{< fa plus >}} Add Status**.

b. Enter in a **[name]{.smallcaps}** and assign a **[color]{.smallcaps}** to your artifact status.

c. When you are done, click **Add Status** to create your new status.

#### Edit or delete artifact statuses

a. Hover over the artifact status you'd like to modify.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select:

    - **{{< fa pencil >}} Edit Details** to change the **[name]{.smallcaps}** or **[color]{.smallcaps}** of the status, then click **Update Status** to apply your changes.
    - [**{{< fa trash-can >}} Delete Status**]{.red} to remove the status. After you confirm, the status will be deleted.

::: {.callout-important title="Artifact status deletion is permanent and cannot be undone."}

Artifact statuses cannot be deleted if in use on an artifact. Ensure that the status you're deleting is not associated with any artifacts before proceeding.
:::

:::

::::


:::: {.content-hidden unless-format="revealjs"}
#### Add artifact statuses

a. Click **{{< fa plus >}} Add Status**.

b. Enter in a **[name]{.smallcaps}** and assign a **[color]{.smallcaps}** to your artifact status.

c. When you are done, click **Add Status** to create your new status.

#### Edit artifact statuses

::: {.embed .pr3 .pl3 .f5 .mb3}
**[{{< fa square >}}]{.red} Closed** and **[{{< fa square >}}]{.green} Open** are [[{{< fa lock >}} default]{.smallcaps}]{.bubble} stages, meaning they cannot be modified or removed.
:::

a. Hover over the artifact status you'd like to modify.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa pencil >}} Edit Details** to change the **[name]{.smallcaps}** or **[color]{.smallcaps}** of the status.

c. Click **Update Status** to apply your changes.

::::