
:::: {.content-visible unless-format="revealjs"}
## Add artifact types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Artifacts, select **Artifact Types**.

3. Click **{{< fa plus >}} Add Artifact Type**.

4. Enter in a [name]{.smallcaps} and an optional [description]{.smallcaps} for your artifact type.

5. Click **Create** to create your new artifact type.

6. Click on your newly created artifact type to edit its details and permissions.

7. Enter in the artifact type's details:

    - **[fields]{.smallcaps}** — Select the default artifact fields that should appear on this type of artifact.[^add-fields-callout]
    - **[model fields display]{.smallcaps}**[^add-model-fields-config] — Select which upstream model inventory fields^[[Edit model inventory fields](/guide/model-inventory/edit-model-inventory-fields.qmd)] to display as read-only under the Model Information section on artifacts of this type.
    - **[artifact statuses]{.smallcaps}** — Configure the statuses available to this artifact type.^[[Manage artifact type statuses](#manage-artifact-type-statuses)]

8. Select the artifact type's permissions:

    - **[create permissions]{.smallcaps}** — Model stakeholder types or user roles[^add-permissions] that can create this type of artifact.
    - **[update permissions]{.smallcaps}** — Model stakeholder types or user roles that can update existing artifacts of this type.

## Edit artifact types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Artifacts, select **Artifact Types**.

3. Click the existing artifact type you want to edit.

4. Make your desired changes to the artifact type's details:

    - **[name]{.smallcaps}**
    - **[description]{.smallcaps}**
    - **[fields]{.smallcaps}** — Select the default artifact fields that should appear on this type of artifact.[^edit-fields-callout]
    - **[model fields display]{.smallcaps}**[^edit-model-fields-config] — Select which upstream model inventory fields^[[Edit model inventory fields](/guide/model-inventory/edit-model-inventory-fields.qmd)] to display as read-only under the Model Information section on artifacts of this type.
    - **[artifact statuses]{.smallcaps}** — Configure the statuses available to this artifact type.^[[Manage artifact type statuses](#manage-artifact-type-statuses)]

5. Make your desired changes to the artifact type's permissions:

    - **[create permissions]{.smallcaps}** — Model stakeholder types or user roles[^edit-permissions] that can create this type of artifact.
    - **[update permissions]{.smallcaps}** — Model stakeholder types or user roles that can update existing artifacts of this type.
::::

<!-- ADDITIONAL FOOTNOTES -->

[^add-fields-callout]:

    ::: {.callout title="Only default fields are available to be selected in this view."}
    To further customize fields displayed on artifact types, refer to: [Manage artifact fields](/guide/model-validation/manage-artifact-fields.qmd)

    :::

[^add-model-fields-config]:

    - Drag-and-drop fields to reorder them.
    - Click **Save Model Fields Configuration** to apply changes.

[^add-permissions]:

    - [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)
    - [Manage roles](/guide/configuration/manage-roles.qmd)

[^edit-fields-callout]:

    ::: {.callout title="Only default fields are available to be selected in this view."}
    To further customize fields displayed on artifact types, refer to: [Manage artifact fields](/guide/model-validation/manage-artifact-fields.qmd)

    :::

[^edit-model-fields-config]:

    - Drag-and-drop fields to reorder them.
    - Click **Save Model Fields Configuration** to apply changes.

[^edit-permissions]:

    - [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)
    - [Manage roles](/guide/configuration/manage-roles.qmd)



:::: {.content-hidden unless-format="revealjs"}

#### Add artifact types

a. Click **{{< fa plus >}} Add Artifact Type**.

b. Enter in a [name]{.smallcaps} and an optional [description]{.smallcaps} for your artifact type.

c. Click **Create** to create your new artifact type.

d. Click on your newly created artifact type to edit its details and permissions.

    Most changes are saved automatically. For **[model fields display]{.smallcaps}** configuration, click **Save Model Fields Configuration** to apply changes.

#### Edit artifact types

a. Click the existing artifact type you want to edit.

b. Make your desired changes to the artifact type's details and permissions.

    Most changes are saved automatically. For **[model fields display]{.smallcaps}** configuration, click **Save Model Fields Configuration** to apply changes.

::::


