:::: {.content-visible unless-format="revealjs"}

::: {.panel-tabset}

#### Add finding fields

To add a new finding field, click **{{< fa plus >}} Add Field**:

a. Finding fields require a **[type]{.smallcaps}**,^[[Finding field types](/guide/model-validation/manage-model-finding-fields.qmd#finding-field-types)] a **[name]{.smallcaps}**, and a **[finding type]{.smallcaps}**.^[[Manage finding types](/guide/model-validation/manage-finding-types.qmd)]

    - (Optional) Enter a **[description]{.smallcaps}** to indicate the purpose of the field.
    - (Optional) You can also choose to indicate that a field is **[required when creating findings]{.smallcaps}**.
    - (Optional) You can also assign a field to a group.^[[Add finding field groups](/guide/model-validation/manage-model-finding-fields.qmd#add-finding-field-groups)]
    - Assign **[write permissions]{.smallcaps}** to allow granular access to editing this field gated by model stakeholder types or user roles. Leave this field blank for default permissions where only the [{{< fa hand >}} Customer Admin]{.bubble} role has write access.[^edit-finding-fields]

a. When you are satisfied with the setup of your finding field, click **Save**.

#### Edit finding fields

To edit an existing finding field:

a. Click on the finding field you would like to edit.

    Expand any inventory field group to see more fields.^[[Add finding field groups](/guide/model-validation/manage-model-finding-fields.qmd#add-finding-field-groups)]

a. Make your desired changes to your finding field, then click **Save**.

:::

<!-- ADDITIONAL FOOTNOTES -->

[^edit-finding-fields]:

    ::: {.callout}
    ## All other users will have read-only access unless specified under the **[write permissions]{.smallcaps}**.

    - [**Model Stakeholders**](/guide/configuration/manage-model-stakeholder-types.qmd) — Write permissions on a per model basis.
    - [**Application Roles**](/guide/configuration/manage-roles.qmd) — Write permissions on a per field basis across all findings.

    :::

::::


:::: {.content-hidden unless-format="revealjs"}
1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under Findings, select **Finding Fields**. Here you can edit existing finding fields, or add a new one:

    - Click **{{< fa plus >}} Add Field** to add a new field.
    - Click on an existing field to edit that field.

1. Finding fields require a **[type]{.smallcaps}**, a **[name]{.smallcaps}**, and a **[finding type]{.smallcaps}**.

    - (Optional) Enter a **[description]{.smallcaps}** to indicate the purpose of the field.
    - (Optional) You can also choose to indicate that a field is **[required when creating findings]{.smallcaps}**.
    - (Optional) You can also assign a field to a group.
    - Assign **[write permissions]{.smallcaps}** to allow granular access to editing this field gated by model stakeholder types or user roles.

1. When you are satisfied with the setup of your finding field, click **Save**.

::::


