<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
See the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
::: {.panel-tabset}

#### View all validation issues

In the left sidebar, click **{{< fa triangle-exclamation >}} Validation Issues** to view a list of validation issues across all models:

- Filter this list to include only validation issues you want to see,^[[Filter and sort artifacts](/guide/model-validation/view-filter-artifacts.qmd#filter-and-sort-artifacts)] or toggle visibilty for column headers.^[[Customize artifact layouts](/guide/model-validation/customize-artifact-layouts.qmd)]

- Click on any validation issue for more information, including the proposed remediation plan and any supporting attachments.^[[Manage supporting documentation](/guide/model-validation/add-manage-artifacts.qmd#manage-supporting-documentation)]

   Attachments are listed with the following information:

   - Filename
   - Icon representing file type
   - Date uploaded
   - The user who uploaded the file
   - File size
   - Notes

   Click on the attachment to view or download the file.

#### View all other artifacts

1. In the left sidebar, click **{{< fa border-all >}} Artifacts** to view lists of other artifact types across all models.

1. Select an artifact type^[[Manage artifact types](/guide/model-validation/manage-artifact-types.qmd)] to view from the tabs:

   - Policy Exception
   - Model Limitation

   In the page that opens is a list of all artifacts for that type.

   - Filter this list to include only artifacts you want to see,^[[Filter and sort artifacts](/guide/model-validation/view-filter-artifacts.qmd#filter-and-sort-artifacts)] or toggle visibilty for column headers.^[[Customize artifact layouts](/guide/model-validation/customize-artifact-layouts.qmd)]
   -  Click on any artifact for more information.


:::

::::

:::: {.content-hidden unless-format="revealjs"}

#### View all validation issues

To view a list of validation issues across all models:

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Validation Issues**.

    [Filter this list](/guide/model-validation/view-filter-artifacts.qmd#filter-and-sort-artifacts){target="_blank"} to include only validation issues you want to see, or [toggle visibilty for column headers](/guide/model-validation/customize-artifact-layouts.qmd){target="_blank"}.

1. Click on any validation issue for more information, including the proposed remediation plan and [any supporting attachments](/guide/model-validation/add-manage-artifacts.qmd#manage-supporting-documentation){target="_blank"}.

   Attachments are listed with the following information:

   - Filename 
   - Icon representing file type
   - Date uploaded
   - The user who uploaded the file
   - File size
   - Notes

   Click on the attachment to view or download the file.

#### View all other artifacts

To view lists of other artifact types across all models:

1. In the left sidebar, click **{{< fa border-all >}} Artifacts**.

1. Select an [artifact type](/guide/model-validation/manage-artifact-types.qmd){target="_blank"} to view from the tabs:

   - Policy Exception
   - Model Limitation

   In the page that opens is a list of all artifacts for that type.

    [Filter this list](/guide/model-validation/view-filter-artifacts.qmd#filter-and-sort-artifacts){target="_blank"} to include only artifacts you want to see, or [toggle visibilty for column headers](/guide/model-validation/customize-artifact-layouts.qmd){target="_blank"}.

1. Click on any artifact for more information.

::::