---
title: "Add and update model findings"
date: last-modified
---

Use the {{< var vm.platform >}} to track detailed findings across all your models. From status and severity to proposed remediation plans and due dates, ValidMind allows you to oversee the minutiae to ensure organizational compliance. 

::: {.prereq}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model is already registered in the model inventory.[^1]
- [x] Model documentation is completed or in progress for your model.[^2]
- [x] You are a `Validator` or assigned another role with sufficient permissions to perform the tasks in this guide.[^3] 

:::

## Add model findings

{{< include _add-model-findings.qmd >}}

#### Add finding via overview

To log a finding from the documentation overview: 

1. On your model's **Documentation** page, click **{{< fa plus >}} Add Finding**.

2. On the **Add Model Finding** page that opens, provide information for: 

   - Title
   - Risk area
   - Owner
   - Severity
   - Due date
   - Documentation section
   - Description

   <!-- At a minimum, you must provide the required information indicated by `*`. -->

3. When you are done, click **Save** to submit the finding. 

   Once created, you can then add supporting documentation to your finding.[^4]

#### Add finding via section

While working within a section of your documentation, you can easily log a finding associated with that section without leaving the page:

1. Click on **ValidMind Insights™** to expand the insight panel.

2. For the section you want to add a Finding for, click **{{< fa triangle-exclamation >}}  Add Finding** beneath the Documentation Guidelines.

3. On the **Add Model Finding** page that opens,  provide information for: 

   - Title
   - Risk area
   - Owner
   - Severity
   - Due date
   - Documentation section
   - Description

   <!-- At a minimum, you must provide the required information indicated indicated by <b>*</b>.  -->
   
   The documentation section will be auto-populated with the section you are working from — you are able to select another section if desired.

4. When you are done, click **Save** to submit the finding. 

   Once created, you can then add supporting documentation to your finding.[^5]

## Update model findings

As findings get resolved or require other changes during the model validation process, you can update them:

1. Locate the finding you want to update.[^6]

2. Make your updates to the finding. You can make updates to:

   - Title
   - Description
   - Proposed remediation plan
   - Status
   - Severity
   - Risk area
   - Due date
   - Assignee
   - Documentation section
   - Supporting documentation[^7]

Most updates are applied immediately but you must click **Save** to make changes to the finding description and proposed remediation plan effective. 

### Manage supporting documentation

After a finding is created, you're able to add supporting documentation to it. 

#### Add attachment to finding

::: {.callout}
Uploaded files must be less than 50 MB in size.
:::

1. On the findings detail page, click on **[attachments]{.smallcaps}**.

2. Click **{{< fa circle-plus >}} Add Attachment** to select a file.

3. Click **Save** to submit the upload.
   
Attachments are listed with the following information:

   - Filename
   - The user who uploaded the file
   - File size

   Click on the attachment to view or download the file. 

<!-- DELETION NOT OUT YET AS OF SEPT 2024 -->

<!-- #### Remove attachment from finding

1. On the findings detail page, locate the attachment you'd like to delete under **[attachments]{.smallcaps}**.
 
2. Click **{{< fa trash-can>}}** to remove the file. 

3. Click **Save** to confirm deletion. 

   After you confirm, the attachment will be removed from the finding -->


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Manage supporting documentation](#manage-supporting-documentation)

[^5]: [Manage supporting documentation](#manage-supporting-documentation)

[^6]: [View and filter model findings](view-filter-model-findings.qmd)

[^7]: [Manage supporting documentation](#manage-supporting-documentation)