---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Assess compliance"
date: last-modified
aliases:
  - /guide/assess-compliance.html
---

Use the {{< var validmind.platform >}} to assess compliance of your models with guidelines based on analyzing evidence and artifacts.

Compliance assessments provide an unbiased starting point that enables more efficient discussions between validators and developers and involves three steps:

1. [Link evidence to reports](#link-evidence-to-reports)
2. [Link artifacts to reports](#link-artifacts-to-reports)
3. [Provide compliance assessments](#provide-compliance-assessments)

::: {.callout title="Compliance assessments cannot be performed on static PDF documents."}
You can only assess compliance for PDFs converted to editable documents,[^1] validation reports generated by the {{< var validmind.developer >}}, or validation reports created in the {{< var validmind.platform >}}.
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model you are validating is registered in the model inventory.[^2]
- [x] A model developer has submitted their model documentation for validation.[^3]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^4] 

:::

## Link evidence to reports

### Link developer evidence

To link evidence logged by developers^[[{{< var validmind.developer >}}](/developer/validmind-library.qmd)] to your validation report:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^5]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** tab.[^6]

4. Click on a Validation Report type file.[^7]

   Expand any subsection of the validation report you would like to work with.

5. In any section of the report where the button is available, click **{{< fa link >}} Link Developer Evidence**. 

6. On the **Link Developer Evidence to Validation Report** page that opens, select the evidence that is related to your assessment. 
   
   - Available evidence is associated with the relevant documentation section. 
   - If you are not sure if something is relevant, you can expand the section by clicking **{{< fa chevron-down >}}** for more details.

7. Click **Update Linked Evidence**.

   - Confirm that the newly linked-to evidence shown under Developer Evidence is accurate and is connected to the correct documentation section.
   - Evidence that needs your attention gets flagged with [{{< fa triangle-exclamation >}} Requires Attention]{.bubble .yellow-bg}. These sections get flagged automatically whenever a test result is above or below a certain threshold.

### Link validator evidence

{{< include _link-validator-evidence.qmd >}}

## Link artifacts to reports

{{< include _link-artifacts-to-reports.qmd >}}

## Provide compliance assessments

{{< include _provide-compliance-assessments.qmd >}}


<!-- FOOTNOTES -->

[^1]: [Manage model documents](/guide/templates/manage-model-documents.qmd#upload-pdf-documents)

[^2]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^3]: [Submit for approval](/guide/model-documentation/submit-for-approval.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^6]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^7]: [Preparing validation reports](/guide/model-validation/preparing-validation-reports.qmd#validation-report-overview)
