---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Configure assessment options"
date: last-modified
---

{{< include _assessment-options.qmd >}}

::: {.callout title="By default, new validation report templates include four suggested default assessment options."}
You can add, edit, delete, and reorder these options, or remove them entirely to disable assessments.

:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to manage validation report templates.[^1]

:::

To configure assessment options on individual validation report templates:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Documents, select **Templates**.[^2]

3. Select the **Validation** tab.

4. Click the validation report template you want to configure assessment options for.

5. Under the Assessment Options section, add, edit, reorder, or delete assessment options as desired.

   To disable assessments for a template, delete all assessment options.[^3]

::: {.panel-tabset}

#### Add an option

a. Click **{{< fa plus >}} Add Assessment Option**.

b. Provide the details for your assessment option:

   - **[name]{.smallcaps}** (required) — A short label for the option, between 2 and 50 characters.
   - **[description]{.smallcaps}** (optional) — A longer explanation of what the option means.
   - **[color]{.smallcaps}** (required) — Select a color from the color palette to visually distinguish this option.

c. Click **Add Option** to insert the new option into that validation report template.

#### Edit an option

a. Hover over the assessment option you want to edit.

b. When **{{< fa ellipsis-vertical >}}** appears, select **{{< fa pencil >}} Edit Option**.

c. Update the details for your assessment option:

   - **[name]{.smallcaps}** (required) — A short label for the option, between 2 and 50 characters.
   - **[description]{.smallcaps}** (optional) — A longer explanation of what the option means.
   - **[color]{.smallcaps}** (required) — Select a color from the color palette to visually distinguish this option.

d. Click **Update Option** to apply your changes.

#### Delete an option

::: {.callout-important title="Assessment option deletion is permanent and cannot be undone."}
Assessment options can only be deleted if they are not assigned to sections in active validation reports.

:::

a. Hover over the assessment option you want to edit.

b. When **{{< fa ellipsis-vertical >}}** appears, select [**{{< fa trash-can >}} Delete Option**]{.red}.

c. Click **Delete Assessment Option** to confirm removal of that option.

#### Reorder options

a. Click and hold an assessment option and drag-and-drop to rearrange the order.

b. After reordering, click **Save** to apply your changes.

:::


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Customize document templates](/guide/templates/customize-document-templates.qmd)

[^3]: Validation reports using that template will no longer display the assessment dropdown or assessment summaries.