---
title: "Customize artifact layouts"
date: last-modified
aliases: 
  - customize-model-findings-layouts.qmd
---

Configure the information that displays by default on the list of all tracked model artifacts for each artifact type.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] There are artifacts logged on any model.[^2]

:::

## Customize artifact layouts by type

:::{.callout}
Changes are automatically saved to your account and do not affect other users.
:::

Customize what is displayed on your list of all artifacts for each artifact type:

::: {.panel-tabset}

#### Customize layout for validation issues

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Validation Issues** to view a list of validation issues across all models:

2. Click **{{< fa table >}} Manage Columns**.

   - Search for a column name in the list to narrow down results.
   - Toggle visibility for each item and drag each option to change the order.
   - Available columns are determined by your artifact fields.[^3]

Once customized, you can save a view for later application.[^4]

#### Customize layout for all other artifact types

1. In the left sidebar, click **{{< fa border-all >}} Artifacts** to view lists of other artifact types across all models.

2. Select an artifact type[^5] to view from the tabs:

   - Policy Exception
   - Model Limitation

   In the page that opens is a list of all artifacts for that type.

3. Click **{{< fa table >}} Manage Columns**.

   - Search for a column name in the list to narrow down results.
   - Toggle visibility for each item and drag each option to change the order.
   - Available columns are determined by your artifact fields.[^6]

Once customized, you can save a view for later application.[^7]

:::

## Manage custom artifact views

:::{.callout}
Saved views are unique to you and do not display for other users in your organization.
:::


### Save artifact views

You can save custom artifact configurations as a view to reapply at any time for each artifact type:

1. First, customize a artifact layout.[^6]

   You can also apply filters or sorting before saving your view to include them in the view.[^8]

{{< include /guide/model-inventory/_save-layout-view.qmd >}}

### Edit or remove saved artifact views

::: {.callout-important}
Deletion of saved views is permanent.
:::

::: {.panel-tabset}

#### Edit or remove validation issue views

To modify a saved validation issues view:

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Validation Issues** for a list of validation issues across all models.

{{< include /guide/model-inventory/_remove-layout-view.qmd >}}

#### Edit or remove all other artifact type views

To modify a saved view for all other artifact types:

1. In the left sidebar, click **{{< fa border-all >}} Artifacts** for lists of other artifact types across all models.

2. Select an artifact type[^9] for a list of that artifact type:

   - Policy Exception
   - Model Limitation

{{< include /guide/model-inventory/_remove-layout-view.qmd >}}

:::


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Add and manage artifacts](add-manage-artifacts.qmd)

[^3]: [Manage artifact fields](manage-artifact-fields.qmd)

[^4]: [Manage custom artifact views](#manage-custom-artifact-views)

[^5]: [Manage artifact types](/guide/model-validation/manage-artifact-types.qmd)

[^6]: [Manage artifact fields](manage-artifact-fields.qmd)

[^7]: [Manage custom artifact views](#manage-custom-artifact-views)

[^8]: [Filter and sort artifacts](view-filter-artifacts.qmd#filter-and-sort-artifacts)

[^9]: [Manage artifact types](/guide/model-validation/manage-artifact-types.qmd)
