---
title: "Customize model findings layout"
date: last-modified
---

Configure the information that displays by default on the list of all tracked model findings.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] There are findings logged on any model.[^2]

:::

## Customize model findings layout

:::{.callout}
Changes are automatically saved to your account and do not affect other users.
:::

Customize what is displayed on your list of all model findings:

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Findings** for the list of all model findings.

2. Select a finding type[^9] to view from the tabs:

   - Validation Issue
   - Policy Exception
   - Model Limitation

3. Click **{{< fa table >}} Manage Columns**.

   - Search for a column name in the list to narrow down results.
   - Toggle visibility for each item and drag each option to change the order.
   - Available columns are determined by your model finding fields.[^10]

Once customized, you can save a view for later application.[^11]

### Manage custom findings views

:::{.callout}
Saved views are unique to you and do not display for other users in your organization.
:::

::: {.panel-tabset}

#### Save a findings view

You can save custom findings configuration as a view to reapply at any time:

1. Customize a findings layout.[^12]

   You can also apply filters or sorting before saving your view to include them in the view.[^13]

{{< include /guide/model-inventory/_save-layout-view.qmd >}}

#### Edit or remove saved findings view

::: {.callout-important}
Deletion of saved views is permanent.
:::

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Findings** for the list of all model findings.

{{< include /guide/model-inventory/_remove-layout-view.qmd >}}

:::


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Add and manage model findings](add-manage-model-findings.qmd)

