---
title: "Customize artifact overview page"
date: last-modified
aliases: 
  - customize-finding-overview-page.html
---

Configure what and how artifact fields appear when you pull up artifacts logged on models.

:::{.callout title="Changes are automatically saved to your account and do not affect other users."}
Customizations will apply to all artifacts in your inventory.

:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] There are artifacts logged on models.[^2]

:::

## Show or hide fields

::: {.callout title="Only custom artifact fields can be shown or hidden."}
Default fields will always appear on your artifact overview pages and are represented by by faded cells. Their positions cannot be adjusted.
:::

1. Open an artifact logged on any model.[^3]

2. Click on **{{< fa table-cells-large >}} Customize Layout**.

3. On the Customize Section Layout modal that appears, configure the artifact fields[^4] that appear:

   - Toggle optional artifact fields or field groups on or off to show or hide them from view.
   - Click and hold a field or field group to drag-and-drop to rearrange the order of fields and field groups. Fields and field groups can be moved from the Side Column to the Main Column and vice versa.[^5]

   To narrow down your list of fields, search via the **{{< fa filter >}} Filter** bar.

4. Click **Save Layout** to apply your changes to all model overview pages.


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Add and manage artifacts](add-manage-artifacts.qmd)

[^3]: [View and filter artifacts](view-filter-artifacts.qmd)

[^4]: [Manage artifact fields](/guide/model-validation/manage-artifact-fields.qmd#finding-field-types)

[^5]: `Attachments` or `Long Text` type fields can only be placed in the Main Column.
