---
title: "Edit validation guidelines"
date: last-modified
---

Edit the guidelines for validation reports to ensure that you are compliant your organization's requirements.

::: {.prereq}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a `Customer Admin` or `Validator`, or assigned another role with sufficient permissions to perform the tasks in this guide.[^1] 

:::

## Steps

1. In the left sidebar, click **{{< fa gear >}} Settings**. 

2. Under Workplace Settings, select **Risk Areas & Validation Guidelines**.

3. Add, edit, or delete risk areas and their associated guidelines as required.

    Once a risk area is added, you can then manage guidelines[^2] associated with that risk area.

#### Manage risk areas

To add a risk area:

1. click **+ Add Risk Area**.

2. Provide a **Name** and **Description** for your risk area:

    - Click **Add Risk Area** to save your changes
    - Click **x** to cancel and return to the previous menu.

To edit a risk area:

1. Hover over the title of a risk area until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

2. Select **{{< fa pencil>}} Edit Risk Area**.

3. Make your desired changes to the risk area's **Name** and **Description**:

    - Click **Save Risk Area** to save your changes.
    - Click **x** to cancel and return to the previous menu.

To delete a risk area:

::: {.callout-important}
Please note that any guidelines associated with a risk area will need to be deleted before the risk area can be removed.
:::

1. Hover over the title of a risk area until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

2. Select **{{< fa trash-can>}} Delete Risk Area**.

3. Once you confirm, that risk area will be removed.


#### Manage guidelines

To add a guideline:

1. Hover over the title of a risk area you want to add a guideline to until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

2. Select **+ Add Guideline**.

3. Provide a **Title** and **Description** for your guideline:

    - Click **Add Guideline** to save your changes
    - Click **x** to cancel and return to the previous menu.

To edit a guideline:

1. Expand the menu for a risk area by clicking **{{< fa chevron-down >}}**.

2. Once you've located the guideline you'd like to edit, hover over the title of the guideline until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

3. Select **{{< fa pencil>}} Edit Guideline**.

4. Make your desired changes to the risk area's **Title** and **Description**:

    - Click **Save Guideline** to save your changes.
    - Click **x** to cancel and return to the previous menu.

To delete a guideline:

1. Expand the menu for a risk area by clicking **{{< fa chevron-down >}}**.

2. Once you've located the guideline you'd like to delete, hover over the title of the guideline until the **{{< fa ellipsis-vertical >}}** menu appears, then click on it.

3. Select **{{< fa trash-can>}} Delete Guideline**.

3. Once you confirm, that guideline will be removed.




## What's next

<!---* [Create project findings](create-project-findings.qmd)--->
- [Preparing validation reports](preparing-validation-reports.qmd)
- [Assess compliance](assess-compliance.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Manage guidelines](#manage-guidelines)



