---
title: "Manage validation guidelines"
date: last-modified
aliases:
  - view-validation-guidelines.html
  - /guide/view-validation-guidelines.html
---

Edit the guidelines for validation reports to align them with organization's requirements, and add the guidelines to your report templates to ensure that they are ready for use.

To set up validation guidelines, you'll need to complete these two steps in sequence:

1. [Set up validation guidelines](#set-up-validation-guidelines)
2. [Add guidelines to templates](#add-guidelines-to-templates)

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble}, or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Set up validation guidelines

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Risk Areas & Validation Guidelines**.

3. Add, edit, or delete risk areas and their associated guidelines as required.

    - Once a risk area is added, you can then manage guidelines[^2] associated with that risk area.
    - Once guidelines are set up, you can then add them to your validation report templates.[^3]

### Manage risk areas

{{< include /guide/model-validation/_risk-areas.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Risk Areas & Validation Guidelines**.

::: {.panel-tabset}

#### Add risk areas

{{< include /guide/model-validation/_add-risk-areas.qmd >}}

#### Edit risk areas

a. Hover over the risk area you want to edit.

b. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa pencil>}} Edit Risk Area**.

c. Make your desired changes to the risk area's **[name]{.smallcaps}** and **[description]{.smallcaps}**.

d. Click **Save Risk Area** to apply your changes.

#### Delete risk areas

::: {.callout-important}
Any guidelines associated with a risk area will need to be deleted before the risk area can be removed.
:::

a. Hover over the risk area you want to remove.

b. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select [**{{< fa trash-can>}} Delete Risk Area**]{.red}.

c. After you confirm, that risk area will be removed.

:::

### Manage guidelines

{{< include /guide/model-validation/_validation-guidelines.qmd >}}

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Workspace, select **Risk Areas & Validation Guidelines**.

::: {.panel-tabset}

#### Add guidelines

{{< include /guide/model-validation/_add-validation-guidelines.qmd >}}

#### Edit guidelines

a. Expand the menu for a risk area by clicking **{{< fa chevron-down >}}**.

b. Hover over the guideline you want to edit.

c. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa pencil>}} Edit Guideline**.

d. Make your desired changes to the risk area's **[title]{.smallcaps}** and **[description]{.smallcaps}**.

e. Click **Save Guideline** to apply your changes.

#### Delete guidelines

::: {.callout-important title="Deleting a guideline will remove it from any associated templates without creating a new version of the template."}
You are also unable to delete any guidelines with assessments in validation reports assigned to them.
:::

a. Expand the menu for a risk area by clicking **{{< fa chevron-down >}}**.

b. Hover over the guideline you want to delete.

c. When the  **{{< fa ellipsis-vertical >}}** menu appears, click on it and select [**{{< fa trash-can>}} Delete Guideline**]{.red}.

d. After you confirm, that guideline will be removed.

:::

## Add guidelines to templates

::: {.callout title="To configure validation templates, you must have sufficient guideline and template permissions."}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has all these permissions.[^4]
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**. 

2. Under Workspace, select **Templates**.[^5]

3. Select the **Validation Report** tab, then click on the template you want to edit.

4. On the template details page, click **{{< fa pencil >}} Edit Outline**.

5. For the section you'd like to add a guideline to,[^6] click **{{< fa plus >}}** and select **{{< fa circle-check >}} Guideline Block** under [content]{.smallcaps}.

6. Select the guidelines you'd like to add to that section, then click **{{< fa plus >}} Add # Guideline(s)** to save your changes.

7. When you're done, click **Create New Version** to view a side-by-side comparison of your changes with the previous version:
   - Add a description in **[version notes]{.smallcaps}** to track your changes.
   - Click **Save** to create the new version.

    Once saved, your new template version with the modified guidelines becomes available for use with your validation reports.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Manage guidelines](#manage-guidelines)

[^3]: [Add guidelines to templates](#add-guidelines-to-templates)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Customize document templates](/guide/templates/customize-document-templates.qmd)

[^6]:

    ::: {.callout}
    **{{< fa circle-check >}} Guideline Block**s can only be added to sections that do not contain any children.

    :::



