---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage artifact severities"
date: last-modified
aliases: 
  - manage-finding-severities.html
---

{{< include /guide/model-validation/_artifact-severities.qmd >}}

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Add artifact severities

{{< include /guide/model-validation/_add-artifact-severities.qmd >}}

## Edit artifact severities

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Artifacts, select **Artifact Severities**.

3. Hover over the severity you would like to edit.

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa pencil >}} Edit Severity**.

5. Make your changes to the **[name]{.smallcaps}** and **[color]{.smallcaps}** of the severity.

6. Click **Update Severity** to apply your edits.


## Reorder artifact severities

{{< include /guide/model-validation/_reorder-artifact-severities.qmd >}}

## Remove artifact severities

::: {.callout-important title="Removal of artifact severities is permanent."}
Severities can only be deleted if they are not in use by any artifacts.

:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Artifacts, select **Artifact Severities**.

3. Hover over the severity you would like to delete.

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select [**{{< fa trash-can >}} Delete Severity**]{.red}.

5. After you confirm, the severity will be removed from the list.


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)