---
title: "Manage finding types"
date: last-modified
aliases: 
  - manage-finding-statuses.html
---

Customize the fields and statuses that appear on finding types available to be logged on models in your inventory.

#### Available finding types

By default, the {{< var validmind.platform >}} provides three finding types:

Validation Issues
: Problems discovered during model validation that reflect errors, inconsistencies, or gaps in data, methodology, implementation, or documentation that need to be addressed before the model is considered reliable.

Policy Exception
: When a model or part of its development or usage does not comply with internal policies, regulatory requirements, or governance standards, but an explicit approval or waiver is granted to allow it under controlled conditions.

Model Limitation
: Inherent weaknesses or constraints of the model itself that cannot be fully resolved; definitions under which the model's results should be interpreted with caution.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Edit finding type

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Findings, select **Finding Types**.

3. Click on the finding type[^2] you want to edit:

    - Validation Issues
    - Policy Exception
    - Model Limitation

4. Make your desired changes to the finding type's details:

    - **[name]{.smallcaps}**
    - **[description]{.smallcaps}**
    - **[fields]{.smallcaps}** — Select the default finding fields that should appear on this type of finding.[^3]
    - **[finding statuses]{.smallcaps}** — Configure the statuses available to this finding type.[^4]

### Manage finding type statuses

::: {.callout}
`Open` and `Closed` are [Locked]{.bubble} stages, meaning they cannot be modified or removed.

:::

::: {.panel-tabset}

#### Add finding statuses

a. Click **{{< fa plus >}} Add Status**.

b. Enter in a **[name]{.smallcaps}** and assign a **[color]{.smallcaps}** to your finding status.

c. When you are done, click **Add Status** to create your new status.

#### Edit or delete statuses

a. Hover over the finding status you'd like to modify.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select:

    - **{{< fa pencil >}} Edit Details** to change the **[name]{.smallcaps}** or **[color]{.smallcaps}** of the status.
    - [**{{< fa trash-can >}} Delete Status**]{.red} to remove the status.

::: {.callout-important title="Finding status deletion is permanent and cannot be undone."}

Findings statuses cannot be deleted if in use on a finding. Ensure that the status you're deleting is not associated with any findings before proceeding.
:::

:::


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]: [Available finding types](#available-finding-types)

[^3]:

    ::: {.callout title="Only default fields are available to be selected in this view."}
    To further customize fields displayed on finding types, refer to: [Manage model finding fields](manage-model-finding-fields.qmd)

    :::

[^4]: [Manage finding type statuses](#manage-finding-type-statuses)
