---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage artifact types"
date: last-modified
aliases: 
  - manage-finding-statuses.html
  - manage-finding-types.html
---

Prepare to track the progress and resolution of artifacts by customizing artifact types and their associated statuses available to be logged on models in your inventory.

#### Available artifact types

By default, the {{< var validmind.platform >}} provides three artifact types:

Validation Issue
: Problems discovered during model validation that reflect errors, inconsistencies, or gaps in data, methodology, implementation, or documentation that need to be addressed before the model is considered reliable.

Policy Exception
: When a model or part of its development or usage does not comply with internal policies, regulatory requirements, or governance standards, but an explicit approval or waiver is granted to allow it under controlled conditions.

Model Limitation
: Inherent weaknesses or constraints of the model itself that cannot be fully resolved; definitions under which the model's results should be interpreted with caution.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^1]

:::

## Add artifact types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Artifacts, select **Artifact Types**.

3. Click **{{< fa plus >}} Add Artifact Type**.

4. Enter in a [name]{.smallcaps} and an optional [description]{.smallcaps} for your artifact type.

5. Click **Create** to create your new artifact type.

6. Click on your newly created artifact type to edit its details and permissions.

7. Enter in the artifact type's details:

    - **[fields]{.smallcaps}** — Select the default artifact fields that should appear on this type of artifact.[^2]
    - **[model fields display]{.smallcaps}**[^3] — Select which upstream model inventory fields[^4] to display as read-only under the Model Information section on artifacts of this type.
    - **[artifact statuses]{.smallcaps}** — Configure the statuses available to this artifact type.[^5]

8. Select the artifact type's permissions:

    - **[create permissions]{.smallcaps}** — Model stakeholder types or user roles[^6] that can create this type of artifact.
    - **[update permissions]{.smallcaps}** — Model stakeholder types or user roles that can update existing artifacts of this type.

## Edit artifact types

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under Artifacts, select **Artifact Types**.

3. Click the existing artifact type you want to edit.

4. Make your desired changes to the artifact type's details:

    - **[name]{.smallcaps}**
    - **[description]{.smallcaps}**
    - **[fields]{.smallcaps}** — Select the default artifact fields that should appear on this type of artifact.[^7]
    - **[model fields display]{.smallcaps}**[^8] — Select which upstream model inventory fields[^9] to display as read-only under the Model Information section on artifacts of this type.
    - **[artifact statuses]{.smallcaps}** — Configure the statuses available to this artifact type.[^10]

5. Make your desired changes to the artifact type's permissions:

    - **[create permissions]{.smallcaps}** — Model stakeholder types or user roles[^11] that can create this type of artifact.
    - **[update permissions]{.smallcaps}** — Model stakeholder types or user roles that can update existing artifacts of this type.

## Manage artifact type statuses

::: {.callout}
**[{{< fa square >}}]{.red} Closed** and **[{{< fa square >}}]{.green} Open** are [[{{< fa lock >}} default]{.smallcaps}]{.bubble} stages, meaning they cannot be modified or removed.

:::

::: {.panel-tabset}

#### Add artifact statuses

a. Click **{{< fa plus >}} Add Status**.

b. Enter in a **[name]{.smallcaps}** and assign a **[color]{.smallcaps}** to your artifact status.

c. When you are done, click **Add Status** to create your new status.

#### Edit or delete artifact statuses

a. Hover over the artifact status you'd like to modify.

b. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select:

    - **{{< fa pencil >}} Edit Details** to change the **[name]{.smallcaps}** or **[color]{.smallcaps}** of the status.
    - [**{{< fa trash-can >}} Delete Status**]{.red} to remove the status.

::: {.callout-important title="Artifact status deletion is permanent and cannot be undone."}

Artifact statuses cannot be deleted if in use on an artifact. Ensure that the status you're deleting is not associated with any artifacts before proceeding.
:::

:::


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^2]:

    ::: {.callout title="Only default fields are available to be selected in this view."}
    To further customize fields displayed on artifact types, refer to: [Manage artifact fields](manage-artifact-fields.qmd)

    :::

[^3]:

    - Drag-and-drop fields to reorder them.
    - Click **Save Model Fields Configuration** to apply changes.

[^4]: [Edit model inventory fields](/guide/model-inventory/edit-model-inventory-fields.qmd)

[^5]: [Manage artifact type statuses](#manage-artifact-type-statuses)

[^6]:

    - [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)
    - [Manage roles](/guide/configuration/manage-roles.qmd)

[^7]:

    ::: {.callout title="Only default fields are available to be selected in this view."}
    To further customize fields displayed on artifact types, refer to: [Manage artifact fields](manage-artifact-fields.qmd)

    :::

[^8]:

    - Drag-and-drop fields to reorder them.
    - Click **Save Model Fields Configuration** to apply changes.

[^9]: [Edit model inventory fields](/guide/model-inventory/edit-model-inventory-fields.qmd)

[^10]: [Manage artifact type statuses](#manage-artifact-type-statuses)

[^11]:

    - [Manage model stakeholder types](/guide/configuration/manage-model-stakeholder-types.qmd)
    - [Manage roles](/guide/configuration/manage-roles.qmd)



