---
title: "Manage custom reports"
lightbox: true
date: last-modified
---

Add, edit, or remove custom report pages and visualizations to your analytics within the {{< var validmind.platform >}}. 

- You can also add any of the report widgets to your personal dashboard.[^1]
- The out-of-the-box analytics pages (Models, Findings) cannot be modified. 

::: {.callout collapse="true" appearance="minimal"}
## {{< fa gears >}} Visualization configuration options

#### {{< fa chart-simple >}} Bar Chart

[metrics]{.smallcaps}
: def

[grouping]{.smallcaps}
: def

[filtering]{.smallcaps}
: def

#### {{< fa chart-pie >}} Pie Chart

[metrics]{.smallcaps}
: def

[grouping]{.smallcaps}
: def

[filtering]{.smallcaps}
: def

#### {{< fa hashtag >}} Counter

[metrics]{.smallcaps}
: def

[filtering]{.smallcaps}
: def

[color]{.smallcaps}
: Select the display color for the counter. 
:::

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^2] 

:::

## Add custom analytics

To add custom reports, you'll need to complete these two steps in sequence:

1. [Create an analytics page](#create-an-analytics-page)
2. [Create a visualization](#create-a-visualization)

#### Create an analytics page

1. In the left sidebar, click **{{< fa square-poll-vertical >}} Analytics**.

2. Click **{{< fa plus >}} Add Page**.

3. On the Add New Page module, enter in the:

    - **[page name]{.smallcaps}**
    - **[description]{.smallcaps}**

4. Click **Add New Page** to create your custom analytics page. 

#### Create a visualization

1. On **{{< fa square-poll-vertical >}} Analytics**, click on the tab for your custom page you'd like to add a visualization to. 

2. Click **{{< fa circle-plus >}}** to open the Add Visualization panel.

3. On the Add Visualization panel, enter in your **[title]{.smallcaps}**.

4. Select a **[visualization type]{.smallcaps}**:

    - **{{< fa chart-simple >}} Bar Chart**
    - **{{< fa chart-pie >}} Pie Chart**
    - **{{< fa hashtag >}} Counter**

5. Select a **[dataset]{.smallcaps}**:

    - **Findings**
    - **Inventory Models**

6. Select the visualization configuration options to apply to the dataset.[^3]

7. When you are done configuring your dataset, click **Add Visualization** to insert your visualization onto the analytics page.

For example, to create a 



## Edit custom analytics

1. On **{{< fa square-poll-vertical >}} Analytics**, click on the tab for your custom page you'd like to edit the visualization for.

2. Hover over the visualization you'd like to modify until the **{{< fa ellipsis-vertical >}}** icon appears, then click on it.

3. Select **{{< fa pencil >}} Edit Visualization**.

4. When you are finished with your adjustments, click **Save Visualization** to apply your changes.

## Remove custom analytics

::: {.callout-important title="Deletion of customized report setup is permanent."}
Removing a custom analytics page or visualization cannot be undone.
:::

You can either delete a entire custom analytics page, or remove a single custom visualization: 

#### Delete custom analytics page

1. In the left sidebar, click **{{< fa square-poll-vertical >}} Analytics**.

2. Click on the tab for your custom page you'd like to delete.

3. Click **{{< fa ellipsis-vertical >}}** in the top-right hand corner of the custom page.

4. Select **{{< fa trash-can >}} Delete Page**.

5. After you confirm the deletion, the page will be permanently removed. 


#### Delete custom visualizations

1. On **{{< fa square-poll-vertical >}} Analytics**, click on the tab for your custom page you'd like to delete a visualization for.

2. Hover over the visualization you'd like to remove until the **{{< fa ellipsis-vertical >}}** icon appears, then click on it.

3. Select **{{< fa trash-can >}} Remove Visualization**.




<!-- FOOTNOTES -->

[^1]: [Customize your dashboard](/guide/configuration/customize-your-dashboard.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Visualization configuration options](#visualization-configuration-options)