---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Preparing validation reports"
date: last-modified
listing:
  - id: draft-reports
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - review-model-documentation.qmd
      - assess-compliance.qmd
      - ../model-documentation/work-with-content-blocks.qmd
      - ../model-documentation/work-with-document-versions.qmd
  - id: complete-reports
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
      - ../model-documentation/collaborate-with-others.qmd
      - ../model-documentation/submit-for-approval.qmd
aliases:
  - /guide/preparing-validation-reports.html
---

Use the {{< var validmind.platform >}} to prepare detailed validation reports in adherence with your organization's guidelines. Link evidence and artifacts to your reports and assess compliance status at a granular level.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] The model you are validating is registered in the model inventory.[^1]
- [x] A model developer has submitted their model documentation for validation.[^2]
- [x] Validation guidelines are aligned with your organization's requirements and added to the correct validation templates.[^3]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^4] 

:::

## Key concepts

<!-- TO EDIT THESE KEY CONCEPTS, SEE `about/glossary/_validation-reports.qmd` -->

{{< include /about/glossary/validation_reports/_report-intro.qmd >}}

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}

{{< include /about/glossary/validation_reports/_risk-assessment.qmd >}}

{{< include /about/glossary/validation_reports/_risk-areas.qmd >}}

{{< include /about/glossary/validation_reports/_validation-guidelines.qmd >}}

{{< include /about/glossary/validation_reports/_artifacts.qmd >}}

:::

::: {.w-40-ns}

{{< include /about/glossary/validation_reports/_actions.qmd >}}

{{< include /about/glossary/validation_reports/_evidence.qmd >}}

{{< include /about/glossary/monitoring/_ongoing-monitoring.qmd >}}

:::

::::

## Validation Report Overview

::: {.callout title="Static PDF uploads do not include a Document Overview."}
Only PDFs converted to editable documents,[^5] reports generated by the {{< var validmind.developer >}}, or reports created in the {{< var validmind.platform >}} include a Validation Report Overview.
:::

The **Validation Report Overview** shows a section-by-section outline of your model's validation report, as well as summary of overall compliance.[^6]

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^7]

3. In the left sidebar that appears for your model, click **{{< fa file >}} Documents** and select the **Latest** or **Saved Versions** tab.[^8]

4. Click on a Validation Report type file.[^9]

### Add or edit validation reports

::: {.callout title="Static PDF uploads cannot be edited."}
Only PDFs converted to editable documents,[^10] reports generated by the {{< var validmind.developer >}}, or reports created in the {{< var validmind.platform >}} can be edited.
:::

Modify the contents of the **Latest** version of your validation report:[^11]

1. From the **Validation Report Overview**, jump to any section of the validation report by clicking on the heading you would like to view.

2. Add **Risk Assessment Notes**, as well as assess compliance for each section of your validation report:

    - Validation guidelines are displayed under the header of each section of your report to help ensure that you are compliant with your organization's requirements.[^12]
    - Whenever you make a change, a log of the action is recorded under **{{< fa wifi >}} Model Activity**.[^13]

3. For any **Risk Assessment Notes**, save your edits to retain your changes:

   - Clicking on the {{< fa clock-rotate-left >}} icon in the editor toolbar.
   - Select **Save current revision** and enter a name.
   - Click {{< fa check >}} to save the revision.

   You can also suggest changes and leave comments.[^14]

Compliance assessments and linking evidence and artifacts are both saved automatically after selection.

## Prepare validation reports

Complete your validation report by reviewing submitted model documentation and assessing compliance:

:::{#draft-reports}
:::

Collaborate with other stakeholders and submit your work for approval:

:::{#complete-reports}
:::

## What's next

- [Working with artifacts](working-with-artifacts.qmd)


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Working with model documentation](/guide/model-documentation/working-with-model-documentation.qmd)

[^3]: [Manage validation guidelines](manage-validation-guidelines.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Manage model documents](/guide/templates/manage-model-documents.qmd#add-model-documents)

[^6]: [Assess compliance](/guide/model-validation/assess-compliance.qmd)

[^7]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^8]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^9]: [Working with model documents](/guide/templates/working-with-model-documents.qmd)

[^10]: [Manage model documents](/guide/templates/manage-model-documents.qmd#add-model-documents)

[^11]: [Work with document versions](/guide/model-documentation/work-with-document-versions.qmd)

[^12]: [Manage validation guidelines](/guide/model-validation/manage-validation-guidelines.qmd)

[^13]: [View model activity](/guide/model-inventory/view-model-activity.qmd)

[^14]: [Collaborate with others](/guide/model-documentation/collaborate-with-others.qmd)

