---
title: "View and filter artifacts"
date: last-modified
aliases: 
  - view-filter-model-findings.qmd
---

Access a complete list of filterable artifacts logged across all your models in the {{< var validmind.platform >}}, or look at only artifacts linked to a specific model.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] There are models registered in the model inventory.[^1]
- [x] There are artifacts logged on any model.[^2]
- [x] You are a [{{< fa circle-check >}} Validator]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^3]

:::

## View artifacts

You can view artifacts for all models at once, or only view artifacts linked to a specific model.

::: {.callout}
Within the {{< var validmind.platform >}}, artifacts are spilt into validation issues and other artifact types.[^4]
:::

### View all artifacts

{{< include _view-all-artifacts.qmd >}}

### View model-specific artifacts

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^5]

3. View validation issues or other artifact types for that model.

::: {.panel-tabset}

#### View model-specific validation issues

a. In the left sidebar that appears for your model, click **{{< fa triangle-exclamation >}} Validation Issues**.

b. Click on any validation issue for more information, including the proposed remediation plan and any supporting attachments.[^6]

   Attachments are listed with the following information:

   - Filename
   - Icon representing file type
   - Date uploaded
   - The user who uploaded the file
   - File size
   - Notes

   Click on the attachment to view or download the file.

#### View model-specific artifacts of other types

a. In the left sidebar that appears for your model, click **{{< fa border-all >}} Artifacts**.

b. Select an artifact type[^7] to view from the tabs:

   - Policy Exception
   - Model Limitation

   In the page that opens is a list of all model artifacts for that type.

c. Click on any artifact for more information.

:::


## Filter and sort artifacts

:::{.callout}
Changes are automatically saved to your account and do not affect other users.
:::

- By default, artifacts for all models are listed by creation date in descending order.
- To sort artifacts by a column in ascending ({{< fa angle-down >}}) or descending ({{< fa angle-up >}}) order, click on the column header.

To narrow down the artifacts, you can apply some filters:

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Findings** for the list of all model artifacts.

2. Select a finding type[^7] to view from the tabs:

   - Validation Issue
   - Policy Exception
   - Model Limitation

3. Click **{{< fa filter >}} Filter**.

4. On the **Select Your Filters** dialog that opens, enter your filtering criteria.[^8]

   For example, to filter by open artifacts for the Customer Churn Model assigned to Jane Doe:

      - **[status]{.smallcaps}** — `Open`
      - **[model inventory]{.smallcaps}** — `Customer Churn Model`
      - **[assigned to]{.smallcaps}** — `Jane Doe`

5. Click **Apply Filters**.

Filters can be removed by clicking on the {{< fa xmark >}} next to them on the main **{{< fa triangle-exclamation >}} Findings** page where the results are displayed.


<!-- FOOTNOTES -->

[^1]: [Register models in the inventory](/guide/model-inventory/register-models-in-inventory.qmd)

[^2]: [Add and manage artifacts](add-manage-artifacts.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Manage finding types](/guide/model-validation/manage-finding-types.qmd)

[^5]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^6]: [Manage supporting documentation](add-manage-artifacts.qmd#manage-supporting-documentation)

[^7]: [Manage finding types](/guide/model-validation/manage-finding-types.qmd)


<!-- 




[^8]:

   - [**[status]{.smallcaps}**](/guide/model-validation/manage-finding-types.qmd#manage-finding-type-statuses)
   - [**[model inventory]{.smallcaps}**](/guide/model-inventory/working-with-model-inventory.qmd)
   - [**[risk area]{.smallcaps}**](/guide/model-validation/manage-validation-guidelines.qmd#set-up-validation-guidelines)
   - [**[business units]{.smallcaps}**](/guide/configuration/set-up-your-organization.qmd#manage-business-units)
   - **[severity]{.smallcaps}**
   - **[assigned to]{.smallcaps}**

   -->

