---
title: "Working with model findings"
date: last-modified
listing:
  - id: model-findings
    type: grid
    max-description-length: 250
    sort: false
    grid-columns: 2
    fields: [title, description]
    contents:
      - view-filter-model-findings.qmd
      - add-manage-model-findings.qmd
filters:
  - tachyons
---

Use {{< var validmind.platform >}} to log thorough findings as you validate your models.  From status and severity to proposed remediation plans and due dates, ValidMind allows you to oversee the minutiae to ensure organizational compliance.

## Key concepts

Model findings are detailed observations identified during the model validation process, highlighting any major or minor issues, deficiencies, model limitations, stability and robustness concerns, or needed adjustments. 

- These findings are critical for understanding the risk exposure and compliance status of models within an organization.
- To make them easier to track, findings are typically categorized by risk area, business unit, model status, and individual model, enabling targeted resolution and informed decision-making to mitigate identified risks and ensure model reliability and accuracy.

Good findings help explain how well the model performs in terms of predictive accuracy, generalization to new data, and the importance of variables or features used in the modeling process, and typically include:

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns}

performance metrics
: Quantitative measures that evaluate how well the model predicts outcomes, such as accuracy, precision, and recall.

feature importance
: The ranking of input variables based on their contribution to the predictive power of the model.

model interpretability
: Insights into how the model makes its predictions, which can help in understanding the decision-making process.

:::

::: {.w-40-ns}


validation results
: Findings from testing the model on unseen data, for example cross-validation results.

residual analysis
: Investigating the errors or discrepancies between predicted and actual outcomes.


:::

::::



## Get started

:::{#model-findings}
:::

## What's next

- [Preparing validation reports](preparing-validation-reports.qmd)
- [View reports](view-reports.qmd)
- [Export documentation](/guide/model-documentation/export-documentation.qmd)
- [View model activity](/guide/model-inventory/view-model-activity.qmd)

