---
title: "Documentation updates"
keywords: "release notes, model risk management, ValidMind"
---

## Documentation updates -- July 6, 2023

- **New 'before you begin' PR with Parris' updates, plus edits**

We added some template examples that we can apply to our Jupyter notebooks to make the prerequisites easier to understand. The template adds a "Before you begin" section that describes the prerequisites. 



<!--- REPLACE THIS COMMENT WITH YOUR DESCRIPTION --->


- **Create CI check for Release Notes**

Sample description to test generate release notes script.


- **Docs site rework for template functionality**

Please provide a description that allows an external user to understand the changes made, even without access to the original pull request.



If this is an internal-only change, add the `internal` label to omit the changes from the external release notes. 



Is this a cool new feature we should curate for our users? Add the `highlight` label. 

<!-- end release notes section -->


- **Mock up Quickstart revamp**

Test description for highlight and documentation label.


