<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
::: {.callout}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to abort workflows.
:::

To cancel a run of a workflow:

::: {.panel-tabset}

#### On models

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a model or find your model by applying a filter or searching for it.^[[Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)]

1. On the landing page of your model, locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to abort to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa ban >}} Abort Workflow**.

1. On the confirmation page, make sure **[restart workflow after aborting]{.smallcaps}** is untoggled, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to abort your workflow.

#### On artifacts

1. On the details page of your artifact,^[[View and filter artifacts](/guide/model-validation/view-filter-artifacts.qmd#view-artifacts)] locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to abort to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa ban >}} Abort Workflow**.

1. On the confirmation page, make sure **[restart workflow after aborting]{.smallcaps}** is untoggled, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to abort your workflow.


:::


::::


:::: {.content-hidden unless-format="revealjs"}
To cancel a run of a workflow:

#### On models

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a model or find your model [by applying a filter or searching for it](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models){target="_blank"}.

1. On the landing page of your model, locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to abort to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa ban >}} Abort Workflow**.

1. On the confirmation page, make sure **[restart workflow after aborting]{.smallcaps}** is untoggled, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to abort your workflow.

#### On artifacts

1. On the [details page of your artifact](/guide/model-validation/view-filter-artifacts.qmd#view-artifacts){target="_blank"}, locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to abort to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa ban >}} Abort Workflow**.

1. On the confirmation page, make sure **[restart workflow after aborting]{.smallcaps}** is untoggled, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to abort your workflow.

::::