<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
To add a new blank workflow:

a. In the left sidebar, click **{{< fa gear >}} Settings**.

b. Under {{< fa shield >}} Governance, select **Workflows**.

c. Click **{{< fa plus >}} Add Workflow**.

d. Select the **Workflow Target** type to add:

    - **Inventory Record** — Workflows that apply to records in your inventory.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd)]
    - **Artifact** — Workflows that apply to logged artifacts.^[[Working with artifacts](/guide/validation/working-with-artifacts.qmd)]

::: {.panel-tabset}

#### Add record workflows

i. Enter a **Title** and a **Description** for the workflow.

ii. Select the **Record Type**^[[Manage record types](/guide/inventory/manage-inventory-record-types.qmd)] this workflow applies to.

iii. Under **Workflow Start**, select when the workflow should be initiated:

- **Manually** — Start this workflow manually.^[[Initiate workflows](/guide/workflows/manage-workflows.qmd#initiate-workflows)]
- **On Inventory Record Registration** — Start this workflow when a record is registered in your inventory.[^on-registration]
- **On Field Change** — Start this workflow on a change to a specific record inventory field.[^on-field-change] To configure, select a field under **Inventory Record Field To Monitor**.
- **Via Webhook** — Start this workflow when a webhook event is received.

iv. Under **Workflow Expected Duration**, define the SLA for the workflow based on the start date in days, weeks, months, or years.

v. Click **Save Draft** to save your blank workflow, and then [configure your workflow steps](/guide/workflows/configure-workflows.qmd#configure-workflow-steps).

#### Add artifact workflows

i. Enter a **Title** and a **Description** for the workflow.

ii. Select the **Artifact Type**^[[Manage artifact types](/guide/validation/manage-artifact-types.qmd)] this workflow applies to.

iii. Select the **Inventory Record Type**[^artifact-workflow-record-scopes] this artifact workflow is scoped to.

iv. Under **Workflow Start**, select when the workflow should be initiated:

- **Manually** — Start this workflow manually.^[[Initiate workflows](/guide/workflows/manage-workflows.qmd#initiate-workflows)]
- **On Artifact Registration** — Start this workflow when an artifact is logged on a record.[^on-artifact-registration]
- **On Field Change** — Start this workflow when a specific artifact field changes.[^on-artifact-field-change] To configure, select a field under **Artifact Field to Monitor**.
- **Via Webhook** — Start this workflow when a webhook event is received.

v. Under **Workflow Expected Duration**, define the SLA for the workflow based on the start date in days, weeks, months, or years.

vi. Click **Save Draft** to save your blank workflow, and then [configure your workflow steps](/guide/workflows/configure-workflows.qmd#configure-workflow-steps).

:::


<!-- ADDITIONAL FOOTNOTES -->

[^on-registration]:

    ::: {.callout title="Please note that only one workflow can be configured to initiate on record registration."}
    <br>
    [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd){.button}

    :::

[^on-artifact-registration]:

    ::: {.callout title="Please note that only one workflow can be configured to initiate on registration for each type of artifact."}
    <br>
    [Log artifacts](/guide/validation/log-artifacts.qmd){.button}

    :::

[^on-field-change]:

    [Edit inventory fields](/guide/inventory/edit-inventory-fields.qmd)
    <br></br>
    When selecting date or date time fields, check **Schedule workflow start for this date** to set the workflow to trigger on the existing date captured in the field rather than when its value changes.

[^on-artifact-field-change]:

    [Manage artifact fields](/guide/validation/manage-artifact-fields.qmd)
    <br></br>
    Only artifact fields available to the selected artifact type appear. Artifact fields that apply to all artifact types also appear. Record fields displayed from the parent record are not available as triggers.
    <br></br>
    When selecting date or date time fields, check **Schedule workflow start for this date** to set the workflow to trigger on the existing date captured in the field rather than when its value changes.

[^artifact-workflow-record-scopes]:

    [Manage inventory record types](/guide/inventory/manage-inventory-record-types.qmd)
    <br><br>

    - Record stages and record fields available to this workflow are defined by the inventory record type selected.
    - The type of inventory record an artifact workflow is scoped to cannot be changed after creation.


::::


:::: {.content-hidden unless-format="revealjs"}
a. In the left sidebar, click **{{< fa gear >}} Settings**.

b. Under {{< fa shield >}} Governance, select **Workflows**.

c. Click **{{< fa plus >}} Add Workflow**.

d. Select the **Workflow Target** type to add:

    - **Inventory Record** — Workflows that apply to records in your inventory.
    - **Artifact** — Workflows that apply to logged artifacts.

#### Add record workflows

i. Enter a **Title** and a **Description** for the workflow.

ii. Select the [**Record Type**](/guide/inventory/manage-inventory-record-types.qmd){target="_blank"} this workflow applies to.

iii. Under **Workflow Start**, select when the workflow should be initiated:

- **Manually** — Start this workflow manually.
- **On Inventory Record Registration** — Start this workflow when a record is registered in your inventory.
- **On Field Change** — Start this workflow on a change to a specific record inventory field. To configure, select a field under **Inventory Record Field To Monitor**.
- **Via Webhook** — Start this workflow when a webhook event is received.

iv. Under **Workflow Expected Duration**, define the SLA for the workflow based on the start date in days, weeks, months, or years.

v. Click **Save Draft** to save your blank workflow, and then configure your workflow steps.

#### Add artifact workflows

i. Enter a **Title** and a **Description** for the workflow.

ii. Select the [**Artifact Type**](/guide/validation/manage-artifact-types.qmd){target="_blank"} this workflow applies to.

iii. Select the [**Inventory Record Type**](/guide/inventory/manage-inventory-record-types.qmd) this artifact workflow is scoped to.

iv. Under **Workflow Start**, select when the workflow should be initiated:

- **Manually** — Start this workflow manually.
- **On Artifact Registration** — Start this workflow when an artifact is logged on a record.
- **On Field Change** — Start this workflow when a specific artifact field changes. To configure, select a field under **Artifact Field to Monitor**. Only artifact fields available to the selected artifact type appear; record fields displayed from the parent record are not available as triggers.

v. Under **Workflow Expected Duration**, define the SLA for the workflow based on the start date in days, weeks, months, or years.

vi. Click **Save Draft** to save your blank workflow, and then configure your workflow steps.

::::
