<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
Conditional requirements are required or optional for the following step types:^[[Workflow step types](/guide/workflows/workflow-step-types.qmd)]

### {{< fa cube >}} Inventory Record Stage Change [optional]{.smallercaps .pink}
<span id="record-stage-change">

1. Under **When These Conditions Are Met**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add Rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add Group** to add a linked group of rules that all must be true to qualify.

### {{< fa tag >}} Artifact Status Change
<span id="artifact-status-change">

1. Under **When These Conditions Are Met**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add Rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add Group** to add a linked group of rules that all must be true to qualify.

### {{< fa arrow-pointer >}} User Action [optional]{.smallercaps .pink}
<span id="user-action">

::: {.panel-tabset}

#### User display rules

1. Under **Display Action Button When**, set your `AND` and `OR` conditions.

2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add Rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add Group** to add a linked group of rules that all must be true to qualify.

#### Request record or artifact fields

- Select any **Requested Fields**[^request-fields] to be entered by users during the action.

    **Toggle Optional** to ON if the field should be optional and not required.

- (Optional) Present these requested fields to users in steps:

    i. Click **{{< fa plus >}} Add Step** to add a step.
    ii. On the Add Step modal that appears, enter the step **Title** and provide an optional **Description**.
    iii. Click **Save** to insert the step.
    iv. Drag request fields into a step to add them to that step.

#### Enable user action deadline

1. Toggle **Enable deadline** on to configure a **User Action Deadline** for when users should complete this action by.

2. Then, under **End Action**, select the type of deadline:
    - **After Time Interval** — Set the **Amount** and **Unit** of the deadline.
    - **At Specified Date** — Set the date and time the action should **Wait Until**.
    - **At Specified Date on Custom Field** — Select a date, date time, or calculated **Record Field** that defines the deadline.
    - **Time Delta from Specified Date on Custom Field** — Select a date, date time, or calculated **Record Field** to calculate a deadline from, then set a **Time Delta Direction** and **Wait Duration**.

:::



### {{< fa users >}} Approval [required]{.smallercaps .pink}
<span id="approval">

1. Under **Approval Group**, click **{{< fa plus >}} Add Individual Approver** to set an individual approver selected from **User Roles**,^[[Manage roles](/guide/configuration/manage-roles.qmd)] **Inventory Record Stakeholder Types**,^[[Manage record stakeholder types](/guide/configuration/manage-record-stakeholder-types.qmd)] or **Inventory Record Fields — User**:^[[Manage inventory fields](/guide/inventory/manage-inventory-fields.qmd#inventory-field-types)]

    - Click **{{< fa plus >}} Add Rule** to add an individual rule.
    - Click **{{< fa square-plus >}} Add Group** to add a group of rules.

    One approver per rule or rule group must provide approval. If you've set multiple rules or rule groups, select whether they are `AND` or `OR` conditions.


2. (Optional) Add more individual rule or rule group approvers as required.

    If you've set multiple individual approvers, select whether they are `AND` or `OR` conditions.

3. Select the **Fields To Review** shown to your **Approval Group**s as read-only fields.

<!-- - Under **Threshold**, set the minimum percentage of approvers required for the resource to be approved. -->

### {{< fa bullhorn >}} Broadcast [required]{.smallercaps .pink}
<span id="broadcast">

Select from either **Inventory Record Stakeholder Types**^[[Manage record stakeholder types](/guide/configuration/manage-record-stakeholder-types.qmd)] or **User Roles**.^[[Manage roles](/guide/configuration/manage-roles.qmd)]

### {{< fa maximize >}} Condition Branch [required]{.smallercaps .pink}
<span id="condition-branch">

1. Under each branch's **Conditions**, set your `AND` and `OR` conditions.
2. Add a single independent rule or a linked condition group. These rules and groups can be nested if desired:

    - Click **{{< fa plus >}} Add Rule** to add an independent rule.
    - Click **{{< fa plus-minus >}} Add Group** to add a linked group of rules that all must be true to qualify.

### {{< fa clock >}} Wait [required]{.smallercaps .pink}
<span id="wait">

Select when you would like to **Resume Workflow**:

::: {.panel-tabset}

#### **After Time Interval**

Set the **Wait Duration** in minutes, hours, or days.

#### At Specified Date

Set a time to **Wait Until** as defined by a specific timestamp.

#### At Specified Date on Custom Field

Set the **Record Field**^[[Manage inventory fields](/guide/inventory/manage-inventory-fields.qmd#inventory-field-types)] with a valid `Date` or `Date Time` type record field that defines the specific timestamp on a per record basis.

#### Time Delta from Specified Date on Custom Field

a. Set the **Record Field**^[[Manage inventory fields](/guide/inventory/manage-inventory-fields.qmd#inventory-field-types)] to a valid `Date` or `Date Time` type record field that defines the specific timestamp on a per record basis.

b. Select a **Time Delta Direction** relative to your selected field.

c. Enter a **Wait Duration** in minutes, hours, days, or months for the delta.

:::


### {{< fa cloud-arrow-up >}} HTTP Request [optional]{.smallercaps .pink}
<span id="http-request">

::: {.panel-tabset}

#### Request timeout

- Enter a request timeout in seconds under **Timeout (seconds)**.

- Max 300 seconds, or enter `0` to disable timeout.

#### Request options

Toggle the following request options on or off:

- **Fail on Non-2xx** — Whether or not the request will be considered failed if the response status code is not in the `2xx` range.

- **Allow Invalid Certificates** — Whether or not the request will be allowed to use invalid certificates.

- **Follow Redirects** — Whether or not the request will follow redirects.

- **Require HTTPS** — Whether or not the request will require HTTPS.

#### Request headers

Enter optional headers to include with your request:

1. Click **{{< fa plus >}} Add Header** under **Headers** to enter a header.

2. Provide a **Header Name** and **Header Value**.

To avoid storing credentials in plaintext, use `{{secret:name}}` syntax to reference a webhook secret.^[[Manage secrets](/guide/integrations/manage-secrets.qmd#webhook-secrets)]

:::


::::

[^request-fields]:

    - [Manage inventory fields](/guide/inventory/manage-inventory-fields.qmd)
    - [Manage artifact fields](/guide/validation/manage-artifact-fields.qmd)



:::: {.content-hidden unless-format="revealjs"}
Configure conditional requirements for the following step types:

- {{< fa cube >}} Inventory Record Stage Change **[optional]{.smallercaps}**

- {{< fa tag >}} Artifact Status Change **[optional]{.smallercaps}**

- {{< fa arrow-pointer >}} User Action **[optional]{.smallercaps}**

- {{< fa users >}} Approval **[required]{.smallercaps}**

- {{< fa bullhorn >}} Broadcast **[required]{.smallercaps}**

- {{< fa maximize >}} Condition Branch **[required]{.smallercaps}**

- {{< fa clock >}} Wait **[required]{.smallercaps}**

- {{< fa cloud-arrow-up >}} HTTP Request **[optional]{.smallercaps}**


::::