<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
::: {.callout}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to reset workflows.
:::

To reset a workflow to the beginning:

::: {.panel-tabset}

#### On records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or find your record by applying a filter or searching for it.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)]

1. On the landing page of your record, locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to reset to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select [**{{< fa ban >}} Abort Workflow**]{.red}.

1. On the confirmation page, toggle **[restart workflow after aborting]{.smallcaps}** on, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to restart your workflow.

#### On artifacts

1. On the details page of your artifact,^[[View and filter artifacts](/guide/validation/view-filter-artifacts.qmd#view-artifacts)] locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to reset to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select [**{{< fa ban >}} Abort Workflow**]{.red}.

1. On the confirmation page, toggle **[restart workflow after aborting]{.smallcaps}** on, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to restart your workflow.

:::


::::



:::: {.content-hidden unless-format="revealjs"}
To reset a workflow to the beginning:

#### On records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or find your record [by applying a filter or searching for it](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records){target="_blank"}.

1. On the landing page of your record, locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to reset to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select [**{{< fa ban >}} Abort Workflow**]{.red}.

1. On the confirmation page, toggle **[restart workflow after aborting]{.smallcaps}** on, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to restart your workflow.

#### On artifacts

1. On the [details page of your artifact](/guide/validation/view-filter-artifacts.qmd#view-artifacts){target="_blank"}, locate the [active workflows]{.smallcaps} section.

1. Click on the name of the workflow you'd like to reset to open that specific workflow's details.

1. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select [**{{< fa ban >}} Abort Workflow**]{.red}.

1. On the confirmation page, toggle **[restart workflow after aborting]{.smallcaps}** on, then click **{{< fa arrow-right >}} Yes, Abort Workflow** to restart your workflow.

::::