<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
Review timelines of workflows running or previously run on a specific record or artifact:[^view-all-workflows]

::: {.panel-tabset}

#### On records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)]

3. On the landing page of your record, locate the Workflows section that shows a timeline of workflows associated with that record.

    Use the buttons or keyboard shortcuts[^timeline-shortcuts] to control the timeline:

    - **{{< fa magnifying-glass-plus >}}** — Zoom in
    - **{{< fa magnifying-glass-minus >}}** — Zoom out
    - **{{< fa arrow-left >}}** — Move earlier to the left
    - **{{< fa calendar-days >}} Go to Today** — Focus on today
    - **{{< fa arrow-right >}}** — Move later to the right

If workflows are running or have previously run on your record, you can:

- Click on any listed workflow to review the details of that specific workflow.

- Filter the view using **{{< fa filter >}} Filter** to display only runs from specific types and statuses of workflows.[^filter-workflows-all]

- Click **{{< fa arrow-right-arrow-left >}} See All Workflows** to see records of all workflows by status:
    - **Active** — Workflows currently running.
    - **Scheduled** — Workflows slated to run in the future.
    - **Waiting** — Workflows in a {{< fa clock >}} Wait state.^[[Conditional step requirements](/guide/workflows/conditional-step-requirements.qmd)]
    - **Finished** — Workflows that have reached an {{< fa circle-stop >}} End state.^[[Workflow step types](/guide/workflows/workflow-step-types.qmd)]
    - **Aborted** — Cancelled workflows.^[[Abort workflows](/guide/workflows/manage-workflows.qmd#abort-workflows)]
    - **Available** — Workflows available to be run manually.^[[Initiate workflows](/guide/workflows/manage-workflows.qmd#initiate-workflows)]

#### On artifacts

On the details page of your artifact,^[[View and filter artifacts](/guide/validation/view-filter-artifacts.qmd#view-artifacts)] locate the Workflows section that shows a timeline of workflows associated with that artifact.

Use the buttons or keyboard shortcuts[^timeline-shortcuts] to control the timeline:

- **{{< fa magnifying-glass-plus >}}** — Zoom in
- **{{< fa magnifying-glass-minus >}}** — Zoom out
- **{{< fa arrow-left >}}** — Move earlier to the left
- **{{< fa calendar-days >}} Go to Today** — Focus on today
- **{{< fa arrow-right >}}** — Move later to the right

If workflows are running or have previously run on your artifact, you can:

- Click on any listed workflow to review the details of that specific workflow.

- Filter the view using **{{< fa filter >}} Filter** to display only runs from specific statuses of workflows.[^filter-workflows-artifacts]

- Click **{{< fa arrow-right-arrow-left >}} See All Workflows** to see records of all workflows by status:
    - **Active** — Workflows currently running.
    - **Scheduled** — Workflows slated to run in the future.
    - **Waiting** — Workflows in a {{< fa clock >}} Wait state.^[[Conditional step requirements](/guide/workflows/conditional-step-requirements.qmd)]
    - **Finished** — Workflows that have reached an {{< fa circle-stop >}} End state.^[[Workflow step types](/guide/workflows/workflow-step-types.qmd)]
    - **Aborted** — Cancelled workflows.^[[Abort workflows](/guide/workflows/manage-workflows.qmd#abort-workflows)]
    - **Available** — Workflows available to be run manually.^[[Initiate workflows](/guide/workflows/manage-workflows.qmd#initiate-workflows)]

:::

[^timeline-shortcuts]:

    ::: {.callout title="Timeline control shortcuts"}

    - **Move timeline left or right** — <br>
        - Click and drag
        - OR <kbd>Shift</kbd> + scroll wheel
    - **Slow zoom in or out** — <br><kbd>Alt</kbd> + scroll wheel
    - **Quick zoom in or out** — <br><kbd>Ctrl</kbd> + scroll wheel
    :::

[^filter-workflows-all]:

    - Filter by **Workflow Type**:
        - Record
        - Artifact
    - Filter by **Workflow Status**:
        - Finished
        - Active
        - Scheduled

[^filter-workflows-artifacts]:

    Filter by **Workflow Status**:

    - Finished
    - Active
    - Scheduled

[^view-all-workflows]:

    To monitor workflows across your whole organization on a single timeline, refer to: [View all workflow executions](/guide/workflows/working-with-workflows.qmd#view-all-workflow-executions).

::::



:::: {.content-hidden unless-format="revealjs"}
Review timelines of workflows running or previously run:

#### On records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record [by applying a filter or searching for it](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records){target="_blank"}.

3. On the landing page of your record, locate the Workflows section that shows a timeline of workflows associated with that record.

    If workflows are running or have previously run on your record, you can:

    - Click on any listed workflow to review the details of that specific workflow.

    - Filter the view using **{{< fa filter >}} Filter** to display only runs from specific types and statuses of workflows.

    - Click **{{< fa arrow-right-arrow-left >}} See All Workflows** to see records of workflows by status:
        - **Active** — Workflows currently running.
        - **Scheduled** — Workflows slated to run in the future.
        - **Waiting** — Workflows in a {{< fa clock >}} Wait state.
        - **Finished** — Workflows that have reached an {{< fa circle-stop >}} End state.
        - **Aborted** — Cancelled workflows.
        - **Available** — Workflows available to be run manually.

#### On artifacts

On the [details page of your artifact](/guide/validation/view-filter-artifacts.qmd#view-artifacts){target="_blank"}, locate the Workflows section that shows a timeline of workflows associated with that artifact.

If workflows are running or have previously run on your artifact, you can:

- Click on any listed workflow to review the details of that specific workflow.

- Filter the view using **{{< fa filter >}} Filter** to display only runs from specific statuses of workflows.

- Click **{{< fa arrow-right-arrow-left >}} See All Workflows** to see records of workflows by status:
    - **Active** — Workflows currently running.
    - **Scheduled** — Workflows slated to run in the future.
    - **Waiting** — Workflows in a {{< fa clock >}} Wait state.
    - **Finished** — Workflows that have reached an {{< fa circle-stop >}} End state.
    - **Aborted** — Cancelled workflows.
    - **Available** — Workflows available to be run manually.

::::