<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
::: {.callout-important title="Roles and action visibility"}
Depending on the configuration of your workflows, you may or may not be able to move a workflow into another workflow state as actions can be gated to only users of certain roles.

When all the actions that can be performed by your role are completed for that model or artifact at that stage of the workflow, actions will disappear from your view.
:::

To transition a workflow into next steps:

::: {.panel-tabset}

#### On models

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a model or find your model by applying a filter or searching for it.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)]

1. On the landing page of your model, locate the [active workflows]{.smallcaps} section and the workflow you'd like to transition.

1. If an action is available to your role, you'll see it listed under that workflow:

    - Click **{{< fa arrow-right >}}** to open up the transition panel for your selected action. This arrow will be followed by the action name.
    - Enter your **[notes]{.smallcaps}** and/or any other additional inventory fields^[[Manage inventory fields](/guide/inventory/manage-inventory-fields.qmd)]. To save a working copy of the entered information without transitioning the workflow into its next state, click **Save**.[^submission-drafts]

1. Click **{action}** where `action` is the name of your custom user action to submit the entered information and transition the workflow into its next state.


#### On artifacts

1. On the details page of your artifact,^[[View and filter artifacts](/guide/model-validation/view-filter-artifacts.qmd#view-artifacts)] locate the [active workflows]{.smallcaps} section.

1. If an action is available to your role, you'll see it listed under that workflow:

    - Click **{{< fa arrow-right >}}** to open up the transition panel for your selected action. This arrow will be followed by the action name.
    - Enter your **[notes]{.smallcaps}** and/or any other additional inventory fields^[[Manage inventory fields](/guide/inventory/manage-inventory-fields.qmd)]. To save a working copy of the entered information without transitioning the workflow into its next state, click **Save**.[^submission-drafts]

1. Click **{action}** where `action` is the name of your custom user action to submit the entered information and transition the workflow into its next state.

:::


<!-- ADDITIONAL FOOTNOTES -->

[^submission-drafts]:

    - Working copies are tracked under model activity: [View model activity](/guide/inventory/view-record-activity.qmd)
    - Working copies can be viewed, edited, and submitted by any other users with permissions to transition the workflow into its next state.
    - Fields values updated via working copies will reflect on the field itself.

::::

:::: {.content-visible when-format="revealjs" when-meta="includes.developer"}
To transition a workflow into next steps on models:

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a model or find your model [by applying a filter or searching for it](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records){target="_blank"}.

1. On the landing page of your model, locate the [active workflows]{.smallcaps} section and the workflow you'd like to transition.

1. If an action is available to your role, you'll see it listed under that workflow:

    - Click **{{< fa arrow-right >}}** to open up the transition panel for your selected action. This arrow will be followed by the action name.
    - Enter your **[notes]{.smallcaps}** and/or any other additional inventory fields then click **{action}** where `action` is the name of your custom user action. To save a working copy of the entered information without transitioning the workflow into its next state, click **Save**.

1. Click **{action}** where `action` is the name of your custom user action to submit the entered information and transition the workflow into its next state.


::::


:::: {.content-visible when-format="revealjs" unless-meta="includes.developer"}
To transition a workflow into next steps:

#### On models

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a model or find your model [by applying a filter or searching for it](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records){target="_blank"}.

1. On the landing page of your model, locate the [active workflows]{.smallcaps} section and the workflow you'd like to transition.

1. If an action is available to your role, you'll see it listed under that workflow:

    - Click **{{< fa arrow-right >}}** to open up the transition panel for your selected action. This arrow will be followed by the action name.
    - Enter your **[notes]{.smallcaps}** and/or any other additional inventory fields then click **{action}** where `action` is the name of your custom user action. To save a working copy of the entered information without transitioning the workflow into its next state, click **Save**.

1. Click **{action}** where `action` is the name of your custom user action to submit the entered information and transition the workflow into its next state.


#### On artifacts

1. On the [details page of your artifact](/guide/model-validation/view-filter-artifacts.qmd#view-artifacts){target="_blank"}, locate the [active workflows]{.smallcaps} section.

1. If an action is available to your role, you'll see it listed under that workflow:

    - Click **{{< fa arrow-right >}}** to open up the transition panel for your selected action. This arrow will be followed by the action name.
    - Enter your **[notes]{.smallcaps}** and/or any other additional inventory fields then click **{action}** where `action` is the name of your custom user action. To save a working copy of the entered information without transitioning the workflow into its next state, click **Save**.

1. Click **{action}** where `action` is the name of your custom user action to submit the entered information and transition the workflow into its next state.


::::

:::: {.content-hidden unless-format="revealjs"}
{{< include /guide/workflows/_transition-workflow-examples.qmd >}}

::::



