<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible unless-format="revealjs"}
### Add workflow states

Add workflow states either while configuring a **{{< fa wifi >}} Workflow State Change** step,^[[Configure workflow steps](/guide/workflows/configure-workflows.qmd#configure-workflow-steps)] or via the **{{< fa gear >}} Settings** page:

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa shield >}} Governance, select **Workflow States**.

1. Select the tab for the type of state to add:

    - **Record Workflows** — Workflow states that apply to record workflows.
    - **Artifact Workflows** — Workflow states that apply to artifact workflows.

1. Click on the workflow you'd like to modify workflow states for.

1. Click **{{< fa plus >}} Add Workflow State**.

1. Enter in a **[name]{.smallcaps}** and a **[description]{.smallcaps}**, then select a **[color]{.smallcaps}** for your workflow state.

1. Click **Save** to create the workflow state.

### Edit workflow states

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa shield >}} Governance, select **Workflow States**.

1. Select the tab for the type of state you want to edit:

    - **Record Workflows** — Workflow states that apply to record workflows.
    - **Artifact Workflows** — Workflow states that apply to artifact workflows.

1. Click on the workflow you'd like to edit the states for.

1. Hover over the workflow state you want to edit until the **{{< fa ellipsis-vertical >}}** appears, then click on it.

1. Select **{{< fa pencil >}} Edit Details**.

1. Make your changes to the **[name]{.smallcaps}**, **[description]{.smallcaps}**, and **[color]{.smallcaps}** for your workflow state.

1. Click **Save** to apply your changes.

### Delete workflow states

::: {.callout-important title="Workflow state deletion is permanent."}
If a state is or was previously in use  on a workflow within a {{< fa wifi >}} Workflow State Change step, the state cannot be deleted.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.

1. Under {{< fa shield >}} Governance, select **Workflow States**.

1. Select the tab for the type of state you want to delete:

    - **Record Workflows** — Workflow states that apply to record workflows.
    - **Artifact Workflows** — Workflow states that apply to artifact workflows.

1. Click on the workflow you'd like to delete workflow states for.

1. Hover over the workflow state you want to delete until the **{{< fa ellipsis-vertical >}}** appears, then click on it.

1. Select [**{{< fa trash-can >}} Delete Workflow State**]{.red}.

1. Click **Yes, Delete Workflow State** to confirm permanent deletion of that workflow state.

::::


:::: {.content-hidden unless-format="revealjs"}
Workflow states are statuses unique to a specific workflow, discrete from record stages.

Add workflow states either while configuring a **{{< fa wifi >}} Workflow State Change** step, or [via the **{{< fa gear >}} Settings** page](/guide/workflows/workflow-states.qmd){target="_blank"}.

::::