---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Configure workflows"
date: last-modified
aliases:
  - /guide/set-up-model-workflows.html
  - set-up-model-workflows.html
  - /guide/model-workflows/configure-model-workflows.html
---

{{< include /guide/workflows/_configure-workflows.qmd >}}

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] Model stages must be fully configured.[^1]
- [x] You are a [{{< fa hand >}} Customer Admin]{.bubble} or assigned another role with sufficient permissions to perform the tasks in this guide.[^2]

:::

## Create custom workflows

To set up a new custom workflow, you'll need to complete these four steps in sequence:

1. [Add a new workflow](#add-new-workflows) — Create a new workflow in `Draft` status.
2. [Configure the workflow steps](#configure-workflow-steps) — Configure the workflow steps to define the workflow's logic.
3. [Link the workflow together](#link-workflow-together) — Link the workflow steps together to define the workflow's flow.
4. [Publish the workflow](#publish-workflow) — Publish the workflow to make it available for use.

### 1. Add new workflows

{{< include /guide/workflows/_add-new-workflows.qmd >}}

### 2. Configure workflow steps

{{< include /guide/workflows/_configure-workflow-steps.qmd >}}

### 3. Link workflow together

{{< include /guide/workflows/_link-workflow-together.qmd >}}

<br>

::: {.callout-button .pl4 .nt4}
::: {.callout collapse="true" appearance="minimal"}
### Workflow steps relationship unclear on your canvas?
Click **Tidy Layout** at any time for a linear view of your workflow.

:::
:::

### 4. Publish workflow

{{< include /guide/workflows/_publish-workflows.qmd >}}

## Clone existing workflows

To create a copy of an existing workflow as a new draft workflow:[^3]

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Hover over the workflow you'd like to clone.[^4]

3.  When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa copy >}} Clone Workflow**.

4. Make your changes to the workflow's **[title]{.smallcaps}** and **[workflow type]{.smallcaps}**.

    Additional changes can be made to the cloned workflow after cloning by editing.

Once you are satisfied with the setup of your workflow, publish the workflow for use.

## Edit existing workflows

::: {.callout title="Saving edits to a workflow already executed on models or artifacts will create a new version of the workflow."}

- Workflows executed on models or artifacts will not be updated to the new version. To apply the latest version of a workflow, abort the existing version of the workflow and manually initiate the workflow again.[^6]
- Older versions of a workflow are read-only and cannot be edited or initiated on models or artifacts.

:::

You can edit a workflow in several ways:

::: {.panel-tabset}

#### Via **{{< fa gear >}} Settings**

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa shield >}} Governance, select **Workflows**.

3. Click on the workflow you'd like to modify to edit the configuration for that workflow.[^5]

#### Via workflows applied to models

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a model or find your model by applying a filter or searching for it.[^7]

3. On the landing page of your model, locate the [active workflows]{.smallcaps} section.

4. Click on the name of the workflow you'd like to edit to open that specific workflow's details.

5. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa pencil >}} Edit Workflow**.

#### Via workflows applied to artifacts

1. On the details page of your artifact,[^8] locate the [active workflows]{.smallcaps} section.

2. Click on the name of the workflow you'd like to edit to open that specific workflow's details.

3. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa pencil >}} Edit Workflow**.

:::

a. Make your desired changes to step configuration[^9] and step relationships[^10] on your workflow.

b. When you are finished, click **Save New Version** to apply your changes.

c. Enter in your **[version notes]{.smallcaps}** to describe your changes.


### Delete workflow steps

::: {.callout-important title="Workflow step deletion is permanent."}
Deleting workflow steps on workflows active on models may result in malfunctioning workflows.
:::

1. Hover over the step you want to delete.

2. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa gear >}} Delete**.

3. Click **Yes, Delete Step** to confirm removal of the step.

4. When you are finished, click **Save New Version** to apply your changes.

### Remove links between steps

1. Hover over a connection until the **{{< fa trash-can >}}** appears.

2. Click **{{< fa trash-can >}}** to delete the connection.

3. Click **Yes, Delete Connection** to confirm removal of the connection.

4. When you are finished, click **Save New Version** to apply your changes.

## Delete existing workflows

::: {.callout-important title="Workflow deletion is permanent."}
- If a workflow is in use on a model, that model will not be impacted.
- Deletion will prevent any future runs of that workflow.
:::

1. In the left sidebar, click **{{< fa gear >}} Settings**.

2. Under {{< fa shield >}} Governance, select **Workflows**.

3. Hover over the workflow you would like to remove.[^11]

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa trash-can >}} Delete Workflow**.

5. Click **Yes, Delete Workflow** to permanently remove that workflow and make it inaccessible for any future runs.

## What's next

- [Workflows FAQ](/faq/faq-workflows.qmd)
- [Work with workflows](working-with-workflows.qmd)


<!-- FOOTNOTES -->

[^1]: [Manage model stages](manage-model-stages.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: If a cloned workflow's [workflow start]{.smallcaps} trigger conflicts with an existing workflow, the cloned workflow will be set to manual initiation instead.

[^4]: [Setting up workflows](setting-up-workflows.qmd#view-sort-and-filter-workflows)

[^5]: [Setting up workflows](setting-up-workflows.qmd#view-sort-and-filter-workflows)

[^6]: [Manage workflows](/guide/workflows/manage-workflows.qmd#update-workflow-versions)

[^7]: [Working with the model inventory](/guide/model-inventory/working-with-model-inventory.qmd#search-filter-and-sort-models)

[^8]: [View and filter artifacts](/guide/model-validation/view-filter-artifacts.qmd#view-artifacts)

[^9]: [Configure workflow steps](#configure-workflow-steps)

[^10]: [Link workflow together](#link-workflow-together)

[^11]: [Setting up workflows](setting-up-workflows.qmd#view-sort-and-filter-workflows)

