---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Manage workflows"
date: last-modified
aliases:
  - /guide/model-workflows/manage-model-workflows.html
---

Review workflows associated with your records or artifacts, and initiate or abort workflows configured for your organization on your records or artifacts.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] For record workflows, the record you want to manage workflows for registered in the inventory.[^1]
- [x] For artifact workflows, the artifact you want to manage workflows for is logged on a record.[^2]
- [x] Workflows have already been set up for use with your records or artifacts.[^3]
- [x] You are a assigned role with sufficient permissions to view and run workflows on records or artifacts.[^4]

:::

## Review workflows

### Review active workflows

{{< include _review-active-workflows.qmd >}}

### Review workflow histories

{{< include /guide/workflows/_review-workflow-history.qmd >}}

## Initiate workflows

{{< include /guide/workflows/_initiate-workflows.qmd >}}

### Resume workflows

To manually resume a workflow in a {{< fa clock >}} Wait state:[^5]

::: {.panel-tabset}

#### On records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

1. Select a record or find your record by applying a filter or searching for it.[^6]

1. On the landing page of your record, locate the [active workflows]{.smallcaps} section.

1. For the workflow you'd like to manually advance, click **{{< fa arrow-right-arrow-left >}} Resume Workflow** to open up the workflow's step overview.

1. On the **{{< fa clock >}} Wait** step, double-click on **{{< fa arrow-right-arrow-left >}}** to advance the workflow immediately.

#### On artifacts

1. On the details page of your artifact,[^7] locate the [active workflows]{.smallcaps} section.

1. For the workflow you'd like to manually advance, click **{{< fa arrow-right-arrow-left >}} Resume Workflow** to open up the workflow's step overview.

1. On the **{{< fa clock >}} Wait** step, double-click on **{{< fa arrow-right-arrow-left >}}** to advance the workflow immediately.

::::

## Update active workflows

### Update workflow versions

::: {.callout-important}
Applying the latest version of a workflow will reset the workflow to the beginning.

:::

If you have updated a workflow's configuration and want to apply the newest version of the workflow to your records or artifacts:[^8]

1. Abort the existing execution of the workflow.[^9]

2. Manually initiate the workflow again.[^10]

### Edit workflow end dates

To adjust the expected end date for a workflow:

::: {.panel-tabset}

#### On records

1. In the left sidebar, click **{{< fa cubes >}} Inventory**.

2. Select a record or find your record by applying a filter or searching for it.[^11]

3. On the landing page of your record, locate the [active workflows]{.smallcaps} section.

4. Click on the name of the workflow you'd like to edit the end date for to open that specific workflow's details.

5. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa calendar >}} Edit Expected End Date**.

6. Enter in the new [expected end date]{.smallcaps} for the workflow.

7. Click **Save Expected End Date** to apply the new date.

#### On artifacts

1. On the details page of your artifact,[^12] locate the [active workflows]{.smallcaps} section.

2. Click on the name of the workflow you'd like to edit the end date for to open that specific workflow's details.

3. On the workflow's detail modal, click on the **{{< fa ellipsis-vertical >}}** in the top-right hand corner and select **{{< fa calendar >}} Edit Expected End Date**.

4. Enter in the new [expected end date]{.smallcaps} for the workflow.

5. Click **Save Expected End Date** to apply the new date.

:::

## Abort workflows

{{< include /guide/workflows/_abort-workflows.qmd >}}


<!-- FOOTNOTES -->

[^1]: [Register records in the inventory](/guide/inventory/register-records-in-inventory.qmd)

[^2]: [Add and manage artifacts](/guide/validation/add-manage-artifacts.qmd)

[^3]: [Configure workflows](configure-workflows.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Conditional step requirements](conditional-step-requirements.qmd#wait)

[^6]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^7]: [View and filter artifacts](/guide/validation/view-filter-artifacts.qmd#view-artifacts)

[^8]: [Configure workflows](configure-workflows.qmd#edit-existing-workflows)

[^9]: [Abort workflows](/guide/workflows/manage-workflows.qmd#abort-workflows)

[^10]: [Initiate workflows](/guide/workflows/manage-workflows.qmd#initiate-workflows)

[^11]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd#search-filter-and-sort-records)

[^12]: [View and filter artifacts](/guide/validation/view-filter-artifacts.qmd#view-artifacts)