---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Working with workflows"
date: last-modified
listing:
  - id: workflows
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - manage-workflows.qmd
    - transition-workflows.qmd
    - manage-workflow-tasks.qmd
aliases:
  - /guide/working-with-model-workflows.html
  - /guide/model-workflows/working-with-model-workflows.html
includes:
  workflow:
    view: true
---

Once customized, use workflows to transition your records into their appropriate next stages throughout your risk management lifecycles.

::: {.attn}

## Prerequisites

- [x] {{< var link.login >}}
- [x] Workflows have already been set up for use with your records or artifacts.[^1]
- [x] You are assigned a role with sufficient permissions to view workflows.[^2]

:::

## View all workflow executions

Monitor every workflow execution across your organization on a single timeline:[^3]

1. In the left sidebar, click **{{< fa arrow-right-arrow-left >}} Workflows**.

2. Under the [record type]{.smallcaps} drop-down, select the type of record you want to view all workflow executions for:[^4]

    - In the left column, workflows are grouped by inventory record.
    - Workflows past their [expected end date]{.smallcaps} are color-coded in [red]{.red}.[^5]
    - Use the buttons or keyboard shortcuts[^6] to control the timeline:
      - **{{< fa magnifying-glass-plus >}}** — Zoom in
      - **{{< fa magnifying-glass-minus >}}** — Zoom out
      - **{{< fa arrow-left >}}** — Move earlier to the left
      - **{{< fa calendar-days >}} Go to Today** — Focus on today
      - **{{< fa arrow-right >}}** — Move later to the right
     - **{{< fa magnifying-glass >}} Search** — Search for records using keywords in the record name.
     - **{{< fa filter >}} Filter** — Filter the view to display only runs from specific types and statuses of workflows.[^7]

<br>

::: {.callout-button .pl4 .nt4}
::: {.callout collapse="true" appearance="minimal"}
#### How do I create effective filters?

{{< include /guide/shared/_work-with-filters.qmd >}}
:::
:::

3. Click on any listed workflow to review the details of that specific workflow:

    - **Details** — Name and description (if present) of the workflow, the workflow's status and progress (if applicable), when it was created, and when it was started.
    - **Activity** — History of updates to the workflow on that record, including notes submitted during transitions.[^8]
    - **Artifacts** [record workflows only]{.smallercaps .pink} — Artifacts for that record created within the duration of that workflow's runtime.
    - **Workflow**[^9] — Overview of the entire workflow. The current workflow step is highlighted on this view.

### Manage workflow timeline views

Save searches and filters applied to the workflow timeline as a view to reapply at any time:

#### Manage personal timeline views

::: {.panel-tabset}

### Save personal views

1. Apply a search or filters to the workflow timeline.[^10]

2. Click **{{< fa bookmark >}} Select View** to save your current search and filters.

3. Select **My Views (#)** and click on **{{< fa bookmark >}} Save New View** to create your saved view.

Once you've created a saved personal view, you can share it with others in your organization.[^11]

### Edit or remove saved personal views

::: {.callout-important}
Deletion of saved views is permanent.
:::

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **My Views (#)**.

3. Hover over the name of the view you want to edit or remove.

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select:

    - **{{< fa pencil >}} Edit View** to edit the [view name]{.smallcaps} and [description]{.smallcaps}. Click **Save Changes** to apply your edits.
    - [**{{< fa trash-can >}} Remove View**]{.red} to delete the view. Click **Yes, Delete View** to confirm permanent deletion of that view.

:::

#### Manage organization timeline views

::: {.callout}
To publish a saved personal view to your organization, you must have permissions to manage shared timeline views.[^12]
:::

::: {.panel-tabset}

### Share views with your organization

1. Save a personal workflow timeline view.[^13]

2. Select **My Views (#)**.

3. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

4. Hover over the name of the view you want to share with your organization.

5. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa upload >}} Publish to Organization**.

6. (Optional) Edit the [view name]{.smallcaps} and [description]{.smallcaps} for your shared view.

7. Click **{{< fa upload >}} Publish View** to share your view with your organization.

### Unshare or remove saved organization views

#### Unshare saved organization views

To unshare a saved organization view:

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the view you want to remove from shared organization access.

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa download >}} Unpublish**.

5. Click **Yes, Unpublish View** to confirm removal of the view from shared organization access.

#### Remove saved organization views

To remove a saved organization view:

::: {.callout-important}
Deletion of saved views is permanent.
:::

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the view you want to remove from your organization.

4. When the **{{< fa ellipsis-vertical >}}** appears, click on it and select **{{< fa trash-can >}} Remove View**.

5. Click **Yes, Remove View** to confirm permanent deletion of that view.

:::


## Work with workflows

:::{#workflows}
:::


<!-- FOOTNOTES -->

[^1]: [Configure workflows](configure-workflows.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: To view workflows from within a record or artifact, refer to: [Manage workflows](manage-workflows.qmd#review-workflows)

[^4]: [Manage inventory record types](/guide/inventory/manage-inventory-record-types.qmd)

[^5]: [Manage workflows](manage-workflows.qmd#edit-workflow-end-dates)

[^6]:

    ::: {.callout title="Timeline control shortcuts"}

    - **Move timeline left or right** — <br>
        - Click and drag
        - OR <kbd>Shift</kbd> + scroll wheel
    - **Slow zoom in or out** — <br><kbd>Alt</kbd> + scroll wheel
    - **Quick zoom in or out** — <br><kbd>Ctrl</kbd> + scroll wheel
    :::

[^7]:

    a. Filter by Inventory criteria.
    b. Filter by Workflow criteria:
        - By **Workflow Type**:
            - Record
            - Artifact
        - By **Workflow Status**:
            - Finished
            - Active
            - Scheduled

[^8]:

    Click **{{< fa chevron-down >}}** to reveal notes, and **{{< fa chevron-up >}}** to hide them.
    <br><br>
    [Transition workflows](/guide/workflows/transition-workflows.qmd)

[^9]: Hover over a workflow step to view an animation of the steps connecting to and from that step.

[^10]: [View all workflow executions](#view-all-workflow-executions)

[^11]: [Manage organization timeline views](#manage-organization-timeline-views)

[^12]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^13]: [Manage personal timeline views](#manage-personal-timeline-views)
