---
title: "Edit model inventory fields"
keywords: "edit model inventory fields, model risk management, ValidMind"
---

Learn how to edit individual model detailed fields in the model inventory. This topic is relevant for model owners who want to make model details are accurate and up to date in the Inventory. 

## Prerequisites

* You are a registered user on the ValidMind Platform
* The model is already [registered in the model inventory](register-models.qmd)
* You are the Model Owner for the specific model you would like edit the details of, or an administrator
* You are logged into the ValidMind Platform

## Steps

<!--- NR TO DO Check with Mehdi: these steps didn't work for me, can't edit. Wrong permissions maybe? --->

1. Navigate to the relevant model details in the model inventory: 

   a. From the ValidMind **Home** page, click **Model Inventory** on the left.
   b. Click the relevant model entry to view the model details.

2. Use the **Edit** buttons to edit specific fields on the model details page: 

   a. Make the **Edit** button appear by hovering over a data field you would like to edit.
   b. Click the **Edit** button to modify entries in each field.

3. Click **Done** to save your edits.

::: {.column-margin}
::: {.callout-tip}
The following fields cannot be edited:

- ID
- Model Validators
:::
:::

<!---
## Troubleshooting

[Include any common issues or errors that may arise during the task and how to resolve them.]
--->

## Related topics

* [Create a new documentation project](create-documentation-project.qmd)
<!--- TO DO We don't seem to have a topic for this
* [Edit a documentation project]()
--->
