---
title: "[validmind](/validmind/validmind.html).classifier"
sidebar: validmind-reference
toc-depth: 4
toc-expand: 4
# module.qmd.jinja2
---

<!-- docstring.jinja2 -->

Test suites for sklearn-compatible classifier models

Ideal setup is to have the API client to read a custom test suite from the project's configuration

<!-- class.qmd.jinja2 -->

## [class]{.muted} ClassifierDiagnosis

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">ClassifierDiagnosis</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Test suite for sklearn classifier model diagnosis tests

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} ClassifierFullSuite

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">ClassifierFullSuite</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Full test suite for binary classification models.

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} ClassifierMetrics

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">ClassifierMetrics</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Test suite for sklearn classifier metrics

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} ClassifierModelValidation

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">ClassifierModelValidation</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Test suite for binary classification models.

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} ClassifierPerformance

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">ClassifierPerformance</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Test suite for sklearn classifier models

**Inherited members**
