---
title: "[validmind](/validmind/validmind.html).time_series"
sidebar: validmind-reference
toc-depth: 4
toc-expand: 4
# module.qmd.jinja2
---

<!-- docstring.jinja2 -->

Time Series Test Suites

<!-- class.qmd.jinja2 -->

## [class]{.muted} TimeSeriesDataQuality

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">TimeSeriesDataQuality</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Test suite for data quality on time series datasets

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} TimeSeriesDataset

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">TimeSeriesDataset</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Test suite for time series datasets.

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} TimeSeriesModelValidation

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">TimeSeriesModelValidation</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

Test suite for time series model validation.

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} TimeSeriesMultivariate

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">TimeSeriesMultivariate</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

This test suite provides a preliminary understanding of the features and relationship in multivariate dataset. It presents various multivariate visualizations that can help identify patterns, trends, and relationships between pairs of variables. The visualizations are designed to explore the relationships between multiple features simultaneously. They allow you to quickly identify any patterns or trends in the data, as well as any potential outliers or anomalies. The individual feature distribution can also be explored to provide insight into the range and frequency of values observed in the data. This multivariate analysis test suite aims to provide an overview of the data structure and guide further exploration and modeling.

**Inherited members**

<!-- class.qmd.jinja2 -->

## [class]{.muted} TimeSeriesUnivariate

<!-- signatures.jinja2 -->

::: {.signature}

<span class="kw">class</span><span class="name">TimeSeriesUnivariate</span>(<span class="base">TestSuite</span>):

:::

<!-- docstring.jinja2 -->

This test suite provides a preliminary understanding of the target variable(s) used in the time series dataset. It visualizations that present the raw time series data and a histogram of the target variable(s).

The raw time series data provides a visual inspection of the target variable's behavior over time. This helps to identify any patterns or trends in the data, as well as any potential outliers or anomalies. The histogram of the target variable displays the distribution of values, providing insight into the range and frequency of values observed in the data.

**Inherited members**
