<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

::: {.callout}
To publish a saved personal view to your organization, you must have permissions to manage shared workflow timeline views.^[[Manage permissions](/guide/configuration/manage-permissions.qmd)]
:::

::: {.panel-tabset}

### Share views with your organization

:::: {.content-visible when-format="html" when-meta="includes.workflow.view"}
1. Save a personal workflow timeline view.^[[Manage personal timeline views](/guide/workflows/working-with-workflows.qmd#manage-personal-timeline-views)]

::::

:::: {.content-visible when-format="html" when-meta="includes.inventory"}
1. Save a personal inventory view.^[[Manage personal inventory views](/guide/inventory/customize-inventory-layout.qmd#manage-personal-inventory-views)]

::::

:::: {.content-visible when-format="html" when-meta="includes.artifacts"}
1. Save a personal artifact view.^[[Manage personal artifact views](/guide/validation/customize-artifact-layouts.qmd#manage-personal-artifact-views)]

::::

2. Select **My Views (#)**.

3. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

4. Hover over the name of the view you want to share with your organization.

5. When the  **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa upload >}} Publish to Organization**.

6. (Optional) Edit the [view name]{.smallcaps} and [description]{.smallcaps} for your shared view.

7. Click **{{< fa upload >}} Publish View** to share your view with your organization.

### Unshare or remove saved organization views

#### Unshare saved organization views

To unshare a saved organization view:

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the view you want to remove from shared organization access.

4. When the  **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa download >}} Unpublish**.

5. Click **Yes, Unpublish View** to confirm removal of the view from shared organization access.

#### Remove saved organization views

To remove a saved organization view:

::: {.callout-important}
Deletion of saved views is permanent.
:::

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the view you want to remove from your organization.

4. When the  **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa trash-can >}} Remove View**.

5. Click **Yes, Remove View** to confirm permanent deletion of that view.

:::