<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

:::: {.content-visible when-format="html" when-meta="includes.inventory"}
::: {.callout}
To publish a saved personal layout to your organization, you must have permissions to manage shared inventory record field layouts.^[[Manage permissions](/guide/configuration/manage-permissions.qmd)]

:::

::::

:::: {.content-visible when-format="html" when-meta="includes.artifacts"}
::: {.callout}
To publish a saved personal layout to your organization, you must have permissions to manage shared artifact field layouts.^[[Manage permissions](/guide/configuration/manage-permissions.qmd)]

:::

::::

::: {.panel-tabset}

### Share layouts with your organization

:::: {.content-visible when-format="html" when-meta="includes.inventory"}
1. Save a personal record field layout.^[[Organize, show, or hide record fields](/guide/inventory/customize-record-overview-page.qmd#organize-show-or-hide-record-fields)]

::::

:::: {.content-visible when-format="html" when-meta="includes.artifacts"}
1. Save a personal artifact field layout.^[[Organize, show, or hide artifact fields](/guide/validation/customize-artifact-overview-page.qmd#organize-show-or-hide-artifact-fields)]

::::

2. Click **{{< fa bookmark >}} {Layout Name}** where `{Layout Name}` is the name of your currently active layout, and select **My Configurations (#)**.

3. Hover over the name of the layout you want to share with your organization.

5. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa upload >}} Publish to Organization**.

6. (Optional) Edit the **Layout Name** and **Description** for your shared layout.

7. Click **{{< fa upload >}} Publish Layout** to share your layout with your organization.

### Unshare or remove saved organization layouts

#### Unshare saved organization layouts

To unshare a saved organization layout:

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the layout you want to remove from shared organization access.

4. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa download >}} Unpublish**.

5. Click **Yes, Unpublish View** to confirm removal of the layout from shared organization access.

#### Remove saved organization views

To remove a saved organization view:

::: {.callout-important}
Deletion of saved views is permanent.
:::

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **Organization (#)**.

3. Hover over the layout you want to remove from your organization.

4. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa trash-can >}} Remove View**.

5. Click **Yes, Remove View** to confirm permanent deletion of that view.

### Edit saved organization layouts

Editing while a shared layout is active updates your personal default layout instead of modifying the organization view. To edit a shared organization view:

1. Unpublish the shared layout from your organization.

2. Make the desired changes to your personal view.

4. Share the edited layout with your organization.

### Set saved organization layout as default

Only one layout can be set as the organization default.

1. Click **{{< fa bookmark >}} {Layout Name}*** where `{Layout Name}` is the name of your currently active layout, and select and select ***Organization (#)**.

2. Hover over the name of the layout you want to set as the organization default.

3. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa star >}} Set as organization default**.

:::
