<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

::: {.panel-tabset}

### Save personal layouts

#### Save your first layout

1. Click **{{< fa bookmark >}} Select Layout** and select **My Configurations (#)**.

2. Click **Save as New Configuration** to save changes as a new layout. Enter the:

    - **[layout name]{.smallcaps}**
    - (Optional) **[description]{.smallcaps}**

3. Click **Save New Layout** to create your new layout.

#### Save additional layouts

1. Click **{{< fa bookmark >}} {Layout Name}*** where `{Layout Name}` is the name of your currently active layout.

2. Click **My Configurations (#)**.

3. Select:

   - **Update Configuration** to save changes to the layout you are currently editing. Select **Yes, Update Layout** to apply your changes.
   - **Save as New Configuration** to save changes as a new layout. Edit the **[layout name]{.smallcaps}** and (Optional) **[description]{.smallcaps}** for your new layout. Click **Save New Layout** to create your new layout.

### Edit or remove personal layouts

::: {.callout-important}
Deletion of saved layouts is permanent.
:::

1. Click **{{< fa bookmark >}} {Layout Name}*** where `{Layout Name}` is the name of your currently active layout.

2. Click **My Configurations (#)**.

3. Hover over the name of the layout you want to edit or remove.

4. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select:

    - **{{< fa pencil >}} Edit Configuration** to edit the [layout name]{.smallcaps} and [description]{.smallcaps}. Click **Save Changes** to apply your edits.
    - [**{{< fa trash-can >}} Remove Layout**]{.red} to delete the layout. Click **Yes, Delete Layout** to confirm permanent deletion of that layout.

### Set saved personal layout as default

Setting a personal layout as default will override your organization default for only you. Only one layout can be set as your personal default.

1. Click **{{< fa bookmark >}} {Layout Name}*** where `{Layout Name}` is the name of your currently active layout.

2. Click **My Configurations (#)**.

3. Hover over the name of the layout you want to set as your personal default.

4. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select **{{< fa star >}} Set as my default**.

:::
