<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

::: {.panel-tabset}

### Save personal views

:::: {.content-visible when-format="html" when-meta="includes.workflow.view"}
1. Apply a search or filters to the workflow timeline.^[[View all workflow executions](/guide/workflows/working-with-workflows.qmd#view-all-workflow-executions)]

::::

:::: {.content-visible when-format="html" when-meta="includes.inventory"}
1. Select the type of `{Record}` you want to save a view for by clicking on **{Record} Inventory**, then customize the table view.^[[Customize table view](/guide/inventory/customize-inventory-layout.qmd#customize-table-view)]

    You can also apply filters or sorting before saving your view to include them in the view.^[[Working with the inventory](/guide/inventory/working-with-the-inventory.qmd)]

::::

:::: {.content-visible when-format="html" when-meta="includes.artifacts"}
1. First, customize an artifact layout.^[[Customize artifact layouts by type](/guide/validation/customize-artifact-layouts.qmd#customize-artifact-layouts-by-type)]

   You can also apply filters or sorting before saving your view to include them in the view.^[[View and filter artifacts](/guide/validation/view-filter-artifacts.qmd#filter-and-sort-artifacts)]

::::

2. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

3. Select **My Views (#)** and click on **{{< fa bookmark >}} Save New View** to create your saved view.

4. Enter the **[view name]{.smallcaps}** and **[description]{.smallcaps}** for your saved view.

5. Click **Add New View** to save your saved view.

:::: {.content-visible when-format="html" when-meta="includes.workflow.view"}
Once you've created a saved personal view, you can share it with others in your organization.^[[Manage organization workflow timeline views](/guide/workflows/working-with-workflows.qmd#manage-organization-timeline-views)]

::::

:::: {.content-visible when-format="html" when-meta="includes.inventory"}
Once you've created a saved personal view, you can share it with others in your organization.^[[Manage organization inventory views](/guide/inventory/customize-inventory-layout.qmd#manage-organization-inventory-views)]

::::

:::: {.content-visible when-format="html" when-meta="includes.artifacts"}
Once you've created a saved personal view, you can share it with others in your organization.^[[Manage organization artifact views](/guide/validation/customize-artifact-layouts.qmd#manage-organization-artifact-views)]

::::


### Edit or remove saved personal views

::: {.callout-important}
Deletion of saved views is permanent.
:::

:::: {.content-visible when-format="html" unless-meta="includes.artifacts"}

1. Click on the name of your saved view, or **{{< fa bookmark >}} Select View** if you are not currently displaying a saved view.

2. Select **My Views (#)**.

3. Hover over the name of the view you want to edit or remove.

4. When the **{{< fa ellipsis-vertical >}}** menu appears, click on it and select:

    - **{{< fa pencil >}} Edit View** to edit the [view name]{.smallcaps} and [description]{.smallcaps}. Click **Save Changes** to apply your edits.
    - [**{{< fa trash-can >}} Remove View**]{.red} to delete the view. Click **Yes, Delete View** to confirm permanent deletion of that view.

::::


:::: {.content-visible when-format="html" when-meta="includes.artifacts"}
#### Edit or remove validation issue views

To modify a saved validation issues view:

1. In the left sidebar, click **{{< fa triangle-exclamation >}} Validation Issues** for a list of validation issues across all records.

{{< include /guide/validation/_remove-artifact-view.qmd >}}

#### Edit or remove all other artifact type views

To modify a saved view for all other artifact types:

1. In the left sidebar, click **{{< fa border-all >}} Artifacts** for lists of other artifact types across all records, then select an artifact type^[[Manage artifact types](/guide/validation/manage-artifact-types.qmd)] for a list of that artifact type:

      - Policy Exception
      - Limitation

{{< include /guide/validation/_remove-artifact-view.qmd >}}

::::

:::
