---
title: "QuickStart"
date: last-modified
---

The easiest way to get started with ValidMind is to try out our {{< var vm.developer >}} in JupyterHub and to explore the {{< var validmind.platform >}} online. 

::: {.prereq}

## {{< fa star-of-life >}} Before you begin

To try out ValidMind, you need to be a registered user on the {{< var validmind.platform >}}.

::: {.callout title="Need an account for ValidMind?"}
Signing up is FREE — **[Create your account]({{< var url.us1 >}})**.
:::

:::

### {{< var validmind.developer >}}

To try the {{< var validmind.developer >}}, you need access to **one of the following:**

- [JupyterHub](developer/try-with-jupyterhub.qmd) (recommended)
- [Google Colaboratory](developer/try-with-colab.qmd)
- [Local developer environment](developer/try-in-your-own-environment.qmd)

### {{< var validmind.platform >}}

We support most modern browsers, such as Microsoft Edge, Google Chrome, Apple Safari, or Mozilla Firefox.

To upload from the {{< var vm.developer >}} to the {{< var vm.platform >}} and to access the web user interface, you must be able to access our domains:

- `validmind.ai`
- `validmind.com`

If necessary, ask a network administrator to add these domains to your firewall allowlist (whitelist). If your company has strict security requirements and requires you to connect via VPN or AWS PrivateLink, please contact your IT/InfoSec team.[^1]

## Steps

1. [Try the {{< var validmind.developer >}} with JupyterHub (recommended)](developer/try-with-jupyterhub.qmd) (15 minutes)

   Try our introductory Jupyter Notebook to see the {{< var vm.developer >}} in action. 

2. Explore the {{< var validmind.platform >}} (15 minutes):

    - [Explore sample model documentation](platform/explore-sample-model-documentation.qmd)
    - [Register your first model](platform/register-your-first-model.qmd)
    - [Generate documentation for your model](platform/generate-documentation-for-your-model.qmd)

### What's next

If you're ready to do more with ValidMind, check out [Next steps](platform/next-steps.qmd).


<!-- FOOTNOTES -->

[^1]: For additional help setting up a VPN or PrivateLink with the {{< var validmind.product >}} please visit [configure AWS PrivateLink](/guide/configuration/configure-aws-privatelink.qmd) or send an email to <support@validmind.ai>.
