---
title: "Margin & hover"
subtitle: "Footnotes"
search: false
reference-location: margin
footnotes-hover: true
---

Footnotes in the margin and with hover!

## Beowulf: I

Lesslie Hall translation[^1]:

> Lo! the Spear-Danes'[^2] glory through splendid achievements
>
> The folk-kings' former fame we have heard of,
> 
> How princes displayed then their prowess-in-battle.
> 
> Oft Scyld the Scefing from scathers in numbers
>
> From many a people their mead-benches[^3] tore.

Vivamus faucibus sed lorem vel dignissim. Duis ullamcorper, lorem ut cursus rutrum, elit orci lacinia nulla, in gravida lacus mauris ut sem. Vivamus urna erat, vulputate ut ex eu, pharetra lacinia velit. Quisque vehicula dolor ultricies nulla condimentum, eget auctor diam malesuada. Nullam ac nunc ultricies ligula luctus mattis. Etiam blandit, metus ac rhoncus molestie, ipsum tortor ultrices turpis, sed eleifend mauris diam ac velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam in lorem nec felis iaculis tincidunt vitae quis lorem. Nunc sed mauris rhoncus, lacinia nunc molestie, semper orci. Morbi consequat ipsum sed diam molestie, eget facilisis lorem efficitur. Donec lorem ligula, sollicitudin quis congue eu, commodo vel ipsum. Integer tortor tortor, varius ullamcorper mattis a, ultrices ac felis. Vivamus vitae orci eget odio lobortis lacinia vitae eu purus. Fusce et feugiat ligula. Etiam orci nisl, dictum in eleifend non, iaculis in sapien.

Ut at ipsum lectus. Fusce nec vulputate urna. Quisque luctus metus enim, sed pulvinar augue fringilla non. Duis egestas eget ipsum eget rutrum. Cras vel nisl sit amet enim fringilla malesuada. Curabitur enim justo, ornare sit amet lacus vel, dictum auctor risus. Aenean ullamcorper eros sodales, pharetra diam non, condimentum enim.

Cras eu sapien aliquet, accumsan massa eget, hendrerit ante. Nullam aliquam interdum nisl[^4], vel tristique lorem convallis a. Sed tristique nisi libero, egestas lobortis enim luctus sit amet. Integer sit amet lectus dui. Vestibulum interdum mi eget fermentum hendrerit. Maecenas ac augue accumsan, faucibus tellus vitae, aliquam elit. Quisque in varius urna. Mauris eget elementum diam, nec vehicula augue. Ut id ante sed massa fermentum pulvinar id vitae nulla. Mauris ac magna et massa maximus tempor a nec neque. Maecenas ligula turpis, mattis eget sodales eget, scelerisque a diam. Praesent gravida lacus quis sapien lacinia ullamcorper. Vestibulum nec pellentesque sem.

::: {.callout}
As you can see, this is a much cleaner experience and the notes auto-align with the section it references!
:::


<!-- FOOTNOTES -->

[^1]: [The Life and Death of Scyld](https://www.owleyes.org/text/beowulf/read/i#root-23)

[^2]: The Danes are the residents of Denmark. The Hrothgar, Hrothulf, and Scylding dynasty of kings mentioned are actually spoken of in other Danish and Germanic sources (such as [the poem Widsith](https://en.wikipedia.org/wiki/Widsith)). <br></br>
    
    Some believe that Heorot, the hall of the Danes mentioned in Beowulf, was located on the island of Sjaelland, near the modern-day city of Roskilde, Denmark. 

[^3]: These mead-benches came from mead-halls, which were fortresses and gathering places for medieval Norse and Germanic tribes. Members of society gathered there in safety under the king's protection so that they could feast, share stories, and receive gifts. <br></br>
    
    It is also notable that Valhalla and [Folkvang](https://en.wikipedia.org/wiki/F%C3%B3lkvangr), two divine mead-halls from Scandinavian mythology, are the places where dead souls go in the afterlife. The mead-hall is the center of society, making any attack on the hall, therefore, an assault upon the fabric of society itself.

[^4]: Random note!
