#!/usr/bin/env python3
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
"""
Generate template schema documentation from backend JSON Schema.

Uses json-schema-for-humans to generate HTML documentation from the
template schema used to validate YAML documentation templates.

Usage:
    pip install json-schema-for-humans
    python scripts/generate_template_schema_docs.py

Requirements:
    - Backend repo must be cloned at ../backend/ relative to this repo
    - json-schema-for-humans package installed
"""
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
BACKEND_ROOT = REPO_ROOT.parent / "backend"

SCHEMA_FILE = BACKEND_ROOT / "src/backend/templates/documentation/model_documentation/mdd_template_schema_v5.json"
OUTPUT_FILE = REPO_ROOT / "site/guide/templates/_template-schema-generated.qmd"

# CSS stylesheets to link in the generated HTML
STYLESHEETS = [
    '/styles.css',
    '/assets/styles/template-schema.css',
]


def main():
    # Verify schema file exists
    if not SCHEMA_FILE.exists():
        print(f"Error: Schema file not found: {SCHEMA_FILE}")
        print("Make sure the backend repo is cloned at ../backend/")
        sys.exit(1)

    # Check if json-schema-for-humans is installed
    try:
        subprocess.run(
            ["generate-schema-doc", "--help"],
            capture_output=True,
            check=True
        )
    except FileNotFoundError:
        print("Error: json-schema-for-humans not installed")
        print("Install with: pip install json-schema-for-humans")
        sys.exit(1)

    # Generate HTML documentation
    print(f"Generating schema documentation from {SCHEMA_FILE}...")
    
    # Create temporary output
    temp_output = OUTPUT_FILE.with_suffix(".tmp.html")
    
    subprocess.run([
        "generate-schema-doc",
        "--config", "expand_buttons=true",
        str(SCHEMA_FILE),
        str(temp_output)
    ], check=True)

    # Read generated HTML and inject stylesheet links
    with open(temp_output, "r") as f:
        html_content = f.read()

    # Build stylesheet link tags
    stylesheet_links = '\n'.join(
        f'<link href="{href}" rel="stylesheet">'
        for href in STYLESHEETS
    )

    # Insert stylesheet links after the opening <head> tag
    if "<head>" in html_content:
        html_content = html_content.replace(
            "<head>",
            f"<head>\n{stylesheet_links}"
        )

    # Add scoping class to body for CSS specificity
    html_content = html_content.replace(
        '<body',
        '<body class="template-schema-docs"'
    )

    # Copyright header to place before the raw HTML block
    copyright_header = """<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial

This file is auto-generated by scripts/generate_template_schema_docs.py
Do not edit directly. Re-run the script to update.

Source: backend/src/backend/templates/documentation/model_documentation/mdd_template_schema_v5.json
-->"""

    # Wrap HTML in Quarto raw HTML block for .qmd file, with comment before
    qmd_content = f"""{copyright_header}

```{{=html}}
{html_content}
```
"""

    # Write final output
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(qmd_content)

    # Clean up temp file
    temp_output.unlink()

    print(f"Generated {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
