#!/usr/bin/env python3
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
"""
Generate template schema documentation from backend JSON Schema.

Uses json-schema-for-humans to generate HTML documentation from the
template schema used to validate YAML documentation templates.

Usage:
    pip install json-schema-for-humans
    python scripts/generate_template_schema_docs.py

    # Or with custom backend path:
    BACKEND_ROOT=/path/to/backend python scripts/generate_template_schema_docs.py

Requirements:
    - Backend repo must be cloned (default: ../backend/, or set BACKEND_ROOT)
    - json-schema-for-humans package installed
"""
import os
import re
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
BACKEND_ROOT = Path(os.environ.get("BACKEND_ROOT", REPO_ROOT.parent / "backend"))

SCHEMA_FILE = BACKEND_ROOT / "src/backend/templates/documentation/model_documentation/mdd_template_schema_v5_ui.json"
TARGET_FILE = REPO_ROOT / "site/guide/templates/_template-schema-generated.qmd"

# Minimum expected file size in bytes (sanity check for valid output)
MIN_OUTPUT_SIZE = 1000

# CSS stylesheets to link in the generated HTML
STYLESHEETS = [
    '/styles.css',
    '/assets/styles/template-schema.css',
]


def main():
    # Verify schema file exists
    if not SCHEMA_FILE.exists():
        print(f"Error: Schema file not found: {SCHEMA_FILE}")
        print("Make sure the backend repo is cloned at ../backend/ or set BACKEND_ROOT")
        sys.exit(1)

    # Check if json-schema-for-humans is installed
    try:
        subprocess.run(
            ["generate-schema-doc", "--help"],
            capture_output=True,
            check=True
        )
    except FileNotFoundError:
        print("Error: json-schema-for-humans not installed")
        print("Install with: pip install json-schema-for-humans")
        sys.exit(1)

    # Generate HTML documentation
    print(f"Generating schema documentation from {SCHEMA_FILE}")
    
    # Create temporary output
    temp_output = TARGET_FILE.with_suffix(".tmp.html")
    
    subprocess.run([
        "generate-schema-doc",
        "--config", "expand_buttons=true",
        str(SCHEMA_FILE),
        str(temp_output)
    ], check=True)

    # Read generated HTML and inject stylesheet links
    with open(temp_output, "r") as f:
        html_content = f.read()

    # Strip external CSS/JS that affects global page styling
    # These are included by json-schema-for-humans but break the Quarto page layout
    html_content = re.sub(
        r'<link[^>]*href="https://stackpath\.bootstrapcdn\.com/bootstrap/[^"]*"[^>]*>',
        '',
        html_content
    )
    html_content = re.sub(
        r'<link[^>]*href="https://fonts\.googleapis\.com/css\?family=Overpass[^"]*"[^>]*>',
        '',
        html_content
    )
    html_content = re.sub(
        r'<script[^>]*src="https://use\.fontawesome\.com/[^"]*"[^>]*></script>',
        '',
        html_content
    )
    # Strip local schema_doc.css which has unscoped global body styles
    html_content = re.sub(
        r'<link[^>]*href="schema_doc\.css"[^>]*>',
        '',
        html_content
    )
    # Strip the title tag (not needed when embedded in Quarto page)
    html_content = re.sub(
        r'\s*<title>[^<]*</title>\s*',
        '\n',
        html_content
    )
    # Strip h1 headings (the page already has a heading from Quarto)
    html_content = re.sub(
        r'<h1>[^<]*</h1>',
        '',
        html_content
    )
    # Clean up multiple consecutive blank lines
    html_content = re.sub(r'\n{3,}', '\n\n', html_content)

    # Build stylesheet link tags
    stylesheet_links = '\n'.join(
        f'<link href="{href}" rel="stylesheet">'
        for href in STYLESHEETS
    )

    # Insert stylesheet links after the opening <head> tag
    if "<head>" in html_content:
        html_content = html_content.replace(
            "<head>",
            f"<head>\n{stylesheet_links}"
        )

    # Wrap body content in a div for CSS scoping
    # (Can't use body class because Quarto merges embedded body with its own)
    html_content = re.sub(
        r'(<body[^>]*>)',
        r'\1<div class="template-schema-docs">',
        html_content
    )
    html_content = html_content.replace(
        '</body>',
        '</div></body>'
    )

    # Strip leading/trailing whitespace from HTML content
    html_content = html_content.strip()

    # Build the output content (raw HTML block for Quarto include)
    output_content = f"""<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial

This file is auto-generated by scripts/generate_template_schema_docs.py
Do not edit directly. Re-run the script to update.

Source: {SCHEMA_FILE.relative_to(BACKEND_ROOT.parent)}
-->

```{{=html}}
{html_content}
```
"""

    # Validate output before writing
    if len(output_content) < MIN_OUTPUT_SIZE:
        print(f"Error: Generated output is too small ({len(output_content)} bytes)")
        print("This likely indicates a generation failure.")
        temp_output.unlink(missing_ok=True)
        sys.exit(1)

    if "<html" not in html_content or "</html>" not in html_content:
        print("Error: Generated output does not contain valid HTML structure")
        temp_output.unlink(missing_ok=True)
        sys.exit(1)

    # Write to target file
    TARGET_FILE.write_text(output_content)

    # Clean up temp file
    temp_output.unlink()

    print(f"Generated template schema documentation: {TARGET_FILE}")
    print(f"Output size: {len(output_content)} bytes")


if __name__ == "__main__":
    main()
