<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->


<!-- VISIBLE ONLY ON PAGES THAT HAVE A CUSTOM METADATA TAG:

```includes:
    developer: true
``` -->

:::: {.content-visible when-format="revealjs" when-meta="includes.developer"}
## Get your code snippet

::: {.f4}
Initialize the {{< var validmind.developer >}} with the *code snippet* unique to each record per document, ensuring your test results are uploaded to the correct record and automatically populated in the right document in the {{< var validmind.platform >}} when you run the {{< var vm.developer >}}:

:::

:::: {.columns}

::: {.column width="80%"}

<!-- FOR COPYING THE CODE SNIPPET WE NEED TO USE THIS IFRAME WORKAROUND -->

<div style="zoom: 0.6; overflow: hidden;">
  <iframe 
    src="https://app.prod.validmind.ai/model-inventory" 
    width="100%" 
    height="750" 
    style="border: 1px solid #083E44; border-radius: 8px; border-right-width: 2px; border-bottom-width: 3px;"
    data-preload="yes" 
    sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
    allow="clipboard-read; clipboard-write">
  </iframe>
</div>

:::

::: {.column width="20%" .f4}

::: {.f5}
1. Select the name of your model you registered for this course to open up the model details page.
2. On the left sidebar that appears for your model, click **Getting Started**.
3. Select `Development` from the **[document]{.smallcaps}** drop-down menu.
4. Click **Copy snippet to clipboard**.

When you're done, click [{{< fa chevron-right >}}]() to continue.

:::: {.pl2 .f6 .embed}
**Can't load the {{< var validmind.platform >}}?**

Make sure you're logged in and have refreshed the page in a Chromium-based web browser.

:::

:::

:::

::::


::::

<!-- VISIBLE ONLY ON PAGES THAT **DO NOT** HAVE A CUSTOM METADATA TAG:

```includes:
    developer: true
``` -->

:::: {.content-visible when-format="revealjs" unless-meta="includes.developer"}
## Get your code snippet

::: {.f4}
Initialize the {{< var validmind.developer >}} with the *code snippet* unique to each record per document, ensuring your test results are uploaded to the correct record and automatically populated in the right document in the {{< var validmind.platform >}} when you run the {{< var vm.developer >}}:

:::

:::: {.columns}

::: {.column width="80%"}

<!-- FOR COPYING THE CODE SNIPPET WE NEED TO USE THIS IFRAME WORKAROUND -->

<div style="zoom: 0.6; overflow: hidden;">
  <iframe 
    src="https://app.prod.validmind.ai/model-inventory" 
    width="100%" 
    height="750" 
    style="border: 1px solid #083E44; border-radius: 8px; border-right-width: 2px; border-bottom-width: 3px;"
    data-preload="yes" 
    sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
    allow="clipboard-read; clipboard-write">
  </iframe>
</div>

:::

::: {.column width="20%" .f4}

::: {.f5}
1. Select the name of your model you registered for this course to open up the model details page.
2. On the left sidebar that appears for your model, click **Getting Started**.
3. Select `Validation` from the **[document]{.smallcaps}** drop-down menu.
4. Click **Copy snippet to clipboard**.

When you're done, click [{{< fa chevron-right >}}]() to continue.

:::: {.pl2 .f6 .embed}
**Can't load the {{< var validmind.platform >}}?**

Make sure you're logged in and have refreshed the page in a Chromium-based web browser.

:::

:::

:::

::::


::::










