---
title: "Where do I find &hellip; ?"
sidebar: validmind-training
---

Here's what we have been asked about {{< var vm.product >}} during training sessions. 

## Answers by topic

<!-- DON'T EVEN *THINK* ABOUT PUTTING A PINK BOX AROUND THIS TEXT. :-) -->

### Model inventory

:::: {.flex .flex-wrap .justify-around} 

::: {.w-60-ns .nb3 .pr2}
- How do I configure the model inventory?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](/guide/model-inventory/managing-model-inventory.qmd){.button-small}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I add model inventory fields?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-inventory/manage-inventory-custom-fields.html){.button-small target="blank"}
:::

::::

### User management and roles

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I create new users?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-4){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/manage-users.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I create new user roles?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-6){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/manage-users.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I add users to roles?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-4){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/manage-roles.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I map users to specific groups?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-4){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/manage-groups.html){.button-small target="blank"}
:::

::::

### Workflows for model lifecycle management

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I modify or configure workflows for my use case?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-12){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-workflows/working-with-model-workflows.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I configure workflows for MRM?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/administrator-fundamentals/administrator-fundamentals.html#/section-12){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-workflows/set-up-model-workflows.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I add users into workflows?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/manage-roles.html){.button-small target="blank"}
:::

::::

### Templates for documentation & validation

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I edit templates?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-documentation/customize-documentation-templates.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I add tests to templates?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-documentation/customize-documentation-templates.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I swap templates?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-documentation/customize-documentation-templates.html){.button-small target="blank"}
:::

::::

### Model documentation

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I register a model with existing template?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-inventory/register-models-in-inventory.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I generate documentation for models?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/developers/documenting-models.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I submit my model documentation for validation?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-documentation/submit-for-approval.html){.button-small target="blank"}
:::

::::

### Model testing

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I create custom tests?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/developers/run-tests-and-test-suites.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I reuse existing tests for comparison tests?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/developer-fundamentals/developer-fundamentals.html){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/developers/run-tests-and-test-suites.html){.button-small target="blank"}
:::

::::

### Model validation

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I work with validation reports?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/validator-fundamentals/validator-fundamentals.html#/prepare-validation-reports){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-validation/working-with-model-findings.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I submit validation reports for approval?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa graduation-cap >}} training](https://docs.validmind.ai/training/validator-fundamentals/validator-fundamentals.html#/submit-for-review-and-approval){.button-small target="blank"} [{{< fa book-open >}} docs](https://docs.validmind.ai/guide/model-documentation/submit-for-approval.html){.button-small target="blank"}
:::

::::

### Monitoring

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I set up monitoring?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/monitoring/enable-monitoring.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I integrate monitoring with documentation process?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/monitoring/ongoing-monitoring.html){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I schedule quarterly/monthly runs?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} docs](https://docs.validmind.ai/guide/monitoring/work-with-metrics-over-time.html){.button-small target="blank"}
:::

::::

### Data management

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- How do I work with reference datasets?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa book-open >}} code sample](https://docs.validmind.ai/notebooks/code_samples/nlp_and_llm/llm_summarization_demo.html#initialize-the-python-environment){.button-small target="blank"}
:::

::::

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns .nb3 .pr2}
- Can we connect to external data sources?
:::

::: {.w-40-ns .nb3 .pl2}
[{{< fa brands python >}} pandas docs](https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html){.button-small target="blank"}
:::

::::

{{< include /training/_training-support.qmd >}}

{{< include /support/_submit-feedback.qmd >}}
