## What solutions does {{< var vm.product >}} offer?

{{< var vm.product >}} is a {{< var vm.developer >}} and cloud {{< var vm.platform >}} available in multiple editions catering to different organizational needs:

- **Standard Edition**: Our introductory offering, providing essential features and services.
- **Enterprise Edition**: Builds upon the Standard Edition by adding features tailored for large-scale organizations.
- **{{< var validmind.vpv >}} (VPV)**:^[[{{< var validmind.vpv >}} (VPV)](/about/deployment/virtual-private-validmind.qmd)] Our most secure offering for organizations requiring a higher level of privacy, such as financial services handling sensitive data. Includes all Enterprise Edition features but in a separate, isolated {{< var vm.product >}} environment. VPV accounts do not share resources with accounts outside the VPV.

::: {.callout}
## Access to any edition is facilitated through AWS PrivateLink, which provides private connectivity between {{< var vm.product >}} and your on-premises networks without exposing your traffic to the public internet.^[[Configure AWS PrivateLink](/guide/configuration/configure-aws-privatelink.qmd)] 

{{< var vm.product >}} does not send any personally identifiable information (PII) through our {{< var vm.api >}}.
:::