<!-- Copyright © 2023-2026 ValidMind Inc. All rights reserved.
Refer to the LICENSE file in the root of this repository for details.
SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial -->

## What export options are available in {{< var vm.product >}}?

- Inventory records can be exported as comma-delimited tables (`.csv`)^[[Export inventory](/guide/reporting/export-inventory.qmd)]
- Documents can be exported as Word (.docx) or Portable Document Format (.pdf) files^[[Export documents](/guide/reporting/generating-exports.qmd)]
- Artifacts can be exported as comma-delimited tables (`.csv`)^[[Export artifacts](/guide/reporting/export-artifacts.qmd)]
- Analytics can be exported as comma-delimited tables (`.csv`)^[[Export analytics](/guide/reporting/export-analytics.qmd)]

Depending on the integration requirements of the systems used by your validation teams, such as connectivity via API, SharePoint, and more, {{< var vm.product >}} can work with you to automate the export and storage of inventory records into these systems

