---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Reporting and ongoing monitoring"
date: last-modified
listing:
  - id: faq-reporting
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../guide/reporting/working-with-analytics.qmd
    - ../guide/reporting/generating-exports.qmd
    - ../guide/monitoring/ongoing-monitoring.qmd
categories: ["exports", "analytics", "reports", "ongoing monitoring", "validmind platform", "activity", "auditing"]
---

{{< include _faq-record-activity.qmd >}}

{{< include _faq-settings-activity.qmd >}}

## What analytic features are offered by {{< var vm.product >}}?

- Out-of-the-box reports within the {{< var validmind.platform >}}[^1] are broken down by data on model-type records and data on validation issue artifacts.
- For each of the bar charts, you can hover for numerical breakdowns or click on individual bars to get a more detailed view.[^2]
- You're also able to add custom report pages and analytic widgets to supplement the out-of-the-box reports provided.[^3]

By default, the [{{< fa hand >}} Customer Admin]{.bubble} role[^4] has sufficient permissions to manage custom reporting.

{{< include _faq-exporting.qmd >}}

## How can I export platform data on a schedule to cloud storage?

{{< var vm.product >}} allows you to configure data exports for platform datasets on a schedule to cloud storage, such as Amazon S3, Google Cloud Storage, or Azure Blob Storage.[^5] These exports include:

- Inventory record datasets, including custom inventory record types.[^6]
- Artifact datasets, including validation issues, limitations, policy exceptions, and custom artifact types.[^7]
- Record Activity logs, such as comments, workflow status changes, field updates, document changes, artifact updates, and test-result updates.[^8]
- Settings Activity logs, such as changes to roles, users, workflows, record configuration, artifact configuration, governance settings, document settings, webhook secrets, and page layouts.[^9]

{{< include _faq-monitoring.qmd >}}

## Learn more

:::{#faq-reporting}
:::


<!-- FOOTNOTES -->

[^1]: [Accessing {{< var vm.product >}}](/guide/access/accessing-validmind.qmd)

[^2]: [View report data](/guide/reporting/view-report-data.qmd)

[^3]: [Manage custom reports](/guide/reporting/manage-custom-reports.qmd)

[^4]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^5]: [Configure data exports](/guide/integrations/configure-data-exports.qmd)

[^6]: [Working with the inventory](/guide/inventory/working-with-the-inventory.qmd)

[^7]: [Working with artifacts](/guide/validation/working-with-artifacts.qmd)

[^8]: [View record activity](/guide/reporting/view-record-activity.qmd)

[^9]: [View settings activity](/guide/reporting/view-settings-activity.qmd)
