---
title: "Access and permissions"
date: last-modified
listing:
  - id: faq-organizations
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../guide/access/accessing-validmind.qmd
    - ../guide/configuration/managing-your-organization.qmd
    - ../guide/configuration/managing-users.qmd
categories: ["access", "permissions", "organizations", "user registration", "validmind platform"]
---

## How do I get access to {{< var vm.product >}}?

#### 1. Register with ValidMind

- First register with our cloud-hosted {{< var validmind.platform >}},[^1] which enables you to work with model documentation or configure ValidMind for your organization.
- With an email address or a Google, GitHub, or Microsoft account, you can gain access to ValidMind either by signing up independently, or by accepting an invite from another member of your organization.

#### 2. Log in to ValidMind

- Once you've signed up or accepted an invite, log in to the {{< var validmind.platform >}}.[^2]
- {{< var vm.product >}} supports logging in via both the public interent and private network endpoints.

## What are organizations within {{< var vm.product >}}?

Access to the {{< var validmind.platform >}} where your model inventory is hosted is associated with an organization,[^3] which encompasses all your users, groups, and business units. 

- As a user,[^4] you can belong to multiple organizations.
- You will see the option to switch between organizations only if you belong to more than one organization.

By default, the [{{< fa hand >}} Customer Admin]{.bubble} role[^5] has sufficient permissions to manage your organization.

## How are users added to {{< var vm.product >}} organizations?

- {{< var vm.product >}} provides a built-in user management interface that allows new users to be registered on the {{< var validmind.platform >}} and assigned user roles[^6] and user groups.[^7]
- User roles, user groups, and access permissions are configured during initial onboarding and can be updated at any time.
- In addition, {{< var vm.product >}} also offers support for Single Sign-On (SSO) integration.

## How do user roles, user groups, and access permissions work? 

 - Users belong to groups which determine which models they can see, and have roles with attached permissions which define the level of access they have to features.
 - Groups are segments of users with the ability to view models associated with that group. Access to granular features in the {{< var vm.platform >}} within a group’s set of models is further defined by roles and permissions.
 - Roles are a named set of permissions that determine your users’ access to features within the {{< var vm.platform >}} based on your organization’s structure. 
 - Permissions dictate user access controls within the {{< var vm.platform >}}, and are associated with specific roles.

By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to manage access permissions for users, groups, and roles.

## Learn more

:::{#faq-organizations}
:::


<!-- FOOTNOTES -->

[^1]: [Register with ValidMind](/guide/access/register-with-validmind.qmd)

[^2]: [Log in to ValidMind](/guide/acess/log-in-to-validmind.qmd)

[^3]: [Set up your organization](/guide/configuration/set-up-your-organization.qmd)

[^4]: [Manage users](/guide/configuration/manage-users.qmd)

[^5]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^6]: [Manage roles](/guide/configuration/manage-roles.qmd)

[^7]: [Manage groups](/guide/configuration/manage-groups.qmd)
