---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Workflows and lifecycles"
date: last-modified
aliases:
  - /guide/faq-workflows.html
listing:
  - id: faq-workflows
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../guide/workflows/introduction-to-workflows.qmd
    - ../guide/workflows/setting-up-workflows.qmd
    - ../guide/workflows/working-with-workflows.qmd
categories: ["workflows", "lifecycles", "record stages", "validmind platform", "validmind library"]
---

## Can I customize workflows within {{< var vm.product >}}?

- Yes, you can create custom workflows for the review and approval of records (such as models) throughout their lifecycles with {{< var validmind.platform >}},[^1] enabling you to more easily oversee your organization's unique risk management process.
- For example, workflows can be configured to include any number of review stages involving different sets of stakeholders — at any point in the process.

By default, the [{{< fa hand >}} Customer Admin]{.bubble} role[^2] has sufficient permissions to manage workflows.

## What record stages are available for use in workflows?

- Record stages,[^3] used to track the progress of your records through your organization's lifecycles, are manipulated via workflow transitions and can also be fully customized within the {{< var validmind.platform >}}.
- Default stages are provided for you as suggestions. You can add, edit, remove, and define your own custom stages.

By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to manage record stages.

{{< include _faq-progress-workflow.qmd >}}

## Can we work with disconnected workflows?

Yes, {{< var vm.product >}} supports disconnected workflows natively at the data-collection level since the {{< var validmind.developer >}}[^4] creates individual test runs every time a new test iteration is executed.

- This allows for running parallel/disconnected tests that individually send results to the {{< var validmind.platform >}}.
- Visualizing the disconnected workflow in terms of testing and documentation will depend on requirements at the use-case level.

::: {.callout}
## You can also leverage the {{< var validmind.developer >}} once you are ready to document a specific record (model) for review and validation.

You do not need to use the {{< var validmind.platform >}} while you are in the exploration or R&D phase of development.
:::

{{< include _faq-tracking.qmd >}}

## Learn more

:::{#faq-workflows}
:::


<!-- FOOTNOTES -->

[^1]: [Accessing {{< var vm.product >}}](/guide/access/accessing-validmind.qmd)

[^2]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^3]: [Manage record stages](/guide/workflows/manage-record-stages.qmd)

[^4]: [{{< var validmind.developer >}}](/developer/validmind-library.qmd)