---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Validation and artifacts"
date: last-modified
listing:
  - id: faq-validation
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../guide/validation/managing-validation.qmd
    - ../guide/validation/preparing-validation-reports.qmd
    - ../guide/validation/working-with-artifacts.qmd
categories: ["validation", "validation guidelines", "artifacts", "findings", "documentation", "templates", "compliance", "validmind platform"]
---

## Can I set up custom validation guidelines for use in templates?

Yes, {{< var vm.product >}} supports the implementation of custom validation guidelines from within the {{< var validmind.platform >}}:[^1]

1. After you set up risk areas for your organization, you can then add guidelines to each risk area.[^2]
2. Once guidelines are available, add them to the desired validation report templates.

By default, the [{{< fa hand >}} Customer Admin]{.bubble} role[^3] has sufficient permissions to manage validation guidelines.

## How does {{< var vm.product >}} help with assessing compliance?

Use {{< var vm.product >}} to assess compliance of your records (such as models) with guidelines based on analyzing evidence and artifacts (findings),[^4] providing an unbiased starting point that enables more efficient discussions between validators and developers.

Without leaving the {{< var validmind.platform >}}, you're able to:

1. Link logged evidence to validation reports.
2. Link tracked artifacts to validation reports.
3. Provide granular compliance assessments for each section of your validation report.

By default, the [{{< fa circle-check >}} Validator]{.bubble} role has sufficient permissions to assess compliance on validation reports.

{{< include _faq-document-checker.qmd >}}

## What support does {{< var vm.product >}} offer for artifacts?

- Within the {{< var validmind.platform >}}, you're able to log artifacts at the record (model) level, or optionally attach an artifact to a documentation section if that option has been enabled for that artifact type.[^5]
- On each artifact are attached artifact fields. Default artifact types provided by {{< var vm.product >}} include default artifact fields[^6] — you can also create custom artifact fields to track additional information for your artifacts.[^7]
<!-- For example, on Validation Issue type artifacts, you're able to outline proposed remediation plans, attach supporting documentation, track the artifact's status, attach the artifact to a risk area and/or documentation section, designate a due date, and assign a resolution owner. -->
- You can also access a complete list of filterable artifacts logged across all your records, or look at only artifacts linked to a specific record.[^8]

By default, the [{{< fa circle-check >}} Validator]{.bubble} role has sufficient permissions to manage artifacts.

## Can I create custom artifact types?

Yes, you can create custom artifact types to track categories of observations beyond the default types of:[^9]

- Validation Issue
- Policy Exception
- Limitation

Custom artifact types support the same features as default types, including custom statuses, fields, and workflow triggers.

## Can {{< var vm.product >}} artifact lists and layouts be customized?

- Yes, information that is displayed on artifact lists is configurable.[^10]
- You can also search, filter, and sort artifacts to narrow down results.
- Fields that appear on artifacts can also be customized.[^11]

{{< include _faq-attachments.qmd >}}

{{< include _faq-record-activity.qmd >}}

## Learn more

:::{#faq-validation}
:::


<!-- FOOTNOTES -->

[^1]: [Accessing {{< var vm.product >}}](/guide/access/accessing-validmind.qmd)

[^2]: [Manage validation guidelines](/guide/validation/manage-validation-guidelines.qmd)

[^3]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^4]: [Assess compliance](/guide/validation/assess-compliance.qmd)

[^5]: [Log artifacts](/guide/validation/log-artifacts.qmd)

[^6]: [Manage artifact types](/guide/validation/manage-artifact-types.qmd)

[^7]: [Manage artifact fields](/guide/validation/manage-artifact-fields.qmd)

[^8]: [View and filter artifacts](/guide/validation/view-filter-artifacts.qmd)

[^9]: [Manage artifact types](/guide/validation/manage-artifact-types.qmd)

[^10]: [Customize artifact layouts](/guide/validation/customize-artifact-layouts.qmd)

[^11]: [Customize artifact overview page](/guide/validation/customize-artifact-overview-page.qmd)