---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Data handling and privacy"
date: last-modified
aliases:
  - /guide/faq-privacy.html
  - faq-data-handling.html
  - /guide/faq-data-handling.html
listing:
  - id: faq-privacy
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../about/deployment/deployment-options.qmd
    - ../about/fine-print/data-privacy-policy.qmd
    - ../guide/model-inventory/view-model-activity.qmd
categories: ["data handling", "privacy", "confidentiality", "model activity", "auditing", "validmind platform", "validmind library"]
---

## How does {{< var vm.product >}} handle the processing of PII?

{{< var vm.product >}} does not send any personally identifiable information (PII) through our {{< var validmind.api >}}.[^1]

Access to the {{< var validmind.platform >}} is facilitated through AWS PrivateLink, which provides private connectivity between {{< var vm.product >}} and your on-premises networks without exposing your traffic to the public internet.[^2]

## What model assets are automatically imported into {{< var vm.product >}}?

{{< var vm.product >}} stores the following assets in the documentation via our {{< var validmind.api >}}:

- Dataset and model metadata which allow generating documentation snippets programmatically (example: stored definition for "common logistic regression limitations" when a logistic regression model has been passed to the {{< var vm.product >}} test suite execution)
- Quality and performance metrics collected from the dataset and model
- Outputs from executed test suites
- Images, plots, and visuals generated as part of extracting metrics and running tests

## How is data retained within {{< var vm.product >}}?

- {{< var vm.product >}} is a multi-tenant or single-tenant solution hosted on cloud providers.
- With multi-tenant deployments, infrastructure is shared but with strict data isolation protocols that ensure that no tenant can access another's sensitive information. 

::: {.callout}
## For organizations requiring the highest degree of data security, {{< var vm.product >}} offers a {{< var validmind.vpv >}} (VPV)[^3] option to host the solution in a dedicated single-tenant cloud instance on the {{< var vm.product >}} cloud account. 

Furthermore, {{< var vm.product >}}'s data retention policy complies with the SOC 2 security standard.
:::

## What about the confidentiality or size of data sent to {{< var vm.product >}}?

- {{< var vm.product >}} does not send datasets outside the client's environment. 
- The {{< var validmind.developer >}} executes test suites and functions locally in your environment and is not limited by dataset size.

{{< include _faq-activity.qmd >}}

{{< include _faq-model-updates.qmd >}}

<!-- BELOW REMOVED AFTER ANDRES CONFIRMED WE DON'T SUPPORT SPARK DATAFRAMES IN A WAY OUR USERS WOULD EXPECT - BC (Nov 27, 2024) -->

<!-- ## Can you accommodate Spark DataFrames?

- Yes, the {{< var validmind.developer >}} can extract dataset quality metrics on Pandas DataFrame, NumPy arrays, or Spark DataFrame instances using standard metrics provided by popular open-source frameworks such as scikit-learn, statsmodels, and more.
- Each test defines a mapping to the different supported dataset and/or model interfaces — when passing a Spark DataFrame, the {{< var vm.developer >}} will directly call native evaluation metrics provided by the SparkML API or custom ones built by the developer, such as via UDFs. -->

<!-- BELOW REMOVED ON REQUEST AS PER SC-6528 -->

<!-- ## How does {{< var vm.product >}} handle end-user computing and spreadsheet models?

Customers can register spreadsheet models in the model inventory and centralize tracking of the associated documentation files with the inventory metadata (roadmap item – Q3’2023). However, {{< var vm.product >}} cannot automate documentation generation for spreadsheet models. -->

<!-- ## Can the tool automatically document other non-standard ETL steps or performance metrics from notebooks?

Support for more complex data processing pipelines is on our roadmap, currently scheduled for Q4'2023. We are implementing connector interfaces that will allow us to extract relationships between raw data sources and final post-processed datasets for Spark and Snowflake. -->

<!-- ## Can we customize illustrations?

{{< var vm.product >}} utilizes open-source libraries (such as Seaborn and Matplotlib) to generate plots and illustrations. We are working on implementing the ability for model developers to customize styling parameters for these libraries directly within the {{< var vm.developer >}}.

This feature is currently scheduled for Q4 2023.

Additionally, {{< var vm.product >}} is developing a feature that enables developers to create custom visualization widgets by writing JavaScript-based rendering code. -->

## Learn more

:::{#faq-privacy}
:::


<!-- FOOTNOTES -->

[^1]: [{{< var validmind.developer >}}](/validmind/validmind.qmd)

[^2]: [Configure AWS PrivateLink](/guide/configuration/configure-aws-privatelink.qmd)

[^3]: [{{< var validmind.vpv >}} (VPV)](/about/deployment/virtual-private-validmind.qmd)