---
title: Model inventory
date: last-modified
aliases:
  - ../guide/faq-inventory.html
listing:
  - id: faq-inventory
    type: grid
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../guide/configuration/managing-users.qmd
    - ../guide/model-inventory/manage-model-inventory-fields.qmd
    - ../guide/model-inventory/archive-delete-models.qmd
    - ../guide/model-inventory/configure-model-interdependencies.qmd
---

## How do access permissions to the {{< var validmind.platform >}} work? 

Access to the {{< var validmind.platform >}} where your model inventory is hosted is associated with an organization, which encompasses all your users, groups, and business units. 

 - Users belong to groups which determine which models they can see, and have roles with attached permissions which define the level of access they have to features.
 - Groups are segments of users with the ability to view models associated with that group. Access to granular features in the {{< var vm.platform >}} within a group’s set of models is further defined by roles and permissions.
 - Roles are a named set of permissions that determine your users’ access to features within the {{< var vm.platform >}} based on your organization’s structure. 
 - Permissions dictate user access controls within the {{< var vm.platform >}}, and are associated with specific roles.

::: {.callout}
By default, the [{{< fa hand >}} Customer Admin]{.bubble} role[^1] has sufficient permissions to manage access permissions for users, groups, and roles.
:::

## Can the {{< var vm.product >}} model inventory be customized?

The information that is displayed on the model inventory is configurable on a per user basis.

 - Fields that appear on all models for all users can also be customized. 
 - By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to manage model inventory fields.

## Can I archive or delete models within {{< var vm.product >}}?

Yes, models can be archived within the {{< var validmind.platform >}} model inventory to keep your inventory accurate and up to date with your organization’s current resources.
 
- Once models are archived, they can then be deleted if desired. 
- By default, the [{{< fa hand >}} Customer Admin]{.bubble} role has sufficient permissions to archive and delete models.

## Can I track model interdependencies within the model inventory?

Yes, the {{< var validmind.platform >}} allows you to connect two or more models together in your model inventory. 

- You can note both upstream and downstream models.
- By default, the [{{< fa code >}} Developer]{.bubble} role has sufficient permissions to edit model interdependencies.

## How do I track activity on models, documentation, validation reports, etc.?

The {{< var validmind.platform >}} provides an audit trail functionality, enabling you to track or audit all the information events associated with a specific model. 

You can review a full record of comments, workflow status changes, and any other updates made to the model.

<!-- BELOW REMOVED ON REQUEST AS PER SC-6528 -->

<!-- ## Can the model inventory track revalidation, periodic validation dates, and more?

In addition to initial validation exercises, {{< var vm.product >}} can manage activities throughout the entire model risk management lifecycle, including periodic reviews, change validations, and ongoing monitoring deadlines (roadmap item – Q3 2023). -->

## Does {{< var vm.product >}} support reporting and exporting features?

## Do you support executive reporting for senior leaders in our BUs?

{{< var vm.product >}} is working on a dashboard feature that provides executive metrics, such as model documentation compliance reporting across BUs, findings by status and model use case, and more.

These metrics can be exported into a customizable report for the customer.

## Learn more

:::{#faq-inventory}
:::


<!-- FOOTNOTES -->

[^1]: [Manage permissions](/guide/configuration/manage-permissions.qmd)