---
title: "Collaboration"
date: last-modified
aliases:
  - ../guide/faq-workflows.html
listing:
  - id: faq-collaboration
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../guide/model-workflows/working-with-model-workflows.qmd
---

## How are parallel editing and version control handled?

{{< var vm.product >}} currently allows multiple users to simultaneously edit documentation in the {{< var validmind.platform >}}. If two users are editing the same cell on the UI, the most recently saved version of the content will prevail. 

{{< var vm.product >}} is implementing more sophisticated version control features:

- {{< var vm.product >}} will provide a detailed version and revision history, and notification system, for you to view what changes have been applied to the documentation (roadmap item for Q2’2023).
- The {{< var vm.platform >}} will provide an indication if another user is currently editing the same cell on the online UI (roadmap item for Q3’2023).
- Administrators will be given the ability to configure content syncing and session management preferences (roadmap item currently scheduled for Q4’2023).


