---
# Copyright © 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial
title: "Documents and templates"
date: last-modified
aliases:
  - /guide/faq-documentation.html
listing:
  - id: faq-documentation
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, description]
    contents:
    - ../guide/templates/managing-documents.qmd
    - ../guide/templates/managing-document-templates.qmd
    - ../guide/documentation/working-with-documentation.qmd
categories: ["templates", "documents", "documentation", "customization", "images", "attachments","validmind platform", "validmind library"]
---

## What kind of templates are provided by {{< var vm.product >}}?

{{< var vm.product >}} provides the following default template types:[^1]

- Development (documentation)
- Validation (validation reports)
- Monitoring (ongoing monitoring reports)

You can also create custom document types and associated templates to suit your organization's unique needs.[^2]

## Can templates be customized for our use cases?

Yes, the {{< var validmind.platform >}}[^3] allows you to configure versioned templates based on document requirements for each record (such as a model) or lifecycle use case.

- {{< var vm.product >}}'s templates are fully customizable,[^4] and are complemented by the ability to manage validation guidelines.
- You can swap between different versions of templates or apply another version of the current template.[^5]
- Template outlines can be modified right in the {{< var validmind.platform >}}. We also offer an advanced raw YAML editor, enabling you to make detailed changes.

By default, the [{{< fa hand >}} Customer Admin]{.bubble} role[^6] has sufficient permissions to manage document templates, and you must be a [{{< fa code >}} Developer]{.bubble} or [{{< fa circle-check >}} Validator]{.bubble} to be able to swap document templates.

## Is content from existing documents or templates reusable?

Yes, you can reuse content from existing documents or templates:

- Build a library of reusable text blocks to insert into your documents, including content from existing documents.[^13]
- Duplicate document templates to create new templates with the same content, then edit those duplicates to fit your needs.[^14]

## Can documents be created right in the {{< var validmind.platform >}}?

Yes, you can work with documentation, validation reports, ongoing monitoring reports, or any other document type directly in the {{< var validmind.platform >}}, without having to first generate anything using the {{< var validmind.developer >}}.[^7]

1. Add and edit text on any document within the {{< var vm.platform >}} using our content editing toolbar.[^8]
2. Using the {{< var vm.developer >}}, execute test suites and generate the corresponding supporting results. These results can then be added to your documents within the {{< var vm.platform >}}.[^9]

## Can I run tests and log documentation without a record?
<span id="no-available-model"></span>
Yes! If you do not have a record (such as a model) ready, or your record can't be loaded directly, or you only have access to predictions, you can still run tests and log documentation using the {{< var validmind.developer >}} as long as you're able to load the predictions.

- Use `assign_predictions()`[^10] to load predictions from a separate file or a dataset with predictions.
- Call `init_model()`[^11] to create a model object, but instead of a trained instance, pass an `input_id` and model metadata. `ModelMetadata()`[^12] will use the provided metadata instead of trying to calculate it from the model's library.


::: {.column-margin}
**For example:**

```python
  external_model = vm.init_model(
      input_id="spark_ml_model",
      metadata={...}
  )
```
:::

::: {.callout title="If neither a trained instance nor metadata is provided, `init_model()` will return an error."}
- However, tests that need a trained model will not work with "empty" models.
- Despite the naming convention, model objects can be any type of record you want to test, document, validate, or monitor with {{< var vm.product >}}.

:::

{{< include _faq-attachments.qmd >}}

{{< include _faq-images.qmd >}}

{{< include _faq-document-updates.qmd >}}

## Can we leverage content from historical or external documents?

Yes, {{< var vm.product >}} allows you to leverage content from historical or external documents:

- Convert a Portable Document Format `.pdf` file (PDF) into an editable document in the {{< var validmind.platform >}}, allowing you to seamlessly work with existing PDFs as you would with any other template-based document, such as adding content blocks and attaching test results.[^15]
- You can also choose to upload the PDF as a static document, which is stored as a static file. You can view it within the {{< var vm.platform >}} but you cannot modify its structure or contents.

{{< include _faq-document-checker.qmd >}}

{{< include _faq-exporting.qmd >}}

## Learn more

:::{#faq-documentation}
:::


<!-- FOOTNOTES -->

[^1]: [Manage document templates](/guide/templates/manage-document-template-library.qmd)

[^2]: [Manage document types](/guide/templates/manage-document-types.qmd)

[^3]: [Accessing {{< var vm.product >}}](/guide/access/accessing-validmind.qmd)

[^4]: [Customize document templates](/guide/templates/customize-document-templates.qmd)

[^5]: [Manage document templates](/guide/templates/manage-document-template-library.qmd)

[^6]: [Manage permissions](/guide/configuration/manage-permissions.qmd)

[^7]: [{{< var validmind.developer >}}](/developer/validmind-library.qmd)

[^8]: [Work with content blocks](/guide/documentation/work-with-content-blocks.qmd)

[^9]: [Work with test results](/guide/documentation/work-with-test-results.qmd)

[^10]: [`assign_predictions()`](/validmind/validmind/vm_models.qmd#assign_predictions)

[^11]: [`init_model()`](/validmind/validmind.qmd#init_model)

[^12]: [`ModelMetadata()`](/validmind/validmind/tests/model_validation/ModelMetadata.qmd#modelmetadata)

[^13]: [Manage text block library](/guide/templates/manage-text-block-library.qmd)

[^14]: [Manage document templates](/guide/templates/manage-document-template-library.qmd)

[^15]: [Manage documents](/guide/templates/manage-documents.qmd#add-record-documents)
