---
title: "Using {{< var vm.product >}} <br>for Model Validation"
subtitle: "Validator Fundamentals — Module 1 of 4<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
lightbox: true
format:
  revealjs:
    controls: true
    controls-tutorial: true
    help: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /validmind.png
    footer: "{{< var validmind.training >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/training/training.qmd)"
  html:
  # Change this to the file name prepended by a _ to get around the global HTML output settings required by _metadata.yml
    output-file: _using-validmind-for-model-validation.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

# Learning objectives {.center}

_"As a **validator** who is new to {{< var vm.product >}}, I want to learn how to connect to a champion model in the {{< var validmind.platform >}} using the {{< var validmind.developer >}} installed in my local environment, preview the model's validation report template, and review submitted documentation for the model."_

::: {.tc}
<br>
This first module is part of a four-part series:
<br><br>
[Validator Fundamentals](/training/validator-fundamentals/validator-fundamentals-register.qmd){.button target="_blank"}
:::


## Module 1 — Contents {.center}

::: {.f2}
1. [{{< var vm.product >}} for model validation](#validmind-for-model-validation)
2. [Connect to your champion model](#connect-to-a-model)
3. [Preview your model's validation report template](#preview-validation-report)
4. [Review submitted model documentation](#review-model-documentation)

:::

First, let's make sure you can log in to {{< var vm.product >}}.

{{< include /training/assets/_revealjs-navigation.qmd >}}

## Before you begin {.center}

::: {.panel-tabset}

### Registration

To continue, you need to have been [onboarded](developer-fundamentals-register.qmd#register){target="_blank"} onto {{< var validmind.training >}} with the [**{{< fa circle-check >}} Validator**]{.bubble} role.

<br>

:::: {.tc .mt5 .f2 .embed}
Already logged in and refreshed this module? Click [{{< fa chevron-right >}}]() to continue.

:::


### Log in

1. Log in to check your access:

:::: {.flex .flex-wrap .justify-around}

::: {.w-50-ns .tc}

[Log in to JupyterHub](https://jupyterhub.validmind.ai/){.button target="_blank"}

:::

::: {.w-50-ns .tc}
[Log in to {{< var vm.product >}}](https://app.prod.validmind.ai){.button target="_blank"}
:::

::::


::: {.tc .f3}
Be sure to return to this page afterwards.
:::

2. After you successfully log in, refresh the page to connect this training module up to the {{< var validmind.platform >}}: 

::: {.tc}
<button class="button" onClick="window.location.reload();">Refresh Page</button>

:::

:::

<br>

<!-- USING THE VARIABLE IN THE HEADING MESSES UP THE PAGE ANCHOR -->

# ValidMind for model validation {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Jupyter Notebook series

::: {.f3}
These notebooks walk you through how to validate a model using {{< var vm.product >}}, complete with supporting test results attached as evidence to your validation report.

:::
:::

::: {.column width="70%" .bl .pl4 .f3}
### {{< var vm.product >}} for model development

Our series of four introductory notebooks for model validators include sample code and how-to information to get you started with {{< var vm.product >}}:

1 — [Set up the {{< var validmind.developer >}} for validation](/notebooks/tutorials/model_validation/1-set_up_validmind_for_validation.ipynb){target="_blank"}<br>
2 — [Start the model validation process](/notebooks/tutorials/model_validation/2-start_validation_process.ipynb){target="_blank"}<br>
3 — [Developing a potential challenger model](/notebooks/tutorials/model_validation/3-developing_challenger_model.ipynb){target="_blank"}<br>
4 — [Finalize testing and reporting](/notebooks/tutorials/model_validation/4-finalize_validation_reporting.ipynb){target="_blank"}<br>
<br>

::: {.f4 .pl3 .pr3 .embed}
In this first module, we'll run through **1 — Set up the {{< var validmind.developer >}} for validation** together.
:::

:::
::::

<br>

Let's start our journey with **1 — Set up the {{< var validmind.developer >}} for validation** on the next page. {{< fa hand-point-right >}}


<!-- CHANGE THIS TO EXECUTED LATER -->

## {background-iframe="/notebooks/tutorials/model_validation/1-set_up_validmind_for_validation.html" background-interactive="yes" data-preload="yes"} 

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f4 .tc .pl4 .pr4 .overlay}
**1 — Set up the {{< var validmind.developer >}} for validation**

::: {.f5}
During this course, we'll run through these notebooks together, and at the end of your learning journey you'll have a fully supported sample validation report ready for review.
:::

For now, **scroll through this notebook** to explore. When you are done, click [{{< fa chevron-right >}}]() to continue.

::::

# Connect to a model {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {background-iframe="https://app.prod.validmind.ai" background-interactive="true" data-preload="yes"}

::: {.fr .f4 .nr5 .pa5 .overlay}
**Welcome to the {{< var validmind.platform >}}**

From here, you can:

- Keep track of your models in the <br>customizable inventory ...
- Review model documentation <br> submitted by model developers ...
- Assess the compliance of models by <br>logging findings and test results as <br>evidence on validation reports ...
- ... and much more!

::: {.f5 .pl3 .pr3 .embed}
**Can't load the {{< var validmind.platform >}}?**

Make sure you're logged in and have refreshed<br> the page in a Chromium-based browser.
:::

When you're done navigating around, 
<br>click [{{< fa chevron-right >}}]() to continue.

:::


## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.fr .f4 .nr5 .pa4 .overlay}
**Welcome to the model inventory**

Use the model inventory to track <br>
comprehensive details for all your <br>
models throughout the model lifecycle. 

The model inventory is customizable <br>
and extensible, with a layout that <br>
can be configured to suit your needs.

::: {.f5 .pl3 .pr3 .embed}
In a usual model lifecycle, <br>
a champion model will have been <br>
independently registered in your <br>
model inventory and submitted to <br>
you for validation.

For this training course, <br>
we'll have you register a dummy model <br>
via the **+ Register Model** modal <br>
and assign yourself as the validator <br>
to familiarize you with the <br>
{{< var validmind.platform >}} interface.
:::

**Let's register a model together** for use <br>
with validation on the next page. {{< fa hand-point-right >}}

::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory/?register=open" background-interactive="true" data-preload="yes"}

:::: {.fr .f4 .mv5 .nr5 .pa4 .overlay}
**Register a binary <br>classification model**

1. Select the option <br>
for a new model:

::: {.f5 .nt2 .pl2}
- **Documentation template** — <br>`Binary classification`
- **Use case** — <br>`Attrition/Churn Management`

  You can fill in other options<br> according to your preference.
:::

2. Click **Register Model** to <br>
add the model to your <br>
inventory.

When you're done, <br>click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 left=0 right=50 .w-100 .f4 .tc .pl4 .pr4 .overlay}
**Assign validator credentials**

::: {.tl}
In order to log tests as a validator instead of as a developer, we'll need to adjust your **model stakeholder** permissions:
:::

::: {.f5 .tl}
1. From the **{{< fa cubes >}} Inventory**, select the name the model you registered to open up the model details page.
2. Remove yourself as a developer by clicking on the **[developers]{.smallcaps}** tile, then clicking on the **x** next to your name.<br>
  Click **Save** to apply your changes to that role.

3. Add yourself as a validator by clicking on the [validators]{.smallcaps} tile, and selecting your name from the drop-down menu.<br>
  Click **Save** to apply your changes to that role.

:::

::::

## Get your code snippet

:::: {.columns}

::: {.column width="80%"}

<!-- FOR COPYING THE CODE SNIPPET WE NEED TO USE THIS IFRAME WORKAROUND -->

<div style="zoom: 0.6; overflow: hidden;">
  <iframe 
    src="https://app.prod.validmind.ai/model-inventory" 
    width="100%" 
    height="750" 
    style="border: 1px solid #083E44; border-radius: 8px; border-right-width: 2px; border-bottom-width: 3px;"
    data-preload="yes" 
    sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
    allow="clipboard-read; clipboard-write">
  </iframe>
</div>

:::

::: {.column width="20%" .f4}

::: {.f5}
{{< var vm.product >}} generates a unique *code snippet* for each registered model to connect with your validation environment:

1. From the **{{< fa cubes >}} Inventory**, select the name of your model to open up the model details page.
2. On the left sidebar that appears for your model, click **Getting Started**.
3. Locate the code snippet and click **Copy snippet to clipboard**.

:::

When you're done, click [{{< fa chevron-right >}}]() to continue.

:::

::::

:::: {.tc .f6 .embed}
**Can't load the {{< var validmind.platform >}}?**

Make sure you're logged in and have refreshed the page in a Chromium-based web browser.

:::

<!-- CHANGE THIS TO EXECUTED LATER -->

## {background-iframe="/notebooks/tutorials/model_validation/1-set_up_validmind_for_validation.html#install-the-validmind-library" data-preload="yes"}

:::: {.absolute bottom=15 .w-100 .f4 .tc .pl4 .overlay}
**Install & initialize the {{< var validmind.developer >}}**

::: {.f5}
With your code snippet copied to your clipboard:

1. Open **1 — Set up the {{< var validmind.developer >}} for validation**: [{{< fa square-arrow-up-right >}} JupyterHub](https://jupyterhub.validmind.ai/hub/user-redirect/lab/tree/tutorials/model_validation/1-set_up_validmind_for_validation.ipynb){target="_blank"}
2. Run all the cells under the Setting up sections: **Install the {{< var validmind.developer >}}** / **Initialize the {{< var validmind.developer >}}**

:::

When you're done, return to this page and click [{{< fa chevron-right >}}]() to continue.

::::

# Preview validation report {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

<!-- CHANGE THIS TO EXECUTED LATER -->

## {background-iframe="/notebooks/tutorials/model_validation/1-set_up_validmind_for_validation.html#preview-the-validation-report-template" data-preload="yes"}

:::: {.absolute bottom=15 .w-100 .f4 .tc .pl4 .overlay}
**Preview the validation report template**

::: {.f5}
You can preview your model's validation report template right from the {{< var validmind.developer >}}:

1. Continue with **1 — Set up the {{< var validmind.developer >}} for validation**: [{{< fa square-arrow-up-right >}} JupyterHub](https://jupyterhub.validmind.ai/hub/user-redirect/lab/tree/tutorials/model_validation/1-set_up_validmind_for_validation.ipynb){target="_blank"}
2.  Run all the cells in the sections under **Getting to know ValidMind**.

:::

When you're done, return to this page and click [{{< fa chevron-right >}}]() to continue.

::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=0 left=50 right=50 .w-95 .f4 .tc .pl4 .overlay}
**Verify the report template**

::: {.f5}
Once you've called `preview_template()`:

1. From the model inventory, select the name of your model to open up the model details page.
2. On the left sidebar that appears for your model, click **{{< fa shield >}} Validation Report**.
3. Note how the structure of the validation report reflects the previewed template.

:::

When you're done, click [{{< fa chevron-right >}}]() to continue.

::::

# Review model documentation {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.fr .f4 .nr5 .pa4 .overlay}
**Explore sample model documentation**

In a usual model lifecycle, a champion model <br>
will have been submitted to you for validation <br>
with completed model documentation.

In this next section, we'll review our sample <br>
model documentation template to familiarize <br>
you with what the structure of documentation <br>
could look like when presented to you for review:

::: {.f5 .pl3 .pr3 .embed}
1. From the **{{< fa cubes >}} Inventory**, select the name of <br>
your model you registered for this course to <br>
open up the model details page.
2. On the left sidebar that appears for your model, <br>
click **{{< fa book-open >}} Documentation**.
3. The structure of the model documentation reflects <br>
the documentation template applied to the model, <br>
just like the validation report template.

:::

When you're done taking a look <br>
around the model documentation, <br>
click [{{< fa chevron-right >}}]() to continue.

::::


# In summary {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable .center}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Using {{< var vm.product >}} for model development

:::

::: {.column width="70%" .bl .pl4 .f3}
In this first module, you learned how to:

- [x] Register a model in the {{< var validmind.platform >}}
- [x] Install the {{< var validmind.developer >}} in your environment
- [x] Connect to your registered model in the {{< var validmind.platform >}}
- [x] Preview and verify your model's documentation template

:::
::::

::: {.tc}
<br>
Continue your model development journey with:
<br><br>
<!-- IMPORTANT: USE THE .HTML PATH AND NOT THE .QMD PATH FOR THE REVEALJS OUTPUT -->
[Learning to run tests](learning-to-run-tests.html){.button target="_blank"}
:::