---
title: "Validator <br>Fundamentals COPY"
subtitle: "docs.validmind.ai/training<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
lightbox: true
search: false
format:
  revealjs:
    controls: true
    controls-tutorial: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, ../assets/slides.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /validmind.png
    footer: "{{< var validmind.training >}} | [Home {{< fa person-walking-dashed-line-arrow-right >}}](/training/training.qmd)"
  html:
    output-file: _validator-fundamentals.html
    search: false
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "../assets/home-hero.svg"
skip_preview: true
---

## {background-iframe="https://app.prod.validmind.ai/model-findings" background-interactive="true" data-preload="yes"}

:::: {.fr .f4 .mv6 .nr4 .pa4 .overlay}
From **{{< fa triangle-exclamation >}} Model Findings**, <br>you track:

- Major or minor issues
- Deficiencies
- Model limitations
- Robustness concerns
- And more!

Explore existing findings, <br>then click [{{< fa chevron-right >}}]() to continue.
::::

## {background-iframe="https://app.prod.validmind.ai/reports" background-interactive="true" data-preload="yes"}

:::: {.fr .f4 .mv6 .nr4 .pa4 .overlay}
Under **{{< fa square-poll-vertical >}} Analytics**, you can <br>find:

- Executive summaries
- Model tracking
- Risk assessments
- Compliance review
- Remediation tracking

Explore existing reports, <br>then click [{{< fa chevron-right >}}]() to continue.
::::

# Review documentation {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
<!-- Verify model documentation is complete and complies with regulatory standards by cross-checking against your guidelines. -->

Evaluate the conceptual soundness, data preparation, model development, and ongoing monitoring and governance plans for the model.

::: {.tc}
[Learn more...](/guide/model-validation/review-model-documentation.qmd){.button target="_blank"}
:::

:::

::: {.column width="70%" .bl .pl4 .f3}
### Review model documentation

{{< include /guide/model-documentation/_model-documentation-overview.qmd >}}

{{< include /guide/model-documentation/_review-model-documentation.qmd >}}


:::
::::

Try it **live** on the next page. {{< fa hand-point-right >}}

# Track issue resolution {background-color="#083E44" background-image="/training/assets/home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
As you prepare your report, review open or past due findings, close resolved ones, or add a mitigation plan.

::: {.f5 .nt2 .pl2 .mb4}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/model-validation/add-manage-model-findings.qmd#track-issue-resolution){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}
### Track issue resolution

{{< include /guide/model-validation/_track_issue_resolution.qmd >}}

:::
::::

## {background-iframe="https://app.prod.validmind.ai/model-inventory" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 .w-100 .f4 .tc .pl4 .pr4 .overlay}
To track issue resolution, review open or past due findings, close resolved ones, or add a mitigation plan.

::: {.f5 .nt2}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
::::