
## {{< fa graduation-cap >}} Register to get started

1. Get your access credentials from ValidMind. 

   If you haven't reached out to us yet, email <info@validmind.ai> to enquire about access to the training environment.

2. When you receive your access credentials, make sure you can log in:

   - **ValidMind Jupyter Hub** — <https://jupyterhub.validmind.ai/>
   - **{{< var validmind.platform >}}** — [{{< var url.us1 >}}]({{< var url.us1 >}})

3. Join a kick-off session with ValidMind to get a free instructor-led hands-on demo.

   After we have received your request to try out the training environment, we will contact you to set up a kick-off session.

4. Find your training: [Available courses](#courses).

::: {.callout-important title="For testing and evaluation purposes only"}
Do not upload proprietary information — the training environment environment is not to be used for production. If you have questions about testing in the training environment, please [provide feedback or ask for help](#provide-feedback-or-get-help).
:::
