---
title: "Training for Model Developers"
subtitle: "_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
format:
  revealjs:
    transition: slide
    theme: [default, custom.scss]
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    controls: true
    logo: validmind.png
    footer: "ValidMind Academy | [Home {{< fa person-walking-dashed-line-arrow-right >}}](training-overview.html)"
filters:
  - tachyons
---

# Learning objectives

_"As a developer who is new to ValidMind, I want to learn how to generate model documentation automatically, edit it, and then submit my documentation for approval."_

## In this training module

TBD

First, let's make sure you can log in and show you around ValidMind.

## Can you log in?

To try out this training module, you need to have been [onboarded](training-overview.html#onboarding) onto ValidMind Academy.

<br>Log into the ValidMind Platform UI to check your access:

<form method="get" action="https://app.prod.validmind.ai/" target="_blank" style="display: flex; justify-content: center;">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-top: 40px; margin-bottom: 40px;">Log into ValidMind</button>
</form>

<form method="get" action="https://jupyterhub.validmind.ai/" target="_blank" style="display: flex; justify-content: center;">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-top: 40px; margin-bottom: 40px;">Log into JupyterHub</button>
</form>


<div style="text-align: center;">
  Be sure to return to this page afterwards.
</div>

# SESSION 1:<br>Developer Framework

## 1. Initialize the Developer Framework

Install the client library, register a new model to document in the model inventory, and preview the documentation template.

## 2. Start the model development process

Initialize datasets, access ValidMind’s repository of tests, run pre-built tests, investigate the results, and add evidence to documentation.

## 3. Edit model documentation

Understand how to use text and test-driven content blocks in the Platform UI to expand the existing template structure of your model documentation, and edit documentation.

## 4. Finalize testing and documentation

Ensure model documentation includes custom tests and apply configuration changes. Finalize the process with a fully documented model ready for review.

# SESSION 2:<br>ValidMind Platform UI

## 1. Implement custom tests and integrate external test providers

Include your own custom tests and include them in model documentation as additional evidence, and register an external test provider to run your own tests.

## 2. Collaborate with others

Explore methods for collaborating with model validators on documentation projects.

## 3. View documentation activity

Track changes and updates made to model documentation over time.

## 4. Submit for approval

Follow the process for submitting documentation for review and approval to ensure compliance.

## PREVIEW: Use the AI-based documentation assistant

::: columns

::: {.column width="60%"}
Use the ValidMind AI tool to auto-generate a starting point for sections of the model documentation and to gain insight into test results.
:::

::: {.column width="40%"}
TBD
:::

:::

## What's next

Find your next learning resource: [ValidMind training](training-overview.html)

