---
title: "Training for Model Risk Governance"
format: 
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: validmind.png
    footer: "ValidMind Academy | [Home {{< fa person-walking-arrow-right >}}](training-overview.html)"
---

## _Learning objectives_ {.center}

_Use the ValidMind platform to effectively monitor and control model risks. Understand how to customize workflows for the validation process and ensure compliance. Explore reports to facilitate better decision-making and risk mitigation._

## Prerequisites {.center}

To try out this training module, you need to have been [onboarded](training-overview.html#onboarding) onto the ValidMind training environment.

Log into the ValidMind Platform UI to check your access:

<br><form method="get" action="https://app.prod.validmind.ai/" target="_blank" style="display: flex; justify-content: center;">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-bottom: 20px;">Log in<br></button>
</form>

<div style="text-align: center;">
  <small>Be sure to return to this page afterwards.</small>
</div>

## Model tracking 

Get insights into validation findings, highlighting major issues.

## Compliance review

Ensure adherence to regulatory requirements and internal policies.

## Remediation tracking

Monitor actions taken to address validation findings.

## Risk assessment 

Summarize risks, including model limitations and needed adjustments.

## Executive summaries

Get overviews for validation activities and risk exposure.

## What's next

Find your next learning resource: [ValidMind training](training-overview.html)

