---
title: "Training for Model Developers Fundamentals"
subtitle: Register for this course
date: last-modified
filters:
  - tachyons
---

As a developer who is new to ValidMind, learn how to generate model documentation, add your own tests, edit the content, and then submit your documentation for approval.

## Brief Introduction

Provide a brief introduction to the concept that this article will cover:

- What is [Concept Name]? Explain the concept or topic that the article is about. Provide a clear and concise definition that accurately reflects the scope of the article.

- Why is [Concept Name] Important? Explain why the concept or topic is important and why users should be interested in learning more about it.

- How Does [Concept Name] Work? Provide a detailed explanation of how the concept or topic works. Use examples or diagrams to help illustrate key points.

- Key Terms. List important terms and concepts related to the main topic and provide clear definitions for each one.


### For model developers

:::: {.flex .flex-wrap .justify-around}

::: {.w-60-ns}

- Initialize the developer framework
- Start the model development process
- Edit model documentation
- Collaborate with others
- Implement custom tests and integrate external test providers
- Finalize testing and documentation
- View documentation activity
- Submit for approval

:::

::: {.w-40-ns}

<div style="position: relative; display: inline-block; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); border-radius: 5px; border: 1px solid #222425;">
  <iframe src="training-for-model-developers.html" width="270" height="125" style="border:none; border-radius: 5px;"></iframe>
  <a href="training-for-model-developers.html" target="_blank" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 10;"></a>
</div>

:::

::::




## Feedback

Provide one or more examples that illustrate how the concept or topic works in practice. These examples should be clear and concise and should help users understand how to apply the concept or topic in real-world situations.

## Get help

Join our [Community Slack](/about/contributing/join-community.qmd) to get some help or ask questions. 

