---
title: "Training for Model Validators"
format: 
  revealjs:
    transition: slide
    theme: [default, custom.scss]
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: validmind.png
    footer: "ValidMind Academy | [Home {{< fa person-walking-arrow-right >}}](training-overview.html)"
# title-slide-attributes:
#   data-background-color: pink
---

## _Learning objectives_ {.center}

_Enable model validators to review and approve documentation on the ValidMind platform. Collaborate with model developers._

## Prerequisites {.center}

To try out this training module, you need to have been [onboarded](training-overview.html#onboarding) onto the ValidMind training environment.

Log into the ValidMind Platform UI to check your access:

<br><form method="get" action="https://app.prod.validmind.ai/" target="_blank" style="display: flex; justify-content: center;">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-bottom: 20px;">Log in<br></button>
</form>

<div style="text-align: center;">
  <small>Be sure to return to this page afterwards.</small>
</div>

## {background-iframe="https://app.prod.validmind.ai/" background-interactive="true" width="90%" height="90%"}

::: footer
[{{< fa person-walking-luggage >}} Discover **Model Inventory** → pick a model | ** Documentation** → **Validation Report** | **Model Findings** → **Reports**](#training-for-model-validators)
:::


## 1. Review documentation

:::: {.columns}

::: {.column width="50%"}
Verify model documentation is complete and complies with regulatory standards by cross-checking against your guidelines. 

:::

::: {.column width="50%"}
Have a question? Ask your model developer right in their model documentation to collaborate.
:::

::::

:::: {.columns}

::: {.column width="50%"}
<br><form method="get" action="../guide/review-model-documentation.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-left: 32px; margin-bottom: 20px;">Show me how</button>
</form>
:::

::: {.column width="50%"}
<br><form method="get" action="../guide/collaborate-with-others.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-left: 32px; margin-bottom: 20px;">Show me how</button>
</form>
:::

::::


## 2. Analyze test results

:::: {.columns}

::: {.column width="50%"}
Access the test results section in ValidMind, review the data, and interpret the findings to identify any issues with model performance. 
:::

::: {.column width="50%"}
Link evidence and findings to validation reports.
:::

:::

:::: {.columns}

::: {.column width="50%"}
<br><form method="get" action="../guide/review-model-documentation.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-left: 32px; margin-bottom: 20px;">Show me how</button>
</form>
:::

::: {.column width="50%"}
<br><form method="get" action="../guide/work-with-model-findings.html" target="_blank">
   <button type="submit" style="color: white; background-color: #de257e; border-radius: 8px; border: none; font-size: 32px; padding: 6.25px 12.5px; margin-left: 32px; margin-bottom: 20px;">Show me how</button>
</form>
:::

::::

##  3. Prepare validation reports

Use predefined templates within the ValidMind platform to create validation reports. 

Ensure all necessary data from model tests and evaluations are included.

## 4. Track approvals

Submit validation reports for review through the ValidMind platform, monitor the approval status, and address any feedback or required changes.

## PREVIEW: AI documentation assistant

Use the ValidMind AI tool to auto-generate initial report content based on model metadata and to gain insight into test results.

## What's next

Find your next learning resource: [ValidMind training](training-overview.html)
