---
title: "Training for Administrators"
subtitle: "docs.validmind.ai/training<br><br>_Click [{{< fa chevron-right >}}](#learning-objectives) to start_"
format:
  revealjs:
    controls: true
    controls-tutorial: true
    controls-back-arrows: visible
    transition: slide
    theme: [default, custom.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    view-distance: 2
    logo: /validmind.png
    footer: "ValidMind Academy | [Home {{< fa person-walking-dashed-line-arrow-right >}}](training.qmd)"
title-slide-attributes:
  data-background-color: "#083E44"
  data-background-image: "home-hero.svg"
filters:
  - tachyons
---

# Learning objectives

_"As an administrator who is new to ValidMind, I want to onboard my organization, manage users and roles, and manage permissions for specific roles."_

## In this training module

:::: {.columns .f2}
::: {.column width="50%"}
- [Set up your organization](#set-up-your-organization)
- [Onboard users](#onboard-users)
- [Manage roles and permissions](#manage-roles-and-permissions)
:::
::: {.column width="50%"}
- [Manage groups](#manage-groups)
- [Customize templates](#customize-templates)
- [Configure workflows](#configure-workflows)
:::
::::

First, let's make sure you can log in and show you around ValidMind.

{{< include _revealjs_navigation.qmd >}}

## Can you log in?

To try out this training module, you need to have been [onboarded](training.qmd#onboarding) onto ValidMind Academy with the **Customer Admin** role.

<br>Log in to check your access:

::: {.tc}
[Log in to ValidMind](https://app.prod.validmind.ai/){.button target="_blank"}
:::
<br>
<div style="text-align: center;">
  Be sure to return to this page afterwards.
</div>

# You're in — let's show you around.

## {background-iframe="https://app.prod.validmind.ai/settings" data-preload="yes"} 

:::: {.fr .f3 .mv5 .nr4 .pa5 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
From  **{{< fa gear >}} Settings** in the {{< var validmind.platform >}}, <br>you can: 

- Set up your organization
- Onboard new users
- Manage roles, groups and <br>permissions
- Configure the model inventory
- Manage templates and workflows
- And much more!

Try it **live** on the next page. {{< fa hand-point-right >}}
::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 .w-100 .f3 .tc .pl4 .pr4 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
Explore these pages available from **{{< fa gear >}} Settings**:

:::: {.columns}
::: {.column width="33%" .nt2 .tr}
- **Your Account**
:::

::: {.column width="33%" .nt2 .tc}
- **User Permissions**
:::

::: {.column width="33%" .nt2 .tl}
- **Workspace Settings**
:::
::::

::: {.f5 .nt2}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
:::

# Set up your organization {background-color="#083E44" background-image="home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Get your organization ready for your first users by defining business units, risk areas, and use cases.

::: {.tc}
[Learn more ...](/guide/configuration/set-up-your-organization.qmd){.button target="_blank"}
:::
:::

::: {.column width="70%" .bl .pl4 .f3}

::: {.panel-tabset}

{{< include /guide/configuration/_set-up-your-organization-business-units.qmd >}}

{{< include /guide/configuration/_set-up-your-organization-use-cases.qmd >}}

{{< include /guide/configuration/_set-up-your-organization-risk-areas.qmd >}}
:::

:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 .w-100 .f3 .tc .pl4 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
Add a business unit, a risk area, and a use case. (Choose your own names.)

::: {.f5 .nt2}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
::::

# Onboard users {background-color="#083E44" background-image="home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Onboard your initial users by sending them email invitations to join your organization.

::: {.tc}
[Learn more ...](/guide/configuration/manage-users.qmd){.button target="_blank"}
:::
:::

::: {.column width="70%" .bl .pl4 .f3}

::: {.panel-tabset}
### Invite new users

{{< include /guide/configuration/_manage-users-invite.qmd >}}

### Monitor invitations

{{< include /guide/configuration/_manage-users-monitor.qmd >}}
:::

:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

<!-- Avoid overlapping with UI elements by moving instructions into footer -->
::: footer
:::: {.absolute bottom=0 left=50 right=50 .w-95 .f3 .tc .pl4 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
Invite a user with the **Developer** role to the **All** group, and monitor the invitation status. 

::: {.f4}
Hint: Try inviting yourself. Add **+1** to your email handle (**handle+1@your-company.com**) and accept the invitation.
:::

::: {.f5}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
::::
:::

# Manage roles and permissions {background-color="#083E44" background-image="home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Assign roles to users to define responsibilities based on your organization's structure, granting them acccess to features within the {{< var validmind.platform >}}.
:::

::: {.column width="70%" .bl .pl4 .f3}

::: {.panel-tabset}
### Manage roles

{{< include /guide/configuration/_manage-roles.qmd >}}


::: {.tc}
[Learn more ...](/guide/configuration/manage-roles.qmd){.button target="_blank"}
:::

### Manage permissions

{{< include /guide/configuration/_manage-permissions.qmd >}}

::: {.tc}
[Learn more ...](/guide/configuration/manage-permissions.qmd){.button target="_blank"}
:::
:::

:::

Try it **live** on the next page. {{< fa hand-point-right >}}
::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

<!-- Avoid overlapping with UI elements by moving instructions into footer -->
::: footer
:::: {.absolute bottom=0 left=50 right=50 .w-95 .f3 .tc .pl4 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
For the user you added earlier, grant the **Validator** role. Also grant all validators the **Duplicate templates** permission.

::: {.f5 .nt2}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
::::
:::

# Manage groups {background-color="#083E44" background-image="home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Create groups to organize users based on your departments or project teams.

::: {.tc}
[Learn more ...](/guide/configuration/manage-groups.qmd){.button target="_blank"}
:::
:::

::: {.column width="70%" .bl .pl4 .f3}
### Add new groups

{{< include /guide/configuration/_manage-groups-add.qmd >}}

:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 .w-100 .f3 .tc .pl4 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
Add a new **Senior Validators** group and invite the user you created earlier to that group. 

::: {.f5 .nt2}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
::::

# Customize templates {background-color="#083E44" background-image="home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
As part of managing templates, customize how documentation and validation reports are structured.

::: {.f5 .nt2}
(Scroll down for the full instructions.)
:::

::: {.tc}
[Learn more ...](/guide/model-documentation/working-with-documentation-templates.qmd){.button target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
:::

::: {.column width="70%" .bl .pl4 .f3}
### Customize templates

{{< include /guide/model-documentation/_customize-documentation-templates-simplified.qmd >}}

:::
::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

:::: {.absolute bottom=15 .w-100 .f3 .tc .pl4 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
Customize the **Binary classification** template by adding a **1.4 Feature Engineering** subsection.

::: {.f5 .nt2}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
::::

# Configure workflows {background-color="#083E44" background-image="home-hero.svg"}

## {.scrollable}

:::: {.columns}
::: {.column width="30%" .pr4 .f2}
Configure workflows to oversee model development and validation for your organization.

::: {.tc}
[Learn more ...](/guide/model-workflows/working-with-model-workflows.qmd){.button target="_blank"}
:::
:::

::: {.column width="70%" .bl .pl4 .f3}
Workflows can be configured to match your organizational needs for overseeing model development, validation, or implementation activities.

You can customize the default workflows for:

- **Model Documentation** — when model documentation is created
- **Inventory Model** — when a model is registered

To set up a workflow, you'll need to complete these two steps in sequence:

1. [Configure the workflow steps](/guide/model-workflows/set-up-model-workflows.qmd#configure-workflow-steps){target="_blank"}
2. [Link the workflow together](/guide/model-workflows/set-up-model-workflows.qmd#link-workflow-together){target="_blank"}
:::

<br>Try it **live** on the next page. {{< fa hand-point-right >}}
::::

## {background-iframe="https://app.prod.validmind.ai/settings" background-interactive="true" data-preload="yes"}

<!-- Avoid overlapping with UI elements by moving instructions into footer -->
::: footer
:::: {.absolute bottom=0 left=50 right=50 .w-95 .f3 .tc .pl4 .bg-near-white .ba .b--dark-pink .bw1 .br3 .near-black .shadow-5}
Modify the user action for the default **Inventory Model** workflow, so that the **Submit for Initial Validation** action button is displayed for model owners.

::: {.f4}
Hint: You need to add a rule for **Model Stakeholder Roles** to the user action that lists **Owners**. 
:::

::: {.f5 .nt2}
When you are done, click [{{< fa chevron-right >}}]() to continue.
:::
::::
:::

# About administering ValidMind

There is much more that ValidMind can do to support you as an administrator of the platform, from customizing the model inventory, to setting up a private connection between ValidMind and your company network.

::: {.tc}
[All onboarding guides](/guide/guides.qmd#onboarding){.button target="_blank"}
:::
<br>
Or, find your next learning resource on [ValidMind Academy](training.qmd).
