name: Execute prod notebook
description: Installs python3, validmind, checks dependencies then executes ONLY the Intro for Model Developers notebook with production heap tracking

inputs:
  env_file:
    description: "Load the created .env file"
    required: true

runs: 
  using: "composite"
  steps: 
    - name: Install python3 for Jupyter Notebooks
      shell: bash
      run: |
        python3 -m pip install jupyter
        python -m pip install --upgrade pip

    - name: Install validmind for notebook execution
      shell: bash
      run: |
        pip install validmind 
        pip install validmind[llm] 
        pip install fairlearn aequitas 
        pip install shap==0.44.1

    - name: Ensure .env file is available
      shell: bash
      id: find_env
      run: |
        if [ ! -f "${{ inputs.env_file }}" ]; then
          echo "Error: .env file not found at ${{ inputs.env_file }}"
          exit 1
        fi

    - name: Execute ONLY the Intro for Model Developers notebook with heap production
      shell: bash
      if: ${{ steps.find_env.outcome == 'success' }}
      run: |
          cd site 
          source ../${{ inputs.env_file }}
          quarto render --profile exe-prod notebooks/tutorials/intro_for_model_developers_EXECUTED.ipynb &> render_errors.log || { 
          echo "Execute for intro_for_model_developers_EXECUTED.ipynb failed";
          cat render_errors.log;
          exit 1;
          }