name: CI Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install PyGithub pyyaml

      - name: Get pull request number
        id: pr
        run: echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"

      - name: Run CI Check
        run: python .github/scripts/ci_check.py ${{ steps.pr.outputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
