name: Run quarto render

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest Quarto release URL
      id: get-quarto-url
      run: |
        API_URL="https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest"
        DOWNLOAD_URL=$(curl -s $API_URL | jq -r '.assets[] | select(.name | endswith("linux-amd64.deb")).browser_download_url')
        echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV

    - name: Download and install Quarto
      run: |
        wget ${{ env.DOWNLOAD_URL }} -O quarto-latest-linux-amd64.deb
        sudo dpkg -i quarto-latest-linux-amd64.deb

    - name: Render Site
      run: |
          cd ./site 
          quarto render &> render_errors.log || { 
          echo "Quarto render failed immediately";
          cat render_errors.log;
          exit 1;
          }

    - name: Check for render errors 
      run: |
        if grep -q 'WARN:\|ERROR:' site/render_errors.log; then
          echo "Warnings or errors detected during Quarto render"
          cat site/render_errors.log
          exit 1
        else
          echo "No warnings or errors detected during Quarto render"
        fi
