---
title: "July 30, 2024"
---

## Bug fixes

<!---
PR #229: Updated test descriptions 
URL: https://github.com/validmind/documentation/pull/229
Labels: bug
--->
### Updated test descriptions

We fixed a number of missing test descriptions

We fixed several missing test descriptions caused by a scripting issue. You can find more details in the [test descriptions](../../guide/test-descriptions.qmd).

<!--- REPLACE THIS COMMENT WITH YOUR DESCRIPTION --->

## Documentation

<!---
PR #209: "Model Workflows" section in Guides
URL: https://github.com/validmind/documentation/pull/209
Labels: documentation
--->
### Model workflows section in guides

see workflow

https://github.com/validmind/documentation/assets/164545837/e2f93d8a-25ba-4155-afbc-16f4416a9528

You can now manage lifecycle processes within your ValidMind Platform UI setup using workflows. Use workflows to match your organizational needs for overseeing model development, validation, or implementation activities.

Check out our documentation on working with your model workflows

To use workflows, you'll need to:

1. Customize your resource statuses
https://github.com/validmind/documentation/guide/customize-resource-statuses.qmd,

2. Then set up your model workflows
https://github.com/validmind/documentation/guide/set-up-model-workflows.qmd

<!---
PR #200: Create training collateral
URL: https://github.com/validmind/documentation/pull/200
Labels: documentation
--->
### Create training collateral

we're introducing the first training modules

We are introducing the first training modules that are part of our new program for model developers, validators, and administrators.

our interactive training modules

Our training modules are interactive. They combine instructional content with our live product and are easy to use.

try it

[Welcome to ValidMind Academy](../../training/training-overview.qmd)

<!---
PR #220: Clarify what review means
URL: https://github.com/validmind/documentation/pull/220
Labels: documentation
--->
### Clarify what review means



We clarified what the concept of review entails by adding a glossary entry. 

You can find this in the new key concepts section in our topic for reviewing model documentation. We also updated our validator training to be more explicit. [../training/training-for-model-validators.html]

<!--- REPLACE THIS COMMENT WITH YOUR DESCRIPTION --->

